### ISSUE TITLE
URL search is broken

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#10]
Partially a URI encode / decode issue.

**Comment by dessalines** [comment]
Nevermind, this seems fine now.

**Comment by Nutomic** [comment]
I can still reproduce it with `dessalines/lemmy-ui:v0.7.61`.

**Comment by dessalines** [comment]
Hrm.. how are you seeing it?

**Comment by Nutomic** [comment]
With the local federation setup. Searching for an apub id doesnt give any results, and its not properly urlencoded, just like before. Same on voyager.lemmy.ml.
