### ISSUE TITLE
Unresponsiveness when editing forms

### ISSUE THREAD

**Issue by SorteKanin** [LemmyNet/lemmy-ui#1001]
### Issue Summary

While having certain forms open (like editing posts, comments or communities), other links become unresponsive.

### Steps to Reproduce

1. Go to one of your own posts.
2. Click edit.
3. Click Communities at the top.
4. Nothing happens.

Expected behavior: The page switches to Communities (possibly prompting the user before switching to ensure they don't lose the changes in the form).

The same seems to happen for comment edit forms and community edit forms.

### Technical details
I see this in the console:
```
Uncaught TypeError: e is not a function
    call https://feddit.dk/static/js/client.js:2
    call https://feddit.dk/static/js/client.js:2
    C https://feddit.dk/static/js/client.js:2
    t https://feddit.dk/static/js/client.js:2
    G https://feddit.dk/static/js/client.js:2
    ae https://feddit.dk/static/js/client.js:2
    t https://feddit.dk/static/js/client.js:2
```
I experience this on Windows 10 using Firefox.

**Comment by dessalines** [comment]
Thanks for submitting, I've also experienced this. Its a bug in the main branch, and its been really difficult to figure out where its coming from, with the browser stack traces. I'll have to experiment with removing some of the fields
