### ISSUE TITLE
Improve markdown

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#101]
There are currently some problems with markdown:
+ Titles do not scale (#99)
+ Space escaping
  + Bold, italic and scratch do not escape spaces, when applied format with buttons ¹
+ Line breaks
  + Bold, italic, scratch, mono/code and lower/upper-index convert upper and lower line breaks into spaces into the same line ²
+ Link creates space before selection ³
+ Applies on bottom
  + Title, quote and list applies it on bottom of box, instead of on selection

_________
¹
```
"lana "  |> "_lana _" [But not rendered]

```
______
²
```
"lana  |> " _lana_ lan" [Rendered]
lan"   |>
```
_____
³ With link button
```
"lana"  |> " [lana]()" [Space not rendered, maybe this is on purpose]
```

**Comment by dessalines** [comment]
What are markdown buttons? Could you do those in the github markdown here?

This uses the markdown parser [markdown-it](https://github.com/markdown-it/markdown-it), which follows the commonmark specification, which has strict requirements for line breaks like that.

Could you use screenshots? I'm not sure what most of these mean.

**Comment by Porrumentzio** [comment]
_Markdown buttons:_
![irudia](https://user-images.githubusercontent.com/61913683/101246014-e4a5af00-3710-11eb-8556-d85c95111077.png)
___
1
from
![irudia](https://user-images.githubusercontent.com/61913683/101246095-567df880-3711-11eb-89ea-856f5de05041.png)
to
![irudia](https://user-images.githubusercontent.com/61913683/101246242-5b8f7780-3712-11eb-909c-bd4473a5bce6.png)
*Note that there are spaces created before and after selection, and the `l` from the second word is converted to space. But most important, it is **not rendered** into format*

_______
2
from
![irudia](https://user-images.githubusercontent.com/61913683/101246049-128af380-3711-11eb-931b-1bbbde6e261f.png)
to
![irudia](https://user-images.githubusercontent.com/61913683/101246287-a27d6d00-3712-11eb-994b-b44bfe3f53c8.png)
*Linebreaks not maintained and spaces generated*
_______
3
from
![irudia](https://user-images.githubusercontent.com/61913683/101246177-f20f6900-3711-11eb-99f0-220cd266f26a.png)
to
![irudia](https://user-images.githubusercontent.com/61913683/101246183-ff2c5800-3711-11eb-8ca2-2a4c7c249287.png)
*Space is created before selection. Maybe by design.*

____
Applies on bottom
from
![irudia](https://user-images.githubusercontent.com/61913683/101246310-cb056700-3712-11eb-9ef6-3073626f2469.png)
to
![irudia](https://user-images.githubusercontent.com/61913683/101246318-d789bf80-3712-11eb-9fe8-b52bdd98803b.png)
*Applies on end of text/box, instead of on selection*

___
___
I propose using CommonMark, which is used by Discourse, Reddit, Gitlab... https://commonmark.org/
