### ISSUE TITLE
Language indicator for posts and comments

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#1010]
Posts and comments can specify which language they are written in. This should be displayed in the UI.

**Comment by wiki-me** [comment]
isn't this a little too excessive? is that really useful information that is worth the cognitive load? If you know the language you can recognize it and just read it, if not why should i care what language is displayed? If i want to translate it there is the "detect language" functionality on google translate.

**Comment by Nutomic** [comment]
You can make the same argument about other indicators, such as those for thread creator or admin/mod. None of these are required because you can get the information in other ways. But as we already have this information, it makes sense to display it.

**Comment by wiki-me** [comment]
> You can make the same argument about other indicators, such as those for thread creator or admin/mod. None of these are required because you can get the information in other ways.

In those cases i can come up with "user story" for why they could be used (So it might make sense to provide easy access for them), I can't think of a user story for this feature.
