### ISSUE TITLE
Navigating to other page via link causes infinite loading status

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#1018]
As the title describes, navigating to a page via link causes an infinite loading state. It doesn't happen if you navigate by putting the URL directly into the address bar, and it can be fixed by refreshing the page. I suspect this means there's something wrong with the client-side fetching logic.

**Edit**: Important to note that this is happening with the latest changes on the both the backend and frontend main branches, not on version 0.17.2.

**Comment by dessalines** [comment]
This had to do with the back end not being able to deserialize strings into bigints. I corrected and deployed this in a lemmy-js-client rc now.
