### ISSUE TITLE
PWA one-click share

### ISSUE THREAD

**Issue by friedmag** [LemmyNet/lemmy-ui#1027]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

When using the PWA, there is no easy way to share a link to a post or comment with someone.

### Describe the solution you'd like

I'd like to have a button the link and fedi link buttons to simply use the OS-level share function directly. This should be doable with the [web share API](https://developer.mozilla.org/docs/Web/API/Web_Share_API)

### Describe alternatives you've considered

The current functionality allows a long-press on the link to select a share option. That's OK, but much less convenient. Another alternative is a new button, however I'm not sure I see the value in having the current links as-is in the PWA.

### Additional context

I'm not aware of related issues.

**Comment by SleeplessOne1917** [comment]
I'll give this and your other issue a look. It would probably go well with the recent PWA changes.

**Comment by friedmag** [comment]
> I'll give this and your other issue a look. It would probably go well with the recent PWA changes.

I'm actually interested in taking a look but am not sure how to test the pwa locally, especially for this feature which needs a mobile browser. Any suggestions?

**Comment by SleeplessOne1917** [comment]
You don't need an https connection for webshare to work when the domain is localhost. As for how to test it on desktop, webshare is enabled by default on chromium browsers and can be enabled in Firefox browsers in the about:config. I think I have something working and will open a PR shortly.

**Comment by SleeplessOne1917** [comment]
@friedmag If you'd like to test the changes locally yourself, the PR is open now.

**Comment by friedmag** [comment]
@SleeplessOne1917 Thanks, I didn't realize that. Is it possible to run without a local Lemmy instance? It seems to be quite directly tied. Just learning about Inferno (pretty familiar with React), I'm guessing it's related to its isomorphic nature.

**Comment by SleeplessOne1917** [comment]
If you run it without a local lemmy instance there won't be any posts to test it with. If you want to test locally, try using the docker compose file in the backend project. For the UI container, you'll have to comment the part that uses the image from docker hub and uncomment the part for the local repo.
