### ISSUE TITLE
Should we get rid of admin/mod badges on posts and comments

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#1037]
![Screenshot_20230523_223802](https://github.com/LemmyNet/lemmy-ui/assets/1044450/bb2ff0bb-1cea-4e05-b1b9-2817d02bee89)

This used to be necessary to distinguish official announcements. But now we can sticky posts and comments to say moderation-related things. Having these badges on all the time when posting about random things (not moderation related) is a bit annoying. It also might make users scared to receive a ban if they say something wrong.

**Comment by dessalines** [comment]
I like and prefer them. It's nice to know who the mods and admins are, even if they're not speaking in an official capacity. 

I use some more subtle icons for them in jerboa, maybe that work if a concern is that these badges take up too much space. 

Besides that, it could be made into a setting.

**Comment by krestenlaust** [comment]
I think on they were optional on reddit (not that this is of any real significance, but just as an example), if you had multiple you could choose between them as far as I know.

I'd prefer them not being removed outright, as that would encourage stickying posts with every single mod post (Imo).
