### ISSUE TITLE
Developer help request

### ISSUE THREAD

**Issue by morewings** [LemmyNet/lemmy-ui#1044]
My name is Dima. I'm a front end developer. I decided to help Lemmy project by creating a modern front end app for it. Likewise, I will use Next.js, Typescript and React as an engine. 

So, I'm looking for somebody to help to run a local copy of Lemmy backend. The problem is that when I run it and run [existing front end app](https://github.com/LemmyNet/lemmy-ui), the front end can't access websocket. 

```
2023-05-29T21:34:22.394558Z INFO actix_web::middleware::logger: 127.0.0.1 "GET /api/v3/ws HTTP/1.1" 404 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36" 0.000167
```

```
websocket.js:80 WebSocket connection to 'ws://localhost:8536/api/v3/ws' failed: Websocket.tryConnect @ websocket.js:80 eval @ websocket.js:114 WebSocketService.ts:43 Websocket closed.
```

**Comment by dessalines** [comment]
Join the [dev chat here](https://matrix.to/#/!tUnhsBRCsiePXfsIGe:matrix.org?via=matrix.org&via=chapo.chat&via=tchncs.de).

Lemmy-ui is already written using react jsx (actually inferno, a faster runtime / alternative for react, but its pretty much identical). So you could pretty much copy-paste the jsx if you wanted, and alter the components as you see fit.

> So, I'm looking for somebody to help to run a local copy of Lemmy backend. The problem is that when I run it and run [existing front end app](https://github.com/LemmyNet/lemmy-ui), the front end can't access websocket.

Don't use the websocket, its going away. Use the HTTP library. The lemmy-js-client HTTP / API docs are on the join-lemmy.org site, [here](https://join-lemmy.org/api/).  

You can either run it yourself which is very easy with docker(instructions are on https://join-lemmy.org) , or use our test instances, one is at https://enterprise.lemmy.ml . 

The only issue with using the http client is CORs, which you can circumvent with browser plugins, or run a local copy.

---

To me making *another* front end in react, is probably not a great idea. Lemmy is a large application, and requires a lot of work to build and maintain. Neither me nor other developers would be able to help you maintain another react front end. I cannot stress how often we've had developers plan to do this, then abandon it after realizing how daunting a task it is. It took me a full month of constant work to build a less-than-full-featured android app, and that's by someone who knows the back-end very well.

I highly recommend contributing to lemmy-ui itself, as it has many other devs, such as me, @SleeplessOne1917 , @Nutomic , and @makotech222 to help you.

In a month or so when I get the time, I do plan on making another front end using [leptos-rs](https://github.com/leptos-rs/leptos), (which IMO is finally in a good enough state), and [DaisyUI / tailwind](https://daisyui.com/) for the component styling. This will not replace lemmy-ui , but I could definitely use help in building it. Also then we get to use rust and benefit from its ecosystem, and won't have to deal with the awfulness of javascript.

**Comment by morewings** [comment]
Thanks for onboarding @dessalines. You might be right about workload, at this stage I’m just researching what you have. Though, it still doesn’t look huge to me. I still see benefits in using Next instead of Inferno. Inferno might be a good choice back in the day. But today we see that it’s slowly [loosing its popularity](https://trends.google.com/trends/explore?cat=5&date=today%205-y&q=Inferno.js,Next.js&hl=en). On the other hand Next.js is growing. Also it’s faster. I believe that using Next based front end will open new opportunities for Lemmy. Just because there are more front end devs willing to work with Next.
