### ISSUE TITLE
mobile view is cluttered and difficult to use

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1047]
I was going to put this in a discussion page because this could be cut up into many small issues but it doesnt look like discussions are enabled for this repo. Feel free to close if not helpful.
![mobile view](https://github.com/LemmyNet/lemmy-ui/assets/177491/f1012a0a-fcc6-40fc-a7d3-388c4f8442e1)

**Comment by dessalines** [comment]
Could you break these out into individual issues? Unless you plan on tackling them yourself, it makes it really difficult to fix.

**Comment by trashhalo** [comment]
of course ill do that tonight

**Comment by trashhalo** [comment]
Done.
