### ISSUE TITLE
Missing Moderation options

### ISSUE THREAD

**Issue by 100000BC** [LemmyNet/lemmy-ui#1050]
Hey there! I'm moderating a community on lemmy.ml and when I click the "..." button on a post, it doesn't give me any of the options to pin that post or anything like it should.

![image](https://github.com/LemmyNet/lemmy/assets/67931296/8dd46958-c340-4bb4-9340-dd84770a7e28)

As you can see, I am the moderator, and I have clicked on the "..." button of the second post, which I would like to pin to the top... But it doesn't show me any of the options that it should, such as:
![image](https://github.com/LemmyNet/lemmy/assets/67931296/43f8eeea-b69a-4f36-91f6-f030ef147f94)

**Comment by Nutomic** [comment]
Does it work when you go to the post view? (by clicking on the post title)

**Comment by dessalines** [comment]
There aren't currently moderator actions from the list view.
