### ISSUE TITLE
Footer version numbers

### ISSUE THREAD

**Issue by jSML4ThWwBID69YC** [LemmyNet/lemmy-ui#1052]
How do you set the version numbers in the footer? 

For example,
_UI: v0.17.3 BE: 0.17.3_

When I build Lemmy/Lemmy-UI, the version comes up as: _BE: unknown version_

Is this a compile time option?

**Comment by dessalines** [comment]
It comes from the docker build: 

`echo "pub const VERSION: &str = \"$(git describe --tag)\";" > "crates/utils/src/version.rs" \`

**Comment by jSML4ThWwBID69YC** [comment]
Thank you! That sets the BE: version, but not the UI version. Is there a second item for the UI?

**Comment by SleeplessOne1917** [comment]
Only one version is displayed if the  FE and BE versions are the same.

**Comment by SleeplessOne1917** [comment]
It seems the UI version should have a v at the front and the backend no v. E.g. v0.17.3. It must have been a mistake when making the tag.

**Comment by jSML4ThWwBID69YC** [comment]
> It seems the UI version should have a v at the front and the backend no v. E.g. v0.17.3. It must have been a mistake when making the tag.

Ok. So it'll probably just work on the next release?

**Comment by SleeplessOne1917** [comment]
> So it'll probably just work on the next release?

Provided a similar mistake doesn’t happen again, yes.

**Comment by jSML4ThWwBID69YC** [comment]
> Provided a similar mistake doesn’t happen again, yes.

Thank you. I appreciate your help.

**Comment by verymilan** [comment]
hmm but if i just install with cargo, i can't modify the source anymore to set a version...

**Comment by dessalines** [comment]
@SleeplessOne1917 we should make those a uniform `0.0.0` with no `v`, and then let the UI add the V if necessary.

Lets leave a lot of these smaller issues until after the http rework.
