### ISSUE TITLE
Language drop-down for comments is clipped

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1057]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

Language drop-down for comments is clipped until you interact with it. May be mobile only. Spawned from #1047 

### Steps to Reproduce

1. Open any Lemmy post on mobile

![Screenshot_20230531-224245~3](https://github.com/LemmyNet/lemmy-ui/assets/177491/a4b822fe-8267-421a-88d9-ec7014a553ef)

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
- What OS are you trying to install lemmy on?
- Any browser console errors?

Android Chrome on Pixel 7 pro

**Comment by jsit** [comment]
@dessalines To give this dropdown a little more room, I suggest moving the language drop-down and the "Post" button to a second row. This will:

a. Prevent the language dropdown from being squished
b. Make the distinction between the formatting options and the other elements more clear
c. Give the formatting bar more room
d. Move the "Post" button to the lower-right, which is a very common pattern on the web (I'm seeing it right here on GitHub in fact).

Here are some screenshots of what that might look like at different viewport widths:

<img width="407" alt="Screenshot 2023-06-04 at 4 04 41 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/83947e18-407e-46dd-ad1e-2d6c10d1fa10">

<img width="715" alt="Screenshot 2023-06-04 at 4 04 28 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/ca3393c6-ca65-4faf-9ad9-9ad2eeafcb62">

<img width="754" alt="Screenshot 2023-06-04 at 4 04 11 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/d1c72ac7-78bc-4115-9902-fae156af03ce">

**Comment by Nutomic** [comment]
Can you open a pull request with your changes?
