### ISSUE TITLE
Avatar for user and topic are too big and distracting 

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1058]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?
#1047 
General mobile view user experience

### Describe the solution you'd like
![242756576-f1012a0a-fcc6-40fc-a7d3-388c4f8442e1~2](https://github.com/LemmyNet/lemmy-ui/assets/177491/4002a33e-65d8-48b9-aa0a-9a48da3c010f)

These circles are large and eye catching. I think it's because they are embedded in the text but much larger than the font size, they are also really colorful. I think if you were to follow an avatar pattern it would look more normal. Like overlay the sub icon on top of the user icon kind of like a badge and move the whole thing to the left of title.

The goal here is just to make it fit into existing patterns your brain has seen on other sites so it flows better.

**Comment by dessalines** [comment]
I'm def open to those being smaller / sized to the text better. But also, we are under no obligation to match our UI exactly to reddits. This is a completely different platform.

**Comment by alectrocute** [comment]
Now it seems we have the opposite issue. Closing this as it’s now irrelevant.
