### ISSUE TITLE
Help button leads to dead link

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1060]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

There is this question mark button on users profiles. If you click it, it leads to a dead link.

![Screenshot_20230602-223633.png](https://github.com/LemmyNet/lemmy-ui/assets/177491/c9b91449-9f63-4830-bf0c-927e7f7cc759)

https://join-lemmy.org/docs/en/about/guide.html#sorting

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
- What OS are you trying to install lemmy on?
- Any browser console errors?

**Comment by jsit** [comment]
Fixed by #1007
