### ISSUE TITLE
infinite sign up loading (maybe intentional?)

### ISSUE THREAD

**Issue by sI1vre** [LemmyNet/lemmy-ui#1062]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

when i try and make an account for the site, it gets stuck in infinite loading when i press the 'sign up' button. i dont know enough about the site to know if this is intentional or not but i dont think it is.
almost every website thinks im a bot for some reason so maybe thats the issue?

### Steps to Reproduce

1. click the sign up button on https://lemmy.ml/signup
![image](https://github.com/LemmyNet/lemmy-ui/assets/105620317/17ad6f3f-f1d4-41a7-9a7e-b7ad5e14529c)

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
- What OS are you trying to install lemmy on?
- Any browser console errors?

firefox, windows 10 lenovo pc (i dunno the exact model)

**Comment by Nutomic** [comment]
No this is definitely a bug (probably the backend is overloaded). Try registering on another instance.

**Comment by pineapplemachine** [comment]
I am having a similar problem. I think this is related to email verification, or at least it is in my case.

First I set up a lemmy instance on a server I host by following the instructions here: https://github.com/LemmyNet/lemmy-ansible

Then I visited the domain where the server is hosted and I set up an admin account, it went smoothly enough. I started setting up some communities, but then I wanted to try accessing the instance on another machine. This did not go as smoothly.

When I try to log in to the admin account I set up on the other machine, the "Login" button becomes a spinner and nothing happens, for as long as I've waited. There are no errors in the console or network tab, it just sort of hangs.

In the server log I see an error message when I try to log in that makes this seem related to email verification:

```
lemmy_1     | 2023-06-05T09:10:33.351314Z ERROR HTTP request{http.method=GET http.scheme="http" http.host=lemmy.mydomain.com http.target=/api/v3/ws otel.kind="server" request_id=ed0661ee-2546-4b93-875d-c056c62a2c0f http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: email_not_verified: email_not_verified
lemmy_1     |    0: lemmy_api::local_user::login::perform
lemmy_1     |            with self=Login { username_or_email: Sensitive, password: Sensitive }
lemmy_1     |              at crates/api/src/local_user/login.rs:17
lemmy_1     |    1: lemmy_server::root_span_builder::HTTP request
lemmy_1     |            with http.method=GET http.scheme="http" http.host=lemmy.mydomain.com http.target=/api/v3/ws otel.kind="server" request_id=ed0661ee-2546-4b93-875d-c056c62a2c0f http.status_code=101 otel.status_code="OK"
lemmy_1     |              at src/root_span_builder.rs:16
```

However I do not have any verification email in my inbox after setting up my admin account, and I have not found an option in the UI to send a new verification email.

Login worked fine after I unchecked "Require email verification" in the instance settings, but I do not want to allow accounts with an unverified email on the instance.

**Comment by dessalines** [comment]
I *think* email verifications might be broken on `0.17.3`. They are fixed in the next release tho. Apologies for that.

**Comment by dessalines** [comment]
I'll open up a back-end issue for that one.

**Comment by Nutomic** [comment]
Username is max 20 characters.
