### ISSUE TITLE
Login to multiple instances fails

### ISSUE THREAD

**Issue by wiki-me** [LemmyNet/lemmy-ui#1066]
### Issue Summary

Can't log in to multiple instances:

https://lemmy.serverfail.party/login

https://lemmygrad.ml/login

https://beehaw.org/login

It just gets stuck (the login button keeps spinning), I am using the username "@wiki_me@lemmy.ml"

### Steps to Reproduce

Try to log in to the instances mentioned (or any instance)
### Technical details

In the console beehaw eventually shows: "Object { error: "couldnt_find_that_username_or_email" }"

**Comment by Tmpod** [comment]
Beginners mistake :)

Federation works by allowing an account from one server to read and post stuff on other servers, *without leaving its origin one*. 
This means you always log on lemmy.ml, but through there you can see and interact with the entire network. 
You don't log on other servers with your username/password combo.

**Comment by wiki-me** [comment]
> Federation works by allowing an account from one server to read and post stuff on other servers, without leaving its origin one.

If it would have told me "user not found" i would not have opened this issue, but it gets stuck (which is a major usability bug) . A better option would be to tell me I can't log in to the server, but redirect me to my server when i try to do some action that needs a login .

**Comment by dessalines** [comment]
If someone would like to add that warning, I'd be happy to merge it.
