### ISSUE TITLE
iframely : Error write EPIPE (docker install)

### ISSUE THREAD

**Issue by splacat** [LemmyNet/lemmy-ui#107]
Not sure if is a bug or a problem of my server but I think is a good idea to open this.
My instance lemmy.cat was no embedding URL images ([see here](https://lemmy.cat/post/100)). I got into iframely docker image and found this error in its log:

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:676:19)
    at sendHelper (internal/cluster/utils.js:22:15)
    at send (internal/cluster/child.js:190:10)
    at EventEmitter.cluster._getServer (internal/cluster/child.js:89:3)
    at listenInCluster (net.js:1362:11)
    at doListen (net.js:1488:7)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

iframely kept trying restarting but throwing this error again and again. This was the forever processes list:

/iframely # forever list
info:    Forever processes running
data:        uid  command             script     forever pid id logfile                 uptime       
data:    [0] NSkM /usr/local/bin/node cluster.js 18      422    /root/.forever/NSkM.log 0:0:0:46.822

I did a test, I stopped the forever process with `forever stopall` and started again like this:

`forever start -l iframely.log -a server.js`

(note that is not cluster.js but server.js what I started.)

...and bingo! iframely started running nicely! and embedding URL images like a charm.

I guess is like a workaround but this solution keep iframely running nicely.

**Comment by Nutomic** [comment]
We just reference the upstream iframely docker image in our docker-compose.yml, so you should report it there:

https://github.com/itteco/iframely/issues

**Comment by dessalines** [comment]
I ran into this, and your fix worked great. We really need an iframely replacement, its extremely unreliable, heavy, and doesn't build for arm.
