### ISSUE TITLE
Small font size on mobile triggers zoom

### ISSUE THREAD

**Issue by sean256** [LemmyNet/lemmy-ui#1070]
iOS (maybe android too?) will zoom the page beyond what the meta tag limits if an input takes focus and the font size is smaller than 16px.

I have 2 screenshots here. One before I select the input and one after. This causes uses to have to manually zoom back out to avoid awkward horizontal scrolling.

![IMG_4261](https://github.com/LemmyNet/lemmy/assets/6920955/11b10412-9285-49e6-ad13-a4ea4ba946c8)
![IMG_4262](https://github.com/LemmyNet/lemmy/assets/6920955/0ac00b27-4639-4fd4-a6cd-e1bdd13d48af)

**Comment by dessalines** [comment]
I just tested this on several browsers on android, and can't replicate it. Seems like a very strange browser quirk of safari. 

If you find a way around this that doesn't require too much safari workaround, i'd consider adding it.

**Comment by sean256** [comment]
Is making the font size 16 or higher in an input “too much safari workaround”?

**Comment by dessalines** [comment]
Yep. Why does this one browser do this, but no other one? And why should safari dictate our font sizes?

**Comment by dessalines** [comment]
PRs for safari workarounds welcome. I'll re-open this if you decide to work on it.
