### ISSUE TITLE
Language warning for user preferences shows up on wrong language selector

### ISSUE THREAD

**Issue by jsit** [LemmyNet/lemmy-ui#1078]
### Issue Summary

Language warning for user preferences shows up where it shouldn't.

### Steps to Reproduce

1. Open the Create a Community form
2. Above the language drop-down, you will see this warning: "Warning: If you deselect Undetermined, you will not see most content." This is just true for user settings, but not for Community creation. This message should not appear on this screen.

<img width="581" alt="Screenshot 2023-06-04 at 3 15 29 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/643417/eac1cf0a-fecb-4165-9233-bad0f600a927">

**Comment by dessalines** [comment]
Verified.
