### ISSUE TITLE
shared/utils.ts seems to provide a broken link to markdown help

### ISSUE THREAD

**Issue by realkinetix** [LemmyNet/lemmy-ui#108]
Line 76 currently says:

export const helpGuideUrl = '/docs/about_guide.html';

But the docs got built on my system with the path being /docs/about/guide.html

I see that this report and my production-like build contradicts what's running at lemmy.ml presently - is this a difference between prod & dev setups?

**Comment by Nutomic** [comment]
Right, I put the files in subfolders so its a bit better organised, and not just everything in one flat folder. Thanks for reporting, would you mind making a PR to fix the path?

**Comment by realkinetix** [comment]
Hope I've done everything appropriately here - I'm pretty green with managing git very well.

**Comment by dessalines** [comment]
Looks good to me, thanks!
