### ISSUE TITLE
Some subs are not findable on Lemmy web mobile, but they are findable with desktop view

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy-ui#1085]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

A summary of the bug.

Some subs are not findable on Lemmy web mobile, but they are findable with desktop view

### Steps to Reproduce

Click magnifying glass, try searching or the sub with the url on mobile web Firefox 

### Technical details

- Please post your log: `sudo docker-compose logs > lemmy_log.out`.
- What OS are you trying to install lemmy on?
- Any browser console errors?

**Comment by Nutomic** [comment]
Can you give a concrete example? And fetching a remote community can be slow or fail sometimes, in that case you can retry it.
