### ISSUE TITLE
Someone else's profile [saved] shows your own [saved] posts

### ISSUE THREAD

**Issue by r-hmn** [LemmyNet/lemmy-ui#1090]
### Issue Summary

When checking someone else's profile; under [saved], it lists your own saved posts

### Steps to Reproduce
1. Click on any username from a post
2. On the profile page, from the list of Overview,Comments,Post,Saved  select [saved]
3. Now you see your own profile's saved posts

### Technical details

- On the bottom of the page it says: BE: 0.17.2

**Comment by dessalines** [comment]
Good catch! We need to hide that button when viewing other people's profiles.

**Comment by SleeplessOne1917** [comment]
I wonder if favorites should have their own page instead of being tucked away in the profile?

**Comment by r-hmn** [comment]
> I wonder if favorites should have their own page instead of being tucked away in the profile?

Actually, i like it where it is. it already also has the sorting which is great.

i was thinking to use the "saved"/"favorites" page for the purpose of "top picks". 
So that instead of a community-driven ranking, that i could present a view where the mod has selected specials (even though haters could have downvoted it)

**Comment by dessalines** [comment]
> I wonder if favorites should have their own page instead of being tucked away in the profile?

I think the same page, possibly in a tab instead of a button filter, looks good. Example from boost for reddit:

![Screenshot_2023-06-06-14-46-46-788_com rubenmayayo reddit](https://github.com/LemmyNet/lemmy-ui/assets/930215/9816901e-088c-4254-b5c2-906b8d885c22)

**Comment by dessalines** [comment]
> i was thinking to use the "saved"/"favorites" page for the purpose of "top picks".
So that instead of a community-driven ranking, that i could present a view where the mod has selected specials (even though haters could have downvoted it). But now i'm wondering if the 'saved' page is actually viewable by others?..

@r-hmn that has nothing to do with this issue. Open up a feature request in lemmy.

**Comment by Nutomic** [comment]
I would consider moving Saved to the top right menu, next to Profile and Settings.
