### ISSUE TITLE
Wrong UI in light mode for mobile devices in the community tab

### ISSUE THREAD

**Issue by uuttff8** [LemmyNet/lemmy-ui#11]
just compare these 2 pictures :
<img width="736" alt="Screen Shot 2020-09-14 at 9 52 48 PM" src="https://user-images.githubusercontent.com/40335671/93126612-3ec84280-f6d5-11ea-9003-c777b77b8c16.png">

<img width="736" alt="Screen Shot 2020-09-14 at 9 53 09 PM" src="https://user-images.githubusercontent.com/40335671/93126635-4ab40480-f6d5-11ea-8219-5d8b9ba40539.png">

In light mode, some parts of the table are truncated

**Comment by dessalines** [comment]
Its not truncated, that theme just has different margins, but its correctly showing a horizontal scroll bar. It would show that scroll bar depending on your font size too.
