### ISSUE TITLE
As a community mod, I would like to have analytics about the user interactions

### ISSUE THREAD

**Issue by jgeorgeson** [LemmyNet/lemmy-ui#1102]
### Is your proposal related to a problem?

I created a community, and can see statistics but no details about users/subscribers.

![image](https://github.com/LemmyNet/lemmy-ui/assets/10238523/9291ff23-dd25-4be4-8d45-b1c9c2f473ef)

### Describe the solution you'd like

I would like to be able to drill down into each of the statistics in the screenshot and see details like who the subscribers are and who are the users reflected in the interactions.

**Comment by dessalines** [comment]
Wouldn't that be potentially privacy-offending?

**Comment by jgeorgeson** [comment]
Well that's a fair counterpoint. Maybe users could have an option when subscribing to make it public/private.

**Comment by Nutomic** [comment]
That would be too complicated. Is there any particular reason why you want to see the usernames?
