### ISSUE TITLE
Comments don't render on mobile Safari

### ISSUE THREAD

**Issue by elight** [LemmyNet/lemmy-ui#1107]
### Issue Summary

Latest public release of iOS 16.

### Steps to Reproduce

just use mobile safari 👎 
![IMG_1159](https://github.com/LemmyNet/lemmy-ui/assets/10112/dc31bbad-0bcc-4dfa-bdbe-2164bcd22fc2)

**Comment by dessalines** [comment]
I don't have any apple devices so I can't test this.

**Comment by Klobenda** [comment]
Datapoint: does not happen on the version of mobile safari that ships with iOS 17 dev beta 1 - comments work great

**Comment by mr00z** [comment]
it works for me on iOS 16.5

**Comment by elight** [comment]
One of my plugins then?



On June 7, 2023, Vipercat ***@***.***> wrote:
> it works for me on iOS 16.5
>

—
Reply to this email directly, view it on GitHub
<https://github.com/LemmyNet/lemmy-ui/issues/1107#issuecomment-
1581529620>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAACPAGLUR5SRHN4QH2RDCTXKDWFZANCNFSM6AAAAAAY6B7PKA>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by elight** [comment]
Whatever the f "Ad Block Custom" is blocking is the culprit. Closing.
