### ISSUE TITLE
"Sorting help" icon links to a missing page

### ISSUE THREAD

**Issue by Klobenda** [LemmyNet/lemmy-ui#1108]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

This question mark icon/link leads to a 404:
![image](https://github.com/LemmyNet/lemmy-ui/assets/135837933/dd741c4c-c2c4-4422-9ac1-12a9bd04025e)

The link it attempts to take you to: https://join-lemmy.org/docs/en/users/01-getting-started.html/docs/en/users/03-votes-and-ranking.html

### Steps to Reproduce

1. Click the pictured help icon

### Technical details

N/A

**Comment by dessalines** [comment]
Already fixed in main.
