### ISSUE TITLE
Litely-red theme has green background for "select a community" dropdown when creating a post

### ISSUE THREAD

**Issue by RayBB** [LemmyNet/lemmy-ui#1112]
### Issue Summary

A summary of the bug.

### Steps to Reproduce

1. Set theme to litely-red
2. Visit https://lemmy.ml/create_post

Screenshot:
<img width="920" alt="image" src="https://github.com/LemmyNet/lemmy-ui/assets/921217/37bdcb82-c7a2-481f-844d-18f5f9541dc1">

### Implementation details
imo there should be no background color for this dropdown.
But if there must be one then it should probably be red.

In the theme file it probably shouldn't have green as the secondary bg color: 
https://github.com/LemmyNet/lemmy-ui/blob/850de94c00d9055afcf32e515946c195f8619c06/src/assets/css/themes/litely-red.css#L5812

Where select a community is used:
https://github.com/LemmyNet/lemmy-ui/blob/850de94c00d9055afcf32e515946c195f8619c06/src/shared/components/post/post-form.tsx#L364

PS: I'd like to fix this by removing the color but it's not clear to me where in the css we set this bg-secondary for the communities dropdown.

**Comment by dessalines** [comment]
The main branch uses a different community dropdown, and is fixed there.
