### ISSUE TITLE
Accesibility: missing "jump to content" link

### ISSUE THREAD

**Issue by jonpincus** [LemmyNet/lemmy-ui#1117]
### Issue Summary

There's no "skip to content" link allowing users with screenreaders to skip over all the headers.

### Steps to Reproduce

Go to the main page of any lemmy site.  Click tab.  It should take you to a "jump to content" link, but none appears.

The screenshot of Reddit's interface illustrates what should happen. The "jump to content" link in the image is initally invisible, but appears when I hit a tab.

<img width="320" alt="Screen Shot 2023-06-08 at 11 37 17 AM" src="https://github.com/LemmyNet/lemmy-ui/assets/156896/ed6b9c4a-9f4d-4e30-8723-864f493a3122">

### Technical details

https://www.useragentman.com/blog/2016/12/15/implementing-an-accessible-skip-navigation-link-requires-more-thought-than-youd-think/  is a good discussion of how to provide this functionality (although a little old, not sure if best practices have evolved since then)

**Comment by skspade** [comment]
I'm willing to pick this up @SleeplessOne1917 is this something you all would want?

**Comment by SleeplessOne1917** [comment]
If @dessalines and @Nutomic are good with it, it's fine by me. Accessibility is never a bad thing.

**Comment by skspade** [comment]
Agreed, I'll pick this up!
