### ISSUE TITLE
New HTML escaping breaks quotes after page refresh

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#1123]
### Issue Summary

22a4fae0c2ffe51330484892f13376a46cf9c89c introduced a bug with quotations. When they are first created (when posting a new comment, for example) they show up correctly, but after a refresh they break:

[![Screenshot_20230608_233552](https://github.com/LemmyNet/lemmy-ui/assets/35771816/07c6656a-cd3e-4301-ae5e-f289214dff66)](https://enterprise.lemmy.ml/post/416551)

### Steps to Reproduce

1. Go to a post (for example, [this one](https://enterprise.lemmy.ml/post/416551))
2. Make a comment with a quote.
3. It will render well, but now refresh the page.
4. The quote won't be rendered and the raw `>` will be shown instead.

### Technical details

Introduced by 22a4fae0c2ffe51330484892f13376a46cf9c89c
A possible solution would be to tweak the Markdown parser to accept escape codes such as `&lt;` as well as the actual `>` character.

**Comment by SleeplessOne1917** [comment]
Fixed in #1129
