### ISSUE TITLE
Integrating the Lemmy community browser into lemmy-ui

### ISSUE THREAD

**Issue by Korgen1** [LemmyNet/lemmy-ui#1127]
Right now, it is really a pain to find new communities since they need to have been specifically searched to be available in your home instance, there is the Lemmy community browser, but that requires going to another page and copying the community into the search bar, then waiting while it tells you it can't find anything. This is unintuitive especially for new users not used to Lemmy. 

A good solution might be integrating a community browser into the lemmy-ui that will allow you to browse and fetch communities in other instances from within your home instance.

**Comment by dessalines** [comment]
There's a back-end issue for this. It should be a back end service, so as to be more distributed.
