### ISSUE TITLE
Split up and organize `utils.ts` up into appropriate new folders, files

### ISSUE THREAD

**Issue by alectrocute** [LemmyNet/lemmy-ui#1133]
We really need to split up and organize this [file](https://github.com/LemmyNet/lemmy-ui/blob/2a5c690bdc171311c9ed67ec644b4c102da41338/src/shared/utils.ts
). Reading through it is laborious and taxing to the uninitiated.

I may be open to the task and will update this issue if/when I get started.

**Comment by dessalines** [comment]
100% agree. Feel free to break utils out into its own folder, with logical files, and a `index.ts`

Thanks!

**Comment by alectrocute** [comment]
I'll make this my first task when I get up and running with my dev environment, @dessalines.

Any objection to omitting the `index.ts` and just importing each utility manually on the component/service/etc. file that it's used on?

**Comment by robertnabbe** [comment]
FWIW, IMO using index.ts as a barrel file yields a lot cleaner import rules.
