### ISSUE TITLE
Broken community link

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#1141]
https://lemmy.ml/c/xmpp@lemmy.ml

has a broken link on the sidebar leading to https://lemmy.ml/c/xmpp and a 404 page.

I think it has something to do with how URLs are parsed which must have been improved a few weeks ago.

because as strange as it sounds but this community used to be accessible on https://lemmy.ml/c/xmpp/jabber with the community name being "XMPP/Jabber".

This seems to be related: https://lemmy.ml/post/1185491

**Comment by jsit** [comment]
I can't seem to reproduce this? Can you list explicit steps for reproducing the issue, what you expect to happen, and what happens instead, with links and screenshots? Thanks.

**Comment by poVoq** [comment]
See the linked topic. but this is fixed in 0.18.0 so I am closing it.
