### ISSUE TITLE
Add long-polling for `GetUnreadCounts`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#1148]
After the http merge is complete, we should add long-polling to refetch unread counts.

**Comment by SleeplessOne1917** [comment]
Will this require a change on the backend as well?

**Comment by sunaurus** [comment]
Most likely you've already thought of this, but I would like to highlight that it's probably quite important to do any polling only in active tabs, for example using https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilityState

**Comment by dessalines** [comment]
Its on the navbar component, which has the unread counts.

**Comment by sunaurus** [comment]
@dessalines Many users will have tens (in some cases even hundreds) of tabs open, so it could be extremely useful to either A) completely pause polling or B) just skip invoking the `promiseFn` in your `poll` function whenever `document.visibilityState != "visible"`

**Comment by sunaurus** [comment]
If an instance has an average of 1000 users who leave 100 tabs open in the background, then not pausing background polling will generate 288000000 extra unnecessarsy http requests in a day (1000 users * 100 tabs * 2880 requests in a tab per 24h)
