### ISSUE TITLE
Login stalls when wrong password

### ISSUE THREAD

**Issue by frorayz** [LemmyNet/lemmy-ui#1154]
### Issue Summary

The login indefinately goes to a spinning bar when password is wrong and it does not give any indication of a wrong password. I even noticed this when something errors out (a long post) the submit button also stalls. A visual walk-through of the bug is given below.

In a previous issue, a user also pointed this out https://github.com/LemmyNet/lemmy-ui/issues/1062#issuecomment-1581293967

### Steps to Reproduce

https://github.com/LemmyNet/lemmy-ui/assets/32178410/525c3dbe-8ae1-4046-8741-ec205abaac78

### Technical details
- lemmy_1     | 2023-06-10T16:28:44.060526Z ERROR HTTP request{http.method=GET http.scheme="http" http.host=xxx http.target=/api/v3/ws otel.kind="server" request_id=c8be2219-e29b-4ed4-b405-c425ac8026b1 http.status_code=101 otel.status_code="OK"}: lemmy_server::api_routes_websocket: password_incorrect: password_incorrect
- Ubuntu 22.04
- Running on docker

**Comment by nbm42** [comment]
Also occurs for user sign-up when  password fields entered are not the same

1. Navigate to sign up page, e.g. https://lemmy.ml/signup
2. Enter any username and different passwords in the masked fields
3. Click "Sign Up"

"Sign Up" button spins indefinitely.

**Comment by alectrocute** [comment]
Cannot reproduce on 0.18.
