### ISSUE TITLE
Use <aside> for every sidebar

### ISSUE THREAD

**Issue by HKayn** [LemmyNet/lemmy-ui#1157]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

I noticed that while the sidebar on the homepage is inside an `<aside>` tag, the sidebars on the community and post sites are inside regular `<div>` tags.

### Describe the solution you'd like

Each occurence of a sidebar in lemmy-ui should be inside an `<aside>` tag. This would fix the current inconsistency, further accessibility through additional semantic tags and also make selecting the sidebar in custom CSS themes easier.

I can probably make a PR for this, I just thought it might be more appropriate to open an issue first.

**Comment by ZeusOfTheCrows** [comment]
i disagree with `<aside>`, i think if anything it should be a `<section>`. aside is used for [an aside](https://dictionary.cambridge.org/dictionary/english/aside#:~:text=a%20remark%20or,guide%20rather%20special.), section is used for a part of a page

i do agree with semantic html in general though, and i would expand it to, for example, every post (and perhaps every comment) could be an `<article>`

**Comment by HKayn** [comment]
#1327 closes this.
