### ISSUE TITLE
Add default profile picture

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#1162]
This should hipefully keep things lined up visually. 
Perhaps the Lemmy lemming would be a good default pick. It could be worth letting instance admins be able to set their own default pfps, although that would require a backend change.

**Comment by krestenlaust** [comment]
Related issue: #1174

**Comment by SleeplessOne1917** [comment]
> Personally, I think it falls a bit short of the responsibilities of an instance, to set a default profile picture, since they (as far as I know) aren't supposed to be responsible for the theme, but rather simply focus on hosting.

I was thinking of providing a default lemmy icon so that instance admins don't need to set their own, but giving them the ability to do so if they desire.

**Comment by krestenlaust** [comment]
It might be a good idea to leave it as an option to the instance admin, I agree.

It could also be possible to do it the other way around, where everyone (across instances) has the same default profile picture, but depending on what instance you're viewing as, it changes.
