### ISSUE TITLE
Format the language selection options in the admin panel and user settings as checkboxes

### ISSUE THREAD

**Issue by Wiggoggs** [LemmyNet/lemmy-ui#1182]
Problem:
When setting up an instance and selecting a language for the instance, the warning about deselecting "Undetermined" and the format of the list make it seem like you can only have one language selected. I did not realize that in order to see all the posts in my instance that I needed to _also_ select every language. I thought that "Undetermined" was a catch-all and would allow me to see everything.

Solution:
Format the language selection menu using checkboxes to make it intuitively apparent that you need to select multiple languages. Or add a message to the "Undetermined" warning that you need to select multiple languages.

**Comment by lionirdeadman** [comment]
Closing in favour of https://github.com/LemmyNet/lemmy-ui/issues/1935 after some discussions
