### ISSUE TITLE
Subscription confirmations show up in the wrong window when more than one is open

### ISSUE THREAD

**Issue by kvibber** [LemmyNet/lemmy-ui#1187]
### Issue Summary

I set up an alt on Lemmy.world and started subscribing to communities through there. I'd look for communities, open them in new tabs, then go to each tab, look at the recent posts and subscribe.

Often I'd open a tab and find that instead of the Subscribe box in the upper right, it showed that I'd already joined...except it also showed a *different* community, one that I had open in another tab!

As near as I can tell, the update from subscribing to one community was either hitting all open tabs that had a Subscribe box in them, or was just hitting whichever tab I had visible, even when it was a message for a different community than I was looking at.

### Steps to Reproduce

1. Search for communities that you don't subscribe to
2. Open several in new tabs.
3. Go to a new tab and subscribe.
4. Repeat step 3 until you find one where the Subscribe/Joined status and name in the sidebar don't match the community that's actually on the page.

### Technical details

Browser: Firefox 114 on Windows.
Server: Lemmy.world: UI: 0.17.4-rc.4 BE: 0.17.4-rc.1

**Comment by alectrocute** [comment]
Sounds like websocket wackiness unique to 0.17. Closing.
