### ISSUE TITLE
If the minimize reply thread button was on the left of the username it'd always in the same location.

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy-ui#119]
currently the minimize button is to the right of the username so the position can vary widely depending on peoples username, if they have a profile picture, and on events like someone's cake day it will also be pushed more to the right. If it it was always to the left of the username I could keep my mouse in the same location while scrolling down to hide threads I'm not interested in.
![image](https://user-images.githubusercontent.com/12674582/103329642-862bd200-4a2b-11eb-8e2a-fdbb76e9791d.png)

**Comment by dessalines** [comment]
Its mostly preference, but I really don't like how it looks when user names and icons aren't aligned to the text below. They're much more important than the collapse button.

**Comment by NIXOYE** [comment]
The minimize button can be on its own column to the left so it doesn’t shift usernames.

Its not just preference though is a pretty big UX benefit.

**Comment by dessalines** [comment]
What UI benefit? Why is it difficult to move your finger / mouse a few centimers over to collapse a thread? That's not enough of a reason to add a whole offset for everything.

**Comment by NIXOYE** [comment]
Its a UX benefit not a UI benefit. The user experience is much greater to not need to fetch for a button your going to be pressing multiple times in a thread. You don’t need to offset anything the column can be in the empty space on the left that is already there.
