### ISSUE TITLE
Signup page fails to create account if username contains "-"  characters, but doesn't tell the user why it's not working

### ISSUE THREAD

**Issue by shodanx2** [LemmyNet/lemmy-ui#1196]
Username and email input validation, either fail or refuse to work if a "-" is included.

You click signup and, it just sits there, you hit refresh and fill in everything again, still nothing, it's just not doing anything when you hit signup.

It doesn't say why, it doesn't even give an error, it just doesn't do anything.

**Comment by dullbananas** [comment]
This is because the form handles onsubmit but not oninvalid

**Comment by RocketDerp** [comment]
Lemmy 0.18 is now in beta testing on test server enterprise.lemmy.ml -can you please test to see if  this issue get fixed?

**Comment by shodanx2** [comment]
Just tried in the specified instance
It did not work until the very last dash character was removed from the username

It immediately went through after I removed the last one

Email had dashes no problem

I typed a guid for the username and email

**Comment by RocketDerp** [comment]
Does the user interface behave in better in telling you what is wrong?

**Comment by shodanx2** [comment]
No, the sign up button does literally nothing when pressed, not even changing colour to indicate focus

I am using Firefox for Android plus darkreader

When I initially made this report, I was using Firefox on Windows plus darkreader

**Comment by RocketDerp** [comment]
Did you try a version 0.18.0 server? if you don't want to create real accounts for testing, there is http://enterprise.lemmy.ml testing server
