### ISSUE TITLE
Main page - link to sorting help is broken

### ISSUE THREAD

**Issue by andypiper** [LemmyNet/lemmy-ui#1197]
### Issue Summary

On the Lemmy front page (I've checked this on both lemmy.ml and lemmy.world) the small (?) icon is intended to link to the [votes and ranking help page](https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html ), but the rendered link is wrong and results in a 404 page.

### Steps to Reproduce

1. Open the front page of a Lemmy instance
2. Click on the question mark help icon (hover help says "sorting help") which sits alongside the sorting buttons at the top of the main column.
3. Page result is 404

### Technical details

Here's a screenshot to show what is being described.

<img width="882" alt="Screenshot 2023-06-12 at 10 23 45" src="https://github.com/LemmyNet/lemmy-ui/assets/552452/5936735e-18b7-4547-a714-5a6bc826ab06">

Note that the linked target URL shown in the browser at the bottom of the page includes the complete link to the Lemmy docs getting started page, followed by a relative link to the votes and ranking page.

This appears to be set [here](https://github.com/LemmyNet/lemmy-ui/blob/d56addf7d6b97875696d656eb995b75c34fa06d5/src/shared/utils.ts#L66).

```
export const sortingHelpUrl = `${joinLemmyUrl}/docs/en/users/03-votes-and-ranking.html`;
```

I'm unclear how the `joinLemmyUrl` is being made to include the whole link to the getting started page (which is defined as a separate constant in the same file).

**Comment by fheft** [comment]
Thanks for reporting! This has been fixed in [a commit](https://github.com/LemmyNet/lemmy-ui/commit/1df655d40d0556305c4080eb21e0de2ccc906cc5) one week ago. This commit has not yet been released or deployed to the Lemmy instances, so that's probably the reason for the confusion: it's fixed in the code but broken on Lemmy instances :)

**Comment by andypiper** [comment]
Thank you! I did a search for open issues and PRs but couldn't see anything - glad to know this is coming and apologies for an unnecessary issue 👍🏻
