### ISSUE TITLE
clicking on comments or posts on remote user redirects to undefined user

### ISSUE THREAD

**Issue by krawieck** [LemmyNet/lemmy-ui#120]
When visiting any remote user, (user from another instance) upon switching tabs I get redirected to another user with name `undefined`. I assume that it's not a sabotage by said user, but an innocent bug. So that's why I'm reporting it.

Example:

When viewing [Muad'Dibber](https://lemmy.ml/user/14796)'s account, clicking on comments tab should redirect to [this url](https://lemmy.ml/u/14796/view/Comments/sort/New/page/1), but instead it redirects to [this url](https://lemmy.ml/u/undefined/view/Comments/sort/New/page/1)

https://user-images.githubusercontent.com/10037914/103385776-176a7980-4afc-11eb-8d29-aa2d84088537.mov

**Comment by dessalines** [comment]
Thx, I'll look into this soon.
