### ISSUE TITLE
Improve the contribution templates to enforce standard behavior

### ISSUE THREAD

**Issue by krestenlaust** [LemmyNet/lemmy-ui#1200]
Right now, people seem to disregard the contribution templates, like I've done here (removing the template and writing a wall of text). Adding more firm language and a disclaimer in the beginning that tells people to leave in the headers. There's a ton of enhancement suggestions but it's hard to recognize an issue when they're all walls of text.

Replacing the comments in the templates with "Replace this text" or similar, could also nudge people towards not removing everything.

**Comment by Nutomic** [comment]
Contributions welcome.

**Comment by krestenlaust** [comment]
This is an awesome change, it's much better now!
