### ISSUE TITLE
Lemmy is showing in a different language than my browser's and OS's

### ISSUE THREAD

**Issue by brunofin** [LemmyNet/lemmy-ui#1205]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

Hello, for all Lemmy instances I visit, Lemmy loads in Portuguese. While I do speak Portuguese, it is not my operating system's language neither my browser's, and I cannot find a way to change it back to English. 

Here's my Chrome's language settings:

![image](https://github.com/LemmyNet/lemmy-ui/assets/8077237/7621eac1-482b-4936-a11d-a53d3fa674c6)

Here's Windows 11's language settings:

![image](https://github.com/LemmyNet/lemmy-ui/assets/8077237/04e71ebc-a89d-4431-9349-03113d0346fc)

And here's how I see Behaw for example:

![image](https://github.com/LemmyNet/lemmy-ui/assets/8077237/20b9b417-67c8-4900-914c-10d0049a20a0)

I imagine playing around with the priorities would help as maybe setting a less-specific variation of english as the top language.

**Comment by kennypu** [comment]
I experienced the same. Playing around with it, I can't figure out the exact pattern, but I have English (US, set as main Chrome Language), English, and Japanese. 

If the order is 
1. English (US)
2. Japanese 
3. English

Lemmy turns it into Japanese (expected is English (US)  )

If the order is
1. Japanese
2. English (US)
3. English

Lemmy still uses Japanese 

If the order is 
1. English (US)
2. English
3. Japanese 

It will use English. 
I would imagine it should always use either whatever is at the top, or whatever is set to the Chrome UI.

**Comment by MaartenStaa** [comment]
Looking at the examples above, I guess it only knows what to do with "English", and not "English (US)" or "English (UK)" (or the respective language codes).

**Comment by IrealiTY** [comment]
What is wrong with having an option in the footer or the user profile settings to set a preferred language?

**Comment by ledlamp** [comment]
> What is wrong with having an option in the footer or the user profile settings to set a preferred language?

it's hard to find it when you can't read anything, and a totally unnecessary inconvenience when the browser already said what language it wants; this is a bug.

there is a setting in user settings but this doesnt help unregistered visitors

**Comment by CSRavasio** [comment]
> a totally unnecessary inconvenience when the browser already said what language it wants

Apart from the fact that this automatic selection very much does not work as it should, I don't see how offering an additional setting is an "unnecessary inconvenience", that's not a very user-friendly way of going about it. Also, I would like to be able to set this separately, there can be any number of reasons why you might want to be using a different language than set by the browser.

**Comment by ledlamp** [comment]
that's not what i meant, you shouldn't have to set it because it should be already set to your preferred language.

the setting already exists.

**Comment by ledlamp** [comment]
![image](https://github.com/LemmyNet/lemmy-ui/assets/103386533/5d329727-67f5-49e0-b350-4420a4c68435)

as you can see it's kind of hard to find it with the wrong language...
