### ISSUE TITLE
Add checkboxes to issue template

### ISSUE THREAD

**Issue by RayBB** [LemmyNet/lemmy-ui#1214]
### Is your proposal related to a problem?

> The main thing I want to keep from those, is the checkboxes to make sure people have searched for their issue before. We have so many duplicates on all our repos, and it'll likely help.

Per: https://github.com/LemmyNet/lemmy-ui/pull/1211#pullrequestreview-1475594666

### Describe the solution you'd like.

Add the checkboxes from here: https://github.com/LemmyNet/lemmy/blob/main/.github/ISSUE_TEMPLATE/BUG_REPORT.md

Docs: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema#checkboxes

### Describe alternatives you've considered.

n/a

**Comment by krestenlaust** [comment]
Agree. I wish github would show the search results to the title, when creating an issue, like stackoverflow does.
