### ISSUE TITLE
Security policy

### ISSUE THREAD

**Issue by Nothing4You** [LemmyNet/lemmy-ui#1218]
### Question

Please set up a security policy with a method to privately report security vulnerabilities.

**Comment by boehs** [comment]
There is already one: https://github.com/LemmyNet/lemmy/blob/main/SECURITY.md

**Comment by krestenlaust** [comment]
Shouldn't it be possible to send secure mail as well?

**Comment by Nothing4You** [comment]
thanks, didn't check the main repo, the security policy should be copied to this repo as well.
