### ISSUE TITLE
Exclamation community links should automatically link to the community via the user's own instance

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy-ui#1227]
### Is your proposal related to a problem?

Currently, when I start typing `!community@instance.domain`, it will auto-suggest links and then convert it into a markdown link, linking to that community directly. This works naturally, but it break the flow of the user browsing by transporting them to another instance which of course then prevents them from subscribing to it.

I also don't want the autocomplete to use the writer's own instance either as that link won't work well for any user user from other instances.

### Describe the solution you'd like.

What I want to suggest is that a text in the form of `!community@instance.domain` is automatically parsed by the Lemmy UI as a link without needing markdown. When this happens, the link should **always** point to the user's own instance. So for example if I'm clicking on the link `!autism@lemmy.world` that I found in the comments of a post in `lemmy.fmhy.ml` while I'm browsing it as `@db0@lemmy.dbzer0.com`, then that link should automatically link me to `https://lemmy.dbzer0.com/c/autism@lemmy.world`

Whereas someone logged in from `lemmy.ml` clicking the same link would be directed to `https://lemmy.ml/c/autism@lemmy.world`

This would natively allow both users to subscribe and comment in that community, without breaking their flow.

### Describe alternatives you've considered.

The alternatively is the very disruptive process of editing one's own URL, or  using the search option extra. None of which are particularly user friendly.

EDIT: I just realized one can use the markdown link format `[/c/community@instance.domain]` to achieve the same effect, but this is not done by default with the autocomplete function. If the autocomplete would fill in the relative link instead of the absolute, that would also work

### Additional context

By smartly linking communities using each user's currently logged-in instance, it makes the lemmyverse seem way more natural and interconnected.

**Comment by Undearius** [comment]
Seems to be along the lines of:
[Automatically stay on an instance, when given a link to another #1048](https://github.com/LemmyNet/lemmy-ui/issues/1048)
[Use local urls for community and user urls. #369](https://github.com/LemmyNet/lemmy-ui/issues/369)
[Instance agnostic links #2987](https://github.com/LemmyNet/lemmy/issues/2987)

**Comment by db0** [comment]
Closing this as duplicate.
