### ISSUE TITLE
Set cookie flag `SameSite=Secure` to prevent CSRF

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#123]
Some links that explain it:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite

https://wanago.io/2020/12/21/csrf-attacks-same-site-cookies/

At the same time, it would be good if we could set `Secure=true` in production, so that cookies can only be accessed over TLS, which makes man-in-the-middle attacks more difficult. Info is further down in [this page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie).

**Comment by SleeplessOne1917** [comment]
This is done in [set-auth-cookie.ts](https://github.com/LemmyNet/lemmy-ui/blob/64c0ba37d2d68de6f816da4b12af37b81296aeac/src/shared/utils/browser/set-auth-cookie.ts#L4).
