### ISSUE TITLE
[Bug]: You can post images into titles

### ISSUE THREAD

**Issue by misnina** [LemmyNet/lemmy-ui#1232]
### Summary

Might be opening pandora's box for a moment until it's fixed. Not a bug, but unintended side effect. As cute as it is, you can just put huge images into the titles of your posts that will show on the feed. I would think it would be hard to make exceptions in the markdown, it's possible for UI just to hide/remove/or shrink images in that particular field?

![screenshot of an inline image in a post title](https://misnina.neocities.org/Screenshot%202023-06-13%20095131.png)

### Steps to Reproduce

1. Create new post in a community.
2. In your title add the markdown for an image `![screenshot of an inline image in a post title](https://misnina.neocities.org/Screenshot%202023-06-13%20094009.png)` of any image (preferably large) into the title 
EDIT: This is not the original image I used, I have linked the wrong one, if that matters. `![cain](https://misnina.neocities.org/images/cain_persona_5x.png)`
3. Maybe do this in a contained space that it wouldn't disrupt the feed while testing.

### Technical Details

No errors.

### Version

v0.17.3

**Comment by Nutomic** [comment]
I cant reproduce this with 0.17.4

https://enterprise.lemmy.ml/post/416616

**Comment by misnina** [comment]
That might raise another bug then, this instance that I know just installed today can still see my displayed images. If an older version can still push through images it would be bad. Though checking again, that one I listed to test was actually the markup for the image I put in the github, when I meant for it to be the original image I used. The one on this github does not work for me either. I meant this one, I didn't think it mattered. ```
![cain](https://misnina.neocities.org/images/cain_persona_5x.png)
```

For reference this community here is my instance community. [https://crystals.rest/c/crystal_rest_meta](https://crystals.rest/c/crystal_rest_meta)
This is from another instance I've been talking to: [https://zemmy.cc/c/crystal_rest_meta@crystals.rest](https://zemmy.cc/c/crystal_rest_meta@crystals.rest) on BE: 0.17.4

I will keep it up on that post for now, however github is only giving me the option to close. I'm sorry I don't know how this works.

**Comment by Nutomic** [comment]
With that link it works. Seems like markdown in the title field should generally be ignored.

https://enterprise.lemmy.ml/post/416618

**Comment by Leanna-o** [comment]
Can be solved with a simple css rule though:

```css
.post-title img {
  max-height: 1em !important;
  max-width: 10em !important;
}
```
Restricts any img under an element with the .post-title class to be max 1EM high *(1 character in the current font size)*

_(Adding the !important tag is not necessary at all and not generally good practice, as it overrides anything, but in the edge case there's some more specific CSS rule for images it won't be overridden.)_
