### ISSUE TITLE
[Bug]: Help icon opens a broken link 404

### ISSUE THREAD

**Issue by ngosang** [LemmyNet/lemmy-ui#1233]
### Summary

Help icon in user settings opens a broken link 404

### Steps to Reproduce

1. Go to user settings
2. Click on the Sort help icon
![image](https://github.com/LemmyNet/lemmy-ui/assets/10577978/edd5c03c-7bd0-4d4a-9e77-fa376c829965)
3. 404 page
![image](https://github.com/LemmyNet/lemmy-ui/assets/10577978/6d16ff7a-816e-4a41-a524-2a3281964108)

### Technical Details

.

### Version

BE: 0.17.4

**Comment by Pome-ro** [comment]
This URL points to: https://join-lemmy.org/docs/en/users/01-getting-started.html/docs/en/users/03-votes-and-ranking.html
But should be pointing to: https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html

**Comment by alectrocute** [comment]
Thanks for the bug report. Luckily, this has already resolved in https://github.com/LemmyNet/lemmy-ui/pull/1063. This issue ticket can safely be closed.
