### ISSUE TITLE
[Bug]: More Replies button does not show more replies when clicked

### ISSUE THREAD

**Issue by LilyIsWasHere** [LemmyNet/lemmy-ui#1234]
### Summary

Clicking the "X More Replies" button does not show the hidden replies.

### Steps to Reproduce

1. Go to the comments of any post with hidden replies. (i.e. https://lemmy.blahaj.zone/post/103959)

2. Click the "X More Replies" button.
![image](https://github.com/LemmyNet/lemmy-ui/assets/78503374/1ab80db9-87da-48a2-8096-a61f7fae4036)
 
3. No new replies are shown.

### Technical Details

"GetComments" objects are logged to the console when the button is clicked, one for each hidden comment. There appears to be no data in these objects. I'm unsure if this is intended behaviour or not. 
![image](https://github.com/LemmyNet/lemmy-ui/assets/78503374/a13aecf0-d02a-4b6b-b383-c74dd6096a52)

### Version

BE: 0.17.2-kt.1

**Comment by Nutomic** [comment]
> 0.17.2-kt.1

Seems like you are running a patched version, we cant give support for that.

**Comment by LilyIsWasHere** [comment]
Ah my bad, didn't realize that I was.
