### ISSUE TITLE
Nsfw image thumbnail blur-area unintuitively large

### ISSUE THREAD

**Issue by g-rden** [LemmyNet/lemmy-ui#1245]
### Is your proposal related to a problem?

The clickable area of blurred nsfw thumbnails is smaller than the visible blurred image. This can lead to not clicking the clickable area by mistake.

### Describe the solution you'd like.

Expand the clickable area or limit the blurred area to the clickable area. Anyway the two areas should be the same size.

### Describe alternatives you've considered.

none

**Comment by fheft** [comment]
I think limitting the blurred area would be an easy fix using `overflow: hidden` on the wrapping container:

![image](https://github.com/LemmyNet/lemmy-ui/assets/787786/f84c0456-de89-4fff-a86c-92b79fde34b2)

I'll add a PR.

**Comment by g-rden** [comment]
I like it! But sfw images have rounded edges. So nsfw images probably should have those too.
