### ISSUE TITLE
Use og:image Opengraph attribute to populate link thumbnails 

### ISSUE THREAD

**Issue by cloventt** [LemmyNet/lemmy-ui#1247]
### Is your proposal related to a problem?

Currently, when adding a link to a website with an `og:image` tag in the head of the page's html, there is no image displayed as the thumbnail.

### Describe the solution you'd like.

It would be cool if the image linked in the `og:image` tag by the destination page was displayed in the lemmy UI as the thumbnail of the link.

### Describe alternatives you've considered.

Maybe a few solutions would be:

When creating a post you could:
1. scrape the destination `og:image` header and store the image hyperlink alongside the post metadata
2. scrape the destination `og:image` header and download a copy to the local instance's cache  (might invite some legal issues re: copyright)
3. set it automatically with some UI element to remove it if the user chooses
4. prompt the user that there is a thumbnail available, similar to the existing "Copy suggested title" functionality

When rendering the post you could:
1. use a stored thumbnail URL from the post metadata and hotlink to it in the page markup
2. check the link destination markup at render time, detect an `og:image` and hotlink to it in the page markup
3. use a version of the resource cached onto the lemmy instance

**Comment by dessalines** [comment]
Did you test this already?

The back-end already fetches opengraph images as the thumbnails.

**Comment by cloventt** [comment]
Thanks! Doesn't seem to be working on my instance, I'll check with the server operator.
