### ISSUE TITLE
"collapse all" button for comments

### ISSUE THREAD

**Issue by skomorokh** [LemmyNet/lemmy-ui#1249]
### Is your proposal related to a problem?

It's difficult to quickly skim top level comments without getting caught up in long chains of replies.

### Describe the solution you'd like.

A button to collapse all comment threads.

### Describe alternatives you've considered.

A key shortcut might suffice but would be less discoverable. It would be a nice touch to have in addition eg. a shortcut for skipping to the next thread so that you can leave them expanded and scroll then hit the skip combo when you've lost interest in that particular thread.

**Comment by JohanAR** [comment]
Is this a duplicate of #1061?

**Comment by skomorokh** [comment]
Duplicate of #1061

**Comment by skomorokh** [comment]
Duplicate of #1061
