### ISSUE TITLE
A way to see the number of subscribers to a community

### ISSUE THREAD

**Issue by Kommynct** [LemmyNet/lemmy-ui#1257]
### Is your proposal related to a problem?

I can't see the number of people subscribed to a community on the community page

### Describe the solution you'd like.

I see no reason this shouldn't be exposed to the user

**Comment by Nutomic** [comment]
Its already shown in the sidebar, near the bottom.

![Screenshot_20230614_132446](https://github.com/LemmyNet/lemmy-ui/assets/1044450/5fd53569-ad1b-43f6-9445-3a044e037b64)

**Comment by Kommynct** [comment]
Wellp, i'm stupid, sorry!
