### ISSUE TITLE
[Bug]: When browsing "All" in Hot sorting, new posts show up at the beggining of the page 

### ISSUE THREAD

**Issue by georgeharja** [LemmyNet/lemmy-ui#1279]
### Summary

Pretty self explanatory. When you want to browse "All", new posts just pop up at the beginning of the page, so essentially you can't browse "All", since everything shifts constantly.

### Steps to Reproduce

1. Go to "All"
2. Sort by Hot
3. Try to scroll down
4. New posts constantly pop up at the top

### Technical Details

Using Firefox, latest version. No console errors.

### Version

Doesn't show UI Version, only: BE: 0.17.4

**Comment by alectrocute** [comment]
This issue is likely irrelevant due to migration away from websocket usage in `0.18`, I believe this issue can be safely closed.
