### ISSUE TITLE
Make the [-] minimize-comment button consistently placed

### ISSUE THREAD

**Issue by Leanna-o** [LemmyNet/lemmy-ui#1280]
### Is your proposal related to a problem?

Currently the minimize-comment button is placed after the commenters username:
![image](https://github.com/LemmyNet/lemmy-ui/assets/136490143/1b122e31-dc7d-4890-b060-263d3192f9da)

This leads to a wonky comment-reading experience, as you have to locate the button every time, which can be an issue in big threads with many comments and replies. 

### Describe the solution you'd like.

Place [-] before the commenters profile picture instead
* This lets you instinctively know where the button will be located
* This additionally improves comment-depth readability, as the [-] button can be seen in your periphery and acts as a marker, showing with its horizontal position the depth of the comment you're reading.

### Describe alternatives you've considered.

*An alternative is to make the vertical stripes next to the comments clickable, to make it intuitive which nested comments will be minimized when you click it. However this is a bit more work, so it's best to keep it simple for now.*

*If profile pictures become obligatory or blank ones are inserted in front of usernames, then that would serve as an additional visual indicator of depth instead, and the [-] could be placed after the picture.*

**Comment by alectrocute** [comment]
This has been resolved in https://github.com/LemmyNet/lemmy-ui/pull/1173.

**Comment by Leanna-o** [comment]
Glad to see it! 😄
