### ISSUE TITLE
Add slow mode on the feed

### ISSUE THREAD

**Issue by teacherbuknoy** [LemmyNet/lemmy-ui#1282]
### Is your proposal related to a problem?

When sorting posts by *New*, an influx of new posts continuously loads, so when users try to read them, they keep scrolling down, or the layout keeps janking up and down.

### Describe the solution you'd like.

Introduction of a slow mode will help with this. Mastodon has this feature, and when it's enabled, instead of continuously loading new posts, they are hidden behind a button.

<a href="https://ibb.co/8rhrC8k"><img src="https://i.ibb.co/YcrcCjg/Screenshot-2023-06-15-at-03-47-52-Appearance-Mastodon.png" alt="Mastodon's settings UI with Slow Mode enabled" border="0"></a>

<a href="https://ibb.co/VL00mfW"><img src="https://i.ibb.co/b6jjJcg/Screenshot-2023-06-15-at-03-48-13-Mastodon-1.png" alt="Mastodon's federated timeline showing updates that 8 new items have been posted but they are hidden at the time being." border="0"></a>

### Describe alternatives you've considered.

Another alternative could be making the updates slower by default. I'm aware that Lemmy uses websockets, so I was thinking maybe make the updates come in intervals (say, updates only load on the UI every 5 minutes or so), and this is configurable via the settings page.

**Comment by Nutomic** [comment]
This has been reported many times, and will be fixed soon in 0.18
