### ISSUE TITLE
Replying to a notification of a comment on a removed post spins forever

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1291]
![Screenshot_20230614-184221](https://github.com/LemmyNet/lemmy-ui/assets/177491/2806cf2e-78f4-4892-9e14-5ee2d505c0f4)

### Summary

Post got removed by mods. Went to go reply to their comment and the spinner on the button just spun forever no error message. 

### Steps to Reproduce

1. Get a notification on a post
2. Mod removed post
3. Reply to notification

### Technical Details

Android pwa browser app pixel 7 pro

### Version

0.17.4

**Comment by yaneony** [comment]
Having same but on content creation: https://github.com/LemmyNet/lemmy-ui/issues/1289

**Comment by alectrocute** [comment]
I cannot reproduce. Will reopen if it is reported again or reproduced by another. Thanks!

**Comment by Original-2** [comment]
![image](https://github.com/LemmyNet/lemmy-ui/assets/61599006/c99e819f-86c4-4139-aa33-5909e17da7a7)

having the same issue on desktop

browser: firefox 114.0.2 (64-bit)
OS: Fedora Linux 37 with kernel 6.3.8-100.fc37.x86_64
