### ISSUE TITLE
A moderated communities post feed

### ISSUE THREAD

**Issue by tcripe4** [LemmyNet/lemmy-ui#1294]
### Requirements

- [ ] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [ ] Did you check to see if this issue already exists?
- [x] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

No

### Describe the solution you'd like.

On the main page where you can select “All, Local, Subscriptions” it would be awesome if there was an additional option for those who are moderators to be able to also have a “Moderated” option so we can scroll through all posts of communities we moderate

### Describe alternatives you've considered.

The only other option would be to only subscribe to communities we moderate but that’s pretty inconvenient

**Comment by SleeplessOne1917** [comment]
That sounds like a good idea. This will require a backend change as well as a frontend change. It's fine to keep this issue open, but please also open an issue [on the backend repo](https://github.com/LemmyNet/lemmy).

**Comment by tcripe4** [comment]
> That sounds like a good idea. This will require a backend change as well as a frontend change. It's fine to keep this issue open, but please also open an issue [on the backend repo](https://github.com/LemmyNet/lemmy).

Just submitted it

**Comment by biosfood** [comment]
I think I can work on this issue. Aside from changes in the code, is there any official API documentation where the changes would also need to be published?
