### ISSUE TITLE
Convert !community@instance into a clickable link

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1297]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

People seem to share references to communities in comments in the format !community@instance to use it I need to
1 copy it
2 expand hamburger menu in nav
3 go to search 
4 paste it in the search box
5 click search
6 click the first result

### Describe the solution you'd like.

Let me click the text and go right to the community 

### Describe alternatives you've considered.

None

**Comment by trashhalo** [comment]
A path to doing this would be to update markdown-it/linkify to recognize the !community@server text.

- Here is the code you would need to change. https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/utils.ts#L714
- Here is how you access linkify from markdown it. https://github.com/markdown-it/markdown-it#linkify
- Here is how you add a custom link type to linkify. https://github.com/markdown-it/linkify-it#example-2-add-twitter-mentions-handler

Options for where to link them to:
- Instance's page for community. `!selfhost@lemmy.ml` = `https://beehaw.org/c/selfhost@lemmy.ml`
- Search results for community `!selfhost@lemmy.ml` = `https://beehaw.org/search/q/!selfhost%40lemmy.ml/type/All/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1`

**Comment by trashhalo** [comment]
@dessalines are you good with the implementation plan as defined in the previous comment, and do you have a preference between the two options on where these links could go?

I ask because I want to make sure this ticket is ready to work so someone can pick it up and just build it as is.

**Comment by Dakkaron** [comment]
Apparently, relative links also do the trick. So `!selfhost@lemmy.ml` could also just link to `/c/selfhost@lemmy.ml` and let the browser fill in the domain name.

Then there is no need to insert the instance domain name.

**Comment by trashhalo** [comment]
Fixed by https://github.com/LemmyNet/lemmy-ui/pull/1462
