### ISSUE TITLE
Support for post tags/flair

### ISSUE THREAD

**Issue by db0** [LemmyNet/lemmy-ui#1302]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Most reddits implement a sort post "flair" system, allowing submitters and mods to sort posts according to context, and this can be further used to filter-in or filter-out all such posts in a community.

![image](https://github.com/LemmyNet/lemmy-ui/assets/296513/80140002-0308-4b3a-9588-d4dd81890571)

Currently inside a lemmy community, there's no way to separate topics. Allowing tags would use an existing fediverse functionality to allow for more precise filtering.

### Describe the solution you'd like.

I want to implement tags (or we can also call them flairs) inside lemmy communities. Mods can pre-specify allowed post tags, and users just select one from them when posting (or none at all). Mods should be allowed to set tags on other user's posts.

Allow lemmy to filter a community based on tags. This should allow both inclusive and exclusive filtering, or combined. Clicking on a post tag, should take one to a view of the community with only that tag filtered-in.

As far as I know, the tag functionality already exists in activity pub. If we built on top of that, this would allow them those tags to be searchable accross the whole fediverse, and not just Lemmy

### Describe alternatives you've considered.

None I can think of.

**Comment by gbrindisi** [comment]
Related: https://github.com/LemmyNet/lemmy/issues/1456

**Comment by db0** [comment]
Oh shit, I searched and posted in the wrong repo. No wonder I couldn't find anything. Also [#LemmyNet/lemm](https://github.com/LemmyNet/lemmy/issues/317)
