### ISSUE TITLE
Remove notifications for new frontpage posts

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#132]
Or at least add an option to disable them, because they are pretty annoying.

**Comment by dessalines** [comment]
This needs a back-end setting too.

**Comment by Nutomic** [comment]
@dessalines could you please explain why you added these notifications? Personally I dont see the use, because new posts are automatically inserted in the frontpage. On the other hand, it is very distracting when you are currently reading something. Or writing something (I'm currently not sure if these also show up when viewing a post).

Overall it just seems to be very distracting, and present the new post as something very urgent, even though its still gonna be there in an hour or in a day. I think this is also related to the topic of unhealthy mechanisms  in social media.

**Comment by dessalines** [comment]
I really like having these notifs, but I could see not wanting them. When we add a setting for this, we can set it to off by default.
