### ISSUE TITLE
Add "slow mode" without live updates

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#133]
In this mode, Lemmy would not insert new posts, comments or votes directly into the page, but just show an "update" button which inserts all the new items once clicked.

Mastodon has something similar:

![Screenshot_20210120_024000](https://user-images.githubusercontent.com/1044450/105115071-148df380-5ac0-11eb-80ea-505574f2ab69.png)

![Screenshot_20210120_023906](https://user-images.githubusercontent.com/1044450/105115078-16f04d80-5ac0-11eb-865b-0c6c45f4c695.png)

**Comment by dessalines** [comment]
I'm thinking this will be an account setting, and basically just disable websockets, so all new info requires a page refresh.

**Comment by poVoq** [comment]
Actually I just noticed a related "bug". When the auto update happens and you are just composing a reply, then that draft gets lost, which is a quite serious flaw from a usability point of view.

**Comment by dessalines** [comment]
Can you replicate this? I've solved this a few times but people still say its happening.

**Comment by poVoq** [comment]
Not really, but I guess it happens when the update comes shortly after you start writing? I was about one sentence into a new reply on the main thread (not a comment reply) when someone replied to one of my previous comments and the auto-update caused the wipe of the draft.

**Comment by dessalines** [comment]
I just tried to mess around with this on https://enterprise.lemmy.ml by making two users, and having them open in different firefox containers. Comment replies, edits, deletes, don't seem to wipe the other users fields.

**Comment by lboklin** [comment]
> I just tried to mess around with this on https://enterprise.lemmy.ml by making two users, and having them open in different firefox containers. Comment replies, edits, deletes, don't seem to wipe the other users fields.

I had it happen to me while composing a top-level comment and another comment was made (I don't remember if it was a reply or top-level comment).

In any case, I consider the live updates disruptive and jarring, so I'd appreciate an option to turn it off.

**Comment by dessalines** [comment]
#169 may make this moot.

**Comment by lboklin** [comment]
I don't think it does, because the purpose of slow mode is to prevent any rearranging or new things popping in, while with #169 new comments will still appear.

**Comment by slash-zero** [comment]
By the way, this still happens in the web ui.

**Comment by maxh-** [comment]
I think this will become a major issue. Having the page shift around while trying to read content, write content or clicking links really hampers the user experience.

**Comment by fenn1c** [comment]
Please bump this, I’ve been trying to find a setting to disable the live inserts of new stories in All, I can never read a post before it vanishes!

**Comment by Nutomic** [comment]
This will be fixed soon in 0.18

**Comment by Die4Ever** [comment]
honestly I just think live updates should be disabled for now, they add load to the servers which we don't need right now, and they're a bit buggy

**Comment by dessalines** [comment]
Not relevant as the next release removes live updates.
