### ISSUE TITLE
Retitle Send Message

### ISSUE THREAD

**Issue by L3v3L** [LemmyNet/lemmy-ui#1330]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

On the send message to a user page, the title is "Create Private Message", this creates a false sense of privacy.

### Describe the solution you'd like.

Retitle to "Post Message" , the word post entails a more public view.

### Describe alternatives you've considered.

* removing only the word Private : "Create Message"
* going with a more descriptive: "Send Message"
* more tecnical: "Submit Message"

### Additional context

Take note that this applies to both the title of the page, and the header

**Comment by SleeplessOne1917** [comment]
This only requires a change on the [translations repo](https://github.com/LemmyNet/lemmy-translations). Closing because nothing needs to be done here.
