### ISSUE TITLE
[Bug]: New posts get loaded above any instance's pinned posts

### ISSUE THREAD

**Issue by promitheas17j** [LemmyNet/lemmy-ui#1331]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

When new posts from communities I subscribe to get fetched and loaded they get displayed above the pinned post(s) of my instance. Essentially, with time the pinned posts get pushed lower and lower in the feed until the page is refreshed.
![Screenshot_000059](https://github.com/LemmyNet/lemmy-ui/assets/12212713/a50a0dce-c4bc-471d-aa70-99aba7a8f34d)

### Steps to Reproduce

1. Make sure there is a pinned post or multiple on your instance's home page
2. Wait until new posts from your subscriptions get fetched and loaded on the front page
3. The pinned posts should be pushed down lower in the feed

### Technical Details

Browser: Brave 1.51.114

### Version

BE: 0.17.4

### Lemmy Instance URL

iusearchlinux.fyi

**Comment by alectrocute** [comment]
This is resolved in #1081. It’ll be in the 0.18 release.
