### ISSUE TITLE
Ctrl-Return to send reply

### ISSUE THREAD

**Issue by KAMiKAZOW** [LemmyNet/lemmy-ui#1333]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Many forums and even mail clients allow sending a reply via Ctrl-Return (Cmd-Return on Macs), Lemmy (at least 0.17.4) doesn't.

### Describe the solution you'd like.

Adding that shortcut would be great.

### Describe alternatives you've considered.

That standard shortcut doesn't really have any alternatives.

**Comment by fheft** [comment]
This was already done in #1160, it'll be in the v0.18 release.

**Comment by KAMiKAZOW** [comment]
> This was already done in #1160

That's what I get for not spelling "Control" out. Thanks!
