### ISSUE TITLE
[Bug]: The button “sorting help” links to a page that 404s

### ISSUE THREAD

**Issue by ruudschilders** [LemmyNet/lemmy-ui#1348]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

The "sorting help" button lionks to a non-existing page
<img width="803" alt="Screenshot 2023-06-17 at 16 01 56" src="https://github.com/LemmyNet/lemmy-ui/assets/26794282/349cc8e4-d7e1-46ab-b1d3-090c7a8b8be0">

### Steps to Reproduce

Click the button.

### Technical Details

No, just a 404

### Version

0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by Tex2002ans** [comment]
User [Althea on lemmy.world narrowed the issue down](https://lemmy.world/comment/232730) to a wrong URL:

> - https://join-lemmy.org/docs/en/users/01-getting-started.html/docs/en/users/03-votes-and-ranking.html
>
>should probably be:
>
>- https://join-lemmy.org/docs/en/users/03-votes-and-ranking.html

**Comment by jsit** [comment]
This is fixed in 0.18.0, @SleeplessOne1917 @dessalines can be closed.
