### ISSUE TITLE
[Bug]: When signing up, entering a duplicate email or username results in spinning button forever.

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy-ui#1356]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

When signing up for a new account if a duplicate email address or username is entered, there is no indication of a possible conflict.  When clicking on the "Sign Up" button, a spinner just continues forever.  If the lemmy backend is inspected it throws an error about a duplicate email or username.  This is not reflected in the UI.

Suggest there be a check for a duplicate email or username before the user clicks "Sign up".

### Steps to Reproduce

1. Find a Lemmy instance.
2. Sign up with a duplicate email or username.
3. Spinner goes on and on.

### Technical Details

Tried all browsers and in regular and private mode.

Restarted backend and UI.

Reinstalled Lemmy and Lemmy-ui.

### Version

0.17.4

### Lemmy Instance URL

feddiverse.org

**Comment by RocketDerp** [comment]
Lemmy 0.18 is in beta testing on server enterprise.lemmy.ml - can you test to see if this issue has been fixed?

**Comment by mayniac1** [comment]
I'm not sure if it is the expected behavior, but I get a JSON error popup 2 times on the bottom left corner of the browser window in dark red.

**Comment by RocketDerp** [comment]
Ok, thanks for testing. I mentioned your test results on the announcement of 0.18 beta: https://lemmy.ml/post/1384478
