### ISSUE TITLE
Concider another captcha for people with bad eye sight

### ISSUE THREAD

**Issue by the-digital-anarchist** [LemmyNet/lemmy-ui#136]

**Comment by Nutomic** [comment]
Have you tried the audio captcha by clicking the green button directly under the captcha?

**Comment by the-digital-anarchist** [comment]
Ah sorry missed it, I think that's enough then

**Comment by TheCapsLock** [comment]
Even for people with good eyes it's pretty impossible to find the correct characters to enter. It gave me about 20 retries to succeed...
