### ISSUE TITLE
Consider separate strings for "top all" and "all"

### ISSUE THREAD

**Issue by JohanWinther** [LemmyNet/lemmy-ui#137]
## Problem
Right now the string "all" in Swedish is translated to "Totaltoppen" (roughly corresponding to "Top Total"). This is fine for the use case below where you are sorting by top posts for a certain period:
https://github.com/LemmyNet/lemmy-ui/blob/05065608f368427d0315912b8c89684996106fe5/src/shared/components/sort-select.tsx#L52-L56

However the phrase "all" is also used when selecting from which communities to show posts from on the frontpage (as in _show from all federated communities_ or _search all types of content_):
https://github.com/LemmyNet/lemmy-ui/blob/b74eecc72411dfdffa2d3f249db371d7981f86a0/src/shared/components/listing-type-select.tsx#L82-L89
This is fine in English
![image](https://user-images.githubusercontent.com/28558941/105493406-a6148580-5cb9-11eb-95ff-873209d3aad8.png)
but clearly not in Swedish
![image](https://user-images.githubusercontent.com/28558941/105493538-cfcdac80-5cb9-11eb-96b2-9ee7c3f430ca.png)

## Solutions
I have submitted a change on Weblate to change the translation from "Totaltoppen" to "Allt" which means "everything", but I don't really like that solution because "All" is actually not a sorting option but a filter option.

The solution I propose instead is to create new strings for the sorting options (which for some reason has already been implemented for `top_day` but not the others:
- `top_week` = "Top Week"
- `top_month` = "Top Month"
- `top_year` = "Top Year"
- `top_all` = "Top All Time"

With this solution we can have context relevant strings for **sorting** by "all" (time) or **filtering** by "all" (types).

**Comment by JohanWinther** [comment]
@dessalines Can I create English source strings in [LemmyNet/lemmy-translations](https://github.com/LemmyNet/lemmy-translations), or can only admins do it through Weblate?

**Comment by dessalines** [comment]
Hrm... since english is the source language, I don't know if it'll let you do it. But I'll change it manually right now to Top All Time.

**Comment by dessalines** [comment]
Here's the commit: https://github.com/LemmyNet/lemmy-translations/commit/086cc0b60512907a30455207948cc96756be3102
