### ISSUE TITLE
[Bug]: hight of title field doesn't expand when editing a post

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#1379]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

When editing a post, the text field for the title is always one line tall, even when the title uses more lines. This doen't happen when creating a post.

### Steps to Reproduce

1. Go to (or create) a post with a very long title
2. Press edit button

### Technical Details

No error

### Version

Backend 0.17.4, hidden UI version

### Lemmy Instance URL

https://lemmy.ml/

**Comment by SleeplessOne1917** [comment]
I was unable to replicate this issue with the latest changes. Can you replicate your issue on https://voyager.lemmy.ml?

**Comment by dullbananas** [comment]
It's fixed there
