### ISSUE TITLE
[Bug]: UI Password reset doesn't bubble up errors from backend, user gets a spinning button instead

### ISSUE THREAD

**Issue by Security-Chief-Odo** [LemmyNet/lemmy-ui#1380]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

A user attempts to reset their password from their own logged in settings page. No errors are reported to the user, they just get the spinner icon on the Save button

Backend logs show `invalid_password: invalid_password`, but the [only place I can find this verbiage](https://github.com/LemmyNet/lemmy/blob/d97ff65fe1e9c31e9f7c977a66100816816e07be/crates/api_common/src/utils.rs#L309) isn't passed back to the user. This function is set to check the password length (according to function name), but the error passed back is 
   1) Non helpful, unspecific
   2) Not raised to the user UI level

### Steps to Reproduce

1. Log in with your account, go to settings
2. Try to update your password using a new one that is under 10 characters in length
3. Watch the spinning button and wonder why its not doing much

This issue us not **specifically** related to the password length check, that's just the easiest way to reproduce the error. Error messages [should be propagated](https://uxplanet.org/how-to-write-good-error-messages-858e4551cd4) to the user, which should also _Be Clear And Not Ambiguous_. 

### Technical Details

Lenny Logs for this:
```
ERROR lemmy_server::api_routes_websocket: invalid_password: invalid_password
   0: lemmy_api::local_user::change_password_after_reset::perform
             at crates/api/src/local_user/change_password_after_reset.rs:20
   1: lemmy_server::root_span_builder::HTTP request
           with http.method=GET http.scheme="http" http.host=beehaw.org http.target=/api/v3/ws otel.kind="server" request_id=cce01cf8-ec69-46aa-8e13-587054240a28
             at src/root_span_builder.rs:16
```
Related Functions:

[changePasswordHTMLForm](https://github.com/LemmyNet/lemmy-ui/blob/10dbdd7fb7c4011b4a9f7753082e08e2e9344529/src/shared/components/person/settings.tsx#L302)

[password_length_check](https://github.com/LemmyNet/lemmy/blob/d97ff65fe1e9c31e9f7c977a66100816816e07be/crates/api_common/src/utils.rs#L307)

[PasswordChangeAfteReset](https://github.com/LemmyNet/lemmy/blob/d97ff65fe1e9c31e9f7c977a66100816816e07be/crates/api/src/local_user/change_password_after_reset.rs)

### Version

0.17.4

### Lemmy Instance URL

beehaw.org

**Comment by fmwight482** [comment]
From what I've seen, Lemmy does not propagate *any* error messages back to the user, and instead spins infinitely until they give up and try something (or somewhere) else. Users tend to interpret this as the server being too busy to respond, or simply being broken. In either case there's significant danger of chasing off people who aren't very technical but were willing to try something new.

**Comment by alectrocute** [comment]
Cannot reproduce in 0.18.
