### ISSUE TITLE
Create button to share post outside Lemmy. Ex copy url

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1381]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

When installing Lemmy UI to android as a pwa there is no way to get access to the url of a post. I wanted to share a link to the beehaw post to a slack group.

### Describe the solution you'd like.

An in app share button or copy url button

Id suggest the most ideal solution is to plug into th native share api https://codepen.io/ayoisaiah/pen/YbNazJ

### Describe alternatives you've considered.

Don't install the app as a pwa?

**Comment by trashhalo** [comment]
![Screenshot_20230618-190904](https://github.com/LemmyNet/lemmy-ui/assets/177491/18b38eee-d731-48cf-9249-e71a2e6e31e1)

Here is the page I wanted to share

**Comment by Undearius** [comment]
What was the browser used to install the PWA?

I'm experiencing the same thing from Firefox on Android.

Seems like some work was done here https://github.com/LemmyNet/lemmy-ui/pull/1029

**Comment by trashhalo** [comment]
> What was the browser used to install the PWA?

Android Chrome 114.0.5735.60 on a pixel 7 pro

**Comment by SleeplessOne1917** [comment]
A share button is part of the 0.18 release and was fixed with #1029 as @Undearius mentioned. From https://voyager.lemmy.ml
![image](https://github.com/LemmyNet/lemmy-ui/assets/28871516/f936140c-8839-429e-a40b-9108eb5094c5)
