### ISSUE TITLE
Add a Real-time Search Bar to Improve User Experience

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy-ui#1388]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Currently, users have to navigate to the search page to perform a search in Lemmy-UI. This process can be time-consuming and may disrupt the user experience, especially when users want to perform a quick search without leaving their current page. A more convenient and efficient solution would be to add a search bar directly to the side of the search icon, allowing users to search without navigating away from their current view.

### Describe the solution you'd like.

Introduce a search bar next to the search icon in the header. When users enter a query and press 'Enter' or click the search icon, the search should be performed with the default options. If the search bar is empty and users press 'Enter' or click the search icon, they should be redirected to the search page. This real-time search bar will allow users to quickly search for content without having to navigate away from their current page.

### Describe alternatives you've considered.

An alternative solution would be to use a dropdown search bar that appears when clicking the search icon. However, this could be less intuitive for users, as they may expect the search bar to be visible at all times.

### Additional context

This feature request aims to improve the user experience by providing a more convenient and efficient way to perform searches in Lemmy-UI. By adding a real-time search bar next to the search icon, users will be able to quickly search for content without the need to navigate to a separate search page. [Source 0](https://github.com/LemmyNet/lemmy-ui)

**Comment by YousufSSyed** [comment]
I'll also add that if you enter search on a community page, it should by default search only that community.

**Comment by dessalines** [comment]
The existing postgres searching could support real time search results, but the main question is, who's going to work on it. 

Either way its a big enough change that its not something we'd support in lemmy-ui, which in the long-term is going to be replaced by lemmy-ui-leptos.
