### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: No valid WebSocket class provided

### ISSUE THREAD

**Issue by tateisu** [LemmyNet/lemmy-ui#140]
create new lemmy instance, using docker, dessalines/lemmy:0.9.0 and dessalines/lemmy-ui:0.9.0.
docker-compose logs shows this error.

```
lemmy-ui_1  | (node:1) UnhandledPromiseRejectionWarning: Error: No valid WebSocket class provided
lemmy-ui_1  |     at ReconnectingWebSocket._connect (/app/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:508:19)
lemmy-ui_1  |     at new ReconnectingWebSocket (/app/node_modules/reconnecting-websocket/dist/reconnecting-websocket-cjs.js:205:14)
lemmy-ui_1  |     at new e (/app/dist/js/server.js:2:4106)
lemmy-ui_1  |     at Function.get (/app/dist/js/server.js:2:4542)
lemmy-ui_1  |     at new t (/app/dist/js/server.js:2:465506)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:170:28)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:221:20)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:307:39)
lemmy-ui_1  |     at renderVNodeToString (/app/node_modules/inferno-server/dist/index.cjs.js:307:39)
lemmy-ui_1  | (Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by Nutomic** [comment]
Are you using our nginx config? Because there are some specific parameters needed to make websocket work.

https://github.com/LemmyNet/lemmy/blob/main/ansible/templates/nginx.conf#L83

**Comment by dessalines** [comment]
Very strange. You set up nginx? And what URL did you go to? 

The node server crashed so you probably need to run `docker-compose restart`.

**Comment by tateisu** [comment]
it's new created instance, I have open `http://{site-name}/` from web browser.
- more occur if request from the browser immediately after starting the server.
- less occur if wait requests few minutes after starting the server.

**Comment by tateisu** [comment]
@.Nutomic, 
my nginx.conf 
https://gist.github.com/tateisu/5e34775b6c912f34d02dced8d35f7010
it is edited from https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/lemmy.hjson

**Comment by dessalines** [comment]
One of these lines is wrong:

```
      set $proxpass "http://172.17.0.1:8535";
      if ($http_accept = "application/activity+json") {
        set $proxpass "http://172.17.0.1:8536";
      }
      if ($http_accept = "application/ld+json; profile=\"https://www.w3.org/ns/activitystreams\"") {
        set $proxpass "http://172.17.0.1:8536";
      }
      if ($request_method = POST) {
        set $proxpass "http://172.17.0.1:8536";
      }
      proxy_pass $proxpass;
```

Look over our original nginx config again.

**Comment by tateisu** [comment]
it's very similar to https://raw.githubusercontent.com/LemmyNet/lemmy/main/ansible/templates/nginx.conf

docker-compose.yml 
https://gist.github.com/tateisu/f4ce71bda59a1cd56932003d9100912e

**Comment by dessalines** [comment]
Your docker-compose also looks incorrect when compared to our ansible version. You need to re-read through those again because the ports are all wrong.

**Comment by tateisu** [comment]
I download again and compared again the following files, but there is no port mapping issues.
- https://raw.githubusercontent.com/LemmyNet/lemmy/main/ansible/templates/nginx.conf
- https://raw.githubusercontent.com/LemmyNet/lemmy/main/docker/prod/docker-compose.yml
 
ports mapping of my site is correct.
- 172.17.0.1:8536 lemmy
- 172.17.0.1:8535 lemmy-ui
- 172.17.0.1:8537 pictrs
- 172.17.0.1:8538 iframely

**Comment by dessalines** [comment]
https://gist.github.com/tateisu/f4ce71bda59a1cd56932003d9100912e#file-docker-compose-yml-L28

That block looks very different from ours. 

Your nginx seems okay *I think*.

**Comment by tateisu** [comment]
The difference in the settings is irrelevant to this issue.
In my configuration access from nginx to lemmy-ui is okay, port 1235 is not accessed from anywhere,

**Comment by dessalines** [comment]
Internal host is also strange, why are you not using the docker services names like our compose files?

**Comment by tateisu** [comment]
172.17.0.1 is `docker0` bridge and it can be access from both of host/container. 
there is no connection problem.
```
$ docker-compose exec lemmy-ui wget http://172.17.0.1:8536/api/v2/site
Connecting to 172.17.0.1:8536 (172.17.0.1:8536)
saving to 'site'
site                 100% |************************************************************************|  1212  0:00:00 ETA
'site' saved
```

**Comment by dessalines** [comment]
Again I do not recommend changing these configs so much. Start from scratch with our configs.

**Comment by tateisu** [comment]
Your recommendations lacks sufficient explanation.  Are there any
unexpected uses for those settings?

To be honest, I can't find any relation  between this discussion and this
issue.

2021年1月28日(木) 23:18 Dessalines <notifications@github.com>:

**Comment by tateisu** [comment]
Fortunately, this crash doesn't happen very often.
You can wait until others report the same issue.

2021年1月29日(金) 1:56 tateisu <tateisu@gmail.com>:
