### ISSUE TITLE
[Bug]: Expanded images are hidden when new posts are pushed into the feed

### ISSUE THREAD

**Issue by bonsairobo** [LemmyNet/lemmy-ui#1403]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

When browsing the feed, new posts may be pushed to the top as they are created. I'm not familiar with the underlying mechanism.

When you click on an image thumbnail to expand it inline, it works fine, but as soon as new posts are pushed to the top of the feed, the expanded image will disappear. I consider this a usability bug, because it requires the user to re-expand the image.

### Steps to Reproduce

1. Go to the front page and view "All" posts, i.e. `https://$LEMMY_INSTANCE/home/data_type/Post/listing_type/All/sort/Active/page/1`
2. Find an image post and click the thumbnail to expand it.
3. Wait for new posts to stream in and observe that the expanded image disappears.

### Technical Details

No.

### Version

0.17.4 (I only see the backend version)

### Lemmy Instance URL

lemmy.ml

**Comment by SleeplessOne1917** [comment]
This should be fixed with the removal of the websockets API. Leaving this up for now until confirmed fixed.

**Comment by alectrocute** [comment]
Just confirmed.
