### ISSUE TITLE
[Bug]: Custom theme item gets duplicated in user settings dropdown

### ISSUE THREAD

**Issue by ffolkes** [LemmyNet/lemmy-ui#1411]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

After putting a custom theme CSS file in ./extra_themes, I have run into a bug where once the theme is set via user settings and saved, each subsequent page reload will add another entry to the theme dropdown. Eg.: After selecting icy-nord and saving it, every time the page is refreshed another "icy-nord" will be added to the dropdown. Eg.: Browser Default, darkly, darkly-red, litely, litely-red, icy-nord, icy-nord, icy-nord, icy-nord, etc. 

### Steps to Reproduce

1. Change to a custom theme via user settings (I used https://github.com/promitheas17j/lemmy-ui-themes/blob/main/icy-nord.css)
2. Save the change, then refresh the page.
3. Theme dropdown will now have an extra theme for every time the page is refreshed (eg.: Browser Default, darkly, darkly-red, litely, litely-red, icy-nord, icy-nord, icy-nord, icy-nord, etc)

### Technical Details

No.

### Version

0.18.0-rc.2

**Comment by scme0** [comment]
I've figured this one out. I'll create a PR.
