### ISSUE TITLE
[Bug]: Can't change search result type before inputting search queries first

### ISSUE THREAD

**Issue by krestenlaust** [LemmyNet/lemmy-ui#1413]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

Changing the type of search before typing in the search bar, results in weird behavior.

![screenshot of inputbox in question](https://github.com/LemmyNet/lemmy-ui/assets/17174333/1fcfdb71-3248-4ffd-977c-4201cd1843fc)

Changing the type to e.g. 'comments', also results in the following (AFAIK invalid) URI: `instance.ml/search/q//type/Comments/sort/TopAll/listing_type/All/community_id/0/creator_id/0/page/1` and leaves the button on "All"

### Steps to Reproduce

1. Open search page
2. Change result type

### Technical Details

Recreated in incognito firefox and chrome. And tested on my local instance and lemmy.ml.

### Version

0.17.4

### Lemmy Instance URL

feddit.dk

**Comment by SleeplessOne1917** [comment]
This was fixed in #965 and will be released as part of 0.18. You can verify that it works as expected at https://voyager.lemmy.ml/search.

**Comment by krestenlaust** [comment]
Awesome! Thanks.
