### ISSUE TITLE
Use canonical URLs

### ISSUE THREAD

**Issue by mminer237** [LemmyNet/lemmy-ui#1418]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Each Lemmy site duplicates all the content of every federated site. It's believe that Google and other search engines penalize for duplicated content, although this isn't known for sure. At the least, this spreads the pagerank thin and confuses searchers. It makes discoverability horrible.

Part of the great utility of reddit is that it functions as a sort of repository of knowledge. [Many people noticed how the blackout made Google so much worse](https://www.theverge.com/2023/6/13/23759942/google-reddit-subreddit-blackout-protests) because that knowledge couldn't be discovered. Lemmy should account for SEO to ensure it can help fill that role. This is very related to #1285 but with a specific solution.

### Describe the solution you'd like.

Each post should have a rel=canonical meta tag back to the original post. Currently no such tag exists, which is problematic since Google says "Duplicate without user-selected canonical" on every page it indexes since it indexes both https://civilloquy.com/post/1298 and https://civilloquy.com/post/1298?scrollToComments=true. Canonical tags are needed regardless of implementation. However, rather than each Lemmy instance claiming its own mirror of content as the canonical, I propose that it link back to the original post. So https://civilloquy.com/post/1298?scrollToComments=true would list https://beehaw.org/post/495714 as its canonical URL. This would pool pagerank to the originating post, make it clear we're not trying to scam Google with duplicate content, make search results much cleaner, and give proper credit to the originating community. I know such links are already calculated for the fedilink, so hopefully it wouldn't be too hard to do either.

### Describe alternatives you've considered.

The alternative would be adding canonical tags to your own instances copy of each post (or giving up on them entirely), however, as described I find this likely to be horrible for SEO and a bit dishonest.

**Comment by Pome-ro** [comment]
This shouldn't be that much effort to implement from what I can tell after reviewing the code. My guess is you would add an optional param to https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/common/html-tags.tsx for the canonical URL and then use that to set a `<link rel="canonical" href="..." />`

The thing I'm not sure about is if the UI can actually get the original URL from the local instance DB.

**Comment by mminer237** [comment]
I'll try to do some testing, but from my understanding it should just require adding another property to `HtmlTagsProps`, and then when https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post/post.tsx creates an `HtmlTags`, it would just pass `res.post_view.post.ap_id`.
