### ISSUE TITLE
Make sure trending communities matches local / all filter.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#142]
![image](https://user-images.githubusercontent.com/930215/105798616-8fdc2300-5f60-11eb-9ee9-4da1d100a9ae.png)

**Comment by Nutomic** [comment]
I'm not sure that it makes sense to use the local/all filters for that, because visually they are clearly separate. Maybe "trending communities" should just always show local communities.

**Comment by dessalines** [comment]
K, for now I'll just do a local only filter there.
