### ISSUE TITLE
[Bug]: wrong text color in "click to delete picture" popup

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#1432]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

The text "Click to delete picture: {{filename}}" is white on light gray

![IMG_0558](https://github.com/LemmyNet/lemmy-ui/assets/47706471/d209b3cb-6cf4-488f-a9f6-8a370cdee751)

### Steps to Reproduce

1. Set color scheme to litely-red
2. Create a post
3. Insert image

### Technical Details

No console error

### Version

Backend 0.17.4, hidden UI version

### Lemmy Instance URL

https://lemmy.ml

**Comment by alectrocute** [comment]
Resolved in 0.18.
