### ISSUE TITLE
Incorrect error message displayed when signing up using a long password

### ISSUE THREAD

**Issue by knpwrs** [LemmyNet/lemmy-ui#145]
### Issue Summary

Long passwords always show an error message saying that the passwords entered do not match.

### Steps to Reproduce

1. Attempt to register for an account with a password greater than 60 characters in length
2. You will be presented with an error message that says your entered password do not match, even if they _do_ match.
3. I would expect instead to see a message saying that my password was too long.

### Technical details

ef6e9cdd3a0b346248b212cade76ef2419ec8784 introduced a max password length of 60.

**Comment by dessalines** [comment]
This is in the back-end code:

```
    // Password length check
    if data.password.len() > 60 {
      return Err(APIError::err("invalid_password").into());
    }

    // Make sure passwords match
    if data.password != data.password_verify {
      return Err(APIError::err("passwords_dont_match").into());
    }
```

So what's happening is you're copying a longer than 60 character password into the verify_password one, and the first form is truncating it, but the 2nd form isn't. I'll add a maxLength constraint to that verify password field too.
