### ISSUE TITLE
Mods information

### ISSUE THREAD

**Issue by Kohoshi12** [LemmyNet/lemmy-ui#146]
For backend issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

Communities with deleted moderators are showing the name of the deleted user as a mod. For example !minetest@lemmy.ml. When the user click the mod's username, the user will directed to a page with error. Is interesting to avoid this to happen.

### Describe the solution you'd like

Would be better if the moderators area display a message like "no mods" or "no moderators available". If this is implemented, will be clear if a community is not moderated and it could be claimed.

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

(Write your answer here.)

**Comment by dessalines** [comment]
That user is still technically the mod there, even if their `deleted` is true.
