### ISSUE TITLE
In "Create Post" form, title field is bigger than body

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#147]
This is confusing, the title is normally shorter than the body, so it would make sense if that input was smaller as well.

![Screenshot_20210127_142425](https://user-images.githubusercontent.com/1044450/105997144-2ca6d980-60a3-11eb-869d-04388cbf4364.jpg)

**Comment by dessalines** [comment]
Could you try refreshing the page? I just checked and both are set to 2 rows by default.

**Comment by Nutomic** [comment]
Still the same.

**Comment by dessalines** [comment]
I see that adjust thing on your textarea, maybe you adjusted its size and your browser is saving that preferred size. Try opening it in a new container.

**Comment by Nutomic** [comment]
Done, still looks identical to my screenshot above. I noticed that right after reloading the page, both inputs (title and body) are the same height, the height of the body input decreases.

**Comment by dessalines** [comment]
Okay this maybe had to do with `autosize` slightly resizing the thing. I added autosize to that post-title and changed the title to one row.


https://user-images.githubusercontent.com/930215/106013443-746d3700-608a-11eb-89d7-5cb3c3f8a941.mp4
