### ISSUE TITLE
[Bug]: Deleted posts are visible in 0.18.0-rc.6

### ISSUE THREAD

**Issue by Kradyz** [LemmyNet/lemmy-ui#1477]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

I have upgraded to version 0.18.0-rc.6 and I have noticed that the previously user-deleted posts have become visible. 

### Steps to Reproduce

1. Make a post
2. Delete the post 
3. The post is still visible. No need to be logged in.

This is not an issue that only affects new deletions. You can go to https://lemmy.ml/c/test, scroll down, and you will see a lot of previously deleted posts.

![image](https://github.com/LemmyNet/lemmy-ui/assets/81911574/f338ca79-db73-415f-b5f7-4c33971d4b40)

### Technical Details

No browser console errors. 

### Version

0.18.0-rc.6

**Comment by poVoq** [comment]
This is especially annoying for pinned posts that got deleted when the creator deleted their account and which are not accessible via federation to unpin them.

Examples:
https://lemmy.ml/post/71785
https://lemmy.ml/post/43659
https://lemmy.ml/post/77546

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy/pull/3286

**Comment by lionirdeadman** [comment]
Fixed in https://github.com/LemmyNet/lemmy/pull/3286
