### ISSUE TITLE
[Bug]: Video embeded in post is making title inreadable

### ISSUE THREAD

**Issue by tomjasinski** [LemmyNet/lemmy-ui#1482]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

On the main page, the embedded video is immediately visible in full size and makes the information about the post invisible.

### Steps to Reproduce

1. View the post on main page with video embeded in it.
2. After opening the post, problem stays the same.

### Technical Details

![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/ebc7462a-a4b2-4e41-be17-876deb7cde26)
![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/043ffeff-ab67-4be1-abe7-fcb392f3560a)
![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/026eedf5-8b45-4bd8-883b-8670bb75d05f)
![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/9fadcea4-639c-4f08-a166-96cdd59b7608)

![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/d817a3aa-329a-4738-b139-e4a431f619fe)

### Version

0.18.0-rc.6

### Lemmy Instance URL

https://lemmy.ml/

**Comment by alectrocute** [comment]
Resolved in https://github.com/LemmyNet/lemmy-ui/pull/1479.
