### ISSUE TITLE
[Bug]: The "Next" and "Prev" buttons cause the page to scroll to the bottom of the page

### ISSUE THREAD

**Issue by Kradyz** [LemmyNet/lemmy-ui#1483]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Summary

After moving to a different page by clicking on "Next" or "Prev", the page will scroll such that it brings you to the bottom of the page.

### Steps to Reproduce

1. Go to the front page of an instance
2. Scroll to the bottom
3. Click "Next"

### Technical Details

There are no browser errors.

### Version

0.18.0-rc.6

**Comment by alectrocute** [comment]
Resolved in https://github.com/LemmyNet/lemmy-ui/pull/1472.
