### ISSUE TITLE
Too little icon on user and community page

### ISSUE THREAD

**Issue by tomjasinski** [LemmyNet/lemmy-ui#1485]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a server side (not related to the UI) issue? Use the [Lemmy back end](https://github.com/LemmyNet/lemmy) repo.

### Is your proposal related to a problem?

Small user icon compared to other buttons and information

![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/bb15b64f-5111-42ef-bbdc-6e3f2aaaf98b)
![image](https://github.com/LemmyNet/lemmy-ui/assets/20225776/eb2fedb2-2b10-4d75-a7e9-d0d573ca597d)

### Describe the solution you'd like.

Larger icon size - comparable to buttons. I also suggest to enlarge the statistical information visible under the buttons.

### Describe alternatives you've considered.

Not applicable

**Comment by lordkitsuna** [comment]
agreed it's too small to be useful. Personally I'm also not a fan of circular shape for Community icons. It makes sense for user avatars but I think Square would be better for Community icons.

**Comment by oliverwhite19** [comment]
This appears to have been fixes in #1475:

![Screenshot 2023-07-04 at 21 08 24](https://github.com/LemmyNet/lemmy-ui/assets/46496055/18144404-bd81-46d5-9f4e-d9a4b7e6405a)

![Screenshot 2023-07-04 at 21 08 52](https://github.com/LemmyNet/lemmy-ui/assets/46496055/23bf71a0-f4d2-499d-ad92-c94aa5044734)
