### ISSUE TITLE
Post data randomly changing

### ISSUE THREAD

**Issue by Dakkaron** [LemmyNet/lemmy-ui#1513]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I was on this post: https://feddit.de/post/1026108

And it looked like this.
![grafik](https://github.com/LemmyNet/lemmy-ui/assets/6311558/91622920-4c4e-4ad1-a017-f67c266e9909)

After a few minutes the score started jumping around between 2 at the lowest and 465 at the highest. Every few seconds the post score would show something completely different.

All of a sudden, the post itself changed:

![grafik](https://github.com/LemmyNet/lemmy-ui/assets/6311558/7716634f-d7b7-40b8-96d4-a3a5183ed83d)

As you can see, the URL is still on to the original post, but for some reason it's showing a different post now.

The F12 network tab shows no connections. (At least no connections for the randomized post count, I didn't have it open yet when the post itself changed. Could also be that there are some websocket connections that I didn't catch because I didn't open up F12 early enough.)

I've had the randomized post count issue quite a few times before, but the post changing is the first time for me.

Console doesn't show any errors.

Hovering over the score also shows a different score than the score that is shown without hovering. That one seems to be the correct score at the time the post was first loaded. It doesn't seem to update.

### Steps to Reproduce

1. Open a post
2. Wait

Doesn't happen every time. Maybe 1/10 times.

### Technical Details

Firefox, Win10, no errors on the console, no network connections on the network tab.

Some screenshots with random values. As you can see, the last one is the newest one, but it has a vastly lower score than the first ones.

![grafik](https://github.com/LemmyNet/lemmy-ui/assets/6311558/f84199eb-d352-429e-9471-34049f5628e2)
![grafik](https://github.com/LemmyNet/lemmy-ui/assets/6311558/43211b01-6aa9-4ef5-85ed-96d87310485e)
![grafik](https://github.com/LemmyNet/lemmy-ui/assets/6311558/2d09eee4-fb79-43c6-a00c-8affeb6f93b3)

### Lemmy Instance Version

0.17.4 (not sure if I found the correct version number)

### Lemmy Instance URL

https://feddit.de

**Comment by alectrocute** [comment]
This is an issue solved in 0.18. Will reopen if we get more reports of it. Thanks!
