### ISSUE TITLE
Remove actions dont show loading indicator

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#1514]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When removing a post or comment, there is no indication that the action went through, instead the dialog stays open as if nothing happened. If you reload the page then the item does actually disappear after a while.

### Steps to Reproduce

1. Pick a post or comment
2. Choose "remove" from dropdown menu
3. Enter a reason
4. Click remove button
5. Nothing seems to happen

The problem might be more noticable on production instances where remove queries take a while.

### Technical Details

Firefox

### Lemmy Instance Version

0.18.0-rc.7

**Comment by SleeplessOne1917** [comment]
I fixed this in #2258.
