### ISSUE TITLE
Show API errors to user

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#152]
I was wondering why Lemmy was taking so long to load sometimes, and only later thought to open the browser console. Turns out there was an error. It should really show that error directly to the user, instead of showing the loading icon forever.

**Comment by dessalines** [comment]
I'm guessing its because that one wasn't actually an API error, but a lemmy-ui javascript error. I'll have to look into the proper way to alert / popup for those, because you're right it should show something that users can give to us so we can fix it asap.

**Comment by alectrocute** [comment]
We now have the opposite problem. We show errors directly to the user via toast, perhaps a bit too much.
