### ISSUE TITLE
Unable to edit taglines when reg. mode is set to req. application

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy-ui#1524]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When the Registration Mode is set to "Require registration application", you are unable to edit the taglines.
Once you save, you will get the error message: application_question_required

It seems like when submitting the form, the content from the "Application Questionnaire" won't be submitted to the backend, and therefore the validation fails.,

### Steps to Reproduce

1. Go to your admin menu
2. Set the "Registration Mode" to "Require registration application", and save
3. Go to the "taglines" tab
4. Try to add a new tagline and click save

### Technical Details

Error message: application_question_required

### Lemmy Instance Version

0.18.0

**Comment by alectrocute** [comment]
Thanks so much for the great ticket. Sorry it got quickly duplicated, but please continue to contribute to the Lemmy project.
