### ISSUE TITLE
Error: SendStream.headersAlreadySent

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#1527]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Our prod servers are getting a lot of these errors:

```
lemmy-ui_1  | Error: Can't set headers after they are sent.
lemmy-ui_1  |     at SendStream.headersAlreadySent (/app/node_modules/send/index.js:386:13)
lemmy-ui_1  |     at SendStream.send (/app/node_modules/send/index.js:613:10)
lemmy-ui_1  |     at onstat (/app/node_modules/send/index.js:725:10)
lemmy-ui_1  |     at FSReqCallback.oncomplete (node:fs:199:5)
```

### Steps to Reproduce

Check the `docker-compose logs -f --tail=100 lemmy-ui`

### Technical Details

See above

### Lemmy Instance Version

0.18.0

### Lemmy Instance URL

https://lemmy.ml

**Comment by alectrocute** [comment]
I’ve seen this a ton in my dev environment too, haven’t been able to trace down which specific route handler it’s emitting from.

**Comment by alectrocute** [comment]
Maybe this is it? We aren’t returning here: https://github.com/LemmyNet/lemmy-ui/blob/e8dda77d4b76bb2d0d3746a391815018e52c11fc/src/server/handlers/theme-handler.ts#L15
