### ISSUE TITLE
Emoji upload is broken

### ISSUE THREAD

**Issue by Hellhound1** [LemmyNet/lemmy-ui#1535]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

The custom emoji upload function in the settings panel doesn't appear to work. I can upload an emoji, but the save button doesnt activate unless a URL is in place, which either needs to be inserted by Lemmy or ignored if there is an uploaded image, otherwise there is no way to tell what the URL of the uploaded image was.

### Steps to Reproduce

1.Go to settings, click "Emojis"
2.Click "Upload" and upload an image
3.Save button never activates
4.Unable to know what the URL should be, so unable to continue

### Technical Details

You can upload the image to a thread to get the url and do it that way, but seems a bit of a longer workaround.

### Lemmy Instance Version

0.18

### Lemmy Instance URL

lemmy.zip

**Comment by ludrol** [comment]
The upload button doesn't generate/autofill image url field. When populated from external source it works.
