### ISSUE TITLE
Voting on a comment expands previously collapsed comments

### ISSUE THREAD

**Issue by jason-watkins** [LemmyNet/lemmy-ui#1545]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Voting on a comment expands previously collapsed comments

### Steps to Reproduce

1. Open any post with multiple comments
2. Collapse one or more comments on the page
3. Vote on any uncollapsed comment on the page (relationship to previously collapsed comments does not matter)
4. All comments on the page revert to uncollapsed state

### Technical Details

Tested on Firefox 114.0.1, Windows 10 on both my own instance (lemmy.villa-straylight.social) and lemmy.ml

### Lemmy Instance Version

0.18.0

### Lemmy Instance URL

Any

**Comment by alectrocute** [comment]
Resolved in #1540.
