### ISSUE TITLE
Home feed doesn’t retain scroll position when going back

### ISSUE THREAD

**Issue by alectrocute** [LemmyNet/lemmy-ui#1551]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Home feed doesn’t retain scroll position when going back.

### Steps to Reproduce

1. Go to https://lemmy.ml
2. Scroll down on home feed
3. Open post
4. Go back
5. Scroll position lost

### Technical Details

https://github.com/LemmyNet/lemmy-ui/assets/35377827/51f51402-4c05-4dc4-9093-5fdb140d2570

### Lemmy Instance Version

0.18

### Lemmy Instance URL

https://lemmy.ml

**Comment by Undearius** [comment]
This may have been fix in https://github.com/LemmyNet/lemmy-ui/pull/1526
