### ISSUE TITLE
Require 2FA code before enabling 2FA

### ISSUE THREAD

**Issue by XtremeOwnageDotCom** [LemmyNet/lemmy-ui#1559]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

When a user wishes to enable 2FA, they should be required to entire at least one generated 2FA code, before 2FA is enabled.

This will prevent users from locking themselves out, by ensuring their code-generator, is properly configured and generating the expected. codes.

## Ideal Flow.

1. User enables 2FA in their settings.
2. User is then, required to enter generated 2FA code before 2FA is fully enabled.
3. AFTER user enters valid 2FA code, 2FA is enabled.

## Other related issues-

* [#1544 - Add QR Code](https://github.com/LemmyNet/lemmy-ui/issues/1544)
* [#3325 - Lemmy - Users are  being locked out](https://github.com/LemmyNet/lemmy/issues/3325)
* [#3309 - Lemmy](https://github.com/LemmyNet/lemmy/issues/3309)

**Comment by foss-** [comment]
This can be closed, right? 0.19.1 shows a dialog with a QR Code for 2FA setup asking for a 2FA code confirmation:

![1](https://github.com/LemmyNet/lemmy-ui/assets/5708172/03bc0033-9fa8-4b05-adcc-d7d28193759f)
