### ISSUE TITLE
lemmy-ui (0.18.0) docker image fails to run on CPUs not supporting SSE4

### ISSUE THREAD

**Issue by thomasdouwes** [LemmyNet/lemmy-ui#1566]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Trying to run the docker lemmy-ui 0.18.0 on a CPU not supporting the SSE4 instruction set such as the intel atom N2800 will fail with Illegal instruction.  
From outside this appears as the container continuously restarting and only printing `Inferno is in development mode.`

### Steps to Reproduce

1. run lemmy-ui:0.18.0 docker container with /bin/sh as entrypoint
2. run node dist/js/server.js
3. node exits with Illegal instruction

### Technical Details

OS: debian 11 (bullseye)
CPU: intel atom N2800
Server: K1 kimsufi from OVH  

The exception is in the function `aom_init_plugin()` of `/app/node_modules/sharp/build/Release/../.././vendor/8.14.2/linuxmusl-x64/lib/libvips-cpp.so.42` and is at `0x00007fa846b7e343 <+339>:   pinsrq $0x1,%rax,%xmm0` from gdb. although I don't think that is too useful.  

I don't really know where this issue should go, It's not caused directly by lemmy-ui but possibly changing the Dockerfile might be the only way to fix this. Or if older CPUs are unsupported then feel free to close this issue.

### Lemmy Instance Version

0.18.0

**Comment by mikeesto** [comment]
This error stems from the sharp library and its dependency on libvips. You would need to use a custom version of libvips to get it to run on that CPU: https://sharp.pixelplumbing.com/install#custom-libvips

No change to the Dockerfile is going to help here

**Comment by dessalines** [comment]
We've had to disable arm builds for lemmy-ui because of a libvips issue issue: https://woodpecker.join-lemmy.org/repos/135/pipeline/8497/3
