### ISSUE TITLE
Add infinite scrolling 

### ISSUE THREAD

**Issue by aproposnix** [LemmyNet/lemmy-ui#157]
### Describe the solution you'd like

I would like to continue browsing posts by scrolling instead of having to click on the "Next" button at the end of the stream.

**Comment by dessalines** [comment]
I'm fairly against this for several reasons, but I could be convinced.

1. Its designed to be psychologically addictive: https://uxdesign.cc/why-the-infinite-scroll-is-so-addictive-9928367019c5 . We have to be cautious about not doing everything the big tech giants do: they design their sites to increase time spent on their site, in a way that is often psychologically damaging.
2. It can mess with both navigation, and page links. For example with proper pagination like we currently have, we can link to page 2 of the front page: https://lemmy.ml/home/data_type/Post/listing_type/All/sort/Active/page/2
2. It can often hide footers.

**Comment by aproposnix** [comment]
1. Make it opt-in only. You can't assume that your users can't think for themselves. I get what you mean about the big tech but their motivation is totally different. You could also add a detox feature if this is really concerning for you. 
2. I'm not a developer but i know that this functionality exists in a lot of other application (esp., search engines). I think it just needs to be thought through.
3. I can't say anyhting for this.

**Comment by dessalines** [comment]
@Nutomic what are your thoughts on infinite scrolling?

**Comment by Nutomic** [comment]
Fully agree with @dessalines. If anyone cares about infinite scrolling, they can fork lemmy-ui to implement that, and use the fork on their own instance.
