### ISSUE TITLE
UI doesn't look good

### ISSUE THREAD

**Issue by alejandro-esquivel** [LemmyNet/lemmy-ui#1575]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I don't like the way the website looks, just because I've set my OS to use dark mode doesn't mean I want lemmy to activate dark mode by default, its dark mode doesn't look good. Posts should have a border just like reddit posts do, that way they'd look better, and you should also make the website's background color darker

### Steps to Reproduce

Open the website, look.

### Technical Details

Windows 11, Google Chrome.

### Lemmy Instance Version

BE: 0.17.4

### Lemmy Instance URL

https://lemmy.world/

**Comment by vinoff** [comment]
Sorry but I have to say I laughed so hard at this hahah:

![haha](https://github.com/LemmyNet/lemmy-ui/assets/90382765/cf3e6350-760d-4069-83c0-9eb7591b01c0)

**Comment by alectrocute** [comment]
Belongs in discussion, this is not a bug report.

**Comment by alejandro-esquivel** [comment]
> Can you not just set Lemmy back to light mode manually?
> 
> But an optional automatic dark mode toggle might be handy.

Not really. I can switch to light mode using the devtools, but it reverts back to dark mode when I close the devtools, and I don't want to rely on the devtools to browse a website.

**Comment by alejandro-esquivel** [comment]
> Sorry for the spam, but I have to say I laughed so hard at this hahah:
> 
> ![haha](https://user-images.githubusercontent.com/90382765/248542752-cf3e6350-760d-4069-83c0-9eb7591b01c0.png)
> 
> This entire issue is so funny...

Not really, it bothers me.

**Comment by alejandro-esquivel** [comment]
> Belongs in discussion, this is not a bug report.

It is a bug report is something so essential is missing. 99% of websites that force you to use a dark theme just because your O.S is in dark mode allow you to switch back to its light mode thanks to a theme switcher they usually have at the footer or navbar.
