### ISSUE TITLE
0.18 seems to have broken the "Subscribe" button.

### ISSUE THREAD

**Issue by vinoff** [LemmyNet/lemmy-ui#1581]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

This has been talked both here: https://programming.dev/post/198447 and here: https://programming.dev/post/198468. The first link has a GIF showing what's happening.

The problem is that, if you go to an instance outside of your own and try to subscribe a community there, the subscribe button seems to not actually be a button.

### Steps to Reproduce

1. Go to community hosted on an instance other than your own.
2. Try to subscribe to it.
3. There is no subscribe button, just the text "Subscribe".

### Technical Details

Tested on firefox.

### Lemmy Instance Version

0.18

**Comment by manaskarekar** [comment]
This happens in the same instance also.

Click on Explore Communities, search for something, click on any of the results.

This will reproduce the behavior. Example:

![image](https://github.com/LemmyNet/lemmy-ui/assets/334085/53d5e4e2-12d1-4a25-bcbe-98b4a5cfec0e)

The way to resolve is to click on any link on that community and the Subscribe/Block buttons show up again.

**Comment by KaKi87** [comment]
> The way to resolve is to click on any link on that community and the Subscribe/Block buttons show up again.

That workaround works, thanks !

However, there's another glitch : when clicking the button remains in non-subscribed state after loading, despite successfully being subscribed. Refreshing the page will display the subscribed state.

**Comment by SleeplessOne1917** [comment]
I tested this out by using the js client to make a request with m,my account.
```typescript
import { LemmyHttp } from "lemmy-js-client";

const client = new LemmyHttp("https://lemmygrad.ml");

const doStuff = async () => {
  const { jwt } = await client.login({
    password: "REDCATED",
    username_or_email: "REDACTED",
  });

  const res = await client.followCommunity({
    auth: jwt ?? "",
    community_id: 258,
    follow: true,
  });

  console.log(res);
};

doStuff();
```

This request tries to follow ask lemmy on lemmy.ml from a lemmygrad account. This is the response I get back:
```javascript
{
  community_view: {
    community: {
      id: 258,
      name: 'asklemmy',
      title: 'asklemmy',
      description: 'A loosely moderated place to ask open ended questions\n' +
        '\n' +
        'If your post is\n' +
        '\n' +
        '1. Open ended \n' +
        '2. Not offensive (At this point, I do not have the bandwidth to moderate partisan political discussions)\n' +
        '3. **Not regarding lemmy support** ([!lemmy_support@lemmy.ml](https://lemmy.ml/c/lemmy_support) )\n' +
        '4. not ad nauseam inducing (please make sure its a question that would be new to most members)\n' +
        '5. [An actual topic of discussion](https://lemmy.ml/post/1239589)\n' +
        '\n' +
        'it’s welcome here!',
      removed: false,
      published: '2019-04-25T04:58:33.886275',
      updated: '2023-06-14T00:05:37.871496',
      deleted: false,
      nsfw: false,
      actor_id: 'https://lemmy.ml/c/asklemmy',
      local: false,
      icon: 'https://lemmy.ml/pictrs/image/UsuGsKF2fl.png',
      banner: 'https://lemmy.ml/pictrs/image/XKAjSZCX2P.png',
      hidden: false,
      posting_restricted_to_mods: false,
      instance_id: 339
    },
    subscribed: 'NotSubscribed',
    blocked: false,
    counts: {
      id: 204,
      community_id: 258,
      subscribers: 180,
      posts: 1773,
      comments: 33852,
      published: '2019-04-25T04:58:33.886275',
      users_active_day: 911,
      users_active_week: 3618,
      users_active_month: 7815,
      users_active_half_year: 7986,
      hot_rank: 0
    }
  },
  discussion_languages: []
}
```

Notice that subscribed is `NotSubscribed`.

Compare this to when I try to subscribe to a local community:
```javascript
{
  community_view: {
    community: {
      id: 3957,
      name: 'leftistunix',
      title: 'Linux for Leftists',
      description: 'A Community for all leftists wanting to join and being part of a community that talks about Linux, Unix and the Open-Source Community',
      removed: false,
      published: '2021-04-14T06:10:46.277451',
      updated: '2023-06-24T10:32:37.868872',
      deleted: false,
      nsfw: false,
      actor_id: 'https://lemmygrad.ml/c/leftistunix',
      local: true,
      icon: 'https://lemmygrad.ml/pictrs/image/f0056071-6839-4146-9742-374509ee5fd9.png',
      banner: 'https://lemmygrad.ml/pictrs/image/34095db5-670e-45ba-957c-745ec014abe5.jpeg',
      hidden: false,
      posting_restricted_to_mods: false,
      instance_id: 42
    },
    subscribed: 'Subscribed',
    blocked: false,
    counts: {
      id: 374,
      community_id: 3957,
      subscribers: 532,
      posts: 65,
      comments: 735,
      published: '2021-04-14T06:10:46.277451',
      users_active_day: 2,
      users_active_week: 12,
      users_active_month: 61,
      users_active_half_year: 79,
      hot_rank: 0
    }
  },
  discussion_languages: []
}
```

Subscribed is subscribed, as expected. With this data in mind, I think this is a backend issue instead of a frontend issue. The backend should not be returning the value that it is.

**Comment by KaKi87** [comment]
Regarding the second issue, yes, but not the first one. Or is it ? Because you didn't mention it.

**Comment by SleeplessOne1917** [comment]
I'll reopen this issue. The failure to subscribe is a backend issue, but the subscribe (as well as block community) not being a button still needs to be fixed.

**Comment by SineSwiper** [comment]
Is this bug going to get fast-tracked into a release?  I literally cannot subscribe to many communities because of this bug.  Refreshing the page does not work.

**Comment by KaKi87** [comment]
@SineSwiper As mentioned earlier, the working workaround is to click a post in the community.

**Comment by SineSwiper** [comment]
Strangely enough, this only works within the same tab.  If you try to Ctrl+Click the post from the forum page, the problem manifests again.

**Comment by KaKi87** [comment]
Not strange.

Explanation : the issue occurs when the page is server-side rendered (i.e. at load or reload), but the issue doesn't occur when the page is client-side rendered (i.e. when an already loaded page displays changes route).
