### ISSUE TITLE
Lemmy 0.18.0 does not work when Firefox or Chrome saves a web page when viewing a Post ("Page Not Found")

### ISSUE THREAD

**Issue by RocketDerp** [LemmyNet/lemmy-ui#1587]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Something about the way the page is dynamically generated for the web browser results in no ability to "save as..." the web page on a desktop computer using either Firefox or Chrome browser.  You end up saving a file that has none of the post or comment content from Lemmy.

Saves are often more useful than screenshots...

### Steps to Reproduce

1. go to a lemmy post on lemmy.ml
2. Try to save in Firefox
3. Try to save in Chrome
4. Open the saved page, the content is not there

![Screenshot from 2023-06-25 06-58-52](https://github.com/LemmyNet/lemmy-ui/assets/113625597/8cdbfa60-871c-4c91-b183-ba57710b920d)

### Technical Details

I don't think the OS is relevant, these browsers are pretty consistent on desktop platforms, and both major browsers have the same problem.

### Lemmy Instance Version

0.18.0

### Lemmy Instance URL

https://lemmy.ml

**Comment by alectrocute** [comment]
I don’t see this being a feature added any time soon. @dessalines Feel free to reopen if you disagree.

**Comment by RocketDerp** [comment]
It's deliberately save-hostile?

**Comment by alectrocute** [comment]
> It's deliberately save-hostile?

It relies on JavaScript to build the frontend experience. It would take significant overhaul to make dynamic pages “Save as…” friendly. Feel free to make a PR, I’m sure it would be well received. Thanks.
