### ISSUE TITLE
Dont show "banned" icon on frontpage or community overview

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#16]
It just stands out too much compared to the rest of the page (see screenshot below). I think it would be enough to show the icon only in the post view. Alternatively we could make the colour less bright.

![Screenshot_2020-08-27 Lemmy](https://user-images.githubusercontent.com/1044450/91437043-c2baa780-e858-11ea-8370-e27b47b4f1c6.png)

**Comment by dessalines** [comment]
Looking over this, I do kinda like it showing that everywhere. But I'll make it stand out less.

**Comment by dessalines** [comment]
![image](https://user-images.githubusercontent.com/930215/126021463-c05ba011-12bb-40f4-aa3b-8c4c8f3368d3.png)
