### ISSUE TITLE
Ipad formatting

### ISSUE THREAD

**Issue by RedNumber1** [LemmyNet/lemmy-ui#160]
![E2607C18-DEFE-4D66-A217-BDA30F6ACBB4](https://user-images.githubusercontent.com/32143878/106522261-6fa2eb80-64ad-11eb-8950-3e474d430999.png)
Can we get a decent looking site for iPad?

**Comment by Nutomic** [comment]
That looks like your browser isnt loading the CSS. Can you open some debug tools and look for error messages? And maybe it works after a restart or with a different browser?
