### ISSUE TITLE
Whenever I vote on a comment, the collapsed comments are expanded again

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#1601]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Steps to Reproduce

1. Collapse some comments.
2. Vote another comment.
3. The collapsed comments expand.

### Lemmy Instance Version

0.18

### Lemmy Instance URL

https://lemmy.ml

**Comment by jsit** [comment]
This is fixed in the main branch, but hasn't been released yet. See #1545
