### ISSUE TITLE
Pausing auto-refresh in main feed

### ISSUE THREAD

**Issue by njshockey** [LemmyNet/lemmy-ui#1614]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Often times I'll look at a post and come back to the previous tab and have no idea where I was before because a bunch of new posts showed up at the top. It'd be really nice if you could pause the auto refreshing so you can read stuff without being bombarded with new posts.

**Comment by alectrocute** [comment]
This should be resolved in 0.18. Which Lemmy instance are you testing this on?

**Comment by njshockey** [comment]
I've been using lemmy.world so far. If it's already fixed then I'll just deal with it until it gets updated, then. Thanks!

**Comment by njshockey** [comment]
I was looking around and apparently lemmy.world isn't updating until captchas are added back in 0.18.1 so this issue should be fixed over there when that releases. I'll keep this issue open to spread the word.

https://lemmy.world/post/469761
