### ISSUE TITLE
`allowed` and `blocked` instances are broken in lemmy-ui `0.18.0`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#1621]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I'm noticing that allowed and blocked instances are no longer working in lemmy-ui:

lemmy.ml 's section
![Screenshot_2023-06-26-16-22-15-531_mark via gp](https://github.com/LemmyNet/lemmy-ui/assets/930215/8707f2e0-ec86-4dcf-aea8-a7469639d610)

cc @SleeplessOne1917 

### Steps to Reproduce

1. Go to admin settings.
2. See empty blocklist

### Technical Details

See above

### Lemmy Instance Version

0.18.0

### Lemmy Instance URL

main

**Comment by SleeplessOne1917** [comment]
I tried replicating this locally. They don't show up when you navigate there using client side routing, but will reappear when you refresh the page.

**Comment by dessalines** [comment]
This one is still an issue on main.
