### ISSUE TITLE
Downvoting comments reveals the amount of up- and down- votes

### ISSUE THREAD

**Issue by nogerine** [LemmyNet/lemmy-ui#163]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

Downvoting a comment reveals the amount of up- and down- votes.
This behavior is inconsistent with upvoting, which doesn't reveal the numbers.

![before](https://user-images.githubusercontent.com/24653981/106742507-08a04680-6615-11eb-922d-0e9db25aeb2e.png)
![downvote](https://user-images.githubusercontent.com/24653981/106742510-0938dd00-6615-11eb-9986-170ca437f16a.png)
![upvote](https://user-images.githubusercontent.com/24653981/106742511-09d17380-6615-11eb-9e19-698fcdde01b1.png)

### Steps to Reproduce

1. Downvote any comment
2. Observe

**Comment by dessalines** [comment]
Not a bug. We don't show the downvotes if there are zero downvotes.
