### ISSUE TITLE
[Bug]: Click on New before Chat don't sorts comments like click Chat only.

### ISSUE THREAD

**Issue by Acelya-9028** [LemmyNet/lemmy-ui#1639]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [x] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

First of all, sorry for the size of the captures.

1. Click on New before Chat:

![Capture d’écran 2023-06-23 à 15 27 04-fullpage_NEW_BEFORE_CHAT](https://github.com/LemmyNet/lemmy/assets/45818681/6321f389-73c1-4101-8114-12e301fb5918)

To reproduce, load [a page](https://lemmy.world/post/458325), and click on New and after, on Chat.

All top (in red on the screenshot) comments are stacked in the top of the list ordered by most recent posts first and child comments are stacked at the bottom of the list but with an weird order like `@Fig` at `June 23 / 1:57 PM` or `@V4uban` at `June 23 / 2:48 PM` after multiples 11 AM other child comments instead of before because newest.

[Docs](https://join-lemmy.org/docs/users/03-votes-and-ranking.html?highlight=chat#votes-and-ranking) says:

> Additionally there is a sort option Chat. This eliminates the hierarchy, and puts all comments on the top level, with newest comments shown at the top. It is useful to see new replies at any point in the conversation, but makes it difficult to see the context.

I don't understand the logic with hierarchy and creation time here. In my screenshot, even if they are 2 child comments, `@Fig` and `@V4uban` are the 2 most newest comments but are in the middle of the list instead of the top of the list.

1. Click on Chat only:

![Capture d’écran 2023-06-23 à 15 27 10-fullpage_CHAT_ONLY](https://github.com/LemmyNet/lemmy/assets/45818681/066eec92-b5fb-44ce-85e7-41006f5a9acb)

To reproduce, load [a page](https://lemmy.world/post/458325), and click on Chat.

Here, the list is ordered in a completely new order but with some logic, all top comments are stacked in the top of the list too.

### Steps to Reproduce

1. Load a page and play with New and Chat buttons.

### Technical Details

-

### Version

BE 0.17.4

### Lemmy Instance URL

lemmy.world

**Comment by Die4Ever** [comment]
let me crop your images a little bit lol

1st image: 

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/a30df40d-5d09-4c4a-bebb-27cce705974d)

2nd image:

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/7c81e9d0-e2fd-4440-8fcf-35c23a1267ef)

**Comment by Die4Ever** [comment]
I think the Chat view has been improved in v0.19.4? so maybe this issue is fixed now

here's lemmy.ml on v0.19.4 https://lemmy.ml/post/16960701?sort=New&view=Flat

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/04db6191-f0a6-4724-ab41-2af6ba6b44ff)

We see 15 minutes ago, then 38 minutes, then 51 minutes, then 1 hour ago

then here's programming.dev on v0.19.3 https://programming.dev/post/15621550 (does not get a unique URL for Chat view?)

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/952cdddf-ab04-4784-9c34-d198d177fdd9)

it correctly shows the first 2 comments but then skips the 3rd newest comment.

**Comment by Die4Ever** [comment]
collapsing all the comments actually makes it really easy to see, here's the same thread, programming.dev v0.19.3

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/01a002f1-f498-4139-b12a-5c851d9cab55)

lemmy.ml v0.19.4

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/ccb10d13-508e-41ba-b206-fe5184e3a10b)

**Comment by dessalines** [comment]
@Acelya-9028 Since @Die4Ever shows that this seems to be fixed in `0.19.4`, could you test this on https://voyager.lemmy.ml ? thx.

**Comment by Acelya-9028** [comment]
Ok yes. Thank you @Die4Ever and sorry for these big images :s. I have tested on https://lemmy.ml/post/16976759?sort=New and it seems ok :D
