### ISSUE TITLE
Real-time live feeds should be opt-in

### ISSUE THREAD

**Issue by scottmmjackson** [LemmyNet/lemmy-ui#1647]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

On the main feed screen, new posts show up too quickly to be able to interact with them. The live feed behavior ought to be opt-in. The Mastodon UI allows optional live/static feeds, though it's opt-out IIRC.

I argue for opt-in for a few reasons:
1. Expect that the Lemmyverse is going to expand, and ingesting a live feed will likely become untenable as more than a novelty for most people with significant subscriptions.
2. Folks with disabilities, small screens, or slow mouse/tap skills are not going to be able to use the feed like this. There's also a high risk of misclicking when the feed moves and being unable to return to the list one was browsing through.

**Comment by alectrocute** [comment]
Resolved in 0.18.
