### ISSUE TITLE
'forgot password' button is unintuitive and doesn't work as expected.

### ISSUE THREAD

**Issue by JamesL813** [LemmyNet/lemmy-ui#1668]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

## Current Behavior

As it currently works, the 'forgot password' button doesn't bring you to a new page, it requires you to already have inputted your email, not username. The only indication that this is what you're supposed to do, is the prompt when hovering over that says 'You will not be able to reset your password without an email'. At first, I interpreted this as 'you need to have an email attached to the account you want to reset'.

It seems more obvious when looking back, but I was trying to sign in with my username like I normally would and the 'forgot password' button was giving a 🚫 symbol, which made me think maybe the feature was broken. I had to read the docs to figure it out.

## Expected/Preferred Behavior

I think it would be more intuitive and user-friendly if clicking the 'forgot password' button brought you to a new page. You can then be prompted for the email you signed up with, with a 'send reset instructions' button below or something like that. This way there's very little ambiguity, and it's more familiar to how other sites normally handle resetting passwords.

**Comment by alectrocute** [comment]
Thanks for the ticket, but this has been resolved in 0.18.1.
