### ISSUE TITLE
Implement cache invalidation features

### ISSUE THREAD

**Issue by KAMiKAZOW** [LemmyNet/lemmy-ui#1676]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Bug report #1666 by @ruudschilders exemplifies a big issue with the current state of Lemmy upgrades: They require to clear the browser cache or things break.

According to https://stackoverflow.com/questions/1922910/force-browser-to-clear-cache#1922924 it's pretty easy to get around the issue by adding a parameter after the file name of esp. CSS and JS files. The obvious choice would be to just use the short hash of the used git commit, like `<link rel="stylesheet" type="text/css" href="/static/styles/styles.css?v=0e9faf7" />` and `<script defer src='/static/js/client.js?v=0e9faf7'></script>` for the currently latest commit 0e9faf7.

**Comment by alectrocute** [comment]
@KAMiKAZOW brings up a really good point.

@SleeplessOne1917 @dessalines @jsit adding this to the 0.18.1 milestone.
