### ISSUE TITLE
Captchas aren't being regenerated for lemmy-ui

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#1702]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Captchas aren't being regenerated / refetched in lemmy-ui

### Steps to Reproduce

Click regen captcha.

It loads the same one.

### Technical Details

See above

### Lemmy Instance Version

0.18.1-rc.4

### Lemmy Instance URL

https://voyager.lemmy.mlm

**Comment by alectrocute** [comment]
I can reproduce on https://voyager.lemmy.ml but not on https://voyager.alec.is, same version and everything. Weird.

**Comment by dessalines** [comment]
This *may* be a non-issue. The `setCacheControl` function is caching every response for 60s for non-logged-in users. So at most they can generate a captcha once a minute. 

There's probably a better solution, because if a person fails a captcha, they won't be able to regenerate it for a bit. At the same time, it prevents people from spamming captcha requests.

**Comment by alectrocute** [comment]
Maybe we can lower it from 60s to 5s?

**Comment by 0xAnansi** [comment]
Shouldn't the cache control policy exclude login related pages in the first place?
