### ISSUE TITLE
Icon tags not properly resolving in HTML

### ISSUE THREAD

**Issue by alectrocute** [LemmyNet/lemmy-ui#1703]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

- Icon tags not properly resolving in HTML

### Steps to Reproduce

1. Go to https://voyager.lemmy.ml
2. View source
3. Look for Apple touch icon tag

### Technical Details

<img width="695" alt="Screenshot 2023-06-29 at 12 08 49 PM" src="https://github.com/LemmyNet/lemmy-ui/assets/35377827/3a41dff6-f560-4694-bb44-538cbafbc44f">

### Lemmy Instance Version

0.18.1-rc.4

### Lemmy Instance URL

https://voyager.lemmy.ml

**Comment by alectrocute** [comment]
@SleeplessOne1917 Is `sharp` doing image generation on every single pageload? Do we really need it?

**Comment by SleeplessOne1917** [comment]
It should only be generating the images once, then store the manifest in memory.

See the code in the manifest handler:
```typescript
let manifest: Awaited<ReturnType<typeof generateManifestJson>> | undefined =
  undefined;

export default async (req: Request, res: Response) => {
  if (!manifest || manifest.start_url !== getHttpBaseExternal()) {
    const headers = setForwardedHeaders(req.headers);
    const client = wrapClient(
      new LemmyHttp(getHttpBaseInternal(), { fetchFunction: fetch, headers })
    );
    const site = await client.getSite({});

    if (site.state === "success") {
      manifest = await generateManifestJson(site.data);
    } else {
      res.sendStatus(500);
      return;
    }
  }

  res.setHeader("content-type", "application/manifest+json");

  res.send(manifest);
};
```

**Comment by alectrocute** [comment]
@SleeplessOne1917 This is what I was talking about:

https://github.com/LemmyNet/lemmy-ui/blob/main/src/server/utils/create-ssr-html.tsx#L26
