### ISSUE TITLE
Visting a path containing text considered an auth path always redirects to /login, even if on a non-auth endpoint.

### ISSUE THREAD

**Issue by 0xDEADCADE** [LemmyNet/lemmy-ui#1704]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Any path containing "admin", even in legitimate contexts (such as https://lemmy.ml/c/lemmy_admin) will be seen as the admin page, and redirected to `/login` if the user is unauthenticated.

This issue appears to have been introduced in 0.18.0, as `beehaw.org` (currently on 0.17.4) does not appear to have the issue. (https://beehaw.org/c/lemmy_admin@lemmy.ml). lemmy.world (0.17.4) appears unaffected. However, 0.18.1-rc.4 (as currently seen on https://voyager.lemmy.ml/) appears affected.

This counts for any text considered to be an "auth" path, as defined [in this file](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/utils/app/is-auth-path.ts)

This makes it impossible to visit any communities or users containing text that's considered an auth path when not logged in. I'm assuming any federated instances with one of these strings in its name will also be unavailable from other 0.18.0 instances (but untested).

### Steps to Reproduce

1. Create a community with a word from [this](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/utils/app/is-auth-path.ts) list
2. Visit that community from any instance (local or federated) on 0.18.0 or above
3. Get incorrectly redirected to the /login page
(The same works for users, possibly for instance domains)

### Technical Details

I am on ArchLinux with Firefox 114.0.2. The same behavior happens in ungoogled-chromium 114.0.5735.133.

### Lemmy Instance Version

0.18.0 or above

### Lemmy Instance URL

https://lemmy.ml

**Comment by alectrocute** [comment]
Excellent bug report ticket. Thank you.

**Comment by SleeplessOne1917** [comment]
I know what caused this. It's the regex used to check if a route is an auth route.
