### ISSUE TITLE
Redirect issue

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#1717]
* `https://enterprise.lemmy.ml/static` redirects to `https://enterprise.lemmy.ml/static/` and back
* Browser behavior
    * detected and stopped automatically on Firefox after ca. 30 redirects in quick succession
    * detected and stopped automatically on Chromium

At the moment, I am not aware of practical denial of service situations through this issue.

https://git.radicallyopensecurity.com/nlnet/off-ngid-lemmy/-/issues/16

**Comment by SleeplessOne1917** [comment]
Just tested this with the link `https://enterprise.lemmy.ml/static` and didn't run into the issue.
