### ISSUE TITLE
Reply to private messages shows "Edit view"

### ISSUE THREAD

**Issue by Antik79** [LemmyNet/lemmy-ui#1749]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When I hit "reply" on a private message I often get a bug where I am presented the original message I am replying to with only the option to "Cancel", "Preview" or "Save". There is no reply option.

### Steps to Reproduce

1. Open a private message
2. Click the reply icon
3. You will be presented with a window like below:

![image](https://github.com/LemmyNet/lemmy-ui/assets/3721299/f4231e89-9acc-4824-b034-0097b0bc3520)

### Technical Details

Instance: Lemmy World
UI: 0.18.1-rc.7
BE: 0.18.1-rc.4

Side note: I have to add that I'm an admin on that instance, I'm not sure if "normal" users have this too.

### Lemmy Instance Version

UI 0.18.1-rc.7 / BE: 0.18.1-rc.4

### Lemmy Instance URL

https://lemmy.world

**Comment by sunaurus** [comment]
Hey, this is fixed in #1730

**Comment by Antik79** [comment]
Fixed already
