### ISSUE TITLE
Select text, hit "Reply", text field starts with "undefined>"

### ISSUE THREAD

**Issue by KAMiKAZOW** [LemmyNet/lemmy-ui#1753]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I guess this is related to #969

### Steps to Reproduce

1. Select part of a comments
2. Hit "Reply"

### Technical Details

UI: 0.18.1-rc.7
BE: 0.18.1-rc.4

### Lemmy Instance Version

0.18-rc7

### Lemmy Instance URL

https://lemmy.world

**Comment by sunaurus** [comment]
Already fixed in #1732
