### ISSUE TITLE
When voting your vote gets cleared leaving the impression it did not take 

### ISSUE THREAD

**Issue by trashhalo** [LemmyNet/lemmy-ui#1761]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

On an 0.18.1 instance beehaw we are seeing a behavior where you vote on a post or comment and it turns blue then goes back to the state where you have not voted. After some time it becomes blue.

### Steps to Reproduce

1. Find comment you like
2. Click up arrow
3. Notice how it's not blue or spinning. 

### Technical Details

Looking at the code I believe the issue to be here
 
https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/common/vote-buttons.tsx#L53

As far as I can tell onpost upstream is an async function. This causes the loading state to immediately turn off since nothing is awaiting the promise

### Lemmy Instance Version

0.18.1.rc.7

### Lemmy Instance URL

Https://beehaw.org

**Comment by jsit** [comment]
@trashhalo Thank you for this! Some vote button refactoring happened recently and introduced this regression. Got a fix in that should work.
