### ISSUE TITLE
0.18.1-rc.8 - Blocked instances not showing

### ISSUE THREAD

**Issue by angryce** [LemmyNet/lemmy-ui#1788]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Blocked instances did not show on /instances after I updated to 0.18.1-rc.8 from 0.18.1-rc.7
While they showed up on settings, they did not show up on /instances.

### Steps to Reproduce

1. Simply updated to 0.18.1-rc.8 with ansible

### Technical Details

Debian 11.7

No extra error messages popping up between the versions

### Lemmy Instance Version

0.18-rc.8

### Lemmy Instance URL

https://lemmings.basic-domain.com

**Comment by lionirdeadman** [comment]
They show up in 0.18.2, closing

Note: They are now at the bottom rather than next to the linked instances
