### ISSUE TITLE
On your user page, have the Settings sidebar box be collapsible, and collapsed by default

### ISSUE THREAD

**Issue by OrphieSmol** [LemmyNet/lemmy-ui#180]
I would rather see community lists and other useful sidebar items most of the time I go to my user page. Instead I see lots of tacky input boxes that I have to scroll past. Perhaps we should have the Settings box collapsed by default. Thanks.

**Comment by dessalines** [comment]
This is a good opportunity to create a dedicated user settings page, now that we have a lot of user settings, and will likely add more soon.
