### ISSUE TITLE
Search on communities page searches all content

### ISSUE THREAD

**Issue by RayBB** [LemmyNet/lemmy-ui#1808]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Search bar on communities page doesn't search communities it searches all content.

Video:

https://github.com/LemmyNet/lemmy-ui/assets/921217/debf5db5-07c6-4aa4-9d5e-e814815a1d07

### Steps to Reproduce

1. Go to https://lemmy.ml/communities
2. Type "tech" in the search bar
3. Click "Search"
4. You still be redirected to https://lemmy.ml/search?q=tech
5. The results show search results for "all" instead of just communities
6. It should redirect you to https://lemmy.ml/search?q=tech&type=Communities

### Technical Details

FF on latest Mac OS

### Lemmy Instance Version

BE: 0.18.0

### Lemmy Instance URL

https://lemmy.ml

**Comment by SleeplessOne1917** [comment]
@dessalines @jsit @alectrocute Do you think the user should even be redirected away from the communities page for this?

**Comment by jsit** [comment]
1. Voyager already adds `&type=Communities` when I search from the communities page. Would like others to confirm.
2. I don't think the Communities page is really equipped to display search results, so this redirect makes sense to me for now

**Comment by SleeplessOne1917** [comment]
> I don't think the Communities page is really equipped to display search results, so this redirect makes sense to me for now

Gotcha. TBF, the current search feels a bit too kitchen-sinky. I would expect the Communities page to have to deal with searches at some point, especially since I'm pretty sure sorting by different columns is in the pipeline.
