### ISSUE TITLE
Thumbnails only pull from title links, when they should probably pull from the first image in the body too.

### ISSUE THREAD

**Issue by OrphieSmol** [LemmyNet/lemmy-ui#181]
If you upload an image for a title URL, it will show as the post thumbnail. But you won't be able to see a bigger version of that image when you click on the post, unless you click on the title link and it goes to a new page. And if you don't want to do that and you instead want to post the image in the body, the post won't have a thumbnail at all.

Reddit solved this by having a dedicated "this post is an image" tab when creating a post. However, I don't like that as much as what Lemmy started-- where you can have a body with images _and_ other content.

So here's what I propose:

- If the title of the post links to an image, use that as a thumbnail
- If the title of the post has no link to an image, use the first image in the body as the thumbnail

I think that is a good idea, but I of course am open to others.

**Comment by dessalines** [comment]
> But you won't be able to see a bigger version of that image when you click on the post, unless you click on the title link and it goes to a new page.

You can click on the image itself (it'll show an image icon), to expand it. This works both from the post listings view, and the post view. For links that have image thumbnails, you can click the + button.

**Comment by OrphieSmol** [comment]
It still doesn't take images from the body and use them in the thumbnail on lists though.

**Comment by dessalines** [comment]
The post body can contain any markdown, including pictures, so I wouldn't want to put random pictures from the body as the thumbnail.

There is an issue to possibly add support for multiple post URLs here: https://github.com/LemmyNet/lemmy/issues/981

**Comment by OrphieSmol** [comment]
I just find it kinda bad if a post is supposed to focus on an image, but the image doesn't show up as the post's main thumbnail.

**Comment by dessalines** [comment]
I don't understand. We already have image posts: 
![image](https://user-images.githubusercontent.com/930215/107991480-afd19600-6fa4-11eb-954c-477ad3f9960f.png)

**Comment by OrphieSmol** [comment]
> 
> 
> I don't understand. We already have image posts:
> ![image](https://user-images.githubusercontent.com/930215/107991480-afd19600-6fa4-11eb-954c-477ad3f9960f.png)

When you do that, they DO show up in the thumbnails, but the only way to view the image is to click on the title link-- and then it opens in a new page. That's very clunky.

Also not having text near the post-image upload icon explaining what it is is pretty clunky. But I digress.

**Comment by dessalines** [comment]
There are two buttons here that expand the picture:

![image](https://user-images.githubusercontent.com/930215/107992881-a564cb80-6fa7-11eb-9bb9-3b0d82bb9105.png)

The + and clicking on the picture itself.
