### ISSUE TITLE
Add toggle to community page to show local or global subscriber count

### ISSUE THREAD

**Issue by laikaislost** [LemmyNet/lemmy-ui#1824]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

**Problem Statement:**

When searching for a new community, I often times want to see the total subscriber count.  Going to the communities page and selecting "All" makes communities seem much smaller than they actually are, and does not tell me what communities are the most globally popular.

This could be helpful when first joining Lemmy, as users look for communities with a lot of content.  It could also be helpful when looking for active subs that may not be popular with the vibe of your local instance.  For political communities, a local instance may have a most popular that is very different than the globally most popular, and a user interested in politics may want to subscribe to both the instance's favorite and the global favorite.  

**Proposed Solution:**

Add a second toggle to the communities page to allow users to see either the local instance subscriber count or the global subscriber count.

**Comment by xhci** [comment]
I agree with this - the current counts are somewhat confusing, and it would be great to have a better way to find the "most popular" community globally on a topic.

**Comment by micahmo** [comment]
Does a single Lemmy instance have access to this data? Currently we use sites like https://lemmyverse.net to crawl for this aggregated data. Would each instance have to query each other instance it's federated with to obtain individual aggregates?

**Comment by lionirdeadman** [comment]
Related to https://github.com/LemmyNet/lemmy/issues/3464
