### ISSUE TITLE
Search instance, type anything, this multiplies the result node indefinitely

### ISSUE THREAD

**Issue by lemmygod** [LemmyNet/lemmy-ui#1829]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you type in the search bar a ! community, example: `!plugins@sh.itjust.works`, it multiplies the node indefinitely

https://github.com/LemmyNet/lemmy-ui/assets/137420192/51f83f0a-e13c-4087-bfca-a5b901b00a4f

### Steps to Reproduce

1. Go to search bar in v0.18.1-rc.10
2. Type a ! community, e.g. `!plugins@sh.itjust.works`
3. Press enter
4. Type anything

### Technical Details

Windows 11, Firefox 115.0, lemmy-ui version 0.18.1-rc.10, on vlemmy.net.

no idea if these logs are relevant. The "url changed!" is from my own userscript so disregard it.

![image](https://github.com/LemmyNet/lemmy-ui/assets/137420192/494d6d9e-adc1-46e6-a91d-afb84ee8077d)

### Lemmy Instance Version

0.18.1-rc.10

### Lemmy Instance URL

https://vlemmy.net

**Comment by lionirdeadman** [comment]
I can't reproduce this bug, can you?

**Comment by lionirdeadman** [comment]
Asked around and nobody could reproduce
