### ISSUE TITLE
Ruby annotation support for markdown

### ISSUE THREAD

**Issue by mcaubrey** [LemmyNet/lemmy-ui#1830]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Ruby annotations are an important part of textual communication in some languages, such as Japanese, where using them for pronunciation guides is common. 

![Screenshot 2023-07-06 at 10 11 04](https://github.com/LemmyNet/lemmy-ui/assets/14105176/4058b193-6af0-4a15-a1da-7c27bb470c21)

As you can see above, smaller text annotations are written above characters. These annotations are achieved using HTML ruby annotation elements like so,

```html
<p><ruby>電子出版<rt>でんししゅっぱん</rt></ruby>を手軽に</p>
```

It would be helpful for Lemmy instances using languages which often employ ruby annotations for pronunciation guides if a markdown implementation of ruby text was added.

**Comment by mcaubrey** [comment]
I submitted a pull request for adding this using the [DenDen Markdown](https://conv.denshochan.com/markdown#ruby) implementation. There is an existing extension for `markdown-it` called `markdown-it-ruby` which will add this.

**Comment by SleeplessOne1917** [comment]
Closing because PR implementing this was merged.
