### ISSUE TITLE
All comments are now shown as marked: `0.18.1-rc.11`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#1835]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

All comments are being shown as marked, regardless of time.

### Steps to Reproduce

See above

### Technical Details

See above

### Lemmy Instance Version

`0.18.1-rc.11`

### Lemmy Instance URL

https://voyager.lemmy.ml

**Comment by lionirdeadman** [comment]
I think this has seen been fixed
