### ISSUE TITLE
Comment box collapses when upvoting parent, comment text is lost

### ISSUE THREAD

**Issue by copygirl** [LemmyNet/lemmy-ui#1836]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I wrote a comment and decided to upvote the parent comment before submitting it, but the comment box collapsed. After clicking reply again I found my comment text was gone altogether. Interacting with the parent comment should not collapse the reply box.

### Steps to Reproduce

1. Reply to a comment
2. Write something in the comment box
3. Upvote the parent comment (other actions might cause this too)
4. Comment box collapses and text is forever gone

### Technical Details

Arch Linux (btw)
Firefox 114.0.2

### Lemmy Instance Version

0.18.1-kt.2

### Lemmy Instance URL

https://lemmy.blahaj.zone/

**Comment by dannirook** [comment]
I had this bug pop up for me a LOT when lemmy.world was lagging.  I would try to upvote something, and when it didn't seem to work, would go to comment--then the upvote would finally go through and my half-written comment would vanish into thin air.

So this bug becomes significantly more "obvious" when an instance is already struggling to deal with user load.

**Comment by gabriel-speziali** [comment]
Adding to this - this also seems to happen to me when liking any comment in the post. 

I am on an instance with the latest Lemmy version, and liking any other comment under the main post will collapse the comment and all progress will be lost. 

Just a bit annoying when writing something and realizing you forgot to upvote the parent 😔.

**Comment by SleeplessOne1917** [comment]
Fixed in #1968
