### ISSUE TITLE
Posts are indented different amounts based on vote count

### ISSUE THREAD

**Issue by Crashdoom** [LemmyNet/lemmy-ui#1837]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Posts appear to be getting indented further as the post's vote count increases past single and double digits.

![image](https://github.com/LemmyNet/lemmy-ui/assets/575410/c99395e3-c052-46e9-b5d0-f57e19a7c4f8)

### Steps to Reproduce

1. Create multiple posts (at least three)
2. Increment the vote counter to 1, 10, and 100 respectively
3. Posts will be indented with each additional digit

### Technical Details

OS: Mac OS Sonoma 14.0 Beta
Browser: Firefox 115.0 Stable

### Lemmy Instance Version

0.18.1-rc.4

### Lemmy Instance URL

https://pawb.social

**Comment by dnswrsrx** [comment]
Appears to have been fixed in this [commit](https://github.com/LemmyNet/lemmy-ui/commit/a72cc6807ed7da8238e0e0e9ac80fbd694ecd793)!
