### ISSUE TITLE
[Bug] When users refresh page, they sometimes see a user that is not them on top right & can access their info

### ISSUE THREAD

**Issue by dannirook** [LemmyNet/lemmy-ui#1843]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I only saw it once, days ago when lemmy.world was lagging, but there is a thread here with someone else's screenshot:

https://lemmy.world/post/1104605

But basically, sometimes when you hard refresh the page, on the upper right your user name vanishes and someone else's appears.  Other users say they can also sometimes see what communities that user is subscribed to.

### Steps to Reproduce

1. Ctrl + F5 to hard refresh the page
2.  Sometimes, for an instant, a user that is NOT you appears in the upper right. Other users reported being able to access that user's info from there, suggesting a security issue of some type.

Unfortunately I can't replicate it reliably, I can only say I saw it myself once a few days before the other people posted it.

### Technical Details

I personally am using Firefox on Windows.  I do not know what the other folks are using.

### Lemmy Instance Version

0.18.1-rc.10

### Lemmy Instance URL

https://lemmy.world

**Comment by alectrocute** [comment]
We’ve chalked this up to NGINX cache misconfiguration. Looks like there’s more work to be done.

**Comment by rcmaehl** [comment]
Duplicate of #1375
