### ISSUE TITLE
Clicking "show context" in a comment notification doesnt scroll to comment

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#185]
Instead the scroll position stays at the top of the post page, and you have to search the comment yourself. Guess this was broken by #162.

Also, clicking this button doesnt always mark the comment as read.

**Comment by dessalines** [comment]
Was it a mention by chance? I don't think I have marking those as read working yet.

**Comment by Nutomic** [comment]
Not sure if it was a comment reply or mention, but its confusing because they look almost identical, and I expect them to work identically.

**Comment by dessalines** [comment]
This is fixed now.
