### ISSUE TITLE
Add "Bot accounts cannot create Communities" admin option

### ISSUE THREAD

**Issue by sanicki** [LemmyNet/lemmy-ui#1855]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Add a admin option "Bot accounts cannot create Communities" which would prevent [bot accounts](https://join-lemmy.org/api/interfaces/Person.html#bot_account) from creating communities on an instance.

![image](https://github.com/LemmyNet/lemmy-ui/assets/6764844/55dcf775-f581-4e64-8bf7-2d4576b02935)

This option would provide admins the ability to stop bot accounts from claiming communities on their instance.

A bot account allowlist could also be implemented to exempt certain bot accounts from the blanket ban.

**Comment by lionirdeadman** [comment]
This wouldn't work - people and bots use the same API. As a result, someone can easily just use a non-declared bot account and bypass this restriction.

**Comment by sanicki** [comment]
> This wouldn't work - people and bots use the same API. As a result, someone can easily just use a non-declared bot account and bypass this restriction.

@lionirdeadman That argument doesn't make sense. You expect individuals creating bots to self-report, but then assume that they will not?

"Bot accounts cannot create Communities" would allow the instance admin to set a policy for their instance.

"We will ban all non-declared bots we discover" would also be a policy set by the admin.
