### ISSUE TITLE
Option to use community name instead of display name in the Subscribed to communities section

### ISSUE THREAD

**Issue by Dusky-dev** [LemmyNet/lemmy-ui#1859]
### Requirements

- [x] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

An option for mods to use the name of the community instead of the display name in the Subscribed to communities section or an option for users to do that.

**Comment by lionirdeadman** [comment]
Why? What does this accomplish?
