### ISSUE TITLE
Refreshing page should not restore scroll position

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#186]
I think if you refresh the page, it should show the top of the page instead of scrolling down. Similarly, clicking the site name/icon in the top left to get to the front page should also bring you to the top of the main page.

**Comment by dessalines** [comment]
Hrm... not sure about this one. For example on mobile, firefox often clears that tab to free up memory, but then when you click on the tab again, it refreshes the page. In that case it wouldn't remember my scroll position and I'd have to scroll down again.

**Comment by Nutomic** [comment]
I'm talking about the case where a user explicitly presses the reload button. Though I'm not sure if you can distinguish that from an automatic refresh.
