### ISSUE TITLE
2FA token copy field

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy-ui#1863]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

The 2FA button link is useful for most 2FA apps but for some, we need the secret key that we can copy and paste into our password managers like KeePassDX and KeePassXC. Please add a button or field that will copy the secret key and also inform the user it uses SHA256 when entering the key manually.

**Comment by foss-** [comment]
KeePassXC user here - this is preventing me from setting up 2FA. Please allow displaying or copying the secret to allow a setup. This is the open KeePassXC feature request for QR Code support for TOTP setup https://github.com/keepassxreboot/keepassxc/issues/4825

**Comment by Shadowstreik** [comment]
Can a status of this ticket be provided? I have this issue, also. Thank you.
