### ISSUE TITLE
Give credit to translators

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#187]
We should show the names of translators somewhere, eg in an about page or next to the language setting. Ideally, only translators for your selected language would be shown (so if you use Lemmy in Spanish, you would see the names of Spanish translators). 

We could either write a script which collects the translator names automatically, or someone could volunteer to maintain the list manually. In the second case, it would even be feasible to include extra data, like links to the Lemmy profiles of translators.

[Discussion about this on Lemmy](https://lemmy.ml/post/52676)

**Comment by dessalines** [comment]
The git log for `lemmy-translations` luckily does show translators:

```
* 1a5f453a - (3 days ago) Translated using Weblate (Polish) - Adam Adamsky (weblate/main)
* 8138a114 - (3 days ago) Translated using Weblate (Basque) - Txopi
* 0aaf93b9 - (3 days ago) Translated using Weblate (Polish) - harc
* 45e9fdc1 - (3 days ago) Translated using Weblate (Chinese (Simplified)) - iggyiccy
*   ed8db27a - (7 days ago) Merge remote-tracking branch 'weblate/main' - Dessalines
|\
| * 2f9ca9d2 - (8 days ago) Translated using Weblate (Swedish) - Johan Winther
| * 7c1bdc0a - (8 days ago) Translated using Weblate (Greek) - Panos Alevropoulos
| * 6599dd63 - (8 days ago) Translated using Weblate (Italian) - riccardo
* |   30a5d618 - (8 days ago) Merge remote-tracking branch 'weblate/main' - Dessalines
|\ \
| * | 5a54702c - (8 days ago) Translated using Weblate (Greek) - Panos Alevropoulos
| * | 2c69a444 - (8 days ago) Translated using Weblate (Italian) - riccardo
```

**Comment by skrlet13** [comment]
You could put donations links for those who would like that! Maybe you aren't able to pay, but others may be.

**Comment by Nutomic** [comment]
A donation link sounds good, or alternatively a link to a personal website. But then we would definitely need someone to help us manage that.

**Comment by skrlet13** [comment]
I think I could help if you are not in a hurry. Could it be possible to generate the list of people with a script and then add links manually?

**Comment by Nutomic** [comment]
There is no rush. You can generate the list of translators with the following commands:
```
git clone https://weblate.yerbamate.ml/git/lemmy/lemmy/ weblate-lemmy
cd weblate-lemmy
git shortlog -s -n -e
```

We can also make an announcement on Weblate, and ask the translators to contact you in some way if they want to be credited. I'm not sure how the end result should be formatted, but ideally it should be machine readable, eg a json document like this:
```
{
    "es": [
        {
            "name": "Some User", "link": "https://example.com"
            "name": "Some Other User", "link": "https://example.com"
        }
    ],
    "de": [
        {
            "name": "Another User", "link": "https://example3.com"
        }
    ],
}
```

Then we need to add the file to this repo, and somehow display the information.

Do you have a Matrix account? Would be easier to discuss things there ([link to our dev chat](https://matrix.to/#/#lemmydev:matrix.org)).

**Comment by dessalines** [comment]
Note: use this for a native language conversion: https://github.com/meikidd/iso-639-1

**Comment by dessalines** [comment]
I've decided for the sake of not having to maintain two of these, to have this be at joinlemmy, and not hosted in both places.
