### ISSUE TITLE
Likes/Dislikes

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy-ui#1873]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I know Reddit, Lemmy and most link aggregators use an upvote and downvote system. I am not against this and am not suggesting to remove it.

Perhaps have both displayed, It will show the upvote/downvote count and also the total likes and dislikes on a post or comment.

Or have a setting to enable Like/Dislikes and instead it will show the total likes and total dislikes on a post or comment instead of a upvote/downvote. If it is a setting, the instance can choose weather to display upvotes/downvotes or likes/dislikes by default.

**Comment by JamesLear92** [comment]
I'd love that functionality as an option.

**Comment by rokejulianlockhart** [comment]
I don't understand. Aren't upvotes and downvotes just likes and dislikes with a different name, and vice versa?

**Comment by 8ullyMaguire** [comment]
People already use upvotes downvotes as like/dislike anyways and they would only click upvote and like so nothing would change. This would be a backend issue anyways. I don't think this is helpful. I would prefer if the [saved count was displayed](https://github.com/LemmyNet/lemmy-ui/issues/1654).

**Comment by lionirdeadman** [comment]
With likes/dislikes and upvotes/downvotes, it's very likely the behaviour would be pretty similar and just complicate sorting - closing.

**Comment by trymeouteh** [comment]
I noticed that when using an instance that is using lemmy-ui such as lemmy.world on a mobile phone in the browser (Or in a desktop browser with the page width being less than 575px), it does show the likes count and dislikes count instead of the total likes and dislikes count together.

Having a setting to choose to show the likes and dislikes just like in mobile view instead of the upvote/downvote on the left side is all that is needed to make this change.
