### ISSUE TITLE
Short tab titles

### ISSUE THREAD

**Issue by vmavromatis** [LemmyNet/lemmy-ui#1876]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

<img width="1203" alt="image" src="https://github.com/LemmyNet/lemmy-ui/assets/8668731/d518b878-2fb3-4e38-9385-71b21d37619b">

Having the `- Lemmy.world` at the end of each tab feels redundant (sometime even more so when in Lemmy.world - Lemmy.world), would be better to remove it and just have the community name like old.reddit does it. The favicon and community name is enough to understand where I am.

**Comment by dessalines** [comment]
Some tab finders / switchers let you filter by name though, so you can use the site name to filter tabs. That would take away that functionality. 

I could go either way on this one though.

**Comment by lionirdeadman** [comment]
Will close considering the PR was rejected
