### ISSUE TITLE
Cross-posting should add quote formatting

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#189]
### Is your proposal related to a problem?

I recently noticed that when cross-posting a topic to another community it looks like the text was written by the cross-poster, while in fact it is only a quote from the original poster. See also discussion here: https://lemmy.ml/post/54228

### Describe the solution you'd like

Original text should be clearly marked as a quote or not shown at all.

**Comment by dessalines** [comment]
I'm debating whether the body should link the original post, or quote the old body. Quoting could be kinda dangerous since it would keep nesting quotes if you cross post from a cross post.

**Comment by poVoq** [comment]
In a sense, cross-posting is like "boosting" a post in Mastodon, hence how is that usually handled in ActivityPub?
