### ISSUE TITLE
[Security] Make JWT cookie HttpOnly

### ISSUE THREAD

**Issue by drumlinish** [LemmyNet/lemmy-ui#1903]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

It would improve security if the JWT cookie is set to HttpOnly so JavaScript cannot access it. This requires some changes in the UI though since the cookie is currently managed by JavaScript running in the browser:

https://github.com/LemmyNet/lemmy-ui/blob/51842d64101ff1ef5f023b60a9ed25cb33b886c1/src/shared/utils/browser/set-auth-cookie.ts#L5-L12

**Comment by sunaurus** [comment]
FYI I am planning to work on this tonight

**Comment by sunaurus** [comment]
I realized this is a duplicate of #1252, let's continue tracking this in that issue
