### ISSUE TITLE
Documentation in Settings UI for Rate Limits

### ISSUE THREAD

**Issue by redserk** [LemmyNet/lemmy-ui#1920]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently it is unclear what the impacts of the various rate limits are in the settings UI. It would be very helpful to have documentation in the Admin UI for what the various Rate Limits control and their practical impacts so that instance admins can figure out how to tune these values to prevent abuse.

Admittedly I'm unsure what exactly the various rate limits control but just as an example I'll use the "Register" rate limit and I'll assume it's strictly limiting how many user accounts can be created in a timeframe. Under the "Message" tab, perhaps a blurb of text with something like:

> Restricts the number of accounts that may be registered in a given time-frame on this instance.
> 
> Increasing the rate allows for more users to register in a given time frame while decreasing this value may help restrict automated signups
> If this value is set too low, users may receive errors when attempting to register an account

**Comment by poVoq** [comment]
This would be still good to have as the current setting options are not very easy to understand, and apparently the rate limits were broken until 0.19.4 and now getting these settings wrong seems to have a significant performance impact of sites.
