### ISSUE TITLE
Add Copy to Clipboard Button

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy-ui#1925]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I would like to request the addition of a single-click copy to clipboard button in all relevant places. This button would be located in the right top corner of code blocks, quotes, and post/comment sources, or maybe just post/comments and it copies the source directly, and would be represented by a clipboard icon, it could be hidden/greyed and shown/highlighted on mouse over. Change the cursor to a pointer (hand) when hovering over the button. When clicked, the button would automatically copy the text to the user's clipboard, making it easy to paste the text elsewhere.

My favorite style for code blocks is the one from Claude 2 Chatbot.

Here's an example:

```python
# This code is formatted using the OneDark syntax highlighting theme

def greet(name):
  """Prints a greeting message"""

  print(f"Hello {name}!")

greet("John")
```

![Screenshot from 2023-08-01 13-05-34](https://github.com/LemmyNet/lemmy-ui/assets/126260333/65d3e560-53b4-468a-90f0-74eff9e1746f)

**Comment by jay-knight** [comment]
Would/could this include a copy button here (green box):

![image](https://github.com/LemmyNet/lemmy-ui/assets/42975397/e87a5560-bd35-4db8-b28a-f67de793bde8)

to copy (e.g.) `!lemmy_support@lemmy.ml` to the clipboard, so I don't have to build that link format every time I want to refer to a community.
