### ISSUE TITLE
Login to Multiple Accounts

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy-ui#1926]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I would like to request a new feature that allows users to log in to multiple accounts. Currently, I have created multiple accounts on different instances due to heavy-load, defederations, and other reasons. However, it's difficult to manage them and find my previous posts. With this feature, I would be able to see all my posts for all the accounts when looking at my posts. Having the ability to see all notifications in one place would be a significant advantage. Additionally, when modifying the content, it would be modified with the appropriate account. It would also be great if there was an easy way to select the main account to use when creating new content. This would make it much easier for me to manage my accounts and find my posts.

If the Sync Users feature was implemented, adding some sort of virtual posts and comments to be able to see my content from other accounts without modifying it, then I wouldn't need this feature. However, if this feature was implemented, I wouldn't need the Sync Users feature [^1]

Alternatively being able to migrate accounts including changing the poster of all posts/comments would solve this issue [^2].

[^1]: [Sync Users](https://github.com/LemmyNet/lemmy/issues/3164)
[^2]: [Implement a way for a user to export their account data](https://github.com/LemmyNet/lemmy/issues/506)

**Comment by lionirdeadman** [comment]
This seems like the job of a third-party client - not of the lemmy-ui.
