### ISSUE TITLE
Can't leave mod team by myself

### ISSUE THREAD

**Issue by ggtylerr** [LemmyNet/lemmy-ui#1932]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

(note: not entirely sure if it's a problem with the backend since I don't have access to it.)

When trying to remove myself as moderator, the option doesn't do anything:

![firefox_2FxH7lTdAj](https://github.com/LemmyNet/lemmy-ui/assets/28498877/28304646-8212-4bde-aedc-9d74f1f4bbca)

(Reloading shows that I haven't been removed.) It only works if I ask another mod or admin to remove my perms. It's possible this is because I was the original creator of the community. There's nothing in the console or network requests that indicate anything wrong too.

### Steps to Reproduce

0. Transfer a community you originally created (possibly not related)
1. Attempt to leave via the sidebar

### Technical Details

OS: Windows 11 Home
Browsers: Tested on Firefox 115.0.1 and Ungoogled Chromium 114.0.5735.199
UI version: 0.18.2-img
BE version: 0.18.1

### Lemmy Instance Version

0.18.2-img

### Lemmy Instance URL

https://lemmy.fmhy.ml

**Comment by lionirdeadman** [comment]
Fixed by #1929
