### ISSUE TITLE
Show all languages

### ISSUE THREAD

**Issue by famfo** [LemmyNet/lemmy-ui#1936]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I can't see certain posts as they are in another language, so I'd like an option to be able to see all posts, regardless of language.

**Comment by famfo** [comment]
My instance only lets me select English as the language.

**Comment by lionirdeadman** [comment]
Seems like an instance issue the way you formulated it. If we'd like to fix this to allow people to show all languages regardless of instance restrictions, I think it's best to close in favour of https://github.com/LemmyNet/lemmy-ui/issues/1736 .

In the meanwhile, talk to your instance admin :)
