### ISSUE TITLE
Uploading Files as Lemmy Sub Thumbnail and Icon throws error

### ISSUE THREAD

**Issue by Haui1112** [LemmyNet/lemmy-ui#1944]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When using Lemmy (server discuss.tchncs.de) on Windows (chrome and firefox) and trying to upload icon and banner for a sub, it throws this error: {"data":{"msg":"Error interacting with filesystem","files":null},"state":"success"}.

### Steps to Reproduce

1. Edit Sub
2. Upload PNG files
3. Get error
4.

### Technical Details

Windows 10
Firefox (and Chrome to check if it was a Firefox issue)
error: {"data":{"msg":"Error interacting with filesystem","files":null},"state":"success"}

### Lemmy Instance Version

BE: 0.18.2

### Lemmy Instance URL

https://discuss.tchncs.de/c/ubuntuserver

**Comment by Haui1112** [comment]
Sorry! Yes, I forgot to close this. They had an issue on their side.

**Comment by 1337Reaper** [comment]
Sorry for opening this again, but @Haui1112 do you happen to know what was going on on their end? I am experiencing the same issue.

**Comment by Haui1112** [comment]
https://discuss.tchncs.de/post/759075

Here's the post where we discussed it. Good luck. :)
