### ISSUE TITLE
Can't switch to light mode when my O.S is in dark mode, and other nitpicks regarding the website's appearance

### ISSUE THREAD

**Issue by alejandro-esquivel** [LemmyNet/lemmy-ui#1946]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

What the title says, there should be a button that lets you switch to light mode because Lemmy's dark mode doesn't look good. There should be more contrast between posts and the body. Either make the body's background color darker or the posts background color lighter. 

You should also make the navbar's color lighter because grey on black doesn't look good.

If a post's content is an image then the post should be larger so I don't have to open the post on another tab. Basically, posts should be larger, just like Reddit's posts on the redesign.

**Comment by lionirdeadman** [comment]
This feature already exists - use the theme setting in your user settings.

![image](https://github.com/LemmyNet/lemmy-ui/assets/39467792/60867516-3494-4623-b2e9-c6b1682e0885)
