### ISSUE TITLE
-1 comments

### ISSUE THREAD

**Issue by KAMiKAZOW** [LemmyNet/lemmy-ui#1947]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

![image](https://github.com/LemmyNet/lemmy-ui/assets/3259076/469ddf49-3480-4ea0-a0ea-9d573af18c8a)

### Steps to Reproduce

The comment thread had one comment and two deleted comments.

### Technical Details

Lemmy seems to see one "active" comment and subtract the two deleted ones from the overall count.

### Lemmy Instance Version

0.18.2

### Lemmy Instance URL

https://lemmy.world/post/1559874

**Comment by lionirdeadman** [comment]
I think this is the same bug as https://github.com/LemmyNet/lemmy/issues/2883 and it is ultimately because the backend is giving bad information to the UI so I'm closing this in favor of the backend issue.
