### ISSUE TITLE
[UX] Highlight search bar when opening search page

### ISSUE THREAD

**Issue by krestenlaust** [LemmyNet/lemmy-ui#1949]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

When clicking the search icon to open the search page, it would be nice for the inputfield to be selected immediately.

**Comment by SleeplessOne1917** [comment]
This made it into production in 0.19.0.
