### ISSUE TITLE
[Bug]:  Communities on remote instances link to the RSS feed on the remote server instead of through the local server

### ISSUE THREAD

**Issue by ShinyDog2636** [LemmyNet/lemmy-ui#1954]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Community pages on remote instances link to the RSS feed on the remote server instead of linking to the RSS feed on the local server

### Steps to Reproduce

1. Visit a remote community (for example, https://lemmy.world/c/fediverse@lemmy.ml)
2. Press the RSS button
3. Be directed to the remote server instead of the local server (for example, https://lemmy.ml/feeds/c/fediverse.xml)

### Technical Details

Examples:
https://lemmy.world/c/fediverse@lemmy.ml links to https://lemmy.ml/feeds/c/fediverse.xml instead of https://lemmy.world/feeds/c/fediverse@lemmy.ml.xml

Note that user pages perform differently: https://lemmy.world/u/dessalines@lemmy.ml appears to correctly link to https://lemmy.world/feeds/u/dessalines@lemmy.ml.xml See https://github.com/LemmyNet/lemmy/issues/3650 for a related bug where this RSS feed is not generated.

### Lemmy Instance Version

BE 0.18.2

### Lemmy Instance URL

lemmy.ml, lemmy.world, lemmy.ca, etc

**Comment by lionirdeadman** [comment]
This seems like expected behaviour to me
