### ISSUE TITLE
Voting on a comment discards the comment you are typing

### ISSUE THREAD

**Issue by KatrinaHoffert** [LemmyNet/lemmy-ui#1968]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Voting on posts closes the comment form, losing whatever you've typed.

### Steps to Reproduce

1. Start typing a reply to a comment. Don't submit it yet.
2. Upvote a comment while your reply is insubmitted. It doesn't seem to matter if I upvote the comment I was reply to or a different one.
3. The reply I was typing is now lost. The text area was discarded and reopening the reply form has the text area open again, forcing me to rewrite my entire comment.

### Technical Details

Noticed this in mobile Chrome (114.0.5735.196) on lemm.ee with Android 13, Samsung s23 ultra. Haven't checked if anything else is affected.

### Lemmy Instance Version

0.18.2 (backend, couldn't tell where it says the front-end version)

### Lemmy Instance URL

lemme.ee

**Comment by daviewales** [comment]
Probably obvious, but this also happens if you remove a vote from a comment.

**Comment by NicolasPA** [comment]
It happens when clicking any of the comment buttons: upvote, downvote, report, star...
It seems it triggers a refresh of the block, which closes the reply form.

Probably the same bug when editing a post:

1. Click edit post (optionally make some change)
2. Upvote a comment
3. The "Save" post button is now greyed out, and you can't save your change anymore. Though the change is not lost this time, you can copy it, refresh the page and edit again.

**Comment by DraconicNEO** [comment]
It also happens when scrolling too far down, should note that it hasn't happened for me when writting a comment on the post, only for replies to other comments.

**Comment by ipkpjersi** [comment]
This happens to me when typing a reply, I go to upvote someone while typing a comment like I am used to on other social media websites, and then my comment is just gone before I can even submit it. This is a horribly annoying bug. It's to the point where I'd almost be willing to throw together a bountysource bounty or something for this issue so it can be prioritized lol this is like my number one 1 Lemmy bug right now.

**Comment by josephrocca** [comment]
Terrifying. I typed out a massive reply, and was about to click upvote before I send the reply (as is very common), but I had some otherworldly intuition that it was for some reason a bad idea, so I copied the comment to my clipboard first, then upvoted, and it deleted the whole comment. I bet many, many others haven't been so lucky :scream:

**Comment by Alex-Esko** [comment]
Super annoying! I add 50€ to this bounty.

**Comment by josephrocca** [comment]
@dessalines @SleeplessOne1917 Just upped my bounty to $300 USD, and sent it to the OpenCollective:

![image](https://github.com/LemmyNet/lemmy-ui/assets/1167575/fa3ea41d-6fec-490a-8300-dcbf416dca41)

Please send this $300 to whoever fixes this issue if that's possible.

If it's not possible to allocate donations like that, no worries, of course. I was already the top financial contributor before this donation (💅), so either way, "the donations will continue until UX improves". Thank  you for your service :pray:

**Comment by josephrocca** [comment]
Thank you so much!! 🙏

**Comment by NicolasPA** [comment]
Thank you @SleeplessOne1917 and @dessalines !
