### ISSUE TITLE
Adding a Federated tab on the front page, so it’s Subscribed/Local/Federated/All

### ISSUE THREAD

**Issue by zksmk** [LemmyNet/lemmy-ui#198]
### Is your proposal related to a problem?

New users on Lemmy have a hard time figuring out on their own they can access and interact with other instances' communities from their own home instance. This feature is not easily discoverable.  And once they do learn of this aspect of federation, they don't intuitively know how to do it.

### Describe the solution you'd like

Adding a Federated tab on the top of front page, so it’s Subscribed/Local/Federated/All as opposed to just Subscribed/Local/All would make federation both significantly more obvious and discoverable than if it were just included under "all", by bringing it in the spotlight, and giving the option to visually segregate federated communities from local ones seems like a useful feature in general.

### Describe alternatives you've considered

1. Adding an "instance" column to the Communities page's table of communities.
2. Adding the community@instance.tld and instance.tld/c/community search syntax.
3. Adding a help page, and a prominent button that leads to it, that explains federation and the federation ui in simple terms
4. Making other instances' communities visually different from home instance's communities by adding a "federated" tag to them.

### Additional context

1. [Issue for point 1](https://github.com/LemmyNet/lemmy-ui/issues/199)
2. [Issue for point 2](https://github.com/LemmyNet/lemmy-ui/issues/200)
3. [Issue for point 3](https://github.com/LemmyNet/lemmy-ui/issues/201)
4. [Issue for point 4](https://github.com/LemmyNet/lemmy-ui/issues/202)

**Comment by dessalines** [comment]
This also already exists... click the federated tab.
