### ISSUE TITLE
Letter tails are cut off in compact view 

### ISSUE THREAD

**Issue by VulumeCode** [LemmyNet/lemmy-ui#1991]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

For reference https://lemmy.world/post/2239181 look at the g's, j's, y's etc

![image](https://github.com/LemmyNet/lemmy-ui/assets/2590984/c1752e03-88b5-4f85-b8f3-ed65d89b7348)

### Steps to Reproduce

Go to a text post like https://lemmy.world/post/2239181 
Look at the letters with tails on the last line of each paragraphs in the post text

### Technical Details

Firefox on Win 11

### Lemmy Instance Version

UI: 0.18.2 BE: 0.18.2-1-g68276b2f9

### Lemmy Instance URL

https://lemmy.world

**Comment by VulumeCode** [comment]
Fixed by injecting the following with the Stylish FF add-on.

```
article p {
  overflow: unset !important;
}
```

**Comment by necropola** [comment]
Isn't the actual issue that `.post-listing {line-height: 1;}` in `*-compact.css` is too small? The body `line-height` in compact style (used to format comments) is still `1.5`.
