### ISSUE TITLE
Add Content Security Policy

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#20]
https://infosec.mozilla.org/guidelines/web_security#content-security-policy

This was previously discussed in LemmyNet/lemmy#208, but now might be a good time to actually set it up.

Edit: more requests: https://git.radicallyopensecurity.com/nlnet/off-ngid-lemmy/-/issues/22

**Comment by Nutomic** [comment]
I generated a CSP using [this Firefox addon](https://addons.mozilla.org/en-US/firefox/addon/laboratory-by-mozilla/), and it works fine during tests with the same addon:
```
default-src 'none'; connect-src 'self'; frame-src https://www.youtube.com; img-src 'self' data:; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' 
```

The values for frame-src and image-src clearly need to be changed so that all images and embeds work
```
default-src 'none'; connect-src 'self'; frame-src *; img-src *; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' 
```

We can either add this directly into Lemmy and deploy it on a test server, or set it via nginx on dev.lemmy.ml, and set it to report-only mode.

**Comment by dessalines** [comment]
I'll do a PR for this in a sec, and test it out on the federation instances.
