### ISSUE TITLE
Adding the community@instance.tld and instance.tld/c/community search syntax.

### ISSUE THREAD

**Issue by zksmk** [LemmyNet/lemmy-ui#200]
### Is your proposal related to a problem?

New users on Lemmy have a hard time figuring out on their own they can access and interact with other instances' communities from their own home instance. This feature is not easily discoverable.  And once they do learn of this aspect of federation, they don't intuitively know how to do it.

### Describe the solution you'd like

Searching is the easiest way of discovery, however, the existing search syntax is non-intuitive for new users, to an extent even the "full url" syntax, so searching most likely yields no results for many new users. Adding the "community@instance.tld" and "instance.tld/c/community" search syntax would fix this, it would also resemble the ease of use that simple auto-linked "r/subreddit" links offer on reddit in posts and comments.

### Describe alternatives you've considered

1. Adding a Federated tab on the front page, so it’s Subscribed/Local/Federated/All
2. Adding an "instance" column to the Communities page's table of communities.
3. Adding a help page, and a prominent button that leads to it, that explains federation and the federation ui in simple terms
4. Making other instances' communities visually different from home instance's communities by adding a "federated" tag to them.

### Additional context

1. [Issue for point 1](https://github.com/LemmyNet/lemmy-ui/issues/198)
2. [Issue for point 2](https://github.com/LemmyNet/lemmy-ui/issues/199)
3. [Issue for point 3](https://github.com/LemmyNet/lemmy-ui/issues/201)
4. [Issue for point 4](https://github.com/LemmyNet/lemmy-ui/issues/202)

**Comment by dessalines** [comment]
This is really confusing how you've laid this out. But this already exists.
