### ISSUE TITLE
Preference to hide "Trending communities"

### ISSUE THREAD

**Issue by sandyarmstrong** [LemmyNet/lemmy-ui#2007]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

On my instance (lemmy.world), the "Trending Communities" sidebar sometimes shows content that is NSFW (in the traditional sense, as in not really appropriate for a coworker or a child to randomly see on my screen).

Can we get a preference to hide this from the main page?

<img width="317" alt="image" src="https://github.com/LemmyNet/lemmy-ui/assets/155076/8c453e85-5f21-4029-8ef8-52b190d415a4">

For now, I'm blocking it with ublock, but even that is a little hairy because the HTML doesn't have useful identifiers for this block. My current blocking rule is `###sidebarMain`, which might be too broad.

**Comment by brihuang99** [comment]
One potential quick fix is to simply add the collapse button to 'Trending communities' card 
![Screenshot_20230801_124404](https://github.com/LemmyNet/lemmy-ui/assets/122472324/87c03238-8895-46eb-bb78-7b671b4ba0f3)

Maybe 'Trending communities' can also rest under the 'Communities' tab in the header as an addition to the other categories? 
![Screenshot_20230801_124648](https://github.com/LemmyNet/lemmy-ui/assets/122472324/5123e341-3d14-426d-beac-61fc92fbd689)

**Comment by lionirdeadman** [comment]
I think a better fix would be the ability for admins to hide NSFW from the /all/ feed and trending communities..

**Comment by dessalines** [comment]
@SleeplessOne1917 How would you feel about removing trending communities entirely? 

Doesn't seem that useful, adds clutter, and admins can now use taglines or the sidebar to highlight specific things anyway. 

I'm saying this because it seems to be used almost as a spam vector: make a new spam account, make a spam community.

**Comment by SleeplessOne1917** [comment]
I can do that if others are interested. Maybe a list of most active local communities based on the number of users over some period of time?

**Comment by dessalines** [comment]
I think I'd rather just remove that box entirely, its real estate that would be better for the sidebar anyway. And the create community and explore communities are already in the navbar.
