### ISSUE TITLE
Ability to browse Lemmy without JavaScript 

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy-ui#2015]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

A way to automatically browse lemmy without javascript when a user without javascript enabled arrives. This would help people who browse with NoScript and it would make it possible for archive.org wayback machine to be able to properly archive lemmy threads

**Comment by lionirdeadman** [comment]
Sorry, seems we both tried to do the same.. closing in favor of #2016
