### ISSUE TITLE
Making other instances' communities visually different by adding a "federated" tag

### ISSUE THREAD

**Issue by zksmk** [LemmyNet/lemmy-ui#202]
### Is your proposal related to a problem?

New users on Lemmy have a hard time figuring out on their own they can access and interact with other instances' communities from their own home instance. This feature is not easily discoverable.  And once they do learn of this aspect of federation, they don't intuitively know how to do it.

### Describe the solution you'd like

If federated communities weren’t shown the same way as local communities they would be more obvious and discoverable. This could be achieved by them having a small “federated” tag next to their names. It should sufficiently stand out visually and be noticed at a glance, and not just present visual clutter that's skimmed over and ignored by new users. In the default theme that's currently being used this could be a green background on white text of the tag that says "federated". 

### Describe alternatives you've considered

1. Adding a Federated tab on the front page, so it’s Subscribed/Local/Federated/All
2. Adding an "instance" column to the Communities page's table of communities.
3. Adding the community@instance.tld and instance.tld/c/community search syntax.
4. Adding a help page, and a prominent button that leads to it, that explains federation and the federation ui in simple terms

### Additional context

1. [Issue for point 1](https://github.com/LemmyNet/lemmy-ui/issues/198)
2. [Issue for point 2](https://github.com/LemmyNet/lemmy-ui/issues/199)
3. [Issue for point 3](https://github.com/LemmyNet/lemmy-ui/issues/200)
4. [Issue for point 4](https://github.com/LemmyNet/lemmy-ui/issues/201)

**Comment by dessalines** [comment]
This already exists, all federated communities use the extended syntax: `community@instance`, whereas local communities use `community`
