### ISSUE TITLE
Markdown rendering for spoiler tags

### ISSUE THREAD

**Issue by Jorge-Alda** [LemmyNet/lemmy-ui#2020]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

The following comment
![image](https://github.com/LemmyNet/lemmy-ui/assets/33020998/66f933cb-2a46-4327-90ca-fa586d095cae)
doesn't result in a bold word. Instead, the asterisks are still visible
![image](https://github.com/LemmyNet/lemmy-ui/assets/33020998/70ba6e00-e1be-4c08-a292-83f1e52ff3d3)

**Comment by biosfood** [comment]
This has been implemented in #2126
