### ISSUE TITLE
A better "Trending Communities" viewer

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2027]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently, the "Trending Communities" viewer isn't overly helpful. More often than not, it appears to just show communities that were recently created, and nothing of any meaningful substance. I propose that a more dedicated "Trending Communities" viewer be made with a much longer list of communities sorted by most trending. The user could then possibly refine the sorting by trending over a time period (today, week, month, year, etc.). The algorithm used to display communities should be tweaked to not put so much weight on communities that are recently created.

Aside: I'm not sure if it already does, but it should also show trending communties over all federated instances, or at least give the option to view those, and not jsut the local instance.

**Comment by brihuang99** [comment]
I do think that "Trending Communities" could potentially rest in the main "Communities" page: 
![Screenshot_20230807_104336](https://github.com/LemmyNet/lemmy-ui/assets/122472324/fd8073e9-eec7-4121-b919-305aafc010e8)

Maybe there can be a "Trending" option in the segmented control and we include a drop down with those options to allow users to sort?

**Comment by AvatarMomo** [comment]
Currently trending communities are only shown at your instance home page. For smaller/single user instances, it would be interesting to know what are the trending communities when you visit a community in a remote instance without leaving their instance.
