### ISSUE TITLE
Spinner when switching pages is quite small and not centered. Make it bigger and centered.

### ISSUE THREAD

**Issue by hirusi** [LemmyNet/lemmy-ui#203]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> Spinner when switching pages is quite small and not centered. There is nothing interesting on the screen at that point anyway, just make it bigger and centered

---

**Comment by EchedeyLR** [comment]
A good size and position:

![Screenshot_20210731-122813](https://user-images.githubusercontent.com/56733813/127738530-35de0020-e353-4ea7-83e6-d3ec8f7881fd.png)

**Comment by EchedeyLR** [comment]
@dessalines

**Comment by EchedeyLR** [comment]
Seems that the spinner is not positioned in the centre in some case.

By now, only happens while loading home page.

https://user-images.githubusercontent.com/56733813/128109597-b61fd050-cb79-472b-a85b-1485e4c8f4da.mp4

This happens on desktop in side screen as can be seen.
