### ISSUE TITLE
Improve footer UI

### ISSUE THREAD

**Issue by MaybeThisIsRu** [LemmyNet/lemmy-ui#204]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> Footer could use some centering and padding to better separate it from content

> Agreed. Still an issue. We could use [flexbox sticky footer](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/). Will open an issue.

**Comment by hirusi** [comment]
I honestly believe this should be a "sticky footer."

Whenever I do open lemmy, the fact the footer jumps up and then goes back down feels like a very janky experience.

**Comment by dessalines** [comment]
Could you show me an example of a sticky footer... sticky to me means always shown which would be an overlay or something.

**Comment by hirusi** [comment]
A [demo is available on Philip Walton's 'Solved By Flexbox' site](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/). If you use the `Toggle Contents` button, you'll see that the footer sticks at the bottom of the page even though there's a lot of space for the body contents.

From a quick glance, something like this would be done from https://github.com/LemmyNet/lemmy-ui/blob/1bd2473cdc65357c18a45c8f1afb532c898b66f6/src/shared/components/app.tsx#L20
