### ISSUE TITLE
Show All Replies for Easy Searching

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy-ui#2043]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I suggest a feature that allows users to show all replies to comments without having to click on each individual "show reply" button. Currently, some comment replies are hidden, and users need to click on the button to expand them. While this is useful for reducing clutter, it becomes inconvenient when users want to search for a specific word within the comments. By implementing a "show all replies" option, users can easily view all the comments and perform searches without the need to click on multiple buttons. There is an existing issue (#1061) related to hiding/showing all children comments, and I'm not sure if this suggestion aligns with that issue.

**Comment by lionirdeadman** [comment]
I think this is because of the 300 comment limit introduced in https://github.com/LemmyNet/lemmy/pull/3306
