### ISSUE TITLE
[Feature Request] Add option to hide subscribed communities on profile.

### ISSUE THREAD

**Issue by ORIOLESFan02** [LemmyNet/lemmy-ui#2044]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

I was a little confused on where to post this, but I believe this is the right one. Apologies if it isn't.

Anyways, I was wondering if there would ever be an option to hide the communities you're subscribed to on your profile?

Meaning that if you were to click someones profile, you wouldn't see what communities they're subscribed to.

Thank you.

**Comment by lionirdeadman** [comment]
You only see that for your own profile, can you explain more what you want?

**Comment by jakariyab** [comment]
If you click to someone else's profile, Do you see the communities they are subscribed to?

**Comment by ORIOLESFan02** [comment]
> If you click to someone else's profile, Do you see the communities they are subscribed to?

I do not. My apologies, I didn't know that was already a thing. I wish I checked before. Thanks.
