### ISSUE TITLE
Forgot password button is disabled but does not have disabled cursor on hover

### ISSUE THREAD

**Issue by hirusi** [LemmyNet/lemmy-ui#205]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> Forgot password button is disabled but does not have disabled cursor on hover

**Comment by dessalines** [comment]
This is necessary due to needing a tooltip there. There's no other way around that.

**Comment by hirusi** [comment]
I don't see a tooltip there, but do see a title attribute. I might be naive here but looks like you can do both? See [Imgur](https://imgur.com/HIFX8G3).

**Comment by dessalines** [comment]
Interesting, could you add this? The file is `main.css`
