### ISSUE TITLE
HTML5 autofill attributes are missing on email fields for login/signup forms

### ISSUE THREAD

**Issue by hirusi** [LemmyNet/lemmy-ui#206]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> HTML5 autofill attributes are missing

[HTML autocomplete attribute on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete).

**Comment by dessalines** [comment]
I'm not familiar with these, this is only for logins correct? So maybe `username` and `current-password` ?
