### ISSUE TITLE
Use consistent button width for the login button

### ISSUE THREAD

**Issue by MaybeThisIsRu** [LemmyNet/lemmy-ui#207]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> Login button changes width when in loading state, this is little bit ugly

**Comment by dessalines** [comment]
I'm not sure this should be an issue, seems strange to hack a constant width on some variable text that can turn into a loading indicator.

**Comment by hirusi** [comment]
Yeah, this is super opinionated. I'll just add I've definitely seen this on a lot of platforms, so I can see where it's coming from. I'd prefer it too!

But, like I said, it's a very opinionated thing.

**Comment by hirusi** [comment]
Came across a nice UI tip [posted by Adam Greenough on Twitter](https://twitter.com/adam_greenough/status/1368908706046476292). Could use that and work something out on top of it.

**Comment by thaithcock** [comment]
You can make the parent div 2 columns wide and give the button `w-100` class to make the button take up the whole column. No need to hack a constant width, I don't think.
You'd do that around [this line](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/home/login.tsx#L170).

**Comment by alectrocute** [comment]
Feel free to open a PR, but this doesn't seem like too high of a priority. Closing.
