### ISSUE TITLE
Interacting with another comment will delete your comment draft

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2080]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If you are in the process of writing a comment, and you go to, for example, upvote another comment, your comment draft will be deleted.

### Steps to Reproduce

1. Create a comment draft in a thread
2. Upvote another comment
3. Observe that your comment draft gets deleted

### Technical Details

- Arch Linux, Kernel v6.4.11-arch2-1
- KDE Plasma v5.27.7, Wayland
- Firefox v116.0.3

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

lemm.ee

**Comment by K4LCIFER** [comment]
Related #2079

**Comment by SleeplessOne1917** [comment]
Fixed in #2189
