### ISSUE TITLE
Report dialog does not close after submit

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#2088]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When trying to report a post, comment, or message, the report does not close after the create report button is clicked. Instead, it spins a loading spinner forever.

### Steps to Reproduce

1. Report a post, comment, or message
2. Enter a reason
3. Click create report
4. Notice that the dialog does not close

### Technical Details

Android version 13
OnePlus 11
Mull Browser

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

https://lemmygrad.ml

**Comment by kevinhikaruevans** [comment]
Related https://github.com/LemmyNet/lemmy-ui/issues/1961
