### ISSUE TITLE
Landing page: upvote/downvote buttons have tooltips of `arrow-up` and `arrow-down`

### ISSUE THREAD

**Issue by hirusi** [LemmyNet/lemmy-ui#209]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> Upvote/downvote buttons have tooltips of `arrow-up` and `arrow-down`

**Comment by hirusi** [comment]
Currently, these have a correct tooltip _and_ a title attribute on the SVG that goes `arrow-up1` and `arrow-down1` -- so perhaps something to look into, or _not_?

**Comment by dessalines** [comment]
Ah yeah, that's probably a bug since I switched to the new `<Icon` component.

**Comment by dessalines** [comment]
I fixed this using `sr-only`.
