### ISSUE TITLE
Add meaninful tooltips to upvote button/downvote button/score label/upvotes and downvotes labels

### ISSUE THREAD

**Issue by hirusi** [LemmyNet/lemmy-ui#210]
Issue extracted from https://github.com/LemmyNet/lemmy-ui/issues/34:

> I would add meaninful tooltips to upvote button/downvote button/score label/upvotes and downvotes labels

This is done in part -- upvote/downvote buttons have tooltips.

**Comment by dessalines** [comment]
I just checked, and all of these have meaningful tooltips.
