### ISSUE TITLE
Signup form quitely truncates password

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#211]
## Issue Summary
The 'Password' and the 'Verify Password' fields in the signup form at https://lemmy.ml/login truncate a string that is pasted to a character length of 60, without displaying an error or a warning when the length exceeds the limit.

## Steps to Reproduce
Attempt to paste a string longer than 60 characters in the sign up form.
Remove the characters in the field and count the number of characters that were pasted (since there isn't an option to view the text in the password field at the moment).
Enter the rest of the details and captcha requirements, and the registration is completed without errors or warnings.

##Technical details
Both fields follow a similar pattern so I'm just listing one of them and the related functions here.
login.tsx
The input field specifies a maxLength of 60.
```
	   <input
              type="password"
              id="register-password"
              value={this.state.registerForm.password}
              autoComplete="new-password"
              onInput={linkEvent(this, this.handleRegisterPasswordChange)}
              maxLength={60}
              class="form-control"
              required
            />
```
I'm guessing the length of the event.target.value here needs to be checked (to indicate to the user with an error or a warning that the password is too long and should be limited to 60 characters) before it is set.
```
handleRegisterPasswordChange

  handleRegisterPasswordChange(i: Login, event: any) {
    i.state.registerForm.password = event.target.value;
    i.setState(i.state);
  }
```

Reported by noklue on Matrix.

**Comment by dessalines** [comment]
Two things here, we need to add the password length check to the back-end on saving user settings as well. I'll do that now.

And I'll also add maxlength to all the other password fields, that should be enough. Then whether your browser truncates on paste (firefox doesn't now), you'll either get a back-end error, or the pasting behavior will at least be uniform.

**Comment by Nutomic** [comment]
That could still cause problems if the user signs up with lemmy-ui, but later logs in with another client which doesnt truncate the password. But its definitely better than now.
