### ISSUE TITLE
On the search page, the selected community cleaers when I change other criteria.

### ISSUE THREAD

**Issue by YousufSSyed** [LemmyNet/lemmy-ui#2120]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When I select a community in the lemmy search, and then change the sorting or the search type (posts, comments, etc.), the community I picked gets cleared and I have to search and select it again.

### Steps to Reproduce

1. Go to the search page.
2. Select a community.
3. Select either the sort tye, or search type (posts, comments, etc.)
4. See that the community is cleared.

### Technical Details

Firefox 117, macOS 14 Beta.

### Lemmy Instance Version

BE: 0.18.4?

### Lemmy Instance URL

lemmy.world

**Comment by Richard-Woessner** [comment]
Ill give it a go. I never contributed to an open source project and this seems like a simple start
