### ISSUE TITLE
Proper UI feedback on error

### ISSUE THREAD

**Issue by h3ndrik** [LemmyNet/lemmy-ui#2143]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

I wrote a direct message with more than 10k characters. Once I clicked 'send' it just closed, as I'd expect it to after it gets sent. But instead it vanished into thin air. I'm not sure if there was a small error message somewhere, but nothing I perceived.

I think error messages should be displayed in a (for the user) transparent way and how they would expect it. Please make it one concept that applies to all failure cases... Character limit exceeded for DMs or comments, network error, ...

This should all result in an error message and not just silently drop the data.

### Steps to Reproduce

1. Click on 'reply' on a DM
2. Write a DM with more than 10.000 characters
3. Click 'Send message'

### Technical Details

Chromium 117
Lemmy 0.18.4

### Lemmy Instance Version

0.18.4

### Lemmy Instance URL

discuss.tchncs.de

**Comment by BMaxV** [comment]
I just tried to create a post and the "post" button just turned into a spinny thing and nothing happened.

I would appreciate some kind of timeout or error message why something didn't work (and who and where to ask for help or info, my instance, their instance, the general help for lemmy, etc.)

**Comment by dessalines** [comment]
We have a 10k character limit on all markdown fields, and I've verified that its working correctly: it won't let you enter more characters than that.

**Comment by BMaxV** [comment]
@dessalines So if it's timing out, display a timeout error, instead of just nothing and pretending it's fine?

**Comment by dessalines** [comment]
We have a few long-running operations that take over a minute to do, so I don't think adding a timeout would be that helpful.
