### ISSUE TITLE
Image and different URL when posting

### ISSUE THREAD

**Issue by mikelgs1** [LemmyNet/lemmy-ui#216]
### Is your proposal related to a problem?
Yes, problem is I liked the problem :-)

When I create a post, I add an URL (i.e. website.com). Afterwards, when I "add" an image, my previous URL is replaced by something like myimage.png (I guess it's needed for the image to be loaded when I click "create"). Once I create the post, obviously the image is loaded but the heading of the post doesn't redirect to website.com as I wanted, the browser opens the image in a tab. 

However, if I go back and edit the post, now I can erase myimage.png from the URL box and write website.com. If I refresh, the image does remain (good) and the link redirects to the place I wanted (great!). 

### Describe the solution you'd like

I'd like to do that at once, not going back and editing. Is it possible already? If so, sorry for this unnecesary message. First time I do this :-)

### Describe alternatives you've considered

(Write your answer here.)

### Additional context

I am using lemmy.eus instance, just in case that's relevant.

**Comment by dessalines** [comment]
We don't have the ability to do hybrid image + link posts. Eventually we might add multi-link posts to do things like this to create image albums, several links, etc. 

But for single url posts, it fetches the thumbnail from the website you give it, so adding a custom image thumbnail doesn't make much sense. And image posts, the URL is the image, so lemmy handles them differently.

You can always insert an image in the post body too.

**Comment by mikelgs1** [comment]
All right!
Thank you for answer and for Lemmy!
