### ISSUE TITLE
Report dialog does not close after reporting

### ISSUE THREAD

**Issue by kevinhikaruevans** [LemmyNet/lemmy-ui#2167]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

After reporting a comment, the dialog (text input and button) should disappear.

![report dialog textbox](https://github.com/LemmyNet/lemmy-ui/assets/4730591/e9b706e8-c49a-47ee-9a77-5a3e03fbf623)

Might be related: but I think if the backend has an error (e.g. a duplicate report), there should be a notification saying an error has occurred.

---

Related resolved issues:

- https://github.com/LemmyNet/lemmy-ui/pull/2089
- https://github.com/LemmyNet/lemmy-ui/issues/2088
- https://github.com/LemmyNet/lemmy-ui/issues/1961

### Steps to Reproduce

1. Press report button under a comment
2. Enter in a reason and press "Create report"
3. Observe the toast notification appears saying it was created
4. Observe the textbox and report button are still there

### Technical Details

Firefox 117.0.1 (64-bit) on Ubuntu 22.04

### Lemmy Instance Version

0.18.5

### Lemmy Instance URL

https://lemmy.world/

**Comment by SleeplessOne1917** [comment]
Already fixed in #2089.
