### ISSUE TITLE
Password length limit notification

### ISSUE THREAD

**Issue by harcesz** [LemmyNet/lemmy-ui#2172]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [X] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

User complained about passwords being "only" 60 characters, but the actual problem is that there is no notification explaining maximum length. I'm guessing it's the backbend that should provide this information as an error.

### Describe the solution you'd like.

Notification like; "password length over limit of 60"

### Describe alternatives you've considered.

Notification like; "get a life"

### Additional context

Length established in this commit; https://github.com/LemmyNet/lemmy/pull/1474

**Comment by Nutomic** [comment]
There are two problems in lemmy-ui here:
- The password fields on signup page use attributes `minlength` and `maxlength` which silently cut off the password. So a user might set a password with 100 chars and it appears to work fine. But another client doesnt do any cutoff and sends the full 100 chars to the backend which results in the error. So minlength and maxlength should be removed.
- There is a correct [translation](https://github.com/LemmyNet/lemmy-translations/blob/main/translations/en.json#L255) for the error, but its not used. Instead the error popup shows literally `invalid_password`.

**Comment by danielkrajnik** [comment]
It took me hours (2.25 hours) to figure out why Voyager doesn't let me login. Turns out lemmy truncated my password silently. Very not happy.
