### ISSUE TITLE
Most side actions loses the comment box

### ISSUE THREAD

**Issue by SineSwiper** [LemmyNet/lemmy-ui#2180]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

It is incredibly easy to lose comment boxes on this UI:

* If you vote for another comment, the comment box disappears
* If you CTRL+click on "View all comments", which is _supposed_ to give you a new tab, the comment box disappears as the whole page is reloaded
* If you hit save or vote on the same comment you're replying to, the comment box disappears
* If you accidentally hit any of comment sort buttons or other actions, the comment box disappears
* If you submit a comment with some other comment box not yet complete, that comment box disappears

None of these actions come with a warning. It just immediately cleans out the comment box and your comment is gone. 

### Steps to Reproduce

1. Try to type a comment with random stuff without submitting it.
2. Do any of the actions above

### Technical Details

Windows 10, Firefox

### Lemmy Instance Version

0.18.5

### Lemmy Instance URL

https://lemmy.world

**Comment by SleeplessOne1917** [comment]
Fixed with #2189
