### ISSUE TITLE
No '2FA installation link' displayed during the 2FA activation process using an iPhone and Firefox

### ISSUE THREAD

**Issue by chris-deluca** [LemmyNet/lemmy-ui#2184]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Using an iPhone and Firefox, the '2FA Installation link' does not appear during the 2FA activation process, leading to a scenario where the user can lock themselves out.

### Steps to Reproduce

1. Sign into a lemmy instance (I used programming.dev) with a current valid account using an iPhone with Firefox
2. Go to User > Settings
3. Click “Set up 2-factor authentication”
4. Note the instructional pop-up that indicates next steps, namely:
 a. Click “Save”
 b. Manually reload the page
 c. Scroll down and use the ‘2FA installation link’ to obtain an oauth URL for your authenticator

Expected Results:
1. To be presented with a “2FA installation link”

Actual Results:
1. No such link appears in Firefox on a iPhone.

Notes:
1. This process works properly using Firefox on the desktop and using Safari on an iPhone.  It appears to be a iPhone/Firefox specific bug.

### Technical Details

iPhone 14 Pro Max
iOS 17.0.3

### Lemmy Instance Version

0.18

### Lemmy Instance URL

https://programming.dev

**Comment by SleeplessOne1917** [comment]
@chris-deluca do you still run into this issue? The 2FA UX was overhauled in v0.19.

**Comment by chris-deluca** [comment]
I was presented with a much better UI flow and was able to register 2FA with Firefox on an iPhone. Thanks!!
