### ISSUE TITLE
Use most recent sorting settings instead of profile default preferences

### ISSUE THREAD

**Issue by krestenlaust** [LemmyNet/lemmy-ui#2188]
### Requirements

- [X] Is this a feature request? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [ ] Did you check to see if this issue already exists?
- [X] Is this only a feature request? Do not put multiple feature requests in one issue.
- [ ] Is this a UI / front end issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo.

### Is your proposal related to a problem?

- Configuring the frontpage, or the posts in a community is annoying, since the configuration isn't saved, and it just reverts back to default on page reload.

- Default timeline setting (all vs. subscribed vs. local) should only be the most recent setting.

### Describe the solution you'd like.

- Store most recent settings per community and frontpage, if the configuration is changed away from default. If you meet a new community, use profile defaults.

- Remove timeline setting preference.

### Describe alternatives you've considered.

The ones I can think of aren't satisfactory to me

### Additional context

This is primarily a backend issue, because it's related to the profile settings, and the backend probably needs to store most recent preferences.

**Comment by dessalines** [comment]
That wouldn't be cross-app compatible. Again I don't think its a good idea to remove explicit preferences in favor of "most recent activity", and saving a new user setting every time might also not be clear to other apps.
