### ISSUE TITLE
Option to customize the favicon

### ISSUE THREAD

**Issue by kuba-orlik** [LemmyNet/lemmy-ui#220]
### Describe the solution you'd like

It'd be cool to be able to customize the favicon of the given instance from Lemmy logo to anything else

### Describe alternatives you've considered

Changing the favicon using nginx config

**Comment by dessalines** [comment]
Hrm... I coulda swore we already did this, and I see in the code helmet is setting it, but it doesn't seem to be working correctly. I'll have to investigate.
