### ISSUE TITLE
After clicking the Search icon, place text cursor in the text box automatically

### ISSUE THREAD

**Issue by MetalZealot** [LemmyNet/lemmy-ui#2213]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Selecting the Search icon in most user interfaces immediately places the text cursor in the text box, allowing you to start typing right away.
With Lemmy, after selecting Search, you have to manually select the text box afterwards.

This really isn't a huge issue, just a quality of life suggestion

**Comment by SleeplessOne1917** [comment]
Handled in PR for #2214
