### ISSUE TITLE
Can't login after activation of 2FA (0.19.0-rc.4)

### ISSUE THREAD

**Issue by ismailkarsli** [LemmyNet/lemmy-ui#2216]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Just activated 2FA on my instance (and voyager.lemmy.ml) and can't login back right now.

### Steps to Reproduce

1. Create account
2. Click "Enable 2-factor authentication" button
3. Copy 2FA link
4. Enter OTP code (the modal closes)
5. I tried both saving the profile and without save. Neither worked.
6. Quit and clear caches
7. Got "Error: missing_totp_token" error

### Technical Details

MacOS, Firefox

### Lemmy Instance Version

0.19.0-rc.4

### Lemmy Instance URL

https://lemy.lol or https://voyager.lemmy.ml

**Comment by dessalines** [comment]
Verified.
