### ISSUE TITLE
Remote posts are not listed in profile (0.19.0-rc.8)

### ISSUE THREAD

**Issue by ismailkarsli** [LemmyNet/lemmy-ui#2240]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

User profile: [https://voyager.lemmy.ml/u/isotest](https://voyager.lemmy.ml/u/isotest)

Local post: [https://voyager.lemmy.ml/post/26319](https://voyager.lemmy.ml/post/26319)

Remote posts: [https://voyager.lemmy.ml/post/26316](https://voyager.lemmy.ml/post/26316), [https://voyager.lemmy.ml/post/26325](https://voyager.lemmy.ml/post/26325)

As you can see, only local post is shown on the profile. This issue occured after rc.5 or rc.6 btw.

Also there is a federation issue between test instances. For example, you can see that remote post I made from Voyager is not shown on DS9: https://voyager.lemmy.ml/c/testcomm@ds9.lemmy.ml -> https://ds9.lemmy.ml/c/testcomm

### Steps to Reproduce

1. Create post on a remote community.

### Technical Details

firefox

### Lemmy Instance Version

0.19.0-rc.8

### Lemmy Instance URL

https://voyager.lemmy.ml and https://ds9.lemmy.ml

**Comment by xaegreal** [comment]
duplicated on: https://github.com/LemmyNet/lemmy/issues/4228

**Comment by dessalines** [comment]
Backend issue above.
