### ISSUE TITLE
SSR Broken for most pages

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#2243]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Pages such as inbox, reports, are all broken on first load.

Votes appear to be missing when logged in, and reloading the post page, indicating some issue with SSR.

### Steps to Reproduce

1. Vote on a post and some comments in that post
2. Reload post page
3. Votes appear missing

EDIT: oof, this is gonna be a bad one. I can't reproduce it either locally with the lemmy.ml DB backup, or on voyager.

### Technical Details

NA

### Lemmy Instance Version

main

**Comment by Nutomic** [comment]
https://github.com/LemmyNet/lemmy-ui/issues/2244 also seems to be caused by the same issue. In my case its actually showing posts from blocked communities under subscribed after first load.

**Comment by dessalines** [comment]
I put `rc.9` on lemmy.ml , and it didn't work. Half the initial page loads ignore / don't use auth. @SleeplessOne1917 I'll need your help with this one, its a critical bug we've got to fix before releasing.

**Comment by Nutomic** [comment]
It does send `Cookie:jwt=xyz` for the initial load, but `authorization` header is completely missing.

**Comment by dessalines** [comment]
[This line](https://github.com/LemmyNet/lemmy-ui/blob/main/src/server/handlers/catch-all-handler.tsx#L40) does set the authorization, and I've tested it locally as working (but it could have some issues).

The other issue is the mis-named cookie, which could be renamed to `auth`... I'd just thought we didn't need to use that because we prefer the `authorization` header.

**Comment by dessalines** [comment]
Nope, its only sending the mis-named cookie, not the authorization header.

![Screenshot_20231129_080312_Kiwi Browser_1](https://github.com/LemmyNet/lemmy-ui/assets/930215/0c279dc1-e133-4059-8c1b-f1be24ef48c0)

**Comment by SleeplessOne1917** [comment]
That's the request for the page's HTML. I don't expect the authorization header to be on that request. If you see [this line](https://github.com/LemmyNet/lemmy-ui/blob/main/src/server/handlers/catch-all-handler.tsx#L35), `jwt` is the cookie name that is expected for SSR. All the requests made on the UI server to the backend server to handle SSR should have the authorization header set, and you shouldn't see that header on requests from the client until you navigate to another page, since client side rendering/routing will be used from that point.

**Comment by dessalines** [comment]
We need to change that to `auth` then, because the back-end expects that as the cookie name now: https://github.com/LemmyNet/lemmy/blob/main/crates/api_common/src/utils.rs#L46C1-L46C1 . 

Something in between (2-3) is going wrong, because half the time the request isn't sending the authorization header. The easiest fix would be to just change the name of the cookie in lemmy-ui from `jwt` to `auth`. U want me to do or u?

**Comment by SleeplessOne1917** [comment]
I have some things to attend to. It would likely be faster for you to do it.

**Comment by dessalines** [comment]
mmk

**Comment by dessalines** [comment]
Deployed this to lemmy.ml , and that fix didn't work either, ugh.

**Comment by Nutomic** [comment]
Now it sends both cookies with each request:

```
Cookie: jwt=xxx; auth=xxx
```
Would be good to clean up the old one. Maybe the backend doesnt properly parse a cookie header with multiple values. We can also switch everything back to `jwt` cookie (including backend), its causing unnecessary trouble.

**Comment by Nutomic** [comment]
Im pretty sure the bug is like this: when prerendering pages on the server side, lemmy-ui makes api requests to lemmy and caches the response based on cache-control header. Later when prerendering page for authenticated user, it uses the previously cached response. However it should never use cached responses if the user is logged in.

**Comment by dessalines** [comment]
The front end caching seems okay at least: https://github.com/LemmyNet/lemmy-ui/blob/main/src/server/middleware.ts#L48 .

**Comment by dessalines** [comment]
Upgraded lemmy.ml to include my auth secure PR fix, and it still didn't fix the issue, ugh.

> That code sends cache-control headers for responses created by lemmy-ui. Im talking about caching in the client which makes requests to lemmy backend.

I don't follow, which cache-control headers are incorrect?

**Comment by Nutomic** [comment]
The headers are fine, problem seems to be that lemmy-ui in server-side mode is incorrectly caching api responses from lemmy. So the fetch function in [LemmyHttp](https://github.com/LemmyNet/lemmy-js-client/blob/main/src/http.ts#L151). This seems to use [cross-fetch](https://github.com/lquixada/cross-fetch) by default (unless Lemmy overwrites it somewhere). So cross-fetch should be configured to disable caching.
