### ISSUE TITLE
Seeing posts for communities I'm not subscribed to

### ISSUE THREAD

**Issue by RichardGladman** [LemmyNet/lemmy-ui#2244]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When refreshing my subscribed communities view, I see lots of posts for communities I am not subscribed to. Navigating away (viewing a post for example) and back again usually shows the correct post

### Steps to Reproduce

1. Log in
2. View your subscribed communities

### Technical Details

Firefox 119.0.1 (64-bit)  on Linux, specifically openSUSE Tumbleweed

### Lemmy Instance Version

BE: 0.19.0-rc.8

### Lemmy Instance URL

https://lemmy.ml/

**Comment by mispp** [comment]
This thing is also happening using boost, so probably not an ui issue.

**Comment by SleeplessOne1917** [comment]
Fixed with #2267
