### ISSUE TITLE
No "Previous" button in feed

### ISSUE THREAD

**Issue by glibg10b** [LemmyNet/lemmy-ui#2250]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

There's no "Previous" button at the top or bottom of the feed, on the first page or any subsequent pages.

![Screenshot_20231129_063319_Firefox Nightly](https://github.com/LemmyNet/lemmy-ui/assets/56197853/4b097eda-1b6c-43c9-9767-7e37e915c137)

![Screenshot_20231129_063334_Firefox Nightly](https://github.com/LemmyNet/lemmy-ui/assets/56197853/df6c8c5f-ff34-43df-84bd-71e8c2ca3208)

### Steps to Reproduce

1. Go to Lemmy.
2. Observe no "Previous" button.
3. Click "Next" multiple times.
4. Still no "Previous" button.

### Technical Details

- Firefox Nightly for Android
- Firefox ESR for Linux

### Lemmy Instance Version

0.19-rc8

### Lemmy Instance URL

https://lemmy.ml

**Comment by dessalines** [comment]
Its intentionally gone, with the switch to page cursors. Use the back button on the browser.

**Comment by glibg10b** [comment]
Ah, okay. I don't think I'll miss it

**Comment by heavyboots** [comment]
I actually did do a search, but apparently not well enough… welp, that explains it, lol. Apologies.
