### ISSUE TITLE
Can no longer log into my account - password below required length

### ISSUE THREAD

**Issue by Xeyk** [LemmyNet/lemmy-ui#2263]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Hello! This issue is specifically with the 0.19 testing.

I am no longer able to log into my account due to a new required password length of 10 characters. The password I have set happens to only be 9 characters. I don't have an email tied to my account, so I'm unable to reset the password. 

I'd like to try to recover my account if possible, since it's over 4 years old. I'd also make the suggestion that password complexity should only be required during registration of a new username as opposed to being a requirement during login of existing usernames. 

### Steps to Reproduce

1. Have account with a password set to only 9 characters
2. Have no email address tied to it
3. Try to log in and receieve error that password needs to be more than 10 characters

### Technical Details

![image](https://github.com/LemmyNet/lemmy-ui/assets/7152014/03f7db5f-45f7-4a91-8e89-ba4f162a2bb1)

### Lemmy Instance Version

0.19

**Comment by ciferkey** [comment]
How were you able to resolve is? I also have an old account with a password less than 10 characters. I cannot log in and when I try to request a password reset email I never receive one.

**Comment by Xeyk** [comment]
> How were you able to resolve is? I also have an old account with a password less than 10 characters. I cannot log in and when I try to request a password reset email I never receive one.

**Comment by ciferkey** [comment]
In case anyone else has this issue in the future I was able to edit the `minlength` property on the input field to `9` to log in:
<img width="1021" alt="Screenshot 2023-12-11 at 7 50 07 AM" src="https://github.com/LemmyNet/lemmy-ui/assets/101422/f76e838d-a6b2-4f84-a61a-6fb040ab29b3">

Then I was able to change my password on my settings page. I also had to change `minlength` on the password confirmation input field.
