### ISSUE TITLE
Background color for new comments is too bright on darkly

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#2264]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

With 0.19 new comments receive a yellow background color. Its not a bad idea to highlight them, but the color is way too bright at least on darkly theme. It should be changed to something which is more consistent with the normal background.

Example:
![Screenshot_20231201_155843](https://github.com/LemmyNet/lemmy-ui/assets/1044450/12b73d01-574b-479b-a961-a3fd482ad3c3)

### Steps to Reproduce

1. Go to lemmy.ml and sort by [new comments](https://lemmy.ml/?dataType=Post&listingType=Subscribed&sort=NewComments)
2. Click on a post and view comments

### Technical Details

-

### Lemmy Instance Version

0.19.0-rc.11

### Lemmy Instance URL

lemmy.ml

**Comment by Atemu** [comment]
Perhaps a more subtle marker would be more appropriate; an outline perhaps.

What might also work would be colouring just the timestamp (or its background?) because that way it'd also be way more obvious what the colouring means; it wasn't to me when I first saw it.

**Comment by Pxtl** [comment]
It's a bad feature in general, imho.  It does not appear to say anywhere on the site what it means, besides hurting readability.  My immediate reaction is "why is this post highlighted as snot-color?  Is it a modmin post?  Did somebody pay to boost it?"

Personally I'd find some other way to flag the post.  Either with text, or an emoji with a tooltip, or whatever.  Text+emoji has the advantage that I could ctrl-F it.  Like, example improvement:

New posts get the text "✨new✨" in the header.  When clicked, the "✨new✨" takes you to the *next* "✨new✨" post.  Add a tooltip over the "✨new✨" linkbutton explaining that's what it does, and why it's been highlighted as new (is it that it's only 15 minutes old?  Or that I haven't seen it yet?)

**Comment by Pseudochron** [comment]
It looks like it's supposed to be light grey. In darkly.css it says `--bs-highlight-bg: #333;`. But that is only defined in the `[data-bs-theme=light] {` section. 

`--bs-highlight-bg: #333;` should be added to the `[data-bs-theme=dark] {` section.

**Comment by Undearius** [comment]
At the very least, I think the `mark` class should only be on the timestamp. It's a lot more subtle and actually gives an indication what the highlighting means.

![image](https://github.com/LemmyNet/lemmy-ui/assets/1106442/d285460d-2797-4844-b4e0-1e77bd8b05af)

I'm not very technically but I have narrowed it down to moving `mark: this.isCommentNew` from https://github.com/LemmyNet/lemmy-ui/blob/9e68dbef20816920be7d64b12f534b9cd5ea3739/src/shared/components/comment/comment-node.tsx#L211 and possibly the `isCommentNew()` function at line 600 to https://github.com/LemmyNet/lemmy-ui/blob/9e68dbef20816920be7d64b12f534b9cd5ea3739/src/shared/components/common/moment-time.tsx#L43 Lines 43 and 53

**Comment by Pseudochron** [comment]
If you wanted to highlight the timestamps on recent posts, you wouldn't need to change which element gets the class. You could target other elements under the `mark` class in each theme's CSS.

```
.mark .moment-time {
  color: orange;
}
```

**Comment by dessalines** [comment]
PRs welcome.
