### ISSUE TITLE
Add option to view notificated comment in post

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#227]
### Is your proposal related to a problem?
When I receive a notification when someone commented into my post, I always don't manage to see the comment into context in the original post-thread.

### Describe the solution you'd like
I would add a button/option where, clicking, it goes to the original comment on post.

It would be an "eye" icon which has the comment's link and redirects to it on the same browser tab.

![outline_visibility_black_18dp](https://user-images.githubusercontent.com/61913683/112183181-4c1f3600-8bfe-11eb-9863-edb13414f3dc.png)
https://material.io/resources/icons/?search=view&icon=visibility&style=outline

### Describe alternatives you've considered
Alternatively, the post link on top right of notifications could redirect to the notificated comment, instead of to post.
![irudia](https://user-images.githubusercontent.com/61913683/112183698-c9e34180-8bfe-11eb-8aeb-14309a7f3924.png)

This may not be a good solution.

**Comment by Nutomic** [comment]
It used to scroll directly to the comment, but that was broken by #162 I think.

**Comment by dessalines** [comment]
Most likely. BTW the chain link button is the context / goto link one. 

I just tested, and did find that if you refresh a page, the scrolling does work, but you're correct I think I broke something with #162 for the post pages.
