### ISSUE TITLE
Deleted content showing on user profile

### ISSUE THREAD

**Issue by 8ullyMaguire** [LemmyNet/lemmy-ui#2277]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

In the new 0.19 version, deleted posts are currently visible on a user's profile to all users. However, it is suggested that only the creator should have access to view these posts, ideally in a separate tab similar to saved posts. This approach would prevent cluttering the profile with deleted content while still allowing users to easily locate and potentially undelete their own posts.

### Steps to Reproduce

1. Delete post or comment
2. Visit profile from other user
3. Deleted posts and comments appear there saying "deleted by creator"

### Technical Details

Firefox

### Lemmy Instance Version

0.19

**Comment by Nothing4You** [comment]
I can't reproduce this.

Attempted reproduction steps on 0.19.0:

1. Login as Bob
2. Create post
3. Create comment on this post
4. Delete comment
5. Logout
6. Open Bob's profile page without login
7. Comment is listed, only contains text _deleted by creator_
8. Open Bob's profile page as Alice
9. Comment is listed, only contains text _deleted by creator_
10. Login as Bob again, delete the post, logout
11. Open Bob's profile page without login
12. Post is gone, comment is listed as before
13. Open Bob's profile page as Alice
14. Post is gone, comment is listed as before

**Comment by 8ullyMaguire** [comment]
In the new 0.19 version, deleted posts are visible on a user's profile to all users. I believe only the creator should have access to view these posts, perhaps in a separate tab like saved posts, to avoid cluttering the profile with deleted content. It is beneficial for a user to see their own deleted content for potential undeletion, but for other users, it should not be displayed.

**Comment by Nutomic** [comment]
@8ullyMaguire I deleted a post from this account and dont see it anywhere on the profile:

https://ds9.lemmy.ml/u/nutomic

**Comment by 8ullyMaguire** [comment]
To test this, I deleted all content in this account https://programming.dev/u/CoderSupreme

I can see the deleted posts both from other instances and from the same instance when I'm logged out.
