### ISSUE TITLE
0.19.0 and above: 2FA page should say, "Do not hit Enter".

### ISSUE THREAD

**Issue by Tipoff4317** [LemmyNet/lemmy-ui#2308]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Problem

1. Enable 2FA, finishing by providing the generated code.
2. Logout
3. When supplying the generated TOTP code **after hitting enter**, got recycled back to the login page, while expecting to have been logged in.

I think how it's supposed to work is, you enter the code and the script takes it automatically to the next page. If the script is slow (which often was for me), I think maybe I should hit enter (probably activating the cancel button), it takes me back to the email/password page.

### Request
So, to help a user like me, maybe putting a message saying "do not hit enter" in would suffice.

### Context
The discussion was originallly in a bug report:
* https://github.com/LemmyNet/lemmy/issues/4326#issuecomment-1868998546
* https://github.com/LemmyNet/lemmy/issues/4326#issuecomment-1876319791

**Comment by Die4Ever** [comment]
I don't think telling the user not to hit enter is the correct solution, normally when requests are processing websites will disable the form inputs and buttons so that it can't be resubmitted while processing

**Comment by SleeplessOne1917** [comment]
I think a good approach would be to add a submit button and allow the form to be submittable both manually and automatically after a few seconds. As @Die4Ever added,  the inputs should also be enabled while fetching.

**Comment by SleeplessOne1917** [comment]
Closing this as the PR for this is merged.
