### ISSUE TITLE
When posting from Mastodon, the community's tag is shown at the start of the post title as an unrendered markdown link

### ISSUE THREAD

**Issue by josephrocca** [LemmyNet/lemmy-ui#2309]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If someone makes a post on Mastodon like:
```
@foo@lemmy.world Hello this is the first line of my Mastodon post
```
Then, IIUC, it should appear as a post at lemmy.world/c/foo with the title `Hello this is the first line of my Mastodon post`, but instead the title is `[@foo](https://mastodon.social/@foo@lemmy.world) Hello this is the first line of my Mastodon post`.

Note that the markdown link is not "rendered". Here's what it looks like in the lemmy.world web UI:

![image](https://github.com/LemmyNet/lemmy-ui/assets/1167575/10e7d6c8-d069-4d8d-99b8-1b00bacf9308)

And this is what the associated Mastodon post looks like in the mastodon.social web UI:

![image](https://github.com/LemmyNet/lemmy-ui/assets/1167575/0f45bdf9-57eb-46fd-ac31-1563a840f5f6)

I'm not actually sure whether this is a front end or back end issue - just taking a guess here.

### Steps to Reproduce

1. Make a post on Mastodon like `@foo@lemmy.world Hello`
2. Visit lemmy.world/c/foo and observe post title

### Technical Details

N/A

### Lemmy Instance Version

0.18.5

### Lemmy Instance URL

lemmy.world

**Comment by Nutomic** [comment]
This is fixed in 0.19

https://ds9.lemmy.ml/post/9508
