### ISSUE TITLE
Main Icons pixelating on zoom

### ISSUE THREAD

**Issue by tafiti** [LemmyNet/lemmy-ui#231]
For backend issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

The main website icon - top left of each instance's website - pixelates when zoomed in. This is not the case with Join.Lemmy website. 

### Describe the solution you'd like

An icon that does not pixelate when zoom level changes. 

### Describe alternatives you've considered

The join.lemmy icon does not pixelate and upon inspection, it is using a .png just like lemmy.ml. I wonder why the difference, and if .svg may resolve this.

**Comment by Tafiti** [comment]
While researching on this issue, I encountered a thread on [Adobe's channel ](https://community.adobe.com/t5/illustrator/pixelated-icons-when-saving-for-website/m-p/9380555) with a similar issue. While not perfectly aligned to what we have here, there is the suggestion that one should export whatever image they want in the exact size/dimensions they want for the website etc. If that may help,it raises the question as to whether you have hard coded specific size for the icon, and as such if we can upload icons with those exact dimensions.
