### ISSUE TITLE
Option to enlarge the video

### ISSUE THREAD

**Issue by kuba-orlik** [LemmyNet/lemmy-ui#232]
### Is your proposal related to a problem?

When posting a video (say, an mp4 file), it gets displayed in this small preview box:

![image](https://user-images.githubusercontent.com/2697916/113187194-dbf55d80-9258-11eb-9c6e-bd2122edae5a.png)

The only way to enlarge it is to make it fullscreen.

### Describe the solution you'd like

It'd be best if the video uploads were treated the same way as image uploads are - clicking on them causes them to enlarge, both in single post view, as well as on post lists view

**Comment by dessalines** [comment]
For mp4's, we're using the browser's native video player, that ensures it will work on all browsers. I'm not sure that I'd want that thumbnail being larger than anything else. I'm also not sure what a different player like `video.js` would give us either.

**Comment by kuba-orlik** [comment]
Native player is not an issue here - the issue is how impractically small it is.

![image](https://user-images.githubusercontent.com/2697916/113737666-88728c00-96fe-11eb-89a2-fb919aeb00cc.png)

I can either view it in 100x60 tiny window or fullscreen, there's nothing in between. Compare it to how pictures are shown. At first they show an equally tiny thumbnail:

![image](https://user-images.githubusercontent.com/2697916/113737901-ba83ee00-96fe-11eb-8aa8-52c42789985d.png)

And clicking that thumbnail (or the "+" icon in the headline) causes the image to get bigger:

![image](https://user-images.githubusercontent.com/2697916/113737957-c8d20a00-96fe-11eb-9c38-655e82db1186.png)

Having a similar "expand" option for mp4s would be a GREAT usability improvement

**Comment by alectrocute** [comment]
Resolved in https://github.com/LemmyNet/lemmy-ui/pull/1479.
