### ISSUE TITLE
Add a tab to the user applications to see only denied applications

### ISSUE THREAD

**Issue by Ategon** [LemmyNet/lemmy-ui#2321]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently its a bit difficult to keep track of recent accounts that got denied since they tend to be flooded out by the accepted users.

Use case for seeing denied accounts only would be to do things such as check if someone is attempting to make alts with similar names. Usually spammers will try to do very similar name formats (I had one just add 1 to the end of the username and apply with that)

**Comment by jmcharter** [comment]
I've taken a crack at addressing this. #2322

**Comment by SleeplessOne1917** [comment]
Closed in #2322
