### ISSUE TITLE
question mark breaks URL parsing

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy-ui#2330]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

a URL with a question mark in it breaks the clickable URL

### Steps to Reproduce

1. go to https://programming.dev/comment/6567805 for an example broken link

### Technical Details

a URL such as https://programming.dev/c/lemmy@lemmy.ml?dataType=Post&sort=Hot

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/94ebc6fd-2bcd-4bdc-82f5-817893751dd3)

even if I use markup like

`[https://programming.dev/c/lemmy@lemmy.ml?dataType=Post&sort=Hot](https://programming.dev/c/lemmy@lemmy.ml?dataType=Post&sort=Hot)`

### Lemmy Instance Version

0.18.1

### Lemmy Instance URL

programming.dev

**Comment by sevonj** [comment]
![image](https://github.com/LemmyNet/lemmy-ui/assets/100710152/b06c7c64-97ed-4a77-9e57-5115035773d3)

Still happens on 0.19.3
