### ISSUE TITLE
security.txt expires date

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy-ui#2332]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

the date would have to be adjusted:
https://github.com/LemmyNet/lemmy-ui/blob/main/src/server/handlers/security-handler.ts#L14

### Lemmy Instance Version

0.19.2

### Lemmy Instance URL

https://rollenspiel.forum/

**Comment by Tealk** [comment]
Reading the mail address from .env makes sense, because the ones given there do not exist for me either.

I would continue to offer the file, because security problems are more likely to be reported in the project via `Contact: mailto:security@lemmy.ml` or the repo here instead of the admin who offers the service. Most of them will not be able to fix much of it in the lemmy code.

**Comment by Nutomic** [comment]
The Lemmy footer has a link to the source code which has a way to [report security issues](https://github.com/LemmyNet/lemmy-ui/security/advisories/new). There is also a link to join-lemmy.org which lists additional contact methods. So I dont think the email is necessary, Im not even sure if its working or if anyone ever used it.

cc @dessalines

**Comment by Tealk** [comment]
Line 7 could then also be changed to: 
```
`Contact: https://github.com/LemmyNet/lemmy-ui/security/advisories/new
```
