### ISSUE TITLE
after password entry, focus should be 2FA input field

### ISSUE THREAD

**Issue by derrickoswald** [LemmyNet/lemmy-ui#2338]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Using 2FA with Lemmy login has a speed-bump: when the login-name and password are entered, the 2FA input field is not set as the focus element, and one must cycle focus (using tab) through the "view password" and "forgot password" to the "2FA Token" field (id='login-totp-token') before you can enter the token despite the toast notification popup saying "Enter your 2FA code".

![Screenshot from 2024-01-21 11-29-06](https://github.com/LemmyNet/lemmy-ui/assets/1239771/c2ac314f-c469-4473-8e34-60c7b04a86f3)

**Steps to Reproduce:**

- Set up two factor authentication for a user.
- Login as that user by entering the _username_ &lt;TAB&gt; _password_ &lt;ENTER&gt; on the login form.
- The 2FA field is revealed and a toast popup says "Enter your 2FA code".
- Entering your 2FA code actually adds it to the password field.

**Expected behavior:**

- When the 2FA input field is made visible it would also receive focus.

**Comment by SleeplessOne1917** [comment]
What version of lemmy UI are you using? The 2FA UI was changed fairly recently.

**Comment by derrickoswald** [comment]
I can confirm that the issue is still present in v0.18.5:
Firefox 121.0.1 (64bit) on Linux 6.5.0-14-generic <span>#</span>14~22.04.1-Ubuntu

**Comment by Nutomic** [comment]
@derrickoswald 0.18 is outdated, 0.19 has the latest 2fa changes.
