### ISSUE TITLE
No UI feedback for pending registration when attempting to log in

### ISSUE THREAD

**Issue by vallode** [LemmyNet/lemmy-ui#2341]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

If registration needs to be approved on an instance, attempting to log in before your registration is approved will result in the login button spinning for a moment and then stopping with no feedback. A 400 status network request shows that the login is denied with "registration_application_pending". This should show in the UI to remind the user to wait.

### Steps to Reproduce

1. Register a new account on an approval-only instance (e.g https://lemmy.world/)
2. Attempt to log in before the registration is approved (e.g https://lemmy.world/login)
3. See no visual feedback for failed login

### Technical Details

Browser: Firefox
OS: Linux

Relevant console error:
```
XHRPOST
https://lemmy.world/api/v3/user/login
[HTTP/2 400  988ms]
error	"registration_application_pending"
```

### Lemmy Instance Version

0.18.5

### Lemmy Instance URL

https://lemmy.world/

**Comment by SleeplessOne1917** [comment]
This is fixed on the main branch, but there is a bug with the translation, so I will open a PR for that.
