### ISSUE TITLE
Localized Finnish text partially missing from UI

### ISSUE THREAD

**Issue by Rynach** [LemmyNet/lemmy-ui#240]
### Issue Summary

After updating to Lemmy's newest version, localized Finnish text is partially missing from certain sections of the UI. 
![kuva](https://user-images.githubusercontent.com/8532455/113709241-f01edc00-96ea-11eb-8484-1ef1ba03c639.png)
The text for local view is missing, where as in the English localization it looks like this:
![kuva](https://user-images.githubusercontent.com/8532455/113709374-15134f00-96eb-11eb-9d84-fc0c7ce22c0f.png)
Also the text for sorting posts in the feed is partially missing.
![kuva](https://user-images.githubusercontent.com/8532455/113709482-32e0b400-96eb-11eb-9546-3c034c2cf0df.png)
The English localization for comparison:
![kuva](https://user-images.githubusercontent.com/8532455/113709430-22303e00-96eb-11eb-8a80-3eefa88aef71.png)
In the bottom right corner the texts "Instances" and "Join Lemmy" are missing, making the instances view and [Join Lemmy](https://join.lemmy.ml/) inaccessible.
![kuva](https://user-images.githubusercontent.com/8532455/113709576-54da3680-96eb-11eb-8a64-9ae64e7aae31.png)
The English localization for comparison: 
![kuva](https://user-images.githubusercontent.com/8532455/113709776-936ff100-96eb-11eb-8fa9-0c6483d911e2.png)
User counts per day, week and 6 months are also missing:
![kuva](https://user-images.githubusercontent.com/8532455/113730565-ac36d180-9700-11eb-80a0-fe8abd8b965e.png)
The English localization for comparison: 
![kuva](https://user-images.githubusercontent.com/8532455/113730753-d2f50800-9700-11eb-950f-50d0e3a06834.png)
In the user settings view the texts for uploading a banner and local view are missing: 
![kuva](https://user-images.githubusercontent.com/8532455/113710107-fb263c00-96eb-11eb-91dd-2987e2e4202c.png)
The English localization for comparison: 
![kuva](https://user-images.githubusercontent.com/8532455/113710193-142eed00-96ec-11eb-90bb-7d948dd9a701.png)

### Steps to Reproduce

1. Change the language to Finnish

**Comment by dessalines** [comment]
Thanks, looks like there was some issues with that translation file in `lemmy-translations`. I fixed it in a merge, and they should be fixed / updated in the next patch release.
