### ISSUE TITLE
appoint moderator confirmation dialog has incorrect text

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy-ui#2429]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

when appointing a moderator it shows their username instead of the community name

"Are you sure you want to appoint Die4Ever@programming.dev as a moderator for Die4Ever@programming.dev?"

### Steps to Reproduce

1. go to post from user
2. click appoint as moderator
3. read the confirmation dialog

### Technical Details

![image](https://github.com/LemmyNet/lemmy-ui/assets/30947252/47230779-7b7f-4e3f-b3fd-5d5e54c2bc0c)

### Lemmy Instance Version

0.19.3

### Lemmy Instance URL

https://lemmy.mods4ever.com/post/274

**Comment by SleeplessOne1917** [comment]
I'm unable to reproduce this version on the main. I also tested on https://ds9.lemmy.ml (which runs 0.19.4-beta.2) and I didn't get the bug there. Could you test on ds9 to see if you still encounter the issue?

**Comment by dessalines** [comment]
I think you fixed this, and the issue was probably a dupe.
