### ISSUE TITLE
[Bug] Sending Direct Message fails `0.19.4-beta.5`

### ISSUE THREAD

**Issue by ticoombs** [LemmyNet/lemmy-ui#2439]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Uncaught TypeError: t.preventDefault is not a function

![image](https://github.com/LemmyNet/lemmy-ui/assets/2687896/2ba7b5f4-6ffe-41db-874d-8d769e3a9931)

### Steps to Reproduce

1. Login to a 0.19.4-beta.4 instance
2. Try to send a PM
3. Fail
4.

### Technical Details

Tested on Voyager.lemmy.ml too.

Doesnt happen with alternate UIs which hit the API endpoint, so its a -ui issue

### Lemmy Instance Version

0.19.4-beta.4

### Lemmy Instance URL

https://voyager.lemmy.ml

**Comment by ticoombs** [comment]
@dessalines This one :)

**Comment by dessalines** [comment]
Thx! I'll look into this soon.
