### ISSUE TITLE
ability for admins to view all local users

### ISSUE THREAD

**Issue by Die4Ever** [LemmyNet/lemmy-ui#2450]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Maybe it would be good if admins could see a list of all the local users.

**Comment by SleeplessOne1917** [comment]
I think this will also require an API endpoint. Currently, the only way to fetch a list of users from the server is with the `/search` endpoint, which only works if it has a search query.

**Comment by dessalines** [comment]
iirc we've closed a similar issue for this, mainly because, what use is it? 

If you have thousands of local users, paging through them is pointless.
