### ISSUE TITLE
Crash when viewing page source

### ISSUE THREAD

**Issue by hermantolim** [LemmyNet/lemmy-ui#247]
### Issue Summary

Viewing page source will crash the app with error "No valid WebSocket class provide". This is related to this issue in https://github.com/pladaria/reconnecting-websocket/issues/72

### Steps to Reproduce

1. View page source on browser

### Technical details
* What OS are you trying to install lemmy on?  Linux
* Any browser console errors? nope! the server just crashed

### Solution
in `src/shared/services/WebSocketServices.ts`

```
import WS from "ws";

...

public wsOptions: WsOptions = {
        WebSocket: isBrowser() ? undefined : WS,
        connectionTimeout: 5000,
        maxRetries: 10,
}
```

**Comment by Nutomic** [comment]
Why dont you make a pull request? ;)

**Comment by dessalines** [comment]
How did you even find this? When using view-source, it will automatically use the back-end isomorphic and skip the websocket, I just tested this.

**Comment by hermantolim** [comment]
@dessalines I just tested with the master branch on firefox and chrome, still crashed when view page source. Are you unable to reproduce the same error?

**Comment by dessalines** [comment]
Yep, even on chrome I'm unable to reproduce:

![image](https://user-images.githubusercontent.com/930215/114043047-f2e91080-9853-11eb-8102-2aa3143a363d.png)

I don't think I've set up isomorphic for the setup page, so it might show it for that one.

**Comment by hermantolim** [comment]
yeah, just tested the others pages, looks like only the setup page have this problem. Will close this for now
