### ISSUE TITLE
[Bug]: Error 502 after clicking save in profile settings

### ISSUE THREAD

**Issue by XioR112** [LemmyNet/lemmy-ui#2497]
### Requirements

- [X] Is this a bug report? For questions or discussions use https://lemmy.ml/c/lemmy_support
- [X] Did you check to see if this issue already exists?
- [X] Is this only a single bug? Do not put multiple bugs in one issue.
- [X] Do you agree to follow the rules in our [Code of Conduct](https://join-lemmy.org/docs/code_of_conduct.html)?
- [X] Is this a backend issue? Use the [lemmy-ui](https://github.com/LemmyNet/lemmy-ui) repo for UI / frontend issues.

### Summary

Every time after clicking save in profile settings I receive 502 Bad Gateway error. 

### Steps to Reproduce

1. While logged in go to profile settings.
2. Scroll down and click save.
3. Receive error.

### Technical Details

I tested it on Firefox and my smartphone. I believe it's an backed issue but if I'm mistaken please correct me.

### Version

BE: 0.19.4-rc.2

### Lemmy Instance URL

lemmy.ml

**Comment by dessalines** [comment]
I think I got a simple fix for it.
