### ISSUE TITLE
Selectable Markdown elements (i.e. bold, link etc) don't work on first click. (0.19.4)

### ISSUE THREAD

**Issue by Demigodrick** [LemmyNet/lemmy-ui#2523]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When creating a post, the elements above the text box for the body (bold, italic, url etc) won't work when clicked and instead either do some sort of refresh (the community at the bottom momentarily changes to "select a community" before changing back) or instead deselects the body text box. 

Clicking one of the options will make it work, but won't work if you are for example highlighting text to be bolded.

This appears to work fine when replying to a comment. I suspect this may be linked to #2522 as it seems similar behaviour.

Can replicate this on lemm.ee and lemmy.zip

### Steps to Reproduce

1. Put some text in a new post.
2. Select one of the editor elements
3. Nothing happens
4. Click again to get the element to function.

### Technical Details

Lemmy 0.19.4 instances

### Lemmy Instance Version

0.19.4

### Lemmy Instance URL

lemmy.zip

**Comment by SleeplessOne1917** [comment]
Like the other issue you made recently, I was able to reproduce this on the 0.19.4 tag, but not the main branch. This seems to have been fixed in one of @matc-pub's recent PRs.
