### ISSUE TITLE
Uploads tab on /u/username page shows uploaded files of currently logged in user

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#2524]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Uploads tab on /u/username page shows uploaded files of currently logged in user, not those of the actual user that is being viewed.

At least as an Admin you should be able to view the files a user has uploaded, and for sure seeing your own uploads on a user's page is unexpected.

### Steps to Reproduce

1. navigate to a user-profile page
2. click "uploads" tab
3. See your own uploads

### Technical Details

Image proxy is enabled, but I don't think that makes a difference.

### Lemmy Instance Version

0.19.4

### Lemmy Instance URL

https://slrpnk.net

**Comment by dessalines** [comment]
That's correct, we should only be showing that uploads tab if it's your own user. Was my bad when adding this.

**Comment by SleeplessOne1917** [comment]
Looks like there is more to this than the UI. [The `ListMedia` request always assumes it's fetching media for the currently logged in person.](https://github.com/LemmyNet/lemmy/blob/b2a480f55ce7fd327d46b81f43697069c9befdbd/crates/api_common/src/person.rs#L433-L436)

**Comment by SleeplessOne1917** [comment]
> not all uploads are public, they should definitely not be visible to other users that aren't admins

Would it make sense to filter out private media but still show public media to all users, e.g. everything that's not posted in a direct message or any comments in private communities (and local only communities if viewing from another instance or unauthenticated on the same instance)?

**Comment by Nothing4You** [comment]
there is no way to reliably track that. users can upload images in a private message and then copy the image url and include it in a public post. they may also upload it and never submit the post/comment they intended to upload it for. you'll also have to start tracking this when a user edits or deletes their post/comment containing the image reference and verify there is no other public reference to it before hiding it.

i don't really see the value for a non-admin user to see someone else's uploads, usually you'd just go through a users posts to see their uploads.
