### ISSUE TITLE
address decodes incorrectly in the URL field for the new post submission

### ISSUE THREAD

**Issue by yogthos** [LemmyNet/lemmy-ui#2532]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When calling `https://lemmy.ml/api/v3/post` with the following payload, the URL that gets parsed out ends up being incorrect:

request:

```javascript
{"post_id":16756924,"name":"Joint Statement of the BRICS Ministers of Foreign Affairs/International Relations","url":"https://www.mea.gov.in/bilateral-documents.htm?dtl/37860/joint+statement+of+the+brics+ministers+of+foreign+affairsinternational+relations","body":"https://www.mea.gov.in/bilateral-documents.htm?dtl/37860/joint+statement+of+the+brics+ministers+of+foreign+affairsinternational+relations","nsfw":false,"language_id":37}
```

response:

```javascript
{"post_view":{"post":{"id":16756924,
 "name":"Joint Statement of the BRICS Ministers of Foreign Affairs/International Relations",
 "url":"https://www.mea.gov.in/bilateral-documents.htm?dtl/37860/joint%20statement%20of%20the%20brics%20ministers%20of%20foreign%20affairsinternational%20relations=", ...}
```

### Steps to Reproduce

1. create a new post with the following URL `https://www.mea.gov.in/bilateral-documents.htm?dtl/37860/joint+statement+of+the+brics+ministers+of+foreign+affairsinternational+relations`
2. check whether a valid URL appears in the post that's created

### Technical Details

Firefox on Ubuntu

### Lemmy Instance Version

BE: 0.19.4

### Lemmy Instance URL

https://lemmy.ml

**Comment by SleeplessOne1917** [comment]
I did some debugging on this and the URL stays in the correct encoding for the create post request, but returns in the incorrect encoding in the response. I think this is a serverside issue.

**Comment by yogthos** [comment]
Oops meant to open it on the other repo, let me close it and make a new one there.

**Comment by yogthos** [comment]
moved issue to backend https://github.com/LemmyNet/lemmy/issues/4801
