### ISSUE TITLE
Crossposting is broken

### ISSUE THREAD

**Issue by citking** [LemmyNet/lemmy-ui#2537]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Crossposting a story isn't working. The community search box reloads the UI after finding the searched-for community to crosspost to, clearing the URL, title, and anything else. 

### Steps to Reproduce

1. Click on the crosspost icon in a given post. 
2. The Submit a post page appears, with the title, URL, and anything else contained within the post. 
3. At the very bottom, search for the community you want to crosspost to. Click on the community to select it. 
4. The page will then reload, wiping out everything except for the community. 

### Technical Details

Tested in chrome and Firefox with the same result. It appears to be a bug that is clearing the current page when something loses focus. 

### Lemmy Instance Version

0.19.4

### Lemmy Instance URL

Https://real.lemmy.fan

**Comment by dessalines** [comment]
This is probably fixed now in main, could you test this out on https://voyager.lemmy.ml ?

**Comment by citking** [comment]
Will do, just sent in an account request.

**Comment by dessalines** [comment]
Approved.

**Comment by citking** [comment]
Verified that this is working in main.

**Comment by dessalines** [comment]
Sweet, thx.
