### ISSUE TITLE
Inputs broke

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#2542]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Text field input gets lost somehow

(Bug is not happening on iPhone with newer OS/browser)

### Steps to Reproduce

1. Go to search, or the post creation form
2. Type something
3. Click a button or another text field
4. Typed text disappears

### Technical Details

Safari, iPadOS 16.7.8, desktop mode

### Lemmy Instance Version

0.19.4

### Lemmy Instance URL

https://lemmy.ml

**Comment by dullbananas** [comment]
Also a problem with other inputs, such as the buttons for subscribed, local, all

**Comment by dessalines** [comment]
I believe that @matc-pub and @SleeplessOne1917 fixed this one, and we need to do a bugfix release. 

I'll start some `0.19.5-alpha` builds and put them on voyager to verify.

**Comment by dessalines** [comment]
Okay I've put an alpha build up on https://voyager.lemmy.ml . I can't replicate the bug anymore.

**Comment by dullbananas** [comment]
Still broken on https://voyager.lemmy.ml

**Comment by matc-pub** [comment]
> Also a problem with other inputs, such as the buttons for subscribed, local, all

This sounds like the script fails completely. Do you get any error messages?

**Comment by dullbananas** [comment]
There's no error messages or logs

**Comment by SleeplessOne1917** [comment]
Are there any more specific steps to reproduce this? I followed all of the ones listed in the issue and encountered no errors.

**Comment by dullbananas** [comment]
It seems to be affected by the browser version

**Comment by SleeplessOne1917** [comment]
That's unusual. I don't think we're using any bleeding-edge browser APIs that would cause browser compatibility issues.

**Comment by Krisseck** [comment]
I can replicate the bug on 0.19.4 everytime when cross-posting a post with an image. Using latest Firefox & Chrome.

- Click "cross-post" button on a post
- Change value of f.ex. Community, NSFW fields
- The form loses all values, like Image and Title

**Comment by dessalines** [comment]
I've tried also to replicate this on https://voyager.lemmy.ml , and can't. I spose we can leave this open, but we need a way to replicate this.

**Comment by Krisseck** [comment]
I can't replicate the bug on voyager.lemmy.ml anymore, currently running 0.19.5-alpha.3 🥳

**Comment by dessalines** [comment]
Cool, I spose we can close this then.

**Comment by dullbananas** [comment]
I still have the problem on that version

**Comment by matc-pub** [comment]
The problem appers to be only observable with Safari, iPadOS 16.7.8, desktop mode

> I still have the problem on that version

Does 0.19.3 work? (lemmy.world is on 0.19.3)

**Comment by dullbananas** [comment]
0.19.3 does work

**Comment by makotech222** [comment]
just wanna mention, after 0.19.5 update, hexbear users on safari are running into url-related issues around pagination and such

https://hexbear.net/post/2853344

**Comment by dessalines** [comment]
I think this is fixed now, can re-open if there are any issues on `0.19.6-xx`

**Comment by dullbananas** [comment]
It's fixed
