### ISSUE TITLE
[Bug]: "Expand Media" with `auto_expand_media` off, and an embedded_url gives no way to embed in the page.

### ISSUE THREAD

**Issue by youju26** [LemmyNet/lemmy-ui#2547]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When enabling the "Media Auto Expand" feature and opening the lemmy.ml front page, a video download starts.
Does not happen in lemmy.world.
The cause is this specific post: https://lemmy.ml/post/16978055
It also starts the download, when opening the post directly

### Steps to Reproduce

1. Enable "Media Auto Expand" in settings
2. Open "https://lemmy.ml/post/16978055"

### Technical Details

OS: Windows 11
Browser: Firefox
Instance: lemmy.ml

### Lemmy Instance Version

0.19.4

### Lemmy Instance URL

https://lemmy.ml

**Comment by SleeplessOne1917** [comment]
I think the issue discussed in the PR is distinct from this issue. The change from the PR is already merged and the UI no longer auto-downloads files.
