### ISSUE TITLE
Allow serving .css.map files for custom themes

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#2581]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When serving custom themes like https://github.com/hanubeki/hanubeki-lemmy-themes the browser complains:
`Source-Map-Fehler: Error: request failed with status 400`
Because it is looking for the .css.map file that accompanies the main .css file. And indeed when navigating to where the file should be, Lemmy-ui returns `Theme must be a css file`.
The custom theme still works, but this seems like an unnecessary error.

### Steps to Reproduce

1. Install custom theme .css and .css.map files
2. See error in the browser (Firefox)

### Technical Details

Firefox browser.

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

https://slrpnk.net

**Comment by dessalines** [comment]
Lemmy-ui can only handle a single css file for its custom themes. You need to open up an issue on that repo if its theme files aren't working.

**Comment by hanubeki** [comment]
`FYI, .css.map` files was removed from my themes.
Sorry for the inconvenience, @poVoq.
