### ISSUE TITLE
Add an button to reach users saved items besides the personal menu

### ISSUE THREAD

**Issue by Ninguem** [LemmyNet/lemmy-ui#2613]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

It is cumbersome to have to go to the personal menu, choose profile and select saved to view saved posts.
A little button besides the personal menu (top right) would be great! Near the ones that are already there (notifications, search...).

**Comment by Tmpod** [comment]
I made the following (very crude) userscript to patch in a button like that:

```js
// ==UserScript==
// @name        Lemmy saved icon
// @namespace   Violentmonkey Scripts
// @match       https://lemmy.pt/*
// @grant       none
// @version     1.0
// @author      -
// @description Adds a navbar icon to your saved articles.
// ==/UserScript==


window.addEventListener('load', function() {

user = document.querySelector("#dropdownUser a").href;

saved = document.createElement("li");
saved.innerHTML = `
<li id="navSaved" class="nav-item">
  <a class="nav-link d-inline-flex align-items-center d-md-inline-block" href="${user}?view=Saved">
    S
  </a>
</li>
`;

navbarIcons = document.getElementById("navbarIcons");
dropdownUser = document.getElementById("dropdownUser");
navbarIcons.insertBefore(saved, dropdownUser);

}, false);
```

**Comment by dessalines** [comment]
We have this on the bottom bar in jerboa, and could add it to lemmy-ui-leptos. If someone wants to add it here, I'll re-open this issue and assign it to them.
