### ISSUE TITLE
docker build --platform linux/amd64 -t lemmy-ui .   195 error code ERESOLVE 196 error ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by qiancsff** [LemmyNet/lemmy-ui#2615]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

docker build --platform linux/amd64 -t lemmy-ui .   195 error code ERESOLVE 196 error ERESOLVE unable to resolve dependency tree
root@debian:~/lemmy-ui# node -v # should print `v20.15.1`
npm -v # should print `10.7.0`
v20.15.1
10.7.0
root@debian:~/lemmy-ui#

root@debian:~/lemmy-ui# node -v # should print `v20.15.1`
npm -v # should print `10.7.0`
v20.15.1
10.7.0
root@debian:~/lemmy-ui#

### Steps to Reproduce

docker build --platform linux/amd64 -t lemmy-ui .   195 error code ERESOLVE 196 error ERESOLVE unable to resolve dependency tree
root@debian:~/lemmy-ui# node -v # should print `v20.15.1`
npm -v # should print `10.7.0`
v20.15.1
10.7.0
root@debian:~/lemmy-ui#

root@debian:~/lemmy-ui# node -v # should print `v20.15.1`
npm -v # should print `10.7.0`
v20.15.1
10.7.0
root@debian:~/lemmy-ui#

### Technical Details

root@debian:~/lemmy-ui# node -v # should print `v20.15.1`
npm -v # should print `10.7.0`
v20.15.1
10.7.0
root@debian:~/lemmy-ui#

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

lemmy.com

**Comment by qiancsff** [comment]
root@debian:~/lemmy-ui# cat Dockerfile
FROM node:alpine AS builder

# Added vips-dev and pkgconfig so that local vips is used instead of prebuilt
# Done for two reasons:
# - libvips binaries are not available for ARM32
# - It can break depending on the CPU (https://github.com/LemmyNet/lemmy-ui/issues/1566)
RUN apk update && apk upgrade && apk add --no-cache curl python3 build-base gcc wget git vips-dev pkgconfig

# Enable corepack to use pnpm
RUN corepack enable

# Install node-gyp
RUN npm install -g node-gyp

WORKDIR /usr/src/app

ENV npm_config_target_platform=linux
ENV npm_config_target_libc=musl

# Cache deps
COPY package.json pnpm-lock.yaml ./
RUN pnpm i
# Build
COPY generate_translations.js \
  tsconfig.json \
  webpack.config.js \
  .babelrc \
  ./

COPY lemmy-translations lemmy-translations
COPY src src
COPY .git .git

# Set UI version
RUN echo "export const VERSION = '$(git describe --tag)';" > "src/shared/version.ts"
RUN echo "export const BUILD_DATE_ISO8601 = '$(date -u +"%Y-%m-%dT%H:%M:%SZ")';" > "src/shared/build-date.ts"

RUN pnpm i
RUN pnpm prebuild:prod
RUN pnpm build:prod

RUN rm -rf ./node_modules/import-sort-parser-typescript
RUN rm -rf ./node_modules/typescript
RUN rm -rf ./node_modules/npm

FROM node:alpine AS runner
ENV NODE_ENV=production

RUN apk update && apk add --no-cache curl vips-cpp && rm -rf /var/cache/apk/*

COPY --from=builder /usr/src/app/dist /app/dist
COPY --from=builder /usr/src/app/node_modules /app/node_modules

RUN chown -R node:node /app

LABEL org.opencontainers.image.authors="The Lemmy Authors"
LABEL org.opencontainers.image.source="https://github.com/qiancsff/lemmy-ui"
LABEL org.opencontainers.image.licenses="AGPL-3.0-or-later"
LABEL org.opencontainers.image.description="The official web app for Lemmy."

HEALTHCHECK --interval=60s --start-period=10s --retries=2 --timeout=10s CMD curl -ILfSs http://localhost:1234/ > /dev/null || exit 1

USER node
EXPOSE 1234
WORKDIR /app

CMD ["node", "dist/js/server.js"]
root@debian:~/lemmy-ui#

**Comment by qiancsff** [comment]
npm install eslint@^8.56.0
After installation,
 Docker build crashes

**Comment by dessalines** [comment]
Use `pnpm i`. 

And what version of docker are you using?

**Comment by dessalines** [comment]
Not enough info.
