### ISSUE TITLE
Secondary languages not showing

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#265]
If the language list has several languages, but the top one isn't supported, it will default to english.

**Comment by Nutomic** [comment]
Even the primary language is ignored in some cases. For example when I set my browser language to Korean, it sends the header `Accept-Language: ko,es-ES;q=0.5`, but Lemmy is shown in English. Tested while being logged out, so it cant be related to user settings.

**Comment by Nutomic** [comment]
Ah its because Korean localization isnt enabled, even though its 100% finished. Wouldnt it be possible to use all translations automatically if they exist, instead of having to enable them manually?

**Comment by dessalines** [comment]
Unfortunately not, they do need manual imports. I'll do that now for ko.

**Comment by Nutomic** [comment]
Guess I am too spoiled from Android development, where the SDK takes care of that and you barely ever have to think about localization.
