### ISSUE TITLE
Decrement comment count for blocked user comments

### ISSUE THREAD

**Issue by hungryca-t** [LemmyNet/lemmy-ui#2653]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

**Description**
The feed comment count under a post accounts for blocked user comments, though on viewing the post, the comment is not visible. For example, if a post has a single comment according to the comment counter, and that comment was posted by a blocked user, opening the post will reveal there are no comments.

This is particularly noticeable since I have blocked a media bias checker bot, which is frequently the first if not the only commenter on news-related posts. When scrolling through my feed, the comment count will be 1, but when loading the post, I discover there are no visible comments and realize the counter is considering the bot’s comment.

**Requested resolution**
Decrement the feed comment counter for posts with comments posted by blocked users.

**Context**

### Steps to Reproduce

1. Block the Media Bias Fact Checker not, or any user known to have commented on a post.
2. Scroll through the news community.
3. See most new posts have a single comment.
4. Open the post to reveal that there are no visible comments.

### Technical Details

iPhone SE 2020. iOS 16. Chrome. 

### Lemmy Instance Version

0.19.3

### Lemmy Instance URL

https://lemmy.world

**Comment by dessalines** [comment]
This is a back-end issue, but also I don't see us adding this, because then we'd have to store separate counts for every item for every user based on their blocks and language settings.
