### ISSUE TITLE
Comments more than 8 levels in, fail to load when logged in.

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#2656]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

This seems like a regression of an earlier issue, but replies that are more than 8 levels threaded can not be loaded when pressing the load more replies button. This only happens when logged in. Opening parent post that is 8 levels threaded in a browser window that is not logged into an account loads the responses normally.

And example would be this post: https://slrpnk.net/post/12220714/10342739 but obviously the problem is only visible when logged in.

### Steps to Reproduce

1. Make a threaded comments 8 levels deep
2. Add a 9th or 10th etc reply to it
3. Find that the show more replies button that is hiding these additional posts only results in an endless spinning icon
4. Open 8th comment in a non-logged in browser window to be able to read the replies

### Technical Details

Latest version of LibreWolf (Firefox)

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

https://slrpnk.net/

**Comment by dessalines** [comment]
I don't have an account there, but I tried to replicate this locally, and couldn't:

https://github.com/user-attachments/assets/c166c25c-1906-4172-843a-b4f4c0ea4004

Is it possible that one of the branches is either in a language that you don't support, or by a blocked user? 

I'd need to see the console logs.

**Comment by poVoq** [comment]
Yes it appears that some of these messages are wrongly tagged with Greek language, which I have not enabled.

**Comment by dessalines** [comment]
Gotcha. Ya accounting for blocks and language restrictions in the comment counts and trees isn't something we could support easily (it'd require specific counts to be stored for every user, rather than a single one).
