### ISSUE TITLE
[Bug]:  YouTube links used to give decent suggestios for Title and a thumbnail

### ISSUE THREAD

**Issue by m3t0034** [LemmyNet/lemmy-ui#2658]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Not anymore x 1 week. Just says YouTube and no thumb. Probably YT reshuffled some data. Was nice for music videos.

Thanks

### Steps to Reproduce

1. make new post
2. paste YT URL in form; https://www.youtube.com/watch?v=3mbvWn1EY6g
3. read suggestions

### Technical Details

on FireFox/linux Been putting screenshot in body then grabbing the local url to paste into form for thumbnail

### Lemmy Instance Version

BE: 0.19.5

### Lemmy Instance URL

https://midwest.social/c/music

**Comment by Die4Ever** [comment]
I've also noticed this on programming.dev, I actually thought it was just an issue with the instance. They're still running 0.19.3

**Comment by dessalines** [comment]
Yep, youtube is locking down lots of requests, and we don't control things from their end.

**Comment by m3t0034** [comment]
notice Facebook still gets thumbs and titles. must be a pay service now ;eyeroll;
![youtubefacebookthumbs-Screenshot_2024-08-27_12-23-46](https://github.com/user-attachments/assets/24c0fa54-32f7-4ebf-8f69-3b2a8ad3c4b0)

**Comment by dessalines** [comment]
I've been adding a lot of torrent-specific features to both lemmy and jerboa lately, the next release I'll probably announce a community effort to move a lot of existing youtube content into torrents.
