### ISSUE TITLE
Saved posts should be sorted by the date they were saved, not the date the post was made.

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2683]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

If one sorts saved posts by new, the posts will be ordered by the date the post was created rather than when the posts were saved. It would make more sense, given the context, for the posts to be sorted by the date they were saved. So, sorting by new would put the most recently saved posts at the top, ahead of posts that may be newer, but were saved before.

I'm not sure if this would be better implemented as a backend change.

**Comment by dessalines** [comment]
This is a back end issue, that I believe was already fixed.

**Comment by K4LCIFER** [comment]
> I believe [this issue] was already fixed.

Ah, okay — sh.itjust.works is still on 0.19.3.

**Comment by dessalines** [comment]
It might also be in an unreleased fix, but it is taken care of.
