### ISSUE TITLE
Fediverse logo switcher

### ISSUE THREAD

**Issue by mak448a** [LemmyNet/lemmy-ui#2684]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

There seem to be many different opinions on what the Fediverse logo should be. Could you add different options configuration panel in settings? [This website](https://symbol.fediverse.info/) seems to think that `⁂` should be the logo.

**Comment by dessalines** [comment]
We use the most popular one. If you'd like to add this tho, feel free to do a PR.
