### ISSUE TITLE
Using NavLink instead of Link in navbar

### ISSUE THREAD

**Issue by hermantolim** [LemmyNet/lemmy-ui#269]
### Is your proposal related to a problem?

It's related to navbar active page, in `src/shared/components/navbar.tsx`

https://github.com/LemmyNet/lemmy-ui/blob/1bd2473cdc65357c18a45c8f1afb532c898b66f6/src/shared/components/navbar.tsx#L175-L195

(Write your answer here.)

### Describe the solution you'd like

we should use `NavLink` instead of `Link` from inferno-router

the `NavLink` is a `Link` wrapper that knows if it's active or not

**Comment by dessalines** [comment]
Could you do a PR for this? Thanks.

**Comment by hermantolim** [comment]
working on it
