### ISSUE TITLE
Numbers and padding aren't rendered for some numbered list items

### ISSUE THREAD

**Issue by dullbananas** [LemmyNet/lemmy-ui#2697]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Items 8 to 13 are rendered incorrectly here, and GitHub markdown doesn't have this problem

![IMG_2697](https://github.com/user-attachments/assets/ad595d9d-30fa-4497-aede-95355735ce94)

### Steps to Reproduce

1. Create a post with this body: https://lemmy.ca/post/29274252 (use the view source button)
2. View the post

### Technical Details

Safari from iOS 18.0, desktop mode, iPhony

### Lemmy Instance Version

0.19.5

### Lemmy Instance URL

https://lemmy.ca

**Comment by dessalines** [comment]
Seems like you fixed it, but also this would be a bug with the markdown-it library we're using (but I highly doubt that's the case, because it has good support for the commonmark spec).

**Comment by dullbananas** [comment]
I still see the broken list
