### ISSUE TITLE
Remote follow communities on the front end.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#27]
Needs two components: 

- [ ] A `remote_community_follow.tsx`. [Example](https://mas.to/users/GreenLantern/remote_follow) Needs a form with your user actor_id / `@user@instance`, which redirects to: 
- [ ] An authorize follow page, which has: 
  - Mastos url:  `https://mastodon.social/authorize_interaction?uri=https://instance/users/aaron`.
  - It gets this authorize_interaction url from webfinger ostatus:     
```
{
      "rel": "http://ostatus.org/schema/1.0/subscribe",
      "template": "https://mastodon.social/authorize_interaction?uri={uri}"
    }
```

**Comment by krestenlaust** [comment]
Hello, this is I, from the far-future.

**Comment by SleeplessOne1917** [comment]
This should be covered with the remote follow functionality that was added in 0.19.0.
