### ISSUE TITLE
Expanded images are too small due to only showing thumbnails

### ISSUE THREAD

**Issue by Nothing4You** [LemmyNet/lemmy-ui#2793]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

Lemmy-UI uses the thumbnail URL when showing expanded images.
As thumbnails are now limited in size this is no longer suitable for full size images for expansion.

### Steps to Reproduce

1. Create post to an image URL with a resolution larger than 256x256
2. Expand image of post

### Technical Details

https://github.com/LemmyNet/lemmy/pull/5107 restricts the resolution of generated thumbnails.

Example:
https://lemmy.ml/post/22206928
![image](https://github.com/user-attachments/assets/cab8e9b5-f3fb-4a16-a617-bfbd7ead53ca)

https://sh.itjust.works/post/27691217
![image](https://github.com/user-attachments/assets/9351b6ac-9a52-4a50-a5a2-3b9b77eff497)

### Lemmy Instance Version

0.19.6-beta.15

### Lemmy Instance URL

https://lemmy.ml/

**Comment by dessalines** [comment]
Its a backend issue, so I'll close this one in favor of it: https://github.com/LemmyNet/lemmy/issues/5173
