### ISSUE TITLE
Language tagging for Posts/Comments

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#280]
A list of frontend changes needed for https://github.com/LemmyNet/lemmy/issues/440 / https://github.com/LemmyNet/lemmy/pull/1578.

- On user registration, send `discussion_languages` vec as part of `Register` call
    - This could be set manually by the user, or simply populated from the browser accept-language header
- User preference to select discussion languages, from a list provided by the backend
    - Might be good to allow reordering of languages, if we allow multi-language community description, this would allow us to show the preferred one for each user
- New post/comment form gets a language selection dropdown
    - The list of available languages and the default selection are sent by the backend

**Comment by sam365724** [comment]
For the last point, there really should be a way to set the user's default post language. It would be super annoying if the user has to chose his default language for each post. 
@Nutomic I just tested the language feature on dev.

**Comment by Nutomic** [comment]
Language for new posts is set automatically in some cases, specifically when the union of community languages and user languages contains a single item (eg when community only specifies one language). For comments, the language of parent post/comment is used as default. Note that the implementation in lemmy-ui is not finished yet, as site/community languages arent implemented.

**Comment by sam365724** [comment]
Oh sounds great, thanks for letting me know. 
Regarding UI: I think the additional full line for the language selection box uses too much space on the page, maybe that can be optimized. For new post i would put it on the same line as NSFW for example.

**Comment by dessalines** [comment]
I agree, it does take up too much space. I might even move it to the markdown-editor as a popup, because it shouldn't be so intrusive.

**Comment by Nutomic** [comment]
Already implemented.
