### ISSUE TITLE
[Bug]: Post Thumbnails are not generated anymore, after upgrading to v0.19.6 & v0.19.7

### ISSUE THREAD

**Issue by r-hmn** [LemmyNet/lemmy-ui#2805]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

The post-miniature (for e.g. links to youtube video's) is not showing for new posts.
(i tried pasting a picture by clipboard into a post body, and that pictrs-entry did get properly inserted, and using that url as thumbnail url does work)

### Steps to Reproduce

1. login as bot or non-bot user
2. go to a community, and 'create post' 
3. fill in a link (i tried both a youtube link, and a mainstream news-website link)
4. both the post detail-page and that in the community page show this 'link arrow' instead of a thumbnail

### Technical Details
The previous version before upgrading was v0.19.5

My system is setup using ansible;
```
docker ps
CONTAINER ID   IMAGE                                   COMMAND                  CREATED        STATUS                 
992929be834f   nginx                                   "/docker-entrypoint.…"   6 hours ago    Up 6 hours             
68f555619c4d   dessalines/lemmy-ui:0.19.6              "docker-entrypoint.s…"   6 hours ago    Up 6 hours (healthy)   
9622dd15ff8f   dessalines/lemmy:0.19.6                 "lemmy_server"           6 hours ago    Up 6 hours             
905faa39f108   pgautoupgrade/pgautoupgrade:16-alpine   "/usr/local/bin/dock…"   6 hours ago    Up 6 hours (healthy)   
e3560dd39a8e   portainer/portainer-ce:latest           "/portainer"             4 months ago   Up 6 hours             
40e95d9fa263   mwader/postfix-relay                    "/root/run"              4 months ago   Up 6 hours             
3cea99868998   asonix/pictrs:0.5                       "/sbin/tini -- /usr/…"   4 months ago   Up 6 hours             

uname -a
Linux ly-lubuntu 5.15.0-125-generic #135-Ubuntu SMP Fri Sep 27 13:53:58 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Lemmy Instance Version

0.19.6

### Lemmy Instance URL

https://lemmy.staphup.nl/

**Comment by Nothing4You** [comment]
this isn't a ui issue, there are thumbnails missing for various posts to external urls on lemmy.ml as well: https://lemmy.ml/?dataType=Post&listingType=Local&sort=New

the api response for those posts does not contain a thumbnail url.

**Comment by r-hmn** [comment]
Thanks
i guess i have to copy the content from here to the backend issues list?

**Comment by r-hmn** [comment]
i upgraded to v0.19.7, but this problem is still there.

**Comment by r-hmn** [comment]
In v0.19.9;
When posting a youtube url _the thumbnail is still not automatically populated_, 
even though commit #5208 seemed to attend that issue?

I updated my bot to retrieve the youtube thumbnail-url itself and provides it when posting, so i don't need to track this issue any longer.
