### ISSUE TITLE
Change "Overview" to "Activity" and have it actually display user activity

### ISSUE THREAD

**Issue by K4LCIFER** [LemmyNet/lemmy-ui#2818]
### Requirements

- [X] This is a feature request and not a bug report. Otherwise, please create a new [bug report](https://github.com/LemmyNet/lemmy-ui/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=BUG_REPORT.yml) instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this request (or a similar one) already exists.
- [X] It's a single feature. Please don't request multiple features in one issue.

### Describe the feature you'd like

Currently the Overview just shows comments and posts in the order of the sorting type specified, but I think it would be more useful to show a feed of activity for things like edits. So if a post or a comment is edited, it will show up at the top of the Activity list if one is sorting it by "New".

**Comment by dessalines** [comment]
This is out of scope, editing doesn't and shouldn't bump things in lemmy.
