### ISSUE TITLE
Translations issue?

### ISSUE THREAD

**Issue by fleabeard69** [LemmyNet/lemmy-ui#2842]
### Requirements

- [X] This is a bug report, and if not, please post to https://lemmy.ml/c/lemmy_support instead.
- [X] Please [check](https://github.com/LemmyNet/lemmy-ui/issues) to see if this issue already exists.
- [X] It's a single bug. Do not report multiple bugs in one issue.
- [X] It's a frontend issue, not a backend issue; Otherwise please create an issue on the [backend repo](https://github.com/LemmyNet/lemmy) instead.

### Summary

When signed out of Lemmy you can click on a post or try to create a new post and see the message below.
![ima_39bf073](https://github.com/user-attachments/assets/34b50ce4-92c5-4d57-9113-215ec78156f6)

This was raised to the Lemmy support Element channel and it was found to be caused by:
CI pulls the latest version of translations during the build based on the branch pinned in .gitmodules
so when the new 0.19 release was built it pulled the latest translations instead of the 0.19 compatible translations

### Steps to Reproduce

1. While signed out of Lemmy, open a post.
2. Notice the message in the attached image to this bug report.

### Technical Details

Using Docker Compose image 0.19.7 on Ubuntu 22.04 docker host.

### Lemmy Instance Version

0.19.7

**Comment by dessalines** [comment]
I'll re-add those strings for now.
