### ISSUE TITLE
Hide names of mods/admins in mod log

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#285]
I think this would be a useful option to avoid harrassment of mods/admins by angry users. If it is enabled, the mod log would simply show "!community mods removed post x", or "lemmy.ml admins banned user y".

**Comment by dessalines** [comment]
I think its still a good idea for the API to be unchanged, but the UI should only show the name if you're a mod / admin.

**Comment by Nutomic** [comment]
If we're serious about this then we also need to remove the username from the api and federation. I probably should have opened this issue in the lemmy repo, not sure why I put it here. Though having it only in the frontend for now makes it easier to try if it actually works well.

**Comment by dessalines** [comment]
Yeah that's probably right... I hacked the permissions into the front end, but ideally a `GetModlog` request would have your auth, and only return the mod if you have those perms. I'll open an issue.
