### ISSUE TITLE
Add URL search type to search page

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#286]
This is already done in the API, it should be easy to add to the front end.

**Comment by KaKi87** [comment]
It's working for posts but not for comments though, which is an issue because without `type=Url`, then the resolved post/comment is drowned into a mess of other search results.

Thanks

**Comment by Nutomic** [comment]
@KaKi87 Please open a new issue including steps to reproduce, and a concrete example url where this happens.

**Comment by KaKi87** [comment]
[Done](https://github.com/LemmyNet/lemmy-ui/issues/3450).
