### ISSUE TITLE
No auth header for picture upload

### ISSUE THREAD

**Issue by hermantolim** [LemmyNet/lemmy-ui#297]
### Issue Summary

this maybe also related to the `rust` part, it crash when uploading image with error from rust backend `No auth header for picture upload, when uploading picture`

### Steps to Reproduce

1. `pictrs_url` in config.hjson = `"http://localhost:8080"`
2. login with admin user
3. create a post
4. upload image with the markdown editor

I tried adding  credential to the `MarkdownTextarea` from `src/shared/components/markdown-textarea.tsx` fetch:

```
fetch(pictrsUri, {
     method: "POST",
     body: formData,
     credential: "include"
})
...
```

this fixed the problem, upload also successful but browser drop response due to CORS

### Technical details
- pictrs server run using the docker image from `asonix/pictrs`

**Comment by dessalines** [comment]
This one confuses me, because we already have authenticated picture uploads, it uses your browser cookie `jwt` in the POST request.
