### ISSUE TITLE
Registration is not sanitized for extended ASCII passwords

### ISSUE THREAD

**Issue by Kreyren** [LemmyNet/lemmy-ui#298]
### Steps to Reproduce

0.Go to https://lemmy.ml/login
1. Attempt to create an account with password using extended ASCIi e.g.
```
ðÉ\ëgÅ;÷øÓQþÔh!{Ä;Wç[+;V}ûvõËñîn»Ô2#úÙë¦+gß"FÆCTXÃ§Qw¬`¦MýöZ
```
X. Expect an error message about password having to be <=60 chars which it in.

**Comment by Kreyren** [comment]
Also it seems that me trying to create such account breaks the registration as now it says that the user `kreyren` exists, but i am unable to log-in nor do a password reset.

**Comment by dessalines** [comment]
We already have character length checking: https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/login.tsx#L230

The back end also counts chars.

> Also it seems that me trying to create such account breaks the registration as now it says that the user kreyren exists, but i am unable to log-in nor do a password reset.

Did you provide a password reset email?

**Comment by Kreyren** [comment]
It rather seems that the characters are the issue not the lenght.

---

> Did you provide a password reset email?

Yes, should be set for kreyren@fsfe.org

**Comment by dessalines** [comment]
Then you should be able to do a password reset, maybe you set that password before I added the length check. I'll reopen if that fails.
