### ISSUE TITLE
Add inactive "Previous" button

### ISSUE THREAD

**Issue by LongJohn-Silver** [LemmyNet/lemmy-ui#304]
### Is your proposal related to a problem?

Currently on the feed, when you are on page 1, there is no "Previous" button, and the next button is on the left.

### Describe the solution you'd like

It would be nice if there could be a non clickable, inactive "Previous" button on the left, and active, clickable "Next" button on the right, so that when you go to the next page, the buttons did't change positions.

### Describe alternatives you've considered

N/A

### Additional context

Current style used by Lemmy:

![ima3ge](https://user-images.githubusercontent.com/63723030/120720346-6eb1b300-c4bb-11eb-84c2-262fbedae8e5.png)

How it should look:

![image](https://user-images.githubusercontent.com/63723030/120721243-f21fd400-c4bc-11eb-9072-2d1ba55c7fa6.png)

Current style used by BookWyrm, which used to be just as Lemmy is now:

![image](https://user-images.githubusercontent.com/63723030/120720381-7ffabf80-c4bb-11eb-8e9f-f7431757b8ef.png)

**Comment by LongJohn-Silver** [comment]
Will this be live in the next update, @dessalines?

**Comment by dessalines** [comment]
Yep it will.

**Comment by LongJohn-Silver** [comment]
Do you think the "Next" paginator could be placed at the extreme right, @dessalines? Kind of like what BookWyrm does, instead of having them toghether, or is it a design choice made on purpose? I know it's nitpicky but I feel it looks much better, but I understand if you don't.
