### ISSUE TITLE
introduce <head> tag?

### ISSUE THREAD

**Issue by hacklido** [LemmyNet/lemmy-ui#305]
I would like to use Lemmy but for google analytics and some other scripts, I will be in need of a <head> tag. I guess Lemmy doesn't have one. 

EDIT: Accessing this <head> from admin panel will be more helpful.

**Comment by hacklido** [comment]
I mainly want this for two reasons,
- To integrate google analytics script 
- To integrate arc.io

**Comment by dessalines** [comment]
What does this mean? Lemmy has a <head> tag in its html.

**Comment by hacklido** [comment]
> What does this mean? Lemmy has a `<head>` tag in its html.

Where can I add the google analytics code and arc code? They are enclosed with <script> tag so can you point where to insert them?

**Comment by dessalines** [comment]
I still don't know what you mean. Did you grep the codebase?

**Comment by dessalines** [comment]
I still don't know what you mean. Did you grep the codebase?

**Comment by hacklido** [comment]
> I still don't know what you mean. Did you grep the codebase?

no, I did not, let me try or can you point exactly where to look for it?
