### ISSUE TITLE
Ctrl+Enter to submit comment

### ISSUE THREAD

**Issue by kevincox** [LemmyNet/lemmy-ui#306]
For backend issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

Currently after you have typed a comment you need to use the mouse to submit.

### Describe the solution you'd like

When in text areas `Ctrl+Enter` should submit the form.

Something like this should work:

```javascript
document.body.addEventListener("keydown", e => {
	if (!e.originalTarget.tagName == "TEXTAREA") return;
	if (e.key != "Enter") return;
	if (!e.ctrlKey) return;

	e.preventDefault();
	e.originalTarget.form.requestSubmit();
})
```

### Describe alternatives you've considered

- Get browsers to make `Ctrl+Enter` submit the form. This would be nice but is unlikely to work as it would probably break a lot of sites that submit on enter and use `Ctrl+Enter` to add a new line.
- Do nothing. But then I need to use the mouse.

### Additional context

macOS users may expect a difference combo? IDK I'm not really a macOS user.

**Comment by dessalines** [comment]
Tab+Enter
