### ISSUE TITLE
Markdown monospace/code format does not work properly with linebreaks

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#308]
### Issue Summary
Linebreaks are not kept when selecting multiple lines and clicking monospace formatting button. Doesn't mind if the linebreaks have two spaces or not.

### Steps to Reproduce

1. Write some lines, for example:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```
2. Select them all and click the monospace formatting button.
3. A unique " ` " will be prepended/appended to the selection and it will be shown as a unique line

### Proposal
Monospace formatting button should detect whether selection has multiple lines and if yes, prepend and append **three** grave accents, a line before and after:

> \```
> sudo apt-get update
> sudo apt-get upgrade
> sudo apt-get dist-upgrade
> \```

 This way the linebreaks are ketp. Nevertheless, currently, using three grave accents the text is not highlighted in purple, so that should be added too.

### Technical details
https://lemmy.eus, lemmy `v0.11.0`

**Comment by hammsvietro** [comment]
Hey, first time here, is this open for PRs? I'm interested in contributing

**Comment by Nutomic** [comment]
@hammsvietro Yes, go ahead. And welcome :)

**Comment by hammsvietro** [comment]
thanks :D
About the purple highlight, the markdown highlight is usually different for three grave accents than it is for only one, should this also be changed?

**Comment by Porrumentzio** [comment]
I would expect purple higlighting, even purple,

**Comment by hammsvietro** [comment]
Ok, I'll work on it as soon as I can :)

**Comment by hammsvietro** [comment]
@Porrumentzio  @Nutomic I was looking at the code, and it looks like all the markdown styling is inherited from the selected theme. Should we proceed and override those?

**Comment by Porrumentzio** [comment]
I think that each theme should be modified so it works as intended, better than overriting (as that is destructive/blocking)

**Comment by Porrumentzio** [comment]
Each theme should be modified for appropriate formatting (purpling monospace)

**Comment by hammsvietro** [comment]
ok, I'll try that

**Comment by hammsvietro** [comment]
@Porrumentzio Just updated all the themes to use it's default purple as the multi-line code color
