### ISSUE TITLE
Option to filter community list by instance

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#309]
Look at this, you have to scroll more than a full page to find the first community which is not from lemmy.ml. Maybe we should even hide remote communities by default? Especially users who are not logged in probably care most about local content.

https://lemmy.161.social/communities

**Comment by dessalines** [comment]
Good point... I should add a `Local / All` switch, and let it use your default local / all / subscribed settings ( which defaults to local for non-logged-in users. )

**Comment by dessalines** [comment]
Dupe of #190
