### ISSUE TITLE
Incorrect thumbnail size in Firefox

### ISSUE THREAD

**Issue by Mehran-Baghi** [LemmyNet/lemmy-ui#316]
### Issue Summary

![firefox](https://user-images.githubusercontent.com/17176259/124910360-bec2ee80-e000-11eb-9a41-5015ca84b1b5.png)

### Steps to Reproduce

Firefox 89.0.2
Arch Linux

**Comment by dessalines** [comment]
That's correct, we don't create empty space for vertical type thumbnails.
