### ISSUE TITLE
Tutorial to explain what some useful buttons do and how they can be used.

### ISSUE THREAD

**Issue by concur1** [LemmyNet/lemmy-ui#341]
For backend issues, use [lemmy-ui](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

When new people land on the front page of an instance, it might not be clear how to navigate/explore/use lemmy.

### Describe the solution you'd like

I have seen some websites have a tutorial where the page will go dark/blury except from a single button/element that is highlighed and there will be some text describing what that button/element does.

I think it could be useful for new users to have an optional tutorial like this that explains key funcitonality like:

1. Federation is not a common feature so I think ‘subscribed’, ‘local’ and ‘all’ could be explained.

2. One of the first things a lot of social media apps do is get you to subscribe to content/communities you are interested in. So maybe you could highlight the ‘Communities’ button and say that you can find communities you are interested in.

3. You could also highlight that clicking the username in the top right takes you to post/comment history and settings.

(Describe your proposed solution here.)

### Describe alternatives you've considered

A video tutorial might alos be useful. Maybe this should be done as well as a more 'full' tutorial.

**Comment by dessalines** [comment]
Outside of a "helper" type thing, there's a few things I can add to address these.
