### ISSUE TITLE
Handle YouTube links

### ISSUE THREAD

**Issue by testman42** [LemmyNet/lemmy-ui#353]
### Is your proposal related to a problem?

YouTube links always show "Before you continue to YouTube" as the title and thumbnail does not work

### Describe the solution you'd like

Either implement whatever YouTube API requires for this to work
or, if user is entering a YT link, offer to covert / handle the link with [Invidious](https://github.com/iv-org/invidious) or any other freedom-respecting alternative

**Comment by dessalines** [comment]
This would be a great first issue.

In the post link box, have a front end utility that can read some top level domain names, and give the option to use the private proxies, similar to the `archive url` button. 

This is simple enough that it could be done for youtube, twitter, and reddit.

**Comment by mahanstreamer** [comment]
I'm going to do this

**Comment by testman42** [comment]
If I am not mistaken, it has already been solved.
Posts that point to Youtube videos now get thumbnails and titles correctly assigned.

Latest example of such post: https://lemmy.ml/post/79783

**Comment by dessalines** [comment]
Ah yes, seems that youtube both removed that, and our switch away from iframely fixed it.
