### ISSUE TITLE
A warning message for account/content deletion

### ISSUE THREAD

**Issue by soronixa** [LemmyNet/lemmy-ui#357]
### Is your proposal related to a problem?

I'm concerned that some users of Lemmy might not be aware of how content deletion works right now. Since Lemmy attracts many privacy-aware users, I ask for some form of warning or pop-up to let users know the limitations of content/account deletion. the discussion happened in these threads:

https://lemmy.ml/post/76037

https://lemmy.ml/post/73476/comment/66103

https://lemmy.ml/post/73476/comment/66028

### Describe the solution you'd like

I suggest a warning message that explains to the user how deletion currently functions, it could be something similar to "Currently your content and profile will remain visible when viewed from other instances, because federated user deletion has not been implemented yet. You could wait for its implementation or proceed." when a user attempts to delete their account, or  "Comment deleted successfully. Please note that this action is reversible, and you can restore your comment in future. Your username will remain visible." with a "don't show this message again" option when a user deletes a comment.

### Describe alternatives you've considered

The only other solution I can think of is reworking the deletion system. But of course that will take time so I think a warning message is a good temporary solution.

**Comment by Nutomic** [comment]
The current message is here, if you want to rewrite it. That would be the easiest solution for now.

https://github.com/LemmyNet/lemmy-translations/blob/main/translations/en.json#L102

**Comment by ovrs** [comment]
@soronixa went ahead and made the PR myself, since it looked like you were new to github on lemmy. sorry if i overstepped or anything but i definitely think this prompt should be updated.
https://github.com/LemmyNet/lemmy-translations/pull/13

**Comment by soronixa** [comment]
@Nutomic sorry, I don't really know anything about github, would definitely help if I could :(

@ovrs thank you! yeah, I don't know how to make pull requests. I think it looks good!

**Comment by dessalines** [comment]
This was merged: https://github.com/LemmyNet/lemmy-translations/commit/02b95a701fc3ecdce0435a24eeb34ed12a67f0d8

Thank you @ovrs
