### ISSUE TITLE
Add link icon to posts

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#359]
Lets say I come across [this post](https://lemmy.ml/post/76642), and want to fetch it from my instance. For that I need its apub id (something like `https://sopuli.xyz/post/123`). At the moment I have to go to the user or community profile on the remote instance, and hope to find the post there (difficult if its an old post).

Similarly, the link icon for comments should probably refer to the comment on the original instance. Ideally it would just be the apub id, but for that we first need to implement a comment view under `/comment/123` (see https://github.com/LemmyNet/lemmy/issues/698).

**Comment by dessalines** [comment]
This makes sense, at least for posts on federated communities.

**Comment by Nutomic** [comment]
This is implemented now.
