### ISSUE TITLE
Rich text/WYSIWYG editor

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy-ui#363]
A WYSIWYG editor for posts and comments

**Comment by dessalines** [comment]
We prefer the simple, lightweight textarea with a markdown preview button. Every wysiwyg component I've come across has been very heavy.

**Comment by Nutomic** [comment]
It might be interesting to have a preview field which is live updating. Should be pretty easy to implement, and would give us some benefits of a WYSIWYG editor.

**Comment by dessalines** [comment]
They're not too performant without a debounce (otherwise it has to re-convert everything with every keystroke). The smart ones know how to do a diff-like convert.

**Comment by trymeouteh** [comment]
Reddit has a hood WYSIWYG editor, most likely not open source.
