### ISSUE TITLE
Images, video, audio play in browser

### ISSUE THREAD

**Issue by trymeouteh** [LemmyNet/lemmy-ui#365]
Please allow for images, video and audio to be shown in app without having to select the file to view it.

Please support the following file types
jpg
png
gif
mp4
mp3
m4a
flac

**Comment by Nutomic** [comment]
These should work just fine if your browser supports them. So please fill in the issue template with a steps to reproduce, your browser version etc.

**Comment by dessalines** [comment]
Fixed by #421
