### ISSUE TITLE
Use local urls for community and user urls. 

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#369]
From a pm:

when i am on lemmy.ml and enter !communism@lemmygrad.ml it generates `[!communism@lemmygrad.ml](https://lemmygrad.ml/c/communism)`

but i want the link to open on lemmy.ml so that someone on lemmy.ml who clicks it stays logged in and can subscribe, vote etc

really the link target for `!communism@lemmygrad.ml` has to be the local instance of the viewer, not the instance of the comment author

**Comment by Nutomic** [comment]
Someone on Lemmy suggested a good hack for this: make the mention as `[!communism@lemmygrad.ml](/c/communism)` so it uses a relative url. I think it should be pretty easy to change what the editor generates in that case. Might need some backend changes too, but im not entirely sure how mentions are implemented.

**Comment by db0** [comment]
Note that the relative workaround won't work when someone is visiting from kbin, as that expects "magazines" to be using the `/m/` separator

**Comment by krestenlaust** [comment]
When discussing Kbin, it could also be worth discussing what degree of interoperability with the rest of the fediverse this should have. As it stands now, lemmy doesn't interface very well with other fedisoftware, but what about mastodon user URLs? Should other services be opened separately, while Lemmy is instance-agnostic?

**Comment by Zetaphor** [comment]
@dessalines This can be closed as resolved now that #1462 is merged
