### ISSUE TITLE
Add screenshots in README

### ISSUE THREAD

**Issue by TheEvilSkeleton** [LemmyNet/lemmy-ui#375]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

Not providing screenshots generally makes me want to not install the app in the first place, and I'm sure many others feel the same.

### Describe the solution you'd like

Add screenshot in README.

**Comment by dessalines** [comment]
The screenshots and all the readme for this, is in the Lemmy one: https://github.com/LemmyNet/lemmy
