### ISSUE TITLE
Editing Post UI Change Request

### ISSUE THREAD

**Issue by dginovker** [LemmyNet/lemmy-ui#380]
I want to preface this issue by saying I've used Lemmy for some time now, and been accustomed to most of the UI quirks. This is a UI/UX issue that still persists with me, and if you want to close it as WONTFIX that's cool, just keep it in mind in case someone else brings it up down the line

### Is your proposal related to a problem?

![image](https://user-images.githubusercontent.com/32943174/130373125-16954fcf-bcf2-4775-8404-90e122aaaa60.png)

The "Preview" button is placed where it would make sense to click it to "Save" your changes.

Furthermore, when you click it, the new interface you get looks so much like you hit save that you might be inclined to leave/forget about the tab.

### Describe the solution you'd like

Move the "Preview" button down to the Save/Cancel location - Alternatively, move the Save/Cancel location up.

### Describe alternatives you've considered

* Massive warning that says "This is a preview"
* Preview showing `git diff` style text to emphasize it's a preview

### Additional context

Thx4 reading

**Comment by dessalines** [comment]
The preview is only for that body, as its the only markdown field. Its attached to the markdown component and wouldn't make sense to move it.
