### ISSUE TITLE
Add a sticky button to the mobile view like in soapbox

### ISSUE THREAD

**Issue by loid345** [LemmyNet/lemmy-ui#383]
For the convenience of using lemmy on a mobile device, I suggest adding a sticky button to the mobile view like soapbox (https://gitlab.com/soapbox-pub/soapbox-fe). When you click on the button, 2 buttons will appear, create a community or create a post.
![2a](https://user-images.githubusercontent.com/20200970/131405562-b44ba638-a20e-4ba2-9451-bc5470d12e16.jpg)
An example of a button can be found at https://gleasonator.com/

**Comment by Nutomic** [comment]
In terms of clicks this wouldnt change anything, right now its menu -> create post. So 2 clicks, same as your suggestion. And I dont think that create post/community are used on Lemmy as much as on a twitter-like platform. Plus it would probably encourage spam.

**Comment by loid345** [comment]
> In terms of clicks this wouldnt change anything, right now its menu -> create post. So 2 clicks, same as your suggestion. And I dont think that create post/community are used on Lemmy as much as on a twitter-like platform. Plus it would probably encourage spam.

It depends on which side to look at.  Stimulating user activity so that they write more articles and create more communities is great. And to fight spam by hiding the main buttons somewhere far away is not the best tactic. It is better to use other methods.

**Comment by Nutomic** [comment]
> It depends on which side to look at. Stimulating user activity so that they write more articles and create more communities is great. Any social network owner dreams about it)

That may be true for commercial networks which try to increase engagement, but not for a project like Lemmy. I think we want to have quality over quantity, and making post creation easier will probably lead to more low quality posts. We also dont want to make lemmy-ui too complex by adding lots of options. If someone cares about such features, they can fork the project.

**Comment by loid345** [comment]
> > It depends on which side to look at. Stimulating user activity so that they write more articles and create more communities is great. Any social network owner dreams about it)
> 
> That may be true for commercial networks which try to increase engagement, but not for a project like Lemmy. I think we want to have quality over quantity, and making post creation easier will probably lead to more low quality posts. We also dont want to make lemmy-ui too complex by adding lots of options. If someone cares about such features, they can fork the project.

I understood. Are you planning to support extensions?

**Comment by dessalines** [comment]
What do you mean? lemmy-ui can be forked if anyone wants to add something else.

**Comment by dessalines** [comment]
This type of thing would best be left to an actual mobile app.
