### ISSUE TITLE
A post action button to hide posts

### ISSUE THREAD

**Issue by Nirose** [LemmyNet/lemmy-ui#384]
Lemmy does have "Show/Hide read posts" but there are posts that you don't want to engage with at all. So, could it be possible to add a button to hide them from the UI so they don't appear on return visit? 

This will help user keep their front-page clean and might allow users to view more posts that interest them. As the clutter is be hidden.

May be a "Ignore" or "Hide" icon as a post action.

**Comment by dessalines** [comment]
We don't have the concept of post hiding... but would a button that has `Mark as read` work?

**Comment by Nirose** [comment]
I think that would work, is there a section I can go to view the already read posts? I couldn't find it.

**Comment by dessalines** [comment]
Hrm, no we don't have a read / unread filter for posts.

**Comment by dessalines** [comment]
We'd need to add a `MarkPostAsRead`, similar to `MarkCommentAsRead` in the API.

**Comment by krestenlaust** [comment]
Isn't 'mark post as read' a (wildly) different feature than 'hide post'?

To me, 'Mark post as read' implies that every post you click into, is going to disappear once you click out of it again.
While a 'hide post'-feature sounds more like simply useful for hiding pinned posts

**Comment by joelthelion** [comment]
To elaborate on what @krestenlaust said, I personally don't like hiding read posts. I enjoy going back to posts I have already read.
I do, however, like to occasionally hide posts I have no interest in. This is why I'd like a "hide" feature. Definitely not the same as "marking as read" from my perspective.

**Comment by ericjmorey** [comment]
I would prefer to have the hide feature have a time element to it. You choose the length of time you want to hide the post from a menu. 

15 minutes
1 hour
6 hours
1 day
3 days
1 week
1 month
Infinite 

Maybe even have a custom option.

A similar concept could be applied to blocking accounts communities and instances.

**Comment by krestenlaust** [comment]
What would the use of hiding a post with a timer be. This site is designed around the concept of posts decaying naturally. A post that is hidden in more than a day or so, would be gone anyway.

**Comment by ericjmorey** [comment]
> A post that is hidden in more than a day or so, would be gone anyway.

If you're only using the front page with default settings, perhaps. But there are smaller instances and communities where this would come in handy, especially in posts that stay active in the comments for months.

**Comment by TailyFair** [comment]
From what I've seen on various posts and comments, this is a real pain point for a lot of users.

**Comment by ColorfanXP** [comment]
Personally, I like the action of voting on a post causes it to become hidden.

It should be optional though, not something that happens by default.

**Comment by ericjmorey** [comment]
> > especially in posts that stay active in the comments for months.
> 
> What do you mean here, I don't think I understand. To expand on my other post, I consider it feature bloat to have a timer system as well, the way it is now.

People use Lemmy in different ways. The hot and active algorithms are not settled. The Top-Year, Top-all time, New, Old,  New Comments sorting can all result in posts which are over a month old. Especially on lower volume niche communities. I don't know how you'd consider it bloat to let users use customize their experience with little to no UI costs.

**Comment by madeofstown** [comment]
Such a basic feature that would really help clean up my feed. As it is now, there are posts that stick on my feed for a week or more that I do not intend on ever viewing. That, combined with Lemmy's issue in taking you back to the correct spot when you click back from the article makes browsing a chore. Simply adding the ability to hide a post would make browsing lemmy much better. Automatic hiding of read posts is something different and does not fix the problem.

**Comment by acosmichippo** [comment]
bumping this again because I am really missing this feature from reddit. Actually even moreso on Lemmy because there is so much traffic and posts linger much longer than on reddit.

**Comment by dessalines** [comment]
This got added in c1722a0b6b89fed530590ecb5cb1cfe72fa6347c
