### ISSUE TITLE
Add community and user blocking from those profile pages.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#396]
IE, have a block user button on their profile page, a block community button on the community pages.

**Comment by mahanstreamer** [comment]
Will do this if no one else will now that the youtube issue has been fixed already

**Comment by dessalines** [comment]
Sure! Let me know if you need any assistance.

**Comment by dessalines** [comment]
BTW our dev chat is: https://matrix.to/#/#lemmydev:matrix.org

**Comment by Nutomic** [comment]
This is half implemented, there is a block button on user profiles. But community profiles dont have any block button yet, so that should be added.

**Comment by Nutomic** [comment]
Implemented now.
