### ISSUE TITLE
Will submit pull request - robots.txt

### ISSUE THREAD

**Issue by mahanstreamer** [LemmyNet/lemmy-ui#400]
There is no robots.txt for the frontend. A robots.txt should be added with exclusions to the account login pages, etc..

https://lemmy.ml/robots.txt

**Comment by mahanstreamer** [comment]
Did in #401

**Comment by dessalines** [comment]
Next time, in the commit message, you can just put `Fixes #...`, and it will close this automatically. That's much preferred, so we can see what commits fix what issues.
