### ISSUE TITLE
Arabic language is not implemneted, the users cannot change thier intraface to arabic

### ISSUE THREAD

**Issue by jayabie** [LemmyNet/lemmy-ui#406]
Trying to change my interface in lemmy to Arabic, but the language is not in the list.
more details in the below post:
https://lemmy.ml/post/79573/comment/76190

see the picture as a reference
![yBOISU1z3i](https://user-images.githubusercontent.com/44237013/132245991-a98501df-86bd-4194-971f-b0f6bce7ddb7.png)
.

**Comment by dessalines** [comment]
I just fixed this, its in the `0.12.2` release. Dupe of #404
