### ISSUE TITLE
Dark theme toggle for logged-out users

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy-ui#410]
### problem

Being blinded while viewing remote instances.

### solution

Have a toggle switch where the bell would be for logged out view. 

###  alternatives 

possibly have a config option for alternate theme, otherwise hard-code darkly

**Comment by dessalines** [comment]
It uses your browser preference to use a dark or light theme. I'd much rather rely on that, especially as it becomes more supported by most browsers.

**Comment by Thann** [comment]
Ok, so, I appreciate your perspective, but sometimes users can't control the OS settings of the computer they're using, like when at the library.  Also, sometimes users might want to override the OS setting ¯\\\_(ツ)_/¯

**Comment by dessalines** [comment]
Not an os setting, its a browser setting. Also it takes less than 30 seconds to make an acct, and have that theme go with you to any other browser you use.
