### ISSUE TITLE
Add `version` to package.json

### ISSUE THREAD

**Issue by happysalada** [LemmyNet/lemmy-ui#411]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

yarn has some surprising behavior when the version attribute is missing from a package.json.
Would it be problematic to add a version attribute to the package.json ?

### Describe the solution you'd like

add the version attribute to the package.json

### Describe alternatives you've considered

I'm trying to track down where the problem comes from and if there are ways around it.
Currently, for packaging into nixos, we are patching the package.json file.

### Additional context

Here is the [link to the PR](https://github.com/NixOS/nixpkgs/pull/137186#discussion_r707798127) packaging lemmy for nixos

**Comment by dessalines** [comment]
Sure, that'd be doable.

**Comment by happysalada** [comment]
Thanks a lot for the quick fix!
