### ISSUE TITLE
Next button in profile view does not work

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy-ui#416]
### Issue Summary

Browsing the profile of someone only works for one page. When trying to open the next page, the button does nothing.

### Steps to Reproduce

1. Open a profile, nevermind if it's yours or other ones
2. Scroll to the bottom
3. Click onto Next

### Technical details

Console error:
```
Uncaught TypeError: this.updateUrl is not a function
    at Object.o.handlePageChange [as onPageChange] (client.js:2)
    at n.o.handlePageChange (client.js:2)
    at Object.o.handleNext [as event] (client.js:2)
    at ee (client.js:2)
    at HTMLDocument.<anonymous> (client.js:2)
o.handlePageChange @ client.js:2
o.handlePageChange @ client.js:2
o.handleNext @ client.js:2
ee @ client.js:2
(anonymous) @ client.js:2
```

Tested Browsers (All on Linux):
* Chromium 90.0.4430.212 (Developer Build, ungoogled-chromium) without any AddOns
* Chrome 93.0.4577.82 (Official Build) without any AddOns
* Firefox 92.0 (64-bit)

**Comment by dessalines** [comment]
@lunatichacker pointed out the fix for this too. I've added it now.
