### ISSUE TITLE
"Next" button on user pages doesn't work

### ISSUE THREAD

**Issue by ghost** [LemmyNet/lemmy-ui#432]
### Issue Summary

When at the end of a user page, clicking "Next" does nothing. When I change the URL to show the next page, it displays the page, but clicking on "Previous" or "Next" doesn't work there either.

### Steps to Reproduce

1. Go to any user's page.
2. Scroll down and click on the "Next" button. Nothing happens.

### Technical details

The browser console gives this error message:
```
Uncaught TypeError: this.updateUrl is not a function
    handlePageChange https://lemmygrad.ml/static/js/client.js:2
    handlePageChange https://lemmygrad.ml/static/js/client.js:2
    handleNext https://lemmygrad.ml/static/js/client.js:2
    ee https://lemmygrad.ml/static/js/client.js:2
    t https://lemmygrad.ml/static/js/client.js:2
```

**Comment by dessalines** [comment]
Dupe of #416
