### ISSUE TITLE
Add honeypots to forms to deter spam

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#433]
https://github.com/LemmyNet/lemmy/issues/1688

https://stackoverflow.com/questions/36227376/better-honeypot-implementation-form-anti-spam

Since this requires a server-side check, it might be only feasible to do this with the user signup, and post creation. 

It'd also be possible to ban the user if they edited the form.

**Comment by Nutomic** [comment]
This wont do anything against bots that are written specifically for Lemmy. But its probably easy enough to implement that it wont hurt to have.
