### ISSUE TITLE
Subscribe to remote community button

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#436]
I guess I never made an issue / feature request for this?

On Mastodon there is a button on each profile that you can click even on a instance you have no account on that will ask for your full account address (@user@instance.com) and then opens a pop-up window that redirects to your home instance and allows you to add the remote profile. This works even with other ActivityPub enabled software like Hubzilla.

IMHO this would really help with subscribing to remote communities as the current method of pasting the remote community URL into the search-bar is not intuitive at all and also not explained anywhere in the GUI AFAIK.

**Comment by Nutomic** [comment]
Do you know any details how other software implements this? Maybe a link to a PR?

**Comment by poVoq** [comment]
Sorry no. Has been in Mastodon as long as I can remember.

My guess would be that it is just using an url parameter, i.e. you click on the button, it forces open a new browser window (a bit inconvenient as Firefox suppresses that by default), you enter your instance and username and click ok, then you get redirected to your home instance where you can log in if necessary and are then presented with a confirm follow this user button.

**Comment by dessalines** [comment]
This wouldn't be too difficult to do in lemmy ui. On a subscribe button, if you're not logged in, I could goto a dialog that gives you the option either to create an account there, or type in your instance name. If the latter, redirect to that instance with another page that fetches the remote object and lets you subscribe.

**Comment by Nutomic** [comment]
Right, it would just have to redirect to `your-instance.com/c/community@xyz.com`. Right now that only works if the communtiy is already known on your-instance.com and would show an error otherwise. But I'm making a change where opening that URL will trigger a fetch of the remote community.

**Comment by Thann** [comment]
Should also include "remote post" and "remote comment" features as well.

I'm going to take a stab at this.

**Comment by alectrocute** [comment]
I think we have this feature now. It doesn't work great, but it *works* AFAIK. There's other issue tickets which describe the current issues with its functionality in more detail.
