### ISSUE TITLE
Cannot collapse 

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#439]
### Issue Summary

It is impossible to re-hide the post/comment options after you click on the three dot button.

This is a very small thing, but I think it contributes to the overall polish of Lemmy's UI.

### Steps to Reproduce

1. Open a post or comment ([example](https://lemmy.pt/post/1356/)).
2. Click the three dot button: ![imagem](https://user-images.githubusercontent.com/35771816/135714765-80619a2f-5ced-4997-b8fe-78c50084f81e.png)

### Technical details
N/A

### GIF

![Peek 2021-10-02 12-43](https://user-images.githubusercontent.com/35771816/135714601-7ae12174-7a8d-423e-a978-1c9df1896111.gif)

**Comment by dessalines** [comment]
I'm coming around to possibly moving these extra actions to modals like so:

![image](https://user-images.githubusercontent.com/930215/135760803-be21e5ca-e409-4bcf-911c-2aff74c25a37.png)


I have been generally anti-modal because its hard to do them right for all screen sizes, but I'm starting to think its the way to go now.

#448

**Comment by Tmpod** [comment]
Mmm, yeah, I'm not sure about that. On one hand, I like the way they are at the moment, and, as you said, they are arguably easier to work with. On the other hand, as the platform evolves and grows, more actions will be added, and the current model will become rather unpractical (in small screens, at least), so implementing modals now wouldn't be that bad. Maybe use modals on mobile and leave them as they are on desktop (have some viewport threshold that triggers the switch between the two styles), but I'm unsure if that's a good way to design this UI.

**Comment by dessalines** [comment]
#449 will make this a nofix.
