### ISSUE TITLE
Page loading error

### ISSUE THREAD

**Issue by ktleary** [LemmyNet/lemmy-ui#44]
When trying to use Lemmy, I have experienced loading errors for most events including page loads, comment replies, profile view, etc. The loading wheel starts spinning and never comes back and the page does not load. This happens consistently on mobile and inconsistently on desktop.

One workaround has been to reload the page, which seems to reset the connection, but this is not an option on comment replies, logins, posts.

Mobile is iOS with same issues in Safari, DDG browser, Firefox.
Desktop is Firefox.
Desktop connection is possibly not super low-latency.

PING dev.lemmy.ml (5.196.14.162) 56(84) bytes of data.
0/ 19 ( 0%) lost;  369/ 371/ 379ms; last:  369ms
0/ 19 ( 0%) lost;  369/ 371/ 379/   3ms (last 19)

I have attached 
[lemmy-firefox-console.log](https://github.com/LemmyNet/lemmy-ui/files/5289619/lemmy-firefox-console.log)
output from Firefox console if you would like it. If nobody else is experiencing this, than it might very well be my setup and I have no desire for unnecessary time to be spent on it.

**Comment by dessalines** [comment]
This is difficult to debug both because I don't have an iOS device, and because it *seems* like its a connection issue. After the page load, it needs to connect to websocket, which usually takes a half a second or so, but it seems like your device has trouble staying connected, which would cause the spinners to go forever.

**Comment by ktleary** [comment]
Yes, it would seem so, though it just started happening recently. I've more or less figured out how to work around it on mobile by refreshing the page when it hangs. Firefox desktop will not login at all for the past couple weeks. Since nobody else is having the issue and there's a workaround feel free to close and I'll be happy to debug if this becomes an issue down the road for others.

**Comment by dessalines** [comment]
You can leave it open bc it is an issue... the websocket is an auto-reconnecting one, so I'm not sure what else I can do to make sure it connects properly.

**Comment by ktleary** [comment]
this is no longer an issue, all websocket errors have ceased. you can close afaic.

**Comment by dessalines** [comment]
Thx, I just did a release that tweaked the timeout values, so hopefully that was it.
