### ISSUE TITLE
Mod actions are shown as text, wihch is inconsistent with other post actions

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#440]
### Is your proposal related to a problem?

Currently, the moderation actions (remove, ban, etc) are shown as text, while other post actions (save, cross-post, lock, etc) are shown as icons. Consistency is very important and this breaks it, even though it only affects a small share of the userbase (the admins and mods)

### Describe the solution you'd like

These actions should use icons with the current strings as their tool-tips.

### Describe alternatives you've considered

Haven't really considered anything else for now.

### Additional context

![imagem](https://user-images.githubusercontent.com/35771816/135714980-ac5dd98c-8325-41a4-8a56-1f51080c5be6.png)

**Comment by dessalines** [comment]
#449 will make this a nofix too.
