### ISSUE TITLE
Community sidebar button between post content and comment sort options, on mobile

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#444]
### Issue Summary

On mobile, when viewing a post, the community sidebar button is displayed between the post's content and the comment sorting options.

### Steps to Reproduce

1. Open a post ([example](https://lemmy.pt/post/1356/)) on mobile, or on desktop with mobile view-port enabled (through dev settings)

### Technical details
N/A

### Screenshots

![Screenshot_20211002_131503](https://user-images.githubusercontent.com/35771816/135715725-e338711e-4e6b-465a-aab7-94eb026768bb.png)  
(cursor is hovering the button)

**Comment by LunaticHacker** [comment]
i think this is intended

**Comment by Tmpod** [comment]
It looks very out of place imo, so I thought it was a mistake.

**Comment by dessalines** [comment]
Yeah I think I'd want the sidebar to still be below the post and post description. Anywhere else would take away focus from the post.

![image](https://user-images.githubusercontent.com/930215/135794597-5f55b4b2-7af2-4ba1-8345-d0a48fd426f5.png)

**Comment by Tmpod** [comment]
mmm, I suppose that is better, but I still think it doesn't feel all that right. I don't know how to better position it, though.
