### ISSUE TITLE
Global menu icons are displayed vertically and misaligned on mobile

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#445]
### Issue Summary

On mobile, the global menu icons (donate, search, site settings, notifications, reports, etc) are all shown vertically, instead of horizontally. They are also misaligned (specially search).  
Additionally, the notifications and reports icons are shown twice - one time at the very top of the page and another in the collapsible global menu.

### Steps to Reproduce

1. Open Lemmy on mobile.

### Technical details

Using Firefox 91.0.2.

### Screenshots

![imagem](https://user-images.githubusercontent.com/35771816/135715932-17487ec1-47e3-40ed-9e99-fd59e11a7ffe.png)

**Comment by alectrocute** [comment]
Resolved in 0.18.
