### ISSUE TITLE
Notification counter doesn't count over 20?

### ISSUE THREAD

**Issue by vachan-maker** [LemmyNet/lemmy-ui#452]
I am sure I have more than 20 notifications in my inbox but the counter is not showing the actual number of notifications in my inbox.

I have approximately 30 items in my inbox but 20 is displayed

**Comment by Tmpod** [comment]
[This](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/app/navbar.tsx#L716-L722) is the code that calculates that number

```tsx
calculateUnreadInboxCount(): number {
  return (
    this.state.replies.filter(r => !r.comment.read).length +
    this.state.mentions.filter(r => !r.comment.read).length +
    this.state.messages.filter(r => !r.private_message.read).length
  );
}
```

I don't see anything immediately problematic here. My best guess is that some type of stuff that is shown in the inbox isn't being taken into account here.

**Comment by dessalines** [comment]
This is related to https://github.com/LemmyNet/lemmy/issues/1794 . We need to add `GetUnreadCount` to the API.

**Comment by Tmpod** [comment]
Gotcha. Providing a proper API for this is indeed a much better approach. I suppose you can close this in favour of that other issue.
