### ISSUE TITLE
Ctrl+Enter sends comment/post/generic text field

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#453]
### Is your proposal related to a problem?

I'm used to Ctrl+Enter sending messages in other platforms, so I'd like to see it implemented in Lemmy too. 
It is a rather practical shortcut that avoids having to grab the mouse and click the button :P 

### Describe the solution you'd like

When focused on a text field, hitting Ctrl and Enter triggers the input field to be posted (creating a new post/comment, submitting a mod reason, etc).

### Describe alternatives you've considered

Some other shortcut, but I believe Ctrl+Enter is the most common one. Shift+Enter is usually used for explicit newlines, when Enter does perform the post action.

### Additional context

None.

**Comment by dessalines** [comment]
Tab+enter. Works on all browsers and you don't have to hijack key events.
