### ISSUE TITLE
"Create post" button in community sidebar doesnt preselect community

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#46]
1. go to any community
2. click "create post"
3. look at community dropdown, expecting the current community to be preselected
4. instead, the dropdown is set to "select a community"

**Comment by dessalines** [comment]
Hrm.. I thought I fixed this in #39, could you clear your page cache and try again?

**Comment by Nutomic** [comment]
Okay I suppose that fixed it, its working fine on the prod instances now. I had the problem on local test instances, but turns out that they are still using old versions of lemmy-ui.
