### ISSUE TITLE
Solar theme is borked!

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy-ui#468]
### Issue Summary

The solar theme doenst have styles for the "user popover" in the top-right
![Screenshot from 2021-10-28 11-19-46](https://user-images.githubusercontent.com/578515/139313212-cc2585e9-1025-40fe-bab5-36b6e5f18bbb.png)

### Steps to Reproduce

1. sign in
2. set theme to solar
3. click your username in the top-right
4. ???
5. profit

### Technical details

Chrome and FF on Linux and Android.

**Comment by Kap2022** [comment]
I just bumped into this problem with the Solar Theme as well.

It also means you cannot see the list of communities to choose from when you are creating a post.

**Comment by MrCzwartek** [comment]
Commenting "**/* --light: #FDF6E3;**" may fix it temporarly, as similar issue occurred with vaporwave-dark.css.

![image](https://user-images.githubusercontent.com/46397678/168309564-a88dbea6-ee3b-4690-8fca-2f54b8a5b4a0.png)

-->

![image](https://user-images.githubusercontent.com/46397678/168309454-fb899035-b78e-41b2-9b37-1e69c1afddc3.png)

**Comment by Nutomic** [comment]
These mentioned themes are not included anymore.
