### ISSUE TITLE
Better markdown editing experience

### ISSUE THREAD

**Issue by Aloso** [LemmyNet/lemmy-ui#497]
### Is your proposal related to a problem?

The markdown editor isn't very user friendly: When pressing a button to make some text bold or otherwise highlighted, the editor loses focus, so you have to click in it again.

### Describe the solution you'd like

When text is select and I click on a formatting button, e.g. _Bold_, the text should be surrounded with `**`, but still selected. Furthermore, there should be keyboard shortcuts (<kbd>Ctrl+B</kbd>, <kbd>Ctrl+I</kbd>, etc.).

### Describe alternatives you've considered

None.

### Additional context

The [stackoverflow markdown editor](https://stackoverflow.com/questions/ask) is very good in my opinion.

**Comment by dessalines** [comment]
I'm fairly against keyboard shortcuts / jacking, because I and I'm sure others use browser plugins like tridactyl that turn the browser into vim mode. 

I suppose the text could stay selected tho, I'll see if that can be done.

**Comment by Atemu** [comment]
So, yeah. This broke my workflow.

I use macOS which, by default, has Emacs-like shortcuts for text fields such as C-p to go to the previous line, C-e to jump to the end of the visual line or C-b to go one char backwards.

These "helpful" markdown shortcuts break these shortcuts that I use everywhere else. I don't need them either; I can write Markdown by hand.

Could these at least be made optional?

Other platforms have implemented such "helpful" shortcuts too; it's a pet peeve of mine. GitHub for example did it and, after a bit of turmoil, have painstakingly adapted their shortcuts to not conflict with the different platforms' defaults.  
I question the need for such shortcuts in the first place though. An unfamiliar user will be drawn to the UI buttons for formatting (these are great IMO). An advanced user will know the markdown syntax (it's not *that* hard) and just write it by hand.

Who are the shortcuts for?

Are they really worth the complexity of adapting shortcuts for each platform's conflicting defaults or possibly breaking users' custom shortcuts?

**Comment by Aloso** [comment]
> Could these at least be made optional?

I think that's a good idea.

> Who are the shortcuts for?

Anyone familiar with Microsoft Word, LibreOffice, or most WYSIWYG text editors on the web, maybe?
