### ISSUE TITLE
Support HTML tags in markdown

### ISSUE THREAD

**Issue by Aloso** [LemmyNet/lemmy-ui#498]
### Is your proposal related to a problem?

CommonMark markdown supports HTML tags. Websites usually have an allowlist of accepted tags ([here](https://gist.github.com/seanh/13a93686bf4c2cb16e658b3cf96807f2)'s the list of tags accepted by GitHub). Since Lemmy doesn't follow the CommonMark spec, it doesn't support HTML, but I think it should, since HTML is much more flexible and powerful.

### Describe the solution you'd like

Lemmy should allow HTML tags. Ideally, it should also follow the CommonMark spec as much as possible.

### Describe alternatives you've considered

None.

### Additional context

[Official CommonMark website](https://commonmark.org/) and [playground](https://spec.commonmark.org/dingus/).

**Comment by Nutomic** [comment]
It would also have to be enabled on the backend for RSS and federation.

**Comment by dessalines** [comment]
I don't know that anything would be required for comrak. It doesn't actually render that html and would probably leave it alone when running `markdown_to_html`.
