### ISSUE TITLE
Add license to Javascript files

### ISSUE THREAD

**Issue by kartikynwa** [LemmyNet/lemmy-ui#50]
This would make Lemmy compatible with LibreJS.

[Originally mentioned in this post.](https://dev.lemmy.ml/post/38598/comment/14472) The methods how to do that are outlined [in the GNU LibreJS documentation](https://www.gnu.org/software/librejs/free-your-javascript.html#magnet-link-license).

@dessalines [comment](https://dev.lemmy.ml/post/38598/comment/14475) on that post:

> That seems pretty easy to add, this site uses AGPLv3 so we could add a magnet link in there. Sounds like a good first PR.

**Comment by ncorder** [comment]
[client.js](https://lemmy.ml/static/js/client.js) is not currently properly read.

________________________

Similar issue on https://github.com/LemmyNet/joinlemmy-site/issues/68

**Comment by dessalines** [comment]
What does that mean? It tells you to go to https://lemmy.ml/static/js/client.js.LICENSE.txt

**Comment by TomatDividedBy0** [comment]
Moving here, since I was guided as such. I think I'm running into the same issue as ncorder here, where while using the extension it continues to block client.js. I'm guessing there's still something up with how its being read that needs to be fixed. 


https://github.com/LemmyNet/lemmy/issues/1973

**Comment by dessalines** [comment]
I don't know whats wrong with it, so not sure what to do.
