### ISSUE TITLE
Nav bar search input field very broken

### ISSUE THREAD

**Issue by Tmpod** [LemmyNet/lemmy-ui#500]
### Issue Summary

Something in the new release broke the nav bar search input field. It has three issues:

1. When opened it pushes the layout in a weird way. 
2. The magnifying class icon is slightly darker than the other nav bar icons and the padding is smaller on the left than it is on the right.
3. The input field is actually selectable without it being expanded, which is weird.

### Steps to Reproduce

1. Log onto a Lemmy account (you need to be logged for the icons to appear and the layout shift to happen).
2. Click the search icon on the navigation bar.

### GIF

![Peek 2021-11-20 23-46](https://user-images.githubusercontent.com/35771816/142744143-95f03d92-9b2b-43f7-aff6-e50d06554424.gif)

**Comment by dessalines** [comment]
Might be a bit before I can get to this.
