### ISSUE TITLE
[Bug?] Voting on comments causes them to jump around due to ranking.

### ISSUE THREAD

**Issue by mister-monster** [LemmyNet/lemmy-ui#51]

**Comment by 0rvar** [comment]
I think a good compromise is to show buttons when there are new comments, and to update the comment tree when it's clicked. You could also have a "live-mode" checkbox to toggle auto-updating of the comment tree.

**Comment by lboklin** [comment]
Perhaps (if a "slow mode" is enabled) new comments could be collapsed so as not to displace the page contents, requiring a click to expand them. 

Under no circumstances do I think shuffling comments around based on votes should be done without user intervention. Maybe a button to update the ranking which gets highlighted when they change.

**Comment by dessalines** [comment]
As a short-term fix I can alter the sort logic to only sort on initial load. It won't fix new comments or posts pushing things to the top tho.
