### ISSUE TITLE
View suddenly jumps to top of page while reading comments on mobile

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#529]
I noticed a few times that Lemmy is suddenly jumping to the top of the page while i'm reading comments in a post. This only seems to happen on mobile (Firefox Android) so i dont have access to logs. I guess its caused by the arrival of websocket messages, or something similar.

**Comment by dessalines** [comment]
Yep, this is a tougher one. Has to do with scrolling after the comments have been loaded, which I'm doing wrong here. https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post/post.tsx#L205
