### ISSUE TITLE
Make the modlog button stand out more

### ISSUE THREAD

**Issue by vachan-maker** [LemmyNet/lemmy-ui#531]
In my opinion, the modlog option should stand out more. It should be more identifiable to the user. 

Some of the possible options
- give a new style to the modlog button
- Change the text to 'view modlog'
- Place modlog button somewhere else

![image](https://user-images.githubusercontent.com/65799568/146903358-0e1fee08-ac9c-46f2-9930-f19c87a2a100.png)

**Comment by vachan-maker** [comment]
With all the user and post stats, a user might not really notice   Modlog

**Comment by vachan-maker** [comment]
Well are all these stats necessary??

I think only the essential ones like no of users, no of posts and comments should be listed on the community sidebar. Others should be hidden.

**Comment by dessalines** [comment]
There's also a modlog at the bottom of the page. But ya I agree, this is somewhat hidden. I'm not sure of a different good place to put it though that's not obtrusive. Maybe just changing the color would be enough.

**Comment by dessalines** [comment]
Don't wanna clutter up the top bar with too much. For right now I'll do this:

![image](https://user-images.githubusercontent.com/930215/148079342-2cfa0748-6952-4999-8f98-21ab8e0cff4d.png)

**Comment by vachan-maker** [comment]
This looks better. Thanks @dessalines 
Should this issue be closed?
