### ISSUE TITLE
<hr> hard to see in darkly theme.

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#533]

**Comment by RayBB** [comment]
Looks like we'd want to make the change here: https://github.com/LemmyNet/lemmy-ui/blob/105bbe44609648c188eb8d1de28f86f7b21f9bd1/src/shared/components/post/post-listings.tsx#L46

By adding some of the related `hr` classes from boostrap: https://getbootstrap.com/docs/5.2/content/reboot/#horizontal-rules
