### ISSUE TITLE
Find lemmy-ui folder

### ISSUE THREAD

**Issue by ProjectMakerGeorgia** [LemmyNet/lemmy-ui#537]
i installed lemmy everything works perfectly installed with docker clean vps server ubuntu 20.04 is installed there. not found where is the lemmy-ui folder

**Comment by dessalines** [comment]
This repo is the source code for the UI, but you won't find it in install directories.

The UI is built and deployed to docker hub using the `Dockerfile` in this repo. You would have to change the source code, deploy your own docker image. Then in your install `docker-compose.yml` file, reference your built image.
