### ISSUE TITLE
Menu is illegible in vaporwave dark theme

### ISSUE THREAD

**Issue by Tamnac** [LemmyNet/lemmy-ui#545]
### Issue Summary
Using the vaporwave dark theme makes the user menu illegible, as shown below
![image](https://user-images.githubusercontent.com/49466795/149273065-8ff4989e-1087-4deb-97da-64f3830e5875.png)

### Steps to Reproduce

1. Set theme to vaporwave-dark
2. click the user menu

### Technical details
Tested on vivaldi and edge, lemmy.ml instance.

**Comment by dessalines** [comment]
Keeping themes up to date is very low priority for me, I have so much else going on. But I'll accept a PR to fix it.

**Comment by RayBB** [comment]
This can be closed as the theme has been removed in https://github.com/LemmyNet/lemmy-ui/pull/910 
@Tamnac @dessalines
