### ISSUE TITLE
Can I get involved as a UX Designer and design technologist? 

### ISSUE THREAD

**Issue by jcklpe** [LemmyNet/lemmy-ui#550]
Hi. I'd like to contribute to Lemmy if possible. I'm a professional UX designer and a design technologist. (design technologist means I'm a designer who focuses on design system work and the intersection between code and frontend skillsets)

Involving designers in open source work can be a little bit hard to figure out sometimes but I'd like to offer my services. 

Stuff like this:

![image](https://user-images.githubusercontent.com/9451726/150658896-0fc7b742-32d0-4db1-9693-3ae369dad532.png)

demonstrates some room for improvement on the design front.

**Comment by jcklpe** [comment]
@dessalines : I figured the color stuff was a theme issue but figured it was worth mentioning.   
  
Also the button padding is asymmetrical at least on (though I can see from inspect that it's styled symetrically so not sure why the bottom padding is off. Might be an extra margin in there or something idk. Also I'm on firefox so that could be it)  
  
As for technical skills:  
I'm pretty \["frontend of the frontend"\](https://bradfrost.com/blog/post/front-of-the-front-end-and-back-of-the-front-end-web-development/). I am good with scss and html. I know a little bit of javascript and react (my personal website is built using the frontity framework to plug into the headless Wordpress API) but I'm by no means a javascript dev. Basically I've taken a couple of Wes Bos courses and that's about it.   
  
My best skills are def in the actual design aspect though for sure.   
  
How can I best get involved? How would you like for me to slot in?

**Comment by dessalines** [comment]
The front end is written in bootstrap, which is the most popular front end framework, and not difficult to learn. I have almost no custom classes, everything is using standard bootstrap classes. If you'd like to get a dev environment set up, here's a contributing guide: https://join-lemmy.org/docs/en/contributing/contributing.html

If there's specific pages you'd like to improve, I can point you to the correct files / locations.

**Comment by jcklpe** [comment]
I know what bootstrap is, don't worry haha. I've been working in tech for 7 years. I have used bootstrap. I don't actually use it much anymore though since there's native browser features like CSS Grid and flexbox for layout, but yes I'm familiar.  
  
I'm not simply offering you an ["idea guy"](https://www.urbandictionary.com/define.php?term=Ideas%20Guy). What I'm offering is an informed view on the subject of design. I am not offering my services as a junior dev to fixing styling bugs. I'm not saying I'm above that either, people have to pitch in help where they can, but I think a larger strategic conversation we could have that would help more than a couple of pull requests tweaking the css.   
  
To start:  
What is your thoughts on a design system? Bootstrap is a step in that direction but it's not quite the same.   
  
A design system is a conceptual model used to organize the underlying pattern model of an application, in a way which is compatible with component based thinking.

**Comment by dessalines** [comment]
I don't know what a design system is, but I'd be happy to hear your thoughts on how we can improve lemmy.

**Comment by jcklpe** [comment]
@dessalines : Okay yeah a design system is basically a conceptual model used to define how design works with an application on a systemic level.   
  
Probably one of the most famous design systems is the [Material Design System](https://material.io/design/introduction).   
  
Point of clarification: the Material Design System is not the specific implementations in a component library. Component libraries and Design Systems came to prominence in tech around the same time but they are separate things. A design system is a conceptual model, a component library is a specific way of building ui in code. A component library can be an implementation of a design system but a component library can also be used without a design system undergirding it.   
  
Some other good design systems to reference:  
  
Atlassian: [https://atlassian.design/](https://atlassian.design/)

IBM: [https://www.carbondesignsystem.com/](https://www.carbondesignsystem.com/)

Mailchimp: [https://ux.mailchimp.com/patterns/color](https://ux.mailchimp.com/patterns/color)  
  
So the goal of creating a design system for Lemmy would be to document the existing components, try to define the underlying model of how they are used, examine ways these rules can be tweaked etc.

**Comment by jcklpe** [comment]
@dessalines : Hey I know you've been super busy so don't want to bother but was thinking maybe one way for us to start is I could start documenting the implicit design system as it exists. I could do that in the repo wiki or something. How does that sound?   
  
basically I would start by taking pictures of all the components and trying to document how they're used in the exist app.   
  
And to be clear when I say components I don't mean the actual components as they exist in code but as they appear to the end user.   
  
Also additional resources to learn about Design Systems:

*   [https://bradfrost.com/blog/post/atomic-web-design/](https://bradfrost.com/blog/post/atomic-web-design/)
*   https://www.invisionapp.com/inside-design/guide-to-design-systems/

**Comment by dessalines** [comment]
We don't use github wikis, but a markdown document somewhere in this repo would be fine. If you're going to document with pictures, I'd ask that they be hosted elsewhere and not added to the git here.

**Comment by jcklpe** [comment]
@dessalines Markdown docs in the actual repo seems messy espc with the limits on blob files. I'll document stuff using hackmd.io which is an online markdown editor. Starting a page here: [https://hackmd.io/@jcklpe/Hy2mb1Mk5](https://hackmd.io/@jcklpe/Hy2mb1Mk5)  
  
Once I make some further progress I might need to hop on a call with you or someone else to go through some analysis questions. The main purpose of documenting the design system as it exists implicitly in the system is to try and define it's mental model a little more clearly.

**Comment by jcklpe** [comment]
Did a first pass at documenting all the components. Documented some stuff with the color palette. Any interest in a chat or anything like that? We can do it through a secure platform, anonymously if you'd like. I'm pretty open about who I am, and use Github in a professional context but also understand you might have a different level of comfort on this @dessalines   
  
Also is there anyone more focused on the frontend side of things are you having to do this stuff on your own mostly?

**Comment by dessalines** [comment]
We can just use github to collaborate on this. Its mainly me doing the front end yes.

**Comment by jcklpe** [comment]
@dessalines : okay fair. 

[For reference here is the main page where I've documented stuff.](https://hackmd.io/@jcklpe/Hy2mb1Mk5)

So there's a number of things I notice in my first stab at analyzing the UI as it is currently exists:
Color palette stuff is inconsistent in how it's approached and semantic categories aren't respected: https://hackmd.io/@jcklpe/BJGoHPu1c

Some of the structure of the components don't make a whole lot of sense. For instance the use of a [Pill](https://ux.stackexchange.com/questions/98069/what-is-the-difference-between-pills-chips-and-tags-tokens) styling is often used in ui to indicate a discrete piece of metadata information like a tag but it's used through out the app instead to just group pieces of information, and in some places as a button as with the modlog: https://hackmd.io/bxCGwfO7T1mvIYSUh5IfCw

I can help push the design of this to be more systematic and follow a consistent UI mental model. Do you want to work with me on that?

**Comment by dessalines** [comment]
Sure, just let me know of specific things where you think the design could be better.

**Comment by jcklpe** [comment]
@dessalines  How would you like me to organize that work? I could create a ticket for individual design proposals, that way the team could discuss and weigh whether or not they actually want to implement individual recs. Does that work for you?

**Comment by dessalines** [comment]
Yep, issues for individual items would work best.

**Comment by jcklpe** [comment]
Sounds good. I'll get started on some of that work this week.
