### ISSUE TITLE
Different view modes (compact and classic)

### ISSUE THREAD

**Issue by vinoff** [LemmyNet/lemmy-ui#552]
### Is your proposal related to a problem?

I hate the look of lemmy. It might be because I am used to lobste.rs, news.ycombinator or old.reddit.com. Lemmy's UI just seems to be screaming at me. Everything is too big!

### Describe the solution you'd like

I would love if lemmy had a more "compact" mode. It would be great to have 2 additional view modes actually. If you go to reddit, you have a "classic" and a "compact". Something like that would be fantastic for lemmy.

**Comment by Nutomic** [comment]
Couldnt this be implemented as a theme?

**Comment by dessalines** [comment]
Maybe some things could, things like font size and spacings, but the main things that are making the page bigger, are things like image previews, icon sizes, etc.

**Comment by vinoff** [comment]
https://tildes.net/ could serve as a model for a compact mode. Something more towards discussion and not so much for memes/images.

**Comment by dessalines** [comment]
PRs for adding this welcome.

**Comment by JohanAR** [comment]
I made a quick [userstyle](https://userstyles.world/style/10446/lemmy-world-compact-view) for compact mode, in case anyone wants some inspiration for how it could look like, or just something temporary until a real solution is implemented. I'm using the Stylus plugin for Firefox, but I think there are other options too. One would have to replace lemmy.world with the domain of the instance they're using.
