### ISSUE TITLE
Sitewide taglines

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy-ui#556]
Similar to Reddit's prompts with one of their slogans, sitewide taglines can function to make an instance more cosy for the community.

Implementation is [pretty simple](https://git.chapo.chat/hexbear-collective/hexbear-frontend/src/branch/main/src/tagline.tsx).

It's probably better if it's loaded in from the config file though, we currently have them hardcoded in [a JSON file](https://git.chapo.chat/hexbear-collective/hexbear-frontend/src/branch/main/src/taglines.json).

## Example

![](https://www.hexbear.net/pictrs/image/dSR4e2BNY4.png)

**Comment by Nutomic** [comment]
This seems like a good opportunity to introduce a config file for lemmy-ui (preferably separate from the backend config). It would also be useful for other optimizations, like changing the default theme.

**Comment by dessalines** [comment]
No this should be in the backend like everything else, otherwise apps wouldn't be able to display it, or mods using those apps edit it. I see this as being another table, and coming back with `GetSite`.

**Comment by Nutomic** [comment]
That also works, but having it in a config file would be simpler. And i dont think that apps would really care to show this.

**Comment by not-layla** [comment]
Them coming back with `GetSite` gives more flexibility, I agree that mobile apps wouldn't show the taglines but other web/desktop apps written down the line will probably want to, it's more consistent. Is there a way to transfer issues or shall I recreate this issue in the backend repo?

**Comment by dessalines** [comment]
You could probably just recreate another one in the backend. I don't always do this, but almost every feature should have both a back end and front end issue.
