### ISSUE TITLE
Picture uploads are adding a `:`

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#56]

**Comment by Nutomic** [comment]
This might be related, in the output of `curl -H "Accept: application/activity+json" https://ds9.lemmy.ml/u/dess_ds9 | jq`:

```

"icon": {
"type": "Image",
"url": "https://ds9.lemmy.ml:/pictrs/image/b01dGpv4K2.png"
},
```

**Comment by Nutomic** [comment]
Okay it looks like the extra `:` in federated images comes directly from the frontend, so that should also be fixed with your commit.
