### ISSUE TITLE
Show Activitypub ID for posts and comments

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#569]
For fetching a post/comment from another instance, it is necessary to search for its activitypub id. This works by copying the url from the browser if its a local item, but the same will not work if its a remote post or comment. In that case, the only way to get the apub id is via browser console or api. 

For example, searching `https://feddit.de/post/83962` will fail, and it is necessary to search `https://fapsi.be/post/36912` instead (see https://github.com/LemmyNet/lemmy/issues/2090).

So there should be a link to expose the activitypub id of each post and comment, maybe using the [fediverse icon](https://en.wikipedia.org/wiki/File:Fediverse_logo_proposal.svg).

**Comment by dessalines** [comment]
I agree, that'd be useful, and not too difficult to add, as the `ap_id` already is coming back.

**Comment by Nutomic** [comment]
It looks too flashy and colorful, should just be monocolor like other icons. And i wouldnt put it next to the title, but below with other icons.

**Comment by dessalines** [comment]
![image](https://user-images.githubusercontent.com/930215/154545721-5eabfb9b-c873-47b9-9c3b-998ef32ab1f7.png)

**Comment by crsag** [comment]
Can you please fix the color of this ActivityPub ID button and add tooltips? 

The current colorful fediverse icon is confusing. Shouldn't it match other icons like the share button or link🔗 button? If its purpose is just to show or share post/comments AP_IDs, it's even more confusing without any tooltips.
