### ISSUE TITLE
Don't Redirect on Errors

### ISSUE THREAD

**Issue by kevincox** [LemmyNet/lemmy-ui#570]
### Is your proposal related to a problem?

Right now if the server returns an error (for example because the server is a bit loverloaded) you get redirected to a URL like https://lemmy.ml/404?err=FetchError:%20invalid%20json%20response%20body%20at%20http://lemmy:8536/api/v3/user?sort=New&saved_only=false&page=1&limit=20&auth=REDACTED&username=REDACTED%20reason:%20Unexpected%20end%20of%20JSON%20input to display an error message.

This is bad UX because:
- You can't just refresh to retry.
- The history is "overwritten. So you use the URL. For example if you browse down the homepage and open in new tabs you will just lose one of them and won't remember which it is.

### Describe the solution you'd like

Just render the error page on the URL that failed to load.

### Describe alternatives you've considered

Redirect, but keep the original in the history. But this still isn't as convenient in my opinion.

**Comment by dessalines** [comment]
These are errors that are occurring at the isomorphic layer (IE the server has an error before it can send info back to you). So these are basically a `404 server error` page showing you the error in text form.

It might have history, but I'm not sure.

**Comment by kevincox** [comment]
I'm not sure what you are trying to say.

I agree that the client should show the error in text form. However I think the URL should not be changed to an "error" URL, it should stay at the page that experienced the error.

**Comment by kevincox** [comment]
I feel like I'm vastly how the Lemmy frontend must work. To me it seems like. 

1. Navigate to a page. 
2. JS attempts to call the API. 
3. Error is encountered. 
4. URL is changed to the error page. 
5. The error is rendered. 

My main question is why can't 4 just be skipped. Just render the error page at the original URL. Is this just a framework limitation?

**Comment by dessalines** [comment]
You skipped a step between 1 and 2, lemmy has what's called an isomorphic ui, where there's a ui "server", that builds the page locally and fetches all the data on the server, and serves up pre built html without needing javascript. That ui server can only do a redirect when it fails to build the page.

**Comment by kevincox** [comment]
I see. But in that case why can't it just generate a prerendered error page withuot the redirect?

**Comment by Nutomic** [comment]
I agree, its very different when there is some backend error, and you get redirected to some different url. It means you cant just reload, but have to figure out how to get back to the url that you actually wanted to visit. Its even more complicated because it seems to mess up the browser history as well.

**Comment by dessalines** [comment]
Okay I found a not-as-pretty but clean way to do this.
