### ISSUE TITLE
Lemmy not displaying properly on KDE Falkon

### ISSUE THREAD

**Issue by librewarrior** [LemmyNet/lemmy-ui#571]
When accessing lemmy with a KDE falkon browser, it is not displayed properly. Not sure if this is a lemmy or falkon issue. 

I'm using a Linux.

**Comment by Nutomic** [comment]
Looks normal for me. Please include more details (software versions involved, screenshots, specific error messages).

**Comment by dessalines** [comment]
Yup, seems okay:

![image](https://user-images.githubusercontent.com/930215/153897986-1e507e79-29c3-4a5b-883d-09b99b9a8f60.png)

**Comment by librewarrior** [comment]
![Screenshot from 2022-02-14 21-38-44](https://user-images.githubusercontent.com/89090662/153942747-f8f6c906-7096-4dd8-b087-d7225fdc7ca3.png)

Falcon
Application version 3.1.99 (fcfdc34)
QtWebEngine version 5.12.7

Ubuntu 20.04.3 LTS

No error messages.

**Comment by Nutomic** [comment]
Looks like css isnt loaded for some reason, nothing to do with the version. Check the browser logs for any errors.

**Comment by dessalines** [comment]
It likely has to do with an issue of older browsers not supporting loading / unloading css, which we require for themes. There's a few other older browsers that had this issue iirc. It could also be older browsers not supporting prefers-color-schemes.
