### ISSUE TITLE
Bug on reload comments page 

### ISSUE THREAD

**Issue by woodruffandtheschnibbleofazimuth** [LemmyNet/lemmy-ui#572]
Hello,
when you are on the 'comments' page of a community and refresh it, it shows comments from other communities.
If you click 'Posts' and again 'Comments' they just come back.

I made a video:

![8i5Msyjndg](https://user-images.githubusercontent.com/25532821/153886237-5f2ee7a1-c3ee-47e1-8bea-2d3c3d32bdb7.gif)

**Comment by dessalines** [comment]
Confirmed, this is a bug in my isomorphic fetch. Thx for finding!
