### ISSUE TITLE
Margin change(UI modification)

### ISSUE THREAD

**Issue by Ciphercrypt** [LemmyNet/lemmy-ui#605]
### Is your proposal related to a problem?
-yes .

Was scrolling through the site and realised that decreasing the left margin of page can increase user experience significantly .
![image](https://user-images.githubusercontent.com/71181212/160969940-c6fbf281-2b24-46ba-9e81-6ee019065d8b.png)

this can look better with slightest UI modifications than this ...->
![image](https://user-images.githubusercontent.com/71181212/160970106-b8d7076b-69c8-458d-9318-018229d29d63.png)

**Comment by dessalines** [comment]
What left margin? And that top image looks wrong, what browser are you using?
