### ISSUE TITLE
Photo in pasts on main page of an instance on cell phones

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy-ui#607]
What's the question you have about lemmy?

At the moment on a cell phone, net to the title - there is a "+" sign. If you click on that, it enlarges the photo. I like this more as it makes the photo more visible and is similar to the way a lot of other mobile news feeds/blogs display.

Is there a way I can set my instance to default to have that "+" sign automatically clicked for all posts, so all the photos for each post are enlarged by default?

**Comment by dessalines** [comment]
Dupe of #552
