### ISSUE TITLE
Collapse "Subscribed to communities" list

### ISSUE THREAD

**Issue by Thann** [LemmyNet/lemmy-ui#609]
### Is your proposal related to a problem?

from https://feddit.de/post/142568:
> This list is very long for me, since our server otherwise wouldn’t get all the interesting posts, it’s so long that the home website is ridiculously long and I have to scroll endless to reach the info about the server or the modlog at the bottom etc.

### Describe the solution you'd like

Collapse panel by default to something smaller.
Also would like a filter option <3

### Describe alternatives you've considered

null

### Additional context

null

**Comment by tafiti** [comment]
Related to this, would the sidebar feature more prominently, ideally above the `subscribed to communities`, so that one need not scroll down to find it. 
Collapsing the list would have an informative and design value to it.
