### ISSUE TITLE
Old Reddit Style

### ISSUE THREAD

**Issue by abueide** [LemmyNet/lemmy-ui#61]
Some of us have been using the same old reddit theme for 10 years and just don't like change. It would be cool if there was just a simple theme that emulated the old-style reddit ui for us.

**Comment by dessalines** [comment]
[Here's Lemmy's theming guide](https://dev.lemmy.ml/docs/contributing_theming.html)

Any bootstrap v4 compatible theme works, so you can use https://bootstrap.build/ to make a theme that looks like old reddit, then link me either the `_variables.scss` or the bootstrap.min.css, and I'll add it.

**Comment by abueide** [comment]
Awesome, thanks
