### ISSUE TITLE
Make another version

### ISSUE THREAD

**Issue by soverxxx** [LemmyNet/lemmy-ui#610]
Plz make another version this UI for fast replacement (from docker installing)
Main changes:
1. Delete https://github.com/LemmyNet/lemmy-ui/blob/057a9ff4f50c81dccf1308348f558b2832152d92/src/shared/components/common/pictrs-image.tsx#L26

To make it possible to stretch
preview images of posts via css

2. Move in https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post/post-listing.tsx
 "{this.postTitleLine()} and {this.createdLine()}" (1139-1140)
upper to "  <div class="">{this.thumbnail()}</div>" 

like this:
```
{this.postTitleLine()}
{this.createdLine()}
<div class="">{this.thumbnail()}</div>
```

3. Add  preview post inside to `<div className="col-12">`
 ```
<div
          className="md-div mb-1"
          dangerouslySetInnerHTML={{
            __html: md.render(previewLines(post.body)),
          }}
        />
```

This is necessary for the classic display of posts.

**Comment by soverxxx** [comment]
I am ready to develop a special CSS for proper display, I just need the help of developers, because my knowledge is not enough to implement these changes in the project.

**Comment by Nutomic** [comment]
If you want to make any changes, you will have to make a pull request. [This page](https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github) describes how to do it.

You can also follow [these instructions](https://join-lemmy.org/docs/en/contributing/local_development.html) to run Lemmy on your local computer for development. For that, you will also need to git clone the lemmy repository.
