### ISSUE TITLE
add a wallpaper directory for lemmy-ui

### ISSUE THREAD

**Issue by 2xx04** [LemmyNet/lemmy-ui#617]
The theme I pulled has wallpapers hosted on github because there wasn't a clear folder for wallpapers. Not conventional. If it ever goes down the wallpaper will also disappear.

[Sal](https://mander.xyz/u/Sal) told that they didn't found the pictrs/image folder anywhere so I suppose it was only for uploads on posts. originally the css was:

```
body {background-image: url(/pictrs/image/{wallpaper-name}.wallpaper.jpg); background-attachment:fixed; background-size: cover; background-position: center;}
```

you can add a directory for wallpapers in src/assets/ or src/assets/themes, and somehow serve them on the web

**Comment by Nutomic** [comment]
I would propose a folder structure like this for extra_themes folder. That way, themes both with and without images will work, and the installation is as easy as pasting the file/folder in the right place.

```
extra_themes/
├── theme_1.css   // plain css theme
└── theme_2       // theme with images
├── images
│   ├── image_1.png
│   ├── image_2.png
│   └── main.css
```

**Comment by 2xx04** [comment]
yep, that's a better idea.

**Comment by dessalines** [comment]
@2xx04  When you do a PR to add your themes, you can also just add a wallpapers directory to src/assets/themes .

**Comment by alectrocute** [comment]
> @2xx04 When you do a PR to add your themes, you can also just add a wallpapers directory to src/assets/themes .

This seems like a good solution. Closing.
