### ISSUE TITLE
Need a css class to wrap around search listings and login/signup div element

### ISSUE THREAD

**Issue by 2xx04** [LemmyNet/lemmy-ui#619]
css path: html body div#root div div.mt-4.p-0.fl-1 div.container div

![image](https://user-images.githubusercontent.com/98880829/162642057-bb5e72ae-3d43-4a66-b03b-99e9542c3ef0.png)

(this is on the search page)

I need a background for this but if I added to the css path, it conflicts with others. (since there isn't a class for them too.)

EDIT: the signup div needs this too

**Comment by dessalines** [comment]
The relevant files for this are `search.tsx`, and `signup.tsx`. Let me know if you need any help getting a dev environment set up.

**Comment by 2xx04** [comment]
Alright, I never code but I think I get how this works. You have a documentation for that dev environment setup?

**Comment by 2xx04** [comment]
I found it.
