### ISSUE TITLE
Clicking on site title doesn't refresh stale posts

### ISSUE THREAD

**Issue by stephen304** [LemmyNet/lemmy-ui#630]
### Issue Summary

When the front page is stale, I instinctively click on the site title to refresh, but it seems the SPA routing doesn't let that happen if you're already on the front page. Clicking it while already on the front page should refresh the posts.

### Steps to Reproduce

1. Keep a tab open on front page
2. Click site title
3. Doesn't refresh stale posts

### Technical details

* Version 0.16.3 + Firefox 99.0.1

**Comment by dessalines** [comment]
One main idea of lemmy-ui is that you shouldn't have to refresh the page to get new posts, they should stream in via websocket. T

his tells me that there must be a bug which is preventing new posts from streaming in, I'll check it out.
