### ISSUE TITLE
codeblock design

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy-ui#631]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

the codeblock is currently not very clear and nicely usable
![grafik](https://user-images.githubusercontent.com/12276250/164013260-b007d744-f72d-42d7-b949-5cfdcae03031.png)

### Describe the solution you'd like

it would be great if you could customize the codeblock a little bit, so that it would look like this in the end:
![grafik](https://user-images.githubusercontent.com/12276250/164013531-2af4f854-ff07-4f07-bf90-c5c2af3ed4ee.png)
- no line breaks
- line numbers
- copy button

### Describe alternatives you've considered

do not currently know any

### Additional context

The desired codeblock is from bookstack
https://www.bookstackapp.com/

**Comment by dessalines** [comment]
PR for that CSS change welcome.

**Comment by Tealk** [comment]
Unfortunately this is not a pure CSS problem
Also js would be needed for this

**Comment by Tealk** [comment]
how exactly should I edit the css if there is only one minifyed variant? this may be great for machines to work with but for humans it is cruel
