### ISSUE TITLE
error 404 in `https://<lemmy.url.tld>/admin` space

### ISSUE THREAD

**Issue by XavCC** [LemmyNet/lemmy-ui#635]
### Issue Summary

After the last update v0.16.3, 404 when trying to access in admin webspace.
404 also occurs when we refresh the page.

If we click on the wheel in the menu for access to the administration area: it works.

### Steps to Reproduce

1. Web graphical interface
2. Log with valid ID / password
3. Admin privilege access
4. rom the address bar of the browser `https://lemmy.kaouenn-noz.fr/admin` -> `404: Not logged in` (with white background page and not usual 404 lemmy landing page)

![404: Not logged in](https://wtf.roflcopter.fr/pics/N844lnh3/eMX9K6T3)

![usual 404 lemmy landing page](https://wtf.roflcopter.fr/pics/HWT5XWe2/RWnPMuV7)

### Technical details

+ We tested (2 people, 2 admin servers, with 2 different machines and different access point) on our instance
+ with Firefox 99 & Chromium 100
+ as mentioned in dedicated chatroom some (few) other people reach same trouble and get same 404 point.  

Do you need website admin parameters?

**Comment by dessalines** [comment]
This is a server side rendering issue, I'll investigate.
