### ISSUE TITLE
Allow unmoderated new users with valid emails to follow threads but not comment

### ISSUE THREAD

**Issue by igormcoelho** [LemmyNet/lemmy-ui#643]
Congratulations for Lemmy, I love federated/decentralized technology, and just happened to know this and I am giving a try.

### Is your proposal related to a problem?

Sort of. I know there are many instances out there, but I tried to create a user in lemmy.ml, which is crowded (I know), so I got stuck in login form before moderation...
The issue I see is: while I am unmoderated, I cannot interact with the platform, even in non-destructive ways. I think that having a fast inboarding of new users is important for new tech to gain strength.

### Describe the solution you'd like

Maybe the admins are very fast, so I'm allowed fast, but that may not be the case (or even the case on other instances with less admins...), so I propose an idea:
Could Lemmy allow unmoderated new users with valid email addresses (correctly checked) to follow threads, start filling in its profile, following people, but not commenting or creating new threads?
This way, moderation for new users could work much slower, and users could already follow things and organize their digital lives on the instance, feeling like they were already all in... If moderation goes bad, the account could be deleted (worst case), or even kept on suspension for a longer period of time.

### Describe alternatives you've considered

The alternative seems to be the current system, where user just waits to be moderated, but without any feedback (I didn't even receive an email), so I have no way of knowing if and when I will ever be accepted on the instance.

### Additional context

I have many other fedverse users on ActivityPub platforms, so as other public platforms (such as GitHub)... If some of these information is also put on signup form, maybe this could also help admins to allow or disallow new accounts.
Congratulations again for this nice software.

**Comment by dessalines** [comment]
> The issue I see is: while I am unmoderated, I cannot interact with the platform, even in non-destructive ways. I think that having a fast inboarding of new users is important for new tech to gain strength.

Making comments or posts is potentially "destructive", there's no way to avoid that.

Instances can already turn on email-only validation, and turn off registration applications. We at lemmy.ml just likely won't federate with them because of the high amount of spam and trolls we've historically had from instances with open signups... but again you are fully able to run an instance with open signups with the existing software.
