### ISSUE TITLE
Add Option and Result Rust types to lemmy-ui

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#646]
A few *options* 😆  : 

- https://github.com/karen-irc/option-t
- https://github.com/swan-io/boxed
- https://github.com/sniptt-official/monads

Monads is my fav currently.

**Comment by Nutomic** [comment]
I doubt that this can work half as well in a language without sum types and proper match statements. But if it can at least reduce the usage of null all over the place, i'm all for it.

**Comment by dessalines** [comment]
Finally found a way to do this, been working on it for the past few days. I'm working through a lot of bugs with it, but its also cleaned up a lot of null pointer checks and possibilities. 

Typescript could've eliminated this entire class of bugs by adding first class support for Maybe / Optional, but they didn't.
