### ISSUE TITLE
Landing page redirects to signup rather than login

### ISSUE THREAD

**Issue by TurkeyMan** [LemmyNet/lemmy-ui#649]
### Issue Summary

Navigating to `lemmy.mydomain.com` automatically redirects to `lemmy.mydomain.com/signup`... that's definitely not what people want. People want to login by default. Sign-up is a one-time-only procedure, it shouldn't be the landing page.

### Steps to Reproduce

1. Install a brand new lemmy instance
2. Sign up to the new instance to create an account, then logout
3. Note that navigating to `https://yourlemmy.com` always redirects to `/signup`, which is a poor default landing place. Direct to the login page.

**Comment by dessalines** [comment]
This is for private instances btw.

I disagree, people seeing your site for the first time should see the signup page, not login. Since its rare that you'd ever need to log out, your use case / pattern is a rarer one, than people first seeing the site and needing to sign up.

**Comment by Nutomic** [comment]
I agree that on a private instance, its much more likely to be an existing user trying to login. New users would hardly find the instance in the first place, as there is no content to be indexed by search engines, and it wont be listed on join-lemmy.org because federation is disabled. Also, chances are that a private instance wont have open signups, so the signup form wouldnt be that useful anyway.

**Comment by TurkeyMan** [comment]
@dessalines That really doesn't make sense... Registration is exactly one time ever. People do log out of things. Also, I have several computers, and 3 browsers on each computer, and a phone, and a tablet, etc. Sometimes I buy a new device, re-install my OS, or clear the browser cache. I don't want to see a sign-up page in any of those situations. Signup as landing page is a weird and unprecedented default; you won't find that pattern anywhere else on the internet.

**Comment by dessalines** [comment]
Alright i can change this.

**Comment by sam365724** [comment]
Please make it configurable in settings.

**Comment by sam365724** [comment]
Is there any workaround for this? People getting confused by it honestly. I want the default page to be login and also show login after logout. How is that possible?

**Comment by dessalines** [comment]
There's no workaround rn, but I'll probably get to this before the next release.

**Comment by sam365724** [comment]
In case you want to change it yourself, do this in src/server/index.tsx:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/111515092/198712462-2e922407-d4a5-4a91-9fc1-733255baa143.png">

**Comment by Kommynct** [comment]
Couldn't the login and registration pages be merged?

Perhaps login should be attempted, and if there's nobody with that username, it could flow into a registration page?

**Comment by dessalines** [comment]
We used to have them on a single page, but people requested I split them up, and it was better for code separation. 

The best answer IMO, is just to link to the other one from each page.

**Comment by alectrocute** [comment]
Looks like we can close this out. Feel free to reopen if this is still something we should address.

**Comment by rokejulianlockhart** [comment]
> Looks like we can close this out.

@alectrocute, is that because it doesn't redirect anymore?
