### ISSUE TITLE
Front page shows content from "All" even though I've selected "Subscribed" in the settings.

### ISSUE THREAD

**Issue by amanharwara** [LemmyNet/lemmy-ui#66]
In my preferences, I've selected "Subscribed" as the sort type, but every time I visit the main page, it shows me content from "All" instead of "Subscribed". The weird thing is that it shows that "Subscribed" is selected, but does not actually show content from there. I have to choose "All" and then "Subscribed" again for it show up correctly.

**Comment by dessalines** [comment]
Could you try re-selecting subscribed in your user settings, then clicking save? I recently changed something having to do with adding a new default sort `Local` that might've messed this up.

**Comment by amanharwara** [comment]
Ah yes, that seems to have fixed it. Closing the issue.

**Comment by amanharwara** [comment]
Re-opening this because it looks like the problem didn't get completely solved. It's still happening to me. I tried clearing all the data, but that doesn't work. I have to go to the next page first and then come back to the first page to make it work.

**Comment by dessalines** [comment]
I'll take a look soon.

**Comment by dessalines** [comment]
I just tried and I can't replicate this. I go to my profile, click sort type all, save, then sort type subscribed, save, then refresh the main page, and all seems good.

**Comment by amanharwara** [comment]
Hmm I toggled it in the settings a couple of times and now it seems to be working.

**Comment by dessalines** [comment]
Could you tell me the steps of how to replicate this?

**Comment by amanharwara** [comment]
Happens for me any time I open https://dev.lemmy.ml. It shows that "Subscribed" is selected, but the content does not match. I'm using Firefox so maybe it has something to do with that?
