### ISSUE TITLE
login broken in webkit

### ISSUE THREAD

**Issue by dayinjing** [LemmyNet/lemmy-ui#669]
### Issue Summary

Login does not work in the 16.4 release of lemmy-ui for webkit browsers. ios and osx

### Steps to Reproduce

1. on osx or iphone go to lemmy.ml
2. try to login
3. you can't

### Technical details

Console says something about 'undefined is not an object (evaluating 'this.we.send')'

**Comment by dayinjing** [comment]
Content security policy change here https://github.com/LemmyNet/lemmy-ui/compare/0.16.3...0.16.4#diff-a9ad80ae074de023f610c915d6e37938213c456d1f54fa0e58bbab181045bb59R30

Seems to have broken login on webkit devices

**Comment by dayinjing** [comment]
Looks like this value is comming out wrong in the ui `${wsUriBase}` I guess

**Comment by nicfab** [comment]
It could be the same of my issue https://github.com/LemmyNet/lemmy/issues/2286

**Comment by dayinjing** [comment]
> It could be the same of my issue [LemmyNet/lemmy#2286](https://github.com/LemmyNet/lemmy/issues/2286)

Yeah looks like the same issue; although you should have opened it here because it is a ui issue. I'm working on a fix.

**Comment by dayinjing** [comment]
Ok, this is what needs to be done to fix it,

```
if (!process.env["LEMMY_UI_DEBUG"]) {
  console.log("wsUriBase:",wsUriBase);
  server.use(function (_req, res, next) {
    res.setHeader(
      "Content-Security-Policy",
      `default-src 'none'; connect-src 'self' ${wsUriBase} wss://DOMAINNAME/api/v3/ws; img-src * data:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; form-action 'self'; base-uri 'self'`
    );
    next();
  });
}

```

**DOMAINNAME** needs to be your domain name and then it will work on web-kit browsers. I just hard coded it and tested it on my instance and it works fine. 

My kids woke up So I need to go make breakfast. Hopefully someone else can pick this up Or i'll open a pr later to make it more general.

If anyone knows where the domain name is accessable on the front end and can put it here that would speed it up.

**Comment by dayinjing** [comment]
https://github.com/LemmyNet/lemmy-ui/pull/671

PR to fix here

**Comment by dessalines** [comment]
This seems pretty urgent, so I'm just going to comment out the CSP headers for now. @Nutomic we'll have to try again when we find a way to test iOS devices.

**Comment by dessalines** [comment]
Okay builds started for these, `0.16.5` should be ready to deploy in an hour or so.

**Comment by nicfab** [comment]
I upgraded but the issue remains (macOS 12.4 - M1).

**Comment by makotech222** [comment]
Just want to note, this change breaks websocket connections on local dev testing on Windows machine. I had to revert in order to get it in working condition again. Should we be setting environment variable for 'LEMMY_UI_DEBUG' now?
