### ISSUE TITLE
Flawed "Expand here" tooltip on iOS

### ISSUE THREAD

**Issue by blox814123** [LemmyNet/lemmy-ui#684]
### Issue Summary

On iOS, when clicking on the navigation icon in the top navigation, the "expand here" tooltip appears and doesn't disappear again. This tooltip is probably redundant anyway, as navigation icons are a well-known UI element, and self-explainable.

### Steps to Reproduce

1. visit lemmy.ml on IOS 15.4.1
2. click on navbar icon
3. see screenshot

![photo_2022-06-16_09-04-28](https://user-images.githubusercontent.com/83985490/174012304-84120e7b-4758-4799-9c6b-955e174860fc.jpg)

**Comment by dessalines** [comment]
Unfortunately I don't have an iOS device so I can't test this. That's the same tooltip method used for all buttons, so I imagine this would affect every tooltip on iOS.

**Comment by blox814123** [comment]
Yes, it affects everything. Can't even click on the logo. 

I am not a developer, and can't say more about this. I understand you can't test it yourself, but maybe someone else can look into this, because if lemmy is unusable on 20-30% of devices, that's preventing use for many potential users.

**Comment by dessalines** [comment]
I'd appreciate the help. Its hard to debug something that works one way on iOS / safari, but works correctly on FF, chrome, and all android browsers.

**Comment by fnzen** [comment]
Works for me on [lemmy.ml](https://lemmy.ml). I'm not logged in there, but on [feddit.de](https://feddit.de), where I have my account, it also works.

Safari on iOS 16.1.1.

![IMG_3896](https://user-images.githubusercontent.com/35140568/208307905-b3a14946-b0db-42ce-a610-f953b830148e.jpeg)

**Comment by jsit** [comment]
Can this be closed?

**Comment by cakmakb** [comment]
I‘d say yes, in my case everything is working now 👍🏼
