### ISSUE TITLE
"Create community" doesn't work every time

### ISSUE THREAD

**Issue by blox814123** [LemmyNet/lemmy-ui#686]
### Issue Summary

Creating a community sometimes doesn't work, see screenshot:

![image](https://user-images.githubusercontent.com/83985490/174013236-28073871-cd36-434c-a4f7-d751c73cc568.png)

### Steps to Reproduce

1. Create a community
2. Try to create the same community again, it will say that the community already exists.
3. Immedietally create a new community that doesn't already exist
4. Spinning wheel appears, community isn't created

### Technical details

1. latest lemmy version

**Comment by dessalines** [comment]
I'd need the browser console output to see what's going on.
