### ISSUE TITLE
Suggested post titles have HTML entities remaining

### ISSUE THREAD

**Issue by comfy-v** [LemmyNet/lemmy-ui#691]
### Issue Summary

Suggested post titles have HTML entities (maybe a double encode or non-decode).

### Steps to Reproduce
Begin to make a post with a URL linking to a page with a title which includes a symbol that requires escaping in HTML, then wait for the suggested title.

Example link: https://brooketully.com/dont-do-things-part-1/ (contains ' and > ) 

![image](https://user-images.githubusercontent.com/108037723/175185427-ede3165e-4489-484b-b47c-5f7f7d7b34bf.png)

**Comment by dessalines** [comment]
Verified.
