### ISSUE TITLE
Loading indicator for community search when posting

### ISSUE THREAD

**Issue by comfy-v** [LemmyNet/lemmy-ui#692]
When making a new post, searching for communities can take some time to return a result, probably affected by remote instances and slow user connection. During this time, Lemmy-ui shows "No results found" or old results, which is replaced after some seconds with the actual search result. It should show a loading indicator instead.

Similar to https://github.com/LemmyNet/lemmy-ui/issues/188

**Comment by dessalines** [comment]
Just a note that it'll probably be a while till I can get to these.
