### ISSUE TITLE
Posts from blocked communities still show up in live updates

### ISSUE THREAD

**Issue by Tamnac** [LemmyNet/lemmy-ui#697]
### Issue Summary

If you've blocked a community, posts from it will still show up in the "live updates" feature in the top right. 

**Expected behavior:** posts from blocked communities do not show up in live updates.

### Steps to Reproduce

1. Log in to lemmy
2. block a community 
3. Return to home page
4. Wait for a post (or make one yourself) in previously blocked community
5. It shows up

### Technical details

Windows 10, chromium browser, logged into lemmy.ml

**Comment by dessalines** [comment]
Yep, confirmed.
