### ISSUE TITLE
Provide option for Join Lemmy link in footer to point to instance signup page

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy-ui#698]
At the moment the "Join Lemmy" link in the footer of a default lemmy install clicks through to https://join-lemmy.org/ and then a new user has to click on "Join a Server" which sends them to https://join-lemmy.org/instances

This is probematic for several reasons:
- it is confusing to new users - they just want to join the instance and they are presented with a decision about joining or running a server. I am sure a lot would drop out at this point as they do not want to invest the time to work out what it is all about.
- if they do click on Join a Server - they are presented with a bunch of different servers which again is very confusing
- they instance they want to join may be lowly ranked on the Join a Server site making it difficult to find the instance (even if the understand what an instance is) to join. Again this probably increases the drop out rate.

**Requested Enhancement**
Add a setting to the instance settings page to replace "Join Lemmy" with "Join Instance Name" that links directly through to the sign up page for that instance. This would be  a lot less confusing for new users, reduce the drop out rate, and give new users a better chance of gaining new users from the traffic they generate.

**Comment by dessalines** [comment]
The top of the page already has a sign up / log in thing. Navbar is for instance-specific things, the footer mostly has things related to the lemmy project, or things that couldn't fit on the navbar.
