### ISSUE TITLE
Allow unfollowing a community while status is "pending"

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#705]
In case a follow failed to go through, it would be useful to be able to cancel it, and try again. This could be implemented simply by turning the "subscribe pending" text into a button, which does unfollow when clicked.

![Screenshot_20220630_120029](https://user-images.githubusercontent.com/1044450/176650564-d16e4f50-7088-46ce-8390-5cc874a21a3a.png)

**Comment by dessalines** [comment]
I can add this.
