### ISSUE TITLE
Support for video embeds

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#709]
[This change](https://github.com/LemmyNet/lemmy/pull/2261) removed API field post.embed_html, and added embed_url instead. This should work for Youtube, Peertube and and other sites that set the opengraph attribute in their html.

So lemmy-ui should show a video embed whenever that field is set. At the moment the implementation is a bit strange, because it only shows the embed if post.embed_title is set, which isnt always the case. I would also suggest to change the "plus" button behind which the embed is hidden, because its not clear at all what it does. Maybe just change it to a text label "watch video".

**Comment by Nutomic** [comment]
This will be part of 0.17.0

**Comment by dessalines** [comment]
That PR does add support for video embeds from peertube, but we also need to support pictrs videos.

**Comment by RobertSchuh** [comment]
Could you also support onlineplayer.com?

For example: https://onelineplayer.com/player.html?autoplay=true&autopause=false&muted=true&loop=false&url=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F701745118213832755%2F1065810962164219944%2FPDC_WIP01.mp4&poster=&time=true&progressBar=true&overlay=true&muteButton=true&fullscreenButton=true&style=light&quality=auto&playButton=true

This video player can be iframe-embedded like youtube or vimeo, but can play video files hosted elsewhere, like dropbox or discord.
Or maybe implement your own video player with the same features so that links to .mp4 files hosted elsewhere can be played as videos.

**Comment by lordkitsuna** [comment]
please add support for direct links to videos to be played back on site. a lot of us are all about self hosted and that includes our storage! i have a seafile and i host meme videos on it. these embed in things like Discord without issues would be nice for lemmy to also support it.

example url: https://seafile.kitsuna.net/f/ffb48fd595a34e3b8b0a/?raw=1

**Comment by trymeouteh** [comment]
Would like to see this feature as well for posts and comments. This will allow posts and comments to embed multiple videos in a post or comment.

**Comment by rokejulianlockhart** [comment]
I agree, @lordkitsuna. I believe that the title should be updated to reflect that.

**Comment by q0braa** [comment]
+1

**Comment by Nutomic** [comment]
Video embeds are discovered using [Opengraph attribute](https://ogp.me/), there is no specific logic for Youtube. So it should work with any platform which provides these attributes.

**Comment by graphit0** [comment]
Is there any docs regarding ogp embedding on lemmy? just looking for examples to make it work

---
My case is this ogp, I'd like to display preview either in the body or a comment of lemmy post

```
<meta property="og:title" content="Move fast and break things." />
<meta property="og:description" content="Design Thinking! Comic (@designthinkingcomic@mastodon.cloud)" />
<meta property="og:image" content="https://cdn.fosstodon.org/cache/media_attachments/files/112/602/710/504/014/882/small/f4e45a2b240352f7.png" />
<meta property="og:url" content="https://mastodon.cloud/@designthinkingcomic/112602710437100307" />
<meta property="og:type" content="article" />
<meta property="og:site_name" content="Mastodon.cloud" />
<meta property="article:published_time" content="2024-06-12T08:30:06.000Z" />
```

source for the ogp: https://shkspr.mobi/blog/2022/11/webmentions-privacy-and-ddos-oh-my/

**Comment by dessalines** [comment]
lemmy stores *some* embed info, and lemmy-ui currently shows a [metadata card](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post/metadata-card.tsx) containing the embed title and description, if the back-end was able to fetch and store them correctly.

**Comment by LizardWizardGB** [comment]
Are you supposed to be able to play a PeerTube video, directly on Lemmy? Because it seems that it only gets a thumbnail and then a link to the PeerTube instance.

**Comment by dessalines** [comment]
Yes that should be working, but it does need some people to help test.

**Comment by LizardWizardGB** [comment]
> Yes that should be working, but it does need some people to help test.

Maybe we are misunderstanding each other, but if you go here https://lemmy.wtf/c/gametrailers I am not able to play the videos from PeerTube. I have to go directly to Peertube to play the video.

**Comment by K4LCIFER** [comment]
> if you go here https://lemmy.wtf/c/gametrailers I am not able to play the videos from PeerTube. I have to go directly to Peertube to play the video.

Same goes for https://sh.itjust.works/c/thelinuxexperiment_channel@tilvids.com
