### ISSUE TITLE
White letter on white background on toastify

### ISSUE THREAD

**Issue by skariko** [LemmyNet/lemmy-ui#719]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

With default theme when you upload a photo the notification popup have white lettering on white background:

![white](https://user-images.githubusercontent.com/25532821/179173995-6ea8dc7c-822b-4178-91e0-285880f98964.jpg)

### Steps to Reproduce

Use default theme, upload a photo and wait for the notification.

### Technical details

If I could see correctly, the problem is with the style:

toastify: {
color: #fffff
}

![toastify](https://user-images.githubusercontent.com/25532821/179175152-6be4b93a-cc23-457b-bcc2-2d8f6ef7d051.jpg)

If it is possible to change it only for this theme (and for light themes) to black I think it solves the problem.

**Comment by sam365724** [comment]
I can confirm this issue.

**Comment by dessalines** [comment]
You can make a PR to edit that theme, but I'm not going to do theme upkeep apart from the two main ones. Eventually I'm going to autogenerate all of these from bootstrap v5 `scss` files: #703 .
