### ISSUE TITLE
Permanent links of comments are not working in long threads, when comment linked is under the first rendered comments

### ISSUE THREAD

**Issue by wardrob-lev** [LemmyNet/lemmy-ui#721]
### Issue Summary

It's not possible to link to a single comment if it is in a long thread (below the x first scrollable comments). the "permanent link" will not show the right place inf the thread.

### Steps to Reproduce

1. Choose a thread with a lot more comments than the number of comments loaded in the window without scrolling down.
2. Scroll down to reveal more comments
3. Clic on the "permanent link" of one of these additional comments (or copy paste it)
4. The page refreshes at some random comment. It's then impossible to retrieve the comment by its link.

### Technical details

- I reproduced the issue on two recent versions of Firefox (one fully up to date)
- Issue discussed here with admin : https://lemmy.ml/post/352767

**Comment by dessalines** [comment]
This will be fixed as part of the comment tree paging issue I'm working on. The "scroll to comment", is a hack that can't work when there are too many comments in a thread and it has to do paging. 

Part of the ticket I'm working on is that a comment link will go only to that comment, showing its children, and having the ability to show context.

**Comment by dessalines** [comment]
This is fixed in main.
