### ISSUE TITLE
Error with LEMMY_UI_CUSTOM_HTML_HEADER

### ISSUE THREAD

**Issue by nicfab** [LemmyNet/lemmy-ui#733]
I set in the file `docker-compose.yml` the value of `LEMMY_UI_CUSTOM_HTML_HEADER=` with the following Matomo script on the same line:
```
<!-- Matomo -->
<script>
  var _paq = window._paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://matomo.nicfab.it/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '8']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.async=true; g.src=u+'matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>
<!-- End Matomo Code -->
```
Anyway, from the browser (Firefox, for example) via _Web Developer Tools_ -> _Inspector_ I see the following:
`Content Security Policy: The page’s settings blocked the loading of a resource at https://matomo.nicfab.it/matomo.js (“script-src”).`
Moreover, always via _Web Developer Tools_ -> _Console_ I see:
`Content Security Policy: The page’s settings blocked the loading of a resource at https://matomo.nicfab.it/matomo.js (“script-src”).
`Consequently, the script doesn't work.
I don't know if it derives from the latest update.
How can I solve?

**Comment by Nutomic** [comment]
You can set env var `LEMMY_UI_DEBUG=true`, which will disable content security policy. Then it should work fine. This decreases security, so you might want to set your own csp in nginx.

@dessalines i think that env var should be renamed to LEMMY_UI_DISABLE_CSP` or similar. Also, have you made progress on documenting all the env vars?

**Comment by nicfab** [comment]
> You can set env var `LEMMY_UI_DEBUG=true`, which will disable content security policy. Then it should work fine. This decreases security, so you might want to set your own csp in nginx.
> 
> @dessalines i think that env var should be renamed to LEMMY_UI_DISABLE_CSP` or similar. Also, have you made progress on documenting all the env vars?

Thank you very much.
I think to have found a solution by using an "Image Tracking Link" instead of a "JavaScript Tracking Code", and now it works fine.
I don't want to decrease security.

**Comment by dessalines** [comment]
`LEMMY_UI_DEBUG` is mainly for adding eruda, which also must disable CSP to work.

How about, if a custom html header is used, it should also disable CSP? Seems like pretty much the point of those headers anyway is to have external scripts usable.

**Comment by Nutomic** [comment]
> How about, if a custom html header is used, it should also disable CSP? Seems like pretty much the point of those headers anyway is to have external scripts usable.

That makes sense, but it needs to be documented.

**Comment by dessalines** [comment]
The next release will have LEMMY_UI_DISABLE_CSP env var, so this should be fixed.

**Comment by darkzbaron** [comment]
I have tried to add LEMMY_UI_DISABLE_CSP  = true to my docker-compose.yml file but using Firefox debuggin, I am getting 
Loading failed for the <script> with source ...

Any help?

**Comment by dessalines** [comment]
Post your docker-compose.yml file please, and the full javascript error.
