### ISSUE TITLE
Substitute text for link

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#735]
When creating a link it would be nice if I could select the text that I want to turn into a link and paste the url and have it formatted automatically as a link.

**Comment by Nutomic** [comment]
I dont understand what you mean. Please explain more specifically.

**Comment by JediMaster25** [comment]
Ok. When I want to create a link I can place the text in square brackets and the link in parenthesis writing it myself, or I can select some text and click the create link button to have it place the square brackets around the text automatically with the empty parenthesis at the side. What I'm asking for is another commonly available option in which you copy the link to clipboard and select the text and then you paste the link, and instead of substituting the text for the link, it formats the url with the text in square brackets and the link in the clipboard in parenthesis.

**Comment by dessalines** [comment]
Ooookay I think I know what you're talking about. 

Instead of the link button just inserting a blank `()`, have it insert whatever's in your clipboard into `(CLIPBOARD_TEXT_HERE)`. Yep that's probably doable.

**Comment by JediMaster25** [comment]
No, it's another option without using the link button. Just pasting a link into the selected text same as when you do it here.

**Comment by dessalines** [comment]
That's not necessary, because our markdown already has linkify, that will turn any links in text, into a `<a` type link.

**Comment by JediMaster25** [comment]
But it's a usual feature of markdown. Like here, on reddit, on discourse, and every other I can think of right now.

**Comment by dessalines** [comment]
How does that work on any of those platforms? You select text, paste a link, then it's smart enough to know not to overwrite the text you've selected?
