### ISSUE TITLE
Comment Link Leads to 404 Error

### ISSUE THREAD

**Issue by wiwikuan** [LemmyNet/lemmy-ui#746]
### Issue Summary

I don't know why every comment has two "link" buttons, the first one generates a correct link to the comment, but the second one generates a link that leads to 404 error.

### Steps to Reproduce

My instance: https://nicelink.me

As the image below, the first link button (chain icon) links to https://nicelink.me/post/50/comment/93, which is the correct link to the comment; The second one (star-like icon) links to https://nicelink.me/comment/93, which is a 404 error page.

![image](https://user-images.githubusercontent.com/4676714/183263364-1ba95196-b72d-489f-a93f-9efbd6b0c6cb.png)

**Comment by dessalines** [comment]
This is fixed by #726 , it'll be in the next release.

**Comment by dessalines** [comment]
The first link is the local one, the 2nd link is the federated link, which links to the content on its home instance. Both are necessary because you may want to give someone the link to the content from your instance.

**Comment by xundeenergie** [comment]
Try it yourself:
1. go to a remote instance
2. open a posting with comments
3. take the uri from the chain-symbol
4. search on YOUR instance for this uri -> no result
5. take the uri from the fedi-symbol
6. search on YOUR instance for this uri -> lemmy finds exactly this comment.

I can see no other sense behind this shortened link in the fedi-symbol... but this sense is a very important sense!

Or you improve lemmy to recognise full links to comments and it will find the comment with the full uri.

**Comment by xundeenergie** [comment]
> The first link is the local one, the 2nd link is the federated link, which links to the content on its home instance. Both are necessary because you may want to give someone the link to the content from your instance.

This looks something special... 

I think, it seems as a good idea, to rework something... 

I can find the comment from the "fedi-link" But i can not find the comment from the "chain-symbol" link, if it is not original from this remote instance... 

I think, it is the best, 
- if the link in the chain-icon points to the local representation (with full url, as actual works)
- if the link from the fedi-icon points to the original comment (with full url)
- if lemmy finds a comment with full-url. even from local-representation and fedi-link with full link...

**Comment by dessalines** [comment]
Why are you doing step 4? The only reason to paste a fedi-link in the search box is to cache it.

Step 6 work exactly as it should.

**Comment by xundeenergie** [comment]
> Why are you doing step 4? The only reason to paste a link in the search box is to cache / connect to federated items. It doesn't make any sense to do that with a local link, you can just go to the URL.

Just to demonstrate, that a link with "/post/1234" including does not find the comment.

> 
> Step 6 work exactly as it should.

Yes... when you take the Fedilink now... without the "/post/12345"-part. Then it finds the comment on the original server.
But if you fix it now, and the fedi-link gives you the whole url, including the posting, then the search won't find the comment.

Ok. to make it a bit clearer:

In my scenario i talked about 2 instances:
- My instance
- 1 remote Instance

On the remote instance is a community. Originally there. not from another remote instance. 
This community contains Postings, and this postings have comments. All are from the same instance.
Then the "link" and the "fedilink" point to the same server. This remote-server. 

On MY instance i can search for the "link", including the "/post/12345"-part. It does not find the posting. (step 4)
On MY instance i can search for the "fedilink", the same as the "link", but without the "/post/12345" part. MY instance finds the comment.

When MY instance finds the comment, it got synced to MY instance. I have there also a "Link" and a "Fedilink".
Then i can click on the "Link", and the comment is opened. I can click on the "FediLink"... and get this 404 from the remote instance. 

When someone find THIS comment on MY instance, thisone can take the fedilink and search on HIS instance for the Fedilink and will find the same comment. And the game starts from new.

If you "fix" it now, you add the "/post/12345" part to the fedilink. So someone can click on it, and is led to the original comment on the original server. Ok.
But if someone wants to search for this comment on HIS instance, he has to remove manually the "/post/12345"-part from this link... 

SOLUTION:

Make Lemmy find comments including the "/post/123435"-part. Named the full uri of a comment, which is callable by a webbrowser too.

I hope, you can imagine a little, what i mean.

**Comment by dessalines** [comment]
This is fixed in the upcoming release, as stated in a comment above.

**Comment by xundeenergie** [comment]
I can not watch the linked videos... don't know why.

**Comment by xundeenergie** [comment]
Can you, please, give a short abstract, how you fixed it?

**Comment by dessalines** [comment]
By implementing comment threading and adding the /comment/id endpoint, which didn't exist before.
