### ISSUE TITLE
You Can Press the "Next" Button Forever

### ISSUE THREAD

**Issue by wiwikuan** [LemmyNet/lemmy-ui#747]
### Issue Summary

The "next" button is not disabled when there is no next page.

### Steps to Reproduce

1. Go to any page where you can see a "next" button. (like here: https://lemmy.ml/c/ubi)
2. Press the "Next" button again and again.
3. It keeps incrementing the page number in URL. (But there is no content after page 2)

``` 
https://lemmy.ml/c/ubi/data_type/Post/sort/Active/page/2
https://lemmy.ml/c/ubi/data_type/Post/sort/Active/page/3
https://lemmy.ml/c/ubi/data_type/Post/sort/Active/page/4
and so on ...
```

**Comment by dessalines** [comment]
Lemmy's API doesn't return counts for paging.... main reason is that count queries can be really slow for massive tables, and after a few dozen posts, this becomes a non-issue anyway. Seems an easy choice in the tradeoff between "Always showing the next button" vs "Slowing down fetching".
