### ISSUE TITLE
Search: Minimum Keyword Length is Too Long For Asian Languages

### ISSUE THREAD

**Issue by wiwikuan** [LemmyNet/lemmy-ui#750]
### Issue Summary

The search text box requires me to enter 3 characters minimum. 

But in Chinese (and Japanese also), a lot of the common words are just 2 characters, the 3-character minimum setting makes the search box hard to use for Asian languages.

Can we lower the minimum to 2 characters?

![Screenshot at Aug 07 16-14-14](https://user-images.githubusercontent.com/4676714/183281977-9034fcdf-70f2-47b3-9682-39b7759af951.png)

**Comment by wiwikuan** [comment]
Actually, we have a lot of words which has only one character, too. Is it possible to disable the minimum character altogether?

**Comment by dessalines** [comment]
I spose we could reduce it to one character. We also have search rate limits now, so that should mitigate the spam potential anyway.
