### ISSUE TITLE
Can't see the votes for some comments

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#753]
I can't see the number of positive and negative votes for some comments, but I can see them for the rest. For example [here](https://lemmy.ml/post/419974/comment/252425) I can see the votes in one comment and not another. It should be the same for all comments from the same user, shouldn't it?

I'm using Firefox 103.

**Comment by dessalines** [comment]
It only shows both the positive and negative, if a negative exists. Otherwise the score = the number of upvotes.
