### ISSUE TITLE
Hide "Create Community" if site setting does not allow to create by non admins.

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#754]
### Issue Summary

Hide the top link "Create Community" if the setting "Only Admins can create Communities" is true.

Version: 0.16.6

**Comment by dessalines** [comment]
That's doable.

**Comment by sam365724** [comment]
There is another one, similar to this: 
- Do not show remove post if the user does not have mod or admin permission to actually remove it.

**Comment by dessalines** [comment]
Pretty sure it doesn't show a  remove post button for non admins / mods.

**Comment by sam365724** [comment]
See link: "remove", then click remove post. I'm logged in as normal user.

<img width="412" alt="image" src="https://user-images.githubusercontent.com/111515092/186020766-20b7cd68-0329-43aa-9abf-6596ef0ecd17.png">

<img width="283" alt="image" src="https://user-images.githubusercontent.com/111515092/186020820-49d1d471-49be-4acc-9e36-eb0d0535cd3f.png">

**Comment by dessalines** [comment]
I can't verify the 2nd issue, from the main branch at least.
