### ISSUE TITLE
Community created by an admin: can never add a moderator

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#755]
### Issue Summary

When a community was created by an admin, I don't see a way to add this one to a moderator. For the user with a post, the only action is to make that user an admin too, but how to just give a moderator? 

### Steps to Reproduce

1. Create community as an admin user --> User shon as admin.
2. Post as another user in that community
3. Try to add that other user as moderator

### Technical details

Version: 0.16.6 docker

**Comment by dessalines** [comment]
I can't reproduce this, it always shows appoint as moderator for other users.

**Comment by sam365724** [comment]
I agree, it was my misunderstanding. Sorry for that.
