### ISSUE TITLE
Ongoing problem - not all local communities appearing in post creation drop down box.

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy-ui#756]
https://github.com/LemmyNet/lemmy-ui/issues/633

This problem continues to cause me a lot of grief.

I thought when I reported it last time - you asked me to produce some sort of log file and told me how to produce it limiting it to a recent period so the file was not huge.

I cannot find that instruction again, so I was wondering if you could tell me how to do it. 

I have some time this weekend and would really like to get you some very specific examples to look at.

I cannot reproduce the problem every time, but there are certain cases where I can reproduce it 10% to 20% of the time.

Thanks for your help

**Comment by dessalines** [comment]
Its probably because of the result limit: the search isn't specific enough and your community is pages back.

**Comment by Kap2022** [comment]
I type in the exact name of the community.

**Comment by Kap2022** [comment]
![United Kingdom - list of communities](https://user-images.githubusercontent.com/97898454/185767844-028b8349-fdbe-413e-b7a0-3e04bb491a6c.png)
![United Kingdom Drop Down](https://user-images.githubusercontent.com/97898454/185767848-0acecbb6-e196-4dce-b65c-9b03c4970d06.png)


Here is a screenshot list of communities showing there is a United Kingdom community.

There is also a screenshot of me trying to crosspost to the United Kingdom community and it does not appear in the drop down box.

It is not that it never appears - it only appears sometimes.

**Comment by dessalines** [comment]
I'm like 90% sure this is due to you hitting the search rate limit: https://github.com/LemmyNet/lemmy/blob/main/config/defaults.hjson#L39

We should probably increase that default because its wayy too low.

**Comment by Kap2022** [comment]
If you increase the default search rate limit with the next upgrade, I will let you know if it fixes the issue.

Thanks for your help on this.

**Comment by Nutomic** [comment]
Im also noticing similar problems on lemmy.ml, for example [!trans@lemmygrad.ml](https://lemmygrad.ml/c/trans) doesnt seem to show up in community selection at all. Same problem in the "block community" section under /settings. In case of some communities, the problem can be fixed by typing one letter more, or deleting one letter, but not always. Really doubt that this is related to the rate limit, because then there wouldnt be anything shown in the dropdown.

**Comment by dessalines** [comment]
The community search seems to be searching the name, title, or description, which is probably fine. The issue there is probably just the smaller # of search results returned. 

The search rate limit is also an issue tho, even with a debounce, you're likely to hit 6 searches very quickly.

**Comment by Nutomic** [comment]
I think it should prioritize the name (and maybe title) over everything else. If i search for trans, a community with that exact name should always be shown first.

**Comment by Kap2022** [comment]
Users see the "Display Name" most frequently and will probably use that to search.

The Display Name can be very (or just a little) different from the "Name"

An example of a small difference is I made a typo on the "Name" for a community. I was able to edit the Display Name but not the Name - so there will always be a difference.

Bigger differences could be due the limitations placed on a Name versus a Display Name or a community evolves over time, so the Display Name is refined to more accurately reflect what is happening in the community.

I very much appreciate the time you are putting into sorting out this problem for me.

**Comment by dessalines** [comment]
Unfortunately I can't prioritize fields and sort them in that way, I either search for name and title, or don't search for one of them. 

I think I will remove the description search, that should help limit the results from getting too many hits. And I'll also increase the number of results returned in the UI.

**Comment by Kap2022** [comment]
This problem is resolved with the upgrade to 16.7

Thanks for fixing it for me.
