### ISSUE TITLE
An intuitive way to communicate in the fediverse

### ISSUE THREAD

**Issue by therealmaxmoon** [LemmyNet/lemmy-ui#758]
### Is your proposal related to a problem?

No, but I used Lemmy the first time today and was somehow surprised why the cross-post doesn't work as intended.

The intuitive way would be: I see an interesting post in group A, which fits perfectly to group B and C. So I create cross-posts. But there is only a link saying where it is from. The comments are separated and it is even possible to make a cross-post chain, which looks even more like chaos, but would at least have a link to all comment sections. A good example is [this post](https://lemmy.ml/post/435153).

### Describe the solution you'd like

The Fediverse was invented to be able to communicate across platforms. But with this, it is even hard to communicate within one platform.

The solution would be to link to the original post, no matter which instance.

All comments will land on the instance from the very first post and all comments from this instance will be shown. No redundant comment sections.

### Describe alternatives you've considered

The alternatives don't look like they are compatible with the Fediverse or with the ActivityPub protocol at all.

### Additional context

Comments/discussions wouldn't repeat on every thread/server, because you can see all comments at once. It saves a lot of energy, because there is no redundancy.

**Comment by Nutomic** [comment]
I dont think your suggestion is a clear improvement. One reason for crossposting is specifically to discuss the topic with a different group of users, possibly in a different language or with different rules. All of that would be impossible if all discussions were forced to happen in the same community.

I suppose it would be possible to support both options (crosspost directly points to external link, vs crosspost points to original lemmy post). However im not sure how that could be represented intuituvely in the user interface.

**Comment by therealmaxmoon** [comment]
> One reason for crossposting is specifically to discuss the topic with a different group of users, possibly in a different language or with different rules.

This is a really good point! I didn't thought of it...
