### ISSUE TITLE
docker doesn't build 0.16.6

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#763]
### Issue Summary

Stable version **build fails**:
`[2/5] Resolving packages...
success Already up-to-date.
$ husky install
husky - Git hooks installed
Done in 0.67s.
Removing intermediate container fd2f0894f5c7
 ---> 5d60135102f0
Step 12/18 : RUN yarn build:prod
 ---> Running in 888e9b8dc556
yarn run v1.22.19
$ yarn clean && node generate_translations.js
$ yarn run rimraf dist
$ /usr/src/app/node_modules/.bin/rimraf dist
/usr/src/app/generate_translations.js:7
  files.forEach(filename => {
        ^

TypeError: Cannot read properties of undefined (reading 'forEach')
    at /usr/src/app/generate_translations.js:7:9
    at FSReqCallback.oncomplete (node:fs:201:23)

Node.js v18.8.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn build:prod' returned a non-zero code: 1`

### Steps to Reproduce

1. Checkout stable version 0.16.6
2. docker build . in source directory

**Comment by Nutomic** [comment]
You are probably missing the translations submodule. Run `git submodule init && git submodule update`, and check the output of `git status`.

**Comment by sam365724** [comment]
Absolutely, thanks!
