### ISSUE TITLE
Inserting links and images does not respect cursor position

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#765]
### Issue Summary

When inserting to text box, the cursor position is not respected. The new content always inserts at the end of the post. Here on github this works fine for example. 

### Steps to Reproduce

1. Create new post
2. add multiple lines
3. insert link or image, etc. 
![2022-08-29_15-35-52 (2)](https://user-images.githubusercontent.com/111515092/187214296-ac7d24a2-679d-4879-98e3-e315909da189.gif)

### Technical details

v.16.6

**Comment by dessalines** [comment]
Yep this is an issue, its the `markdown-textearea.tsx` insert functions that need some work. I'm debating whether also to make the insert link a popup, although I've avoided those a lot because they sometimes have screen-size issues.
