### ISSUE TITLE
Username is shown as `@undefined` in page title

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#77]
![Screenshot_20201116_142659](https://user-images.githubusercontent.com/1044450/99257903-abfc6f00-280f-11eb-8ae8-90227550e63b.jpg)

https://ds9.lemmy.ml/user/44

`GetUserDetails` has `data.user.preferred_username: null`, clearly that isnt handled correctly here.

**Comment by dessalines** [comment]
The preferred_username is a separate issue, but I just tested that out, and its like this:

- Only a fetch will update user details (stuff like display name, bio)
- Serge creates a user, does a post, that gets pushed, then changes display name.
- The `last_refresh_at` column hasn't been more than a day yet.
- After serge does another action after a day, it'll refresh that user and their details will get pushed.

I confirmed this by manually searching for `@pioneer@voyager.lemmy.ml` in the search box, which correctly updated their details on ds9.
