### ISSUE TITLE
Logging out on user settings and admin settings results in error and white page

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#770]
### Issue Summary

<img width="546" alt="image" src="https://user-images.githubusercontent.com/111515092/187657820-311ba031-5f7e-4056-8fab-720bc0b59a50.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/111515092/187658064-2446fc5e-09b5-4d2c-8811-89375080125e.png">

### Steps to Reproduce

1. Log in
2. Go to user settings or site settings (/admin)
3. Logout

### Technical details

0.16.6

**Comment by dessalines** [comment]
I'll check this out after I finish up a few things.

**Comment by dessalines** [comment]
This is fixed on main.

**Comment by sam365724** [comment]
Awesome, can you reference the fix please. I can test it if you like.

**Comment by dessalines** [comment]
I can't, because that was fixed with a ton of other null-pointer bugs when I did the massive rework in convert from javascript nulls to rust-styles options with [monads](https://github.com/sniptt-official/monads).

**Comment by sam365724** [comment]
Alright no problem. But these fixes are not in 0.16.7 yet right, but in 0.16.8 then i assume

**Comment by dessalines** [comment]
They'll be in `0.17.0`
