### ISSUE TITLE
Add post and comment language tags

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#771]
Comment language tags example: https://github.com/LemmyNet/lemmy/pull/2417

**Comment by Nutomic** [comment]
It basically needs these elements:

- [ ] Input to select user discussion languages in profile settings (should allow multiple selection, [like this in peertube](https://user-images.githubusercontent.com/1044450/72671021-49deac00-3a3c-11ea-82aa-236014ea71b5.png))
- [ ] I would show a warning if "undefined" is not selected, saying that other platforms dont support language tags, so none of their content will be visible in that case.
- [ ] Language dropdown in post/comment creation form, where you can set the language from your active discussion languages. For comments, should default to language of the parent post/comment. For posts, default to "undefined", or if user only speaks one language, default to that.

I think that should be everything.

**Comment by Nutomic** [comment]
For https://github.com/LemmyNet/lemmy/pull/2434 there should also be the following changes:

- [ ] allowed languages are shown in site/community sidebar (user languages are not publicly shown)
- [ ] admins/mods can edit languages for sites/communities (using the same input as in user profile)

**Comment by dessalines** [comment]
The latter half of this should probably go in another issue.
