### ISSUE TITLE
Useless 404 requests from client to https://domain.com/pictrs/image/

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#774]
### Issue Summary

client.js requesting https://domain.com/pictrs/image/ for each page load. This is resulting in a 404. 

### Steps to Reproduce

1. Load page
2. check in dev console or webserver log

### Technical details
lemmy 16.6

**Comment by Nutomic** [comment]
I checked two different 0.16.6 instances and couldnt find this request in Firefox dev tools. Which instance are you seeing this on, and which browser do you use?

**Comment by sam365724** [comment]
Well, its minor. I understand that lemmy-ui is loading a lot of content when opening the main page. Maybe there is just some wrong link posted by user. I can check on that.

**Comment by dessalines** [comment]
This is almost certainly a federated user ore community from an un-updated instance of lemmy, where they're missing a picture.
