### ISSUE TITLE
The name, server icon, description and sidebar changes when I restart docker or the server

### ISSUE THREAD

**Issue by DokStook** [LemmyNet/lemmy-ui#775]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

I spun up my instance and when I was doing the initial setup I got an error “Server already exists”. I reloaded the page and realized that the server was a copy of https://exploding-heads.com/. I was really confused since I didn’t do anything. I didn’t even federated with that instance. After that I changed the settings to how I wanted them to be and moved on with the day. I thought it was one time issue.

Few days later I restarted the server and when I got back to it the name, logo, description and sidebar have changed back to the ones from the other instance. I changed them back to normal and decided to restart just the docker containers. Again the same issue.

Normally the logs help but this time nothing out of normal shows up.
### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.

https://hastebin.com/macarofigi.apache

* What OS are you trying to install lemmy on? 

Debian GNU/Linux 11 (bullseye) x86_64

* Any browser console errors?

No

**Comment by DokStook** [comment]
https://github.com/LemmyNet/lemmy/issues/2365

**Comment by Nutomic** [comment]
Closing this in favor of https://github.com/LemmyNet/lemmy/issues/2365.
