### ISSUE TITLE
Aggressive caching of images can make site slow

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#776]
### Issue Summary

With many images in posts that show up on the initial page after login, lemmy is caching all those images (from browser requests). Even if the user does not open these posts. If you have hundreds of images, this really slows down the initial page load. 

Is there a way to reduce this caching and thus reduce requests and traffic to nginx/lemmy-backend?

### Steps to Reproduce

1. Crete 10 posts with each one 10-30 images
2. Load initial page
3. See 300 images being loaded in the background. The problem is also the order of the images: Smaller icons for the communities are sometimes loaded at the very end which is strange, as these should be seen by the user earlier.

### Technical details

Lemmy 0.16.6

**Comment by Nutomic** [comment]
Could you share an url where this is happening? I tried with https://lemmy.ml/c/memes which has many image posts, but Firefox dev tools only show 46 requests and 3.76 MB / 1.98 MB transferred.

**Comment by sam365724** [comment]
It's from home. But i don't think it's a an issue anymore. We can close it for now.

**Comment by sam365724** [comment]
I think this is still an issue and not only because of the images, but also because all posts are completely fetched from the home or any community list view. Would there be an option to only fetch the first x characters of the posts for the list view? Also on my mobile I experience a slow, almost freezing view when switching to and back to the list of posts.

**Comment by Nutomic** [comment]
You need to provide specific steps to reproduce this, including a specific url where this happens. Also mention which browser, os etc you are using.

**Comment by dessalines** [comment]
The home.tsx shouldn't be loading any images other that the one linked in the url. The post bodies might contain images but those aren't rendered as markdown.

**Comment by sam365724** [comment]
@dessalines Well that is not what lemmy does. Tippy.esm.js seems to trigger the download: 
<img width="1306" alt="image" src="https://user-images.githubusercontent.com/111515092/198958935-7c97cf2f-81e3-4eb8-acfa-55d3903fb17a.png">


The post has two images:
<img width="792" alt="image" src="https://user-images.githubusercontent.com/111515092/198959061-322b2ddf-c4e7-4853-97ff-7515d805424c.png">


Can tippy be configured or disabled maybe?

**Comment by sam365724** [comment]
I can confirm that removing the tippy feature from the post (commenting those lines in post-listing.tsx) list does workaround this problem.

**Comment by dessalines** [comment]
Hrm... didn't think about that. Might need to make sure tippy doesn't do html rendering.
