### ISSUE TITLE
Downvote icon still visible in mobile UI when downvoting disabled

### ISSUE THREAD

**Issue by m52go** [LemmyNet/lemmy-ui#79]
I have downvoting disabled, and the downvote arrow does not show in desktop mode. But it does show in mobile mode. Clicking it shows the downvote animation as well as error message that the downvote failed because the function is disabled.

The downvote shows in UI until the site is reloaded.

![Screenshot from 2020-11-17 13-56-53](https://user-images.githubusercontent.com/735155/99434592-e09f2200-2906-11eb-93e2-e13f24171efa.png)

**Comment by dessalines** [comment]
Thanks for this. In the future
