### ISSUE TITLE
Add custom notice to sign-up page

### ISSUE THREAD

**Issue by ColdHotman** [LemmyNet/lemmy-ui#791]
For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Is your proposal related to a problem?

NRSK is primarily a regional server for Scandinavia, focused on Scandinavian languages. I want to make users absolutely aware of this before signing up, and give them the option to check out join-lemmy.org/instances to browse for a better fit.

### Describe the solution you'd like

I'd like a text notice on the sign-up form, similar to the verification question text or sidebar, where I'm able to post more information for potential new users.

![bilde](https://user-images.githubusercontent.com/112283844/191691248-618bc71a-c474-4e44-9334-77fc4907b62f.png)

### Describe alternatives you've considered

NRSK is currently using the sidebar for this information.

### Additional context

It seems some applicants have overlooked or not noticed the sidebar information. I want it to be absolutely impossible to ignore when signing up. A surprising number of new users doesn't understand the federated nature of lemmy and I'd like to funnel them to the instance overview at join-lemmy and make sure they at least know they have a choice of home instances.

I'd also like to free up the front-page sidebar, a new user only needs to see it once not every time they visit.

**Comment by dessalines** [comment]
There are already two places for this, as you mentioned, the Question form on the signup, or your server's sidebar. 

Both support markdown, so you can put any information in them you like.

> I'd also like to free up the front-page sidebar, a new user only needs to see it once not every time they visit.

You could remove that from your sidebar, but lurkers that are browsing your site that haven't signed up yet, won't know what your site is about. Its also not a good idea to remove that even for signed-up users, as its a good place to put announcements and such.
