### ISSUE TITLE
Dedicated DM button and threaded Messages

### ISSUE THREAD

**Issue by slrgt** [LemmyNet/lemmy-ui#796]
It would be convenient to be able to have a dedicated notification badge for the number of unread messages that can be clicked to go directly to All Messages section. It would also be really convenient to have the entire message history with someone collapsed to the most recent message that can be either clicked to directly reply or clicked to open to see the entire conversation similar to a comment chain instead of having them all listed as separate messages.

**Comment by dessalines** [comment]
You mean for private messages only? Because we already have a notification button in the navbar for all unread items (replies, mentions, and private messages).

Could you show what this would look like in the UI?

**Comment by slrgt** [comment]
it would look like this 
![image](https://user-images.githubusercontent.com/114287507/192153346-c71c80bb-525b-4238-bc45-68ed3f7cb37a.png)

and when clicking the mail icon it wouyld open directly to the messages section which ideally in the future messages would be displayed more like a comment thread so the full conversation with one user is all organized together.

**Comment by dessalines** [comment]
I don't want to add multiple notification buttons in the navbar. At that point I might as well add 4 notification buttons for all the different types.
