### ISSUE TITLE
Fix lemmy-ui layout on tablets and small wide screens.

### ISSUE THREAD

**Issue by umamawme** [LemmyNet/lemmy-ui#799]
### Issue Summary
Lemmy-ui on 12 inch screens or less is using same desktop layout which is making content stuffed especially in the sidebar.
Giving a wider space for lemmy-ui layout on tablets and small wide screens, can be better for sidebar content. 
**This change will not affect lemmy-ui layout on desktop or mobile.**

#### `container` :
<img width="817" alt="Screen Shot 2022-09-26 at 16 59 41" src="https://user-images.githubusercontent.com/72635080/192298845-398e3752-43bb-40fa-ba9d-8e5a3a45e82a.png">

#### `container-lg` : 
<img width="818" alt="Screen Shot 2022-09-26 at 17 01 02" src="https://user-images.githubusercontent.com/72635080/192301107-eebba63b-40e3-4313-8d31-aa6d5fb987ad.png">

### Steps to Fix

**1. Replace All Bootstrap `container` divs with `container-lg` across all lemmy-ui views**

**Comment by dessalines** [comment]
Hrm... sounds like a good idea. Could you do a PR for this? Grep for all the cases of "container"

**Comment by umamawme** [comment]
I'd like to but, I made many unnecessary edits on my fork and not really sure how to do a PR for specific parts of the code.
It may take some time until I figure out how to do it but I'd be happy to help.

**Comment by Nutomic** [comment]
Easiest option is probably to clone the repo a second time into another folder, and then copy your changes over. There is also `git commit --interactive` but its more complicated.
