### ISSUE TITLE
Change dropdown background color on Create Post page: design request

### ISSUE THREAD

**Issue by jcklpe** [LemmyNet/lemmy-ui#803]
[See this ticket intro to understand what I'm trying to do here. ](https://github.com/LemmyNet/lemmy-ui/issues/801)

This is how it currently looks:
![image](https://user-images.githubusercontent.com/9451726/192411144-41a0d08f-ba4a-42e0-a3c7-503b2b68dc00.png)

This is much clearer:
![image](https://user-images.githubusercontent.com/9451726/192411285-d8e477aa-35e1-46b4-bc4b-69d9adc34b75.png)

Not sure why this choice was made but I'm guessing because the dropdown with the white background otherwise is kind of hard to see. 

Instead of adding a green background my recommendation would be to give it the same light grey outline as the text inputs above it. 

like this:

![image](https://user-images.githubusercontent.com/9451726/192411522-58e286eb-cfce-4534-a997-6110bd61ec48.png)

**Comment by alectrocute** [comment]
Cannot reproduce.
