### ISSUE TITLE
after search text field is disabled

### ISSUE THREAD

**Issue by Tealk** [LemmyNet/lemmy-ui#808]
### Issue Summary
when you open a comment via the search and click on the reply button, the text field is disabled. is this intentional?

![image](https://user-images.githubusercontent.com/12276250/192794839-fb9ee5e3-c52e-43e6-b4f9-dcfcf29ff509.png)

### Steps to Reproduce

1. Search for a comment e.g. `https://beehaw.org/comment/35107`
2. click on the reply icon

### Technical details

lemmy: 0.16.7
lemmyui: 0.16.7

**Comment by dessalines** [comment]
Yep its intentional, things should only be read-only from that search page. In the next update the reply buttons should be hidden.
