### ISSUE TITLE
Upvote/downvote colors are backwards

### ISSUE THREAD

**Issue by ericlathrop** [LemmyNet/lemmy-ui#81]
If you're being "inspired" by reddit, then the upvote should be red and the downvote should be blue. There's a lot of cognitive dissonance from seeing the colors swapped.

**Comment by dessalines** [comment]
There's no requirement that we need to match their color scheme, and also unlike reddit lemmy has custom themes.

**Comment by ericlathrop** [comment]
@dessalines I'm just saying that Lemmy's default color scheme is already using the reddit colors, just in the wrong place, which is confusing to people coming from reddit, which you might want to avoid.
