### ISSUE TITLE
Suggestion: Drop upload area/standard button

### ISSUE THREAD

**Issue by JHenzi** [LemmyNet/lemmy-ui#82]
I'm loving Lemmy and am deciding to drive users to host images with us directly. However they have issues with the image upload button and their native OSes. They would like to either be able to drag a file into a dropzone OR just have the standard upload button exposed which most browsers treat as a drop zone for files.

I hope this makes sense.

**Comment by dessalines** [comment]
This *might* be doable, but the post and markdown areas also support copy paste of images. Also if a browser doesn't support `<input type="file`, that's a bigger problem.

**Comment by alectrocute** [comment]
Feature already implemented.
