### ISSUE TITLE
GDPR compliance: privacy declaration and imprint

### ISSUE THREAD

**Issue by Bluetoothbrot** [LemmyNet/lemmy-ui#820]
First of all I really wanted to say thanks for this monumental software, its so cool!
And secondly, I'd like to suggest an additional UI element. :)

### fulfill gdpr compliance

In the footer there's a "Legal" section already - what do you think about enabling editing of this section in order to be fulfill gdpr compliance? I mean e.g. allowing admins to rename the "Legal" section to their needs and also add other footnote sections.
This would require changes in the back end, also, right? 

The goal is to provide "Imprint" , "Privcacy policy", "FAQ" and "About us" sections :)

**Comment by dessalines** [comment]
> what do you think about enabling editing of this section in order to be fulfill gdpr compliance? 

This already exists, the legal field is entirely customizeable markdown. 

> ? I mean e.g. allowing admins to rename the "Legal"

No, we don't to add a potentially infinite number of variable-named fields for the footer. If you have site information, use your site sidebar. You can use it to link to posts named "About us", or use the spoiler tag as inline expanders.
