### ISSUE TITLE
Target="_blank" attribute

### ISSUE THREAD

**Issue by Bluetoothbrot** [LemmyNet/lemmy-ui#821]
### Clicking a link in a thread opens it in the same tab
Currently a link in a post looks like this.
`<a class="text-body" href="https://...." rel="noopener nofollow">Text</a>`

### Add target blank attribute?

Is it possible to add target="_blank" attribute to the html element so people don't leave the discussion if they just want to quickly see whats behind the link?

**Comment by dessalines** [comment]
That's unpredictable / breaking behavior for screen readers. Use middle click or click and hold to open in a new tab.

Lemmy is consistent about links not opening up in new tabs unless that is explicit.

**Comment by diamondburned** [comment]
For people with a userscript addon, here's a very hacky script that fixes this:

```js
// ==UserScript==
// @name   Lemmy target=_blank link injector
// @grant  none
// @run-at document-start
// ==/UserScript==

const observer = new MutationObserver((mutationList, observer) => {
  if (mutationList.find(mut => mut.type == "childList") == undefined) {
    return
  }
  [...document.querySelectorAll(`.post-listing a[rel="noopener nofollow"]`)]
    .filter(a => a.target == "")
    .forEach(a => { a.target = "_blank" })
})
observer.observe(document.body, { childList: true, subtree: true })
```
