### ISSUE TITLE
Lemmy is not installable as PWA anymore

### ISSUE THREAD

**Issue by EchedeyLR** [LemmyNet/lemmy-ui#822]
### Issue Summary

Lemmy is not "installable" as PWA anymore.

### Steps to Reproduce

1. Open https://lemmy.ml or any other LemmyUI of any instance in Firefox for Android.
2. Check for the install option.
3. See that only "Add to Home screen" is available, as if it was detected as common website.
4. Press it and see that it is indeed opened as a web browser tab.

### Technical details

* OS: Android 10.
* Web Browser: Firefox for Android 105.1.0

**Comment by xximj** [comment]
I can work on this.

**Comment by zcdunn** [comment]
I came to file the same issue. I checked devtools on desktop and found that the web app manifest isn't being loaded.

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://lemmy.ml/static/assets/manifest.webmanifest (“default-src”).
```

There also doesn't seem to be a service worker installed, though I can't find any errors related to it. I don't see any request for a service worker in the network logs

**Comment by dessalines** [comment]
The CSP is most likely the only problem, because nothing else has changed. I'll try to get this in before the next update.

**Comment by m-boyd** [comment]
I'm still experiencing this issue on Android 13, even after the recent commit. Same steps to reproduce.

**Comment by dessalines** [comment]
I'm not too great at CSP, could you check to see what the issue is? I've allowed all manifest-src files so I'm not sure what else it could be.

**Comment by zcdunn** [comment]
I get 
```
Content Security Policy: The page’s settings blocked the loading of a resource at https://lemmy.ml/static/assets/manifest.webmanifest (“default-src”).
```
on Firefox 109.0

**Comment by dessalines** [comment]
That fix hasn't been deployed yet.
