### ISSUE TITLE
Community create button not being properly disabled.

### ISSUE THREAD

**Issue by therealmaxmoon** [LemmyNet/lemmy-ui#823]
### Issue Summary

After deleting all communities (no matter how many were created) it isn't possible to create new communities after the amount of communities is 0. 

### Steps to Reproduce
 
0. [optional step] Install a new lemmy instance and create a test community
1. Delete all communities
2. Try to add a new community

### Technical details

The lemmy instance worked pretty well as far as I know. I just figured out there is a community called main, which I don't needed, because I want to create other communities. But after deleting main, I couldn't create new communities and after uninstalling and installing lemmy again, I tried it again to delete all communities and the same issue appeared. 

**UPDATE 2022-10-12:**

Found another bug, which is caused by the bug mentioned above.

If you visit the site of the admin, it shows:
```
Moderates
The Default Community
Test community on lemmy.utopify.org
Test 123
```
even if the default community (main) doesn't exist anymore.

**Comment by dessalines** [comment]
I can't replicate this now. It will correctly say both the community title and name are required when you try to submit.
