### ISSUE TITLE
Allow `markdown` on title

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#827]
I like how github allows the use of markdown on the title, or at least it allows in line code markdown.

**Comment by dessalines** [comment]
Inline *might* be possible, although it does scare me a bit, because of the possible sizing and a million other abuse possibilities I can't think of right now.

**Comment by TheAwiteb** [comment]
We should be care that there is no something like this #832

**Comment by TheAwiteb** [comment]
We should be care that there is no something like this #832

**Comment by xximj** [comment]
I agree with inline rendering. Like bold, italic typing, and line breaks.
Because sometimes All you need to post something is only title field eg. micro-blogging but Lemmy forces you to put more effort on content.
