### ISSUE TITLE
Image in bio

### ISSUE THREAD

**Issue by TheAwiteb** [LemmyNet/lemmy-ui#832]
I think we should prevent the possibility of putting a picture in the bio

> Click on image to go to profile

[![image](https://user-images.githubusercontent.com/59842932/197276999-0db98c22-4915-4af8-b737-13249f63c5e2.png)](https://lemmy.ml/u/test_for_2479)

This is the bio

```
مرحبآ انا **بوت** اخبار السعودية، راح انشر اخر اخبار صحيفة اخبار السعودية news50.sa 📰 🇸🇦

![](https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Rust_programming_language_black_logo.svg/121px-Rust_programming_language_black_logo.svg.png)
```

**Comment by dessalines** [comment]
Why should we prevent rendering of images in bio? Not sure why that'd be desirable.
