### ISSUE TITLE
List of all smileys

### ISSUE THREAD

**Issue by sam365724** [LemmyNet/lemmy-ui#835]
Is it possible to get a searchable list of all available smileys?

**Comment by dessalines** [comment]
lemmy-ui used to have an emoji picker, but it was really bloated. You can currently search for emojis by typing `:`...

If we added another emoji-picker tho, it'd have to be tiny.

**Comment by sam365724** [comment]
Found it:
https://raw.githubusercontent.com/WebReflection/emoji-essential/master/esm/index.js
