### ISSUE TITLE
Initial setup/signup proceeds even if an invalid password is provided

### ISSUE THREAD

**Issue by egasimus** [LemmyNet/lemmy-ui#838]
### Issue Summary

Confusing and disorienting behavior during initial setup: did it store the admin password or not?

### Steps to Reproduce

1. Start up a blank instance and you're greeted with the admin signup page.
2. Enter a very long password
3. You get an error message that the password must be <60 characters...
4. ...but you're also sent to the next step, initial instance setup. 

### Technical details

I ain't pasting any server logs until [this entire category of bug](https://github.com/LemmyNet/lemmy/issues/2533) is resolved lol. Browser console log? Sure:

![Screenshot from 2022-11-04 12-08-19](https://user-images.githubusercontent.com/1656054/199947408-50698faa-6275-44bf-b4d8-5cf398975270.png)

...and it also contains the entered password in plaintext :man_facepalming: 

Also that button alignment - srsly...

**Comment by LiftedStarfish** [comment]
This issue is *not* fixed. I can still create an account with an invalid password (over 60 characters), and the only indication I'm given that there's any problem is, after I verify my email, when I go to log in, the website hangs.
