### ISSUE TITLE
The url for a post should contain it's community to be able to search it on a search engine

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#839]
I usually search on reddit using `keywords site:reddit.com/r/subname` on the search engine. I would like to be able to do the same on lemmy, but in lemmy all posts have the url `https://lemmy-domain/post/postnumber`. This would need to be changed to `https://lemmy-domain/c/community/postnumber` otherwise I need to search on the whole instance and I don't get good results.

**Comment by dessalines** [comment]
If you need to find a post, don't use search engines or indexers, use lemmy's own search page, which allows you to filter by community if you wish. Its been a concious decision from the beginning to not favor SEO over simple urls: so a comment url (will soon be) 

- `https://domain.tld/comment/X`, not 
- `https://domain.tld/instance/X/community/X/post/X/comment/X`

**Comment by JediMaster25** [comment]
I've encountered another problem related to the way the URLs are constructed. I was attempting to use Hydrus Network to subscribe to a community and automatically download all posted images. It would have been easy if the URLs for Reddit and Lemmy were similar, as I could have simply changed the Reddit URL to the Lemmy URL. However, now I can't do this unless I use the API, which makes things much more complex.

**Comment by JediMaster25** [comment]
Related to https://github.com/LemmyNet/lemmy-ui/issues/846
