### ISSUE TITLE
Block quote

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#841]
I like this feature where you can quote a person. With the current quoting method you can only quote text but you can't reference a person.
```
[quote="username, post:11, topic:115498"]
quoted text
[/quote]
```

It's an example from discourse, it would have to be changed to username and comment number. I would also like to provide username and url to quote someone from outside lemmy.

**Comment by dessalines** [comment]
Everything must be markdown. The best we coud do would be to potentially add a helper function that does this:

> some quoted text

- [@user](link)

**Comment by JediMaster25** [comment]
Unless other people are interested there's no need for that.
