### ISSUE TITLE
Reports shield does not appear if Administrator is not moderator of some community

### ISSUE THREAD

**Issue by EchedeyLR** [LemmyNet/lemmy-ui#842]
### Issue Summary

An Administrator of the instance will not see the reports shield button if it is not moderator of a community/sublemmy.

### Steps to Reproduce

1. Make someone Administrator.
2. Check their Lemmy UI menu and see that the shield does not appear.
3. Make them moderator of a community.
4. Check their Lemmy UI menu again and see that the shield appears correctly.

### Technical details

* Please post your log: Does not matter
* What OS are you trying to install lemmy on? Does not matter
* Any browser console errors? No

**Comment by dessalines** [comment]
I'll test this shortly.

**Comment by dessalines** [comment]
Found the issue: the reports shield was only showing if the user moderates something. It should also just always show for admins.
