### ISSUE TITLE
User interface broken on test instances

### ISSUE THREAD

**Issue by Nutomic** [LemmyNet/lemmy-ui#845]
![Screenshot_20221107_115342](https://user-images.githubusercontent.com/1044450/200293144-a43378da-8064-4da4-8d36-02de54787739.png)

https://ds9.lemmy.ml/

**Comment by dessalines** [comment]
This is fixed by https://github.com/LemmyNet/lemmy-ui/pull/840

**Comment by dessalines** [comment]
Fixed by #840
