### ISSUE TITLE
Accessibility issues with the light themes

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [LemmyNet/lemmy-ui#85]
Some text in all light themes have a grey color that blends in too much with the background, which makes it hard for people with visual impairment to read it.
![image](https://user-images.githubusercontent.com/56773311/100516499-5fd7f580-3152-11eb-900c-b6d60efd55a6.png)
In the image you can see that at the bottom there's text that is hard to make out from the background because of its color.

![image](https://user-images.githubusercontent.com/56773311/100516571-d70d8980-3152-11eb-860c-a6bdbfcb6bde.png)
Threads are unreadable.

A little bit of adjustment in the brightness of the fonts would make light mode easier to use.

**Comment by dessalines** [comment]
Do you have a browser plugin on? That text should look darker, like this:

![image](https://user-images.githubusercontent.com/930215/100526202-b5cd8d00-3194-11eb-9ab2-b37caa612e1f.png)

I can't do too much support for themes other than litely or darkly, unless someone else wants to help maintain them.

**Comment by Lilith-In-Starlight** [comment]
This is strange. I'm not sure what was causing it, but it doesn't seem to be happening now. I'll just close the issue.
