### ISSUE TITLE
Can the patreon be added to the top menu list? 

### ISSUE THREAD

**Issue by NIXOYE** [LemmyNet/lemmy-ui#86]
Patreon has awful discovery and search i would really appreciate if there was a donate link on the top with a link to the patreon and opencollective. This would also help increase the number of donors allowing lemmy to get more programmers to help

**Comment by Nutomic** [comment]
We had it there originally, but then moved it to https://join.lemmy.ml/. But I agree that we can put it in both places.

**Comment by NIXOYE** [comment]
Yeah having it in both places would be really useful. I've never gone to the join site until right now so I would've never seen it. The Support\Donate page could also include a minimalist bar that shows the amount currently being donated to the project monthly (throughout OpenCollective, Patreon, Liberapay) and maybe even some stats on server costs, how many maintainers are working on lemmy etc.

**Comment by Nutomic** [comment]
That last point sounds like a good point to make a post on. I will add it to my list of things to write :)

**Comment by NIXOYE** [comment]
Great!
