### ISSUE TITLE
Proxying media

### ISSUE THREAD

**Issue by kromonos** [LemmyNet/lemmy-ui#871]
Currently, when someone opens lemmy.ml and there are posts from other instances, media… will be loaded directly from the other instances. As a result, the other instance automatically gets the IP address of the person who did not call the page itself.  
Due to the GDPR, this would be a call to third-party provider data without the requester's consent. This should cause plenty of trouble if someone wants to harm an administrator maliciously.  
Could we do it like Mastodon and invoke the call by the instance and deliver it indirectly via the called Lemmy instance? This would also solve the problem when an instance is unavailable, e.g., for maintenance, and nginx is configured to cache, as I do on fapsi.be.

Currently, I already see a call from join-lemmy.org, when someone scrolls down enough, that the icon for my instance get fetched.

**Comment by dessalines** [comment]
You mean replace all the non-local images with something like: `api/v3/image_proxy?url=...` , and make the lemmy back-end do fetches? 

Or should lemmy force pictrs to store every possible image, even those in markdown fields?

cc @Nutomic @asonix

**Comment by kromonos** [comment]
Storing every single image would be full overblown for hard disc space. It's the first way you mentioned. If there's caching needed, one can configure nginx with a clean expiration date.  
Searx is using morty to proxy them.

**Comment by dessalines** [comment]
Using morty would be great. I'd def like to store the original URLs in markdown and post picture urls, but then let lemmy-ui replace them with the proxy urls if they're non-local pictures.

**Comment by alectrocute** [comment]
Media proxy would be ripe for abuse. I don’t see this being a feature added any time soon.
