### ISSUE TITLE
Can't unpin messages pinned by other mods

### ISSUE THREAD

**Issue by poVoq** [LemmyNet/lemmy-ui#875]
### Issue Summary

In a community where I am both mod (and actually site admin) I seem to be able to only unpin posts that I pinned myself, but not those that are pinned by other mods of the same community.

### Steps to Reproduce

1. Mod account 1 pins post
2. Mod account 2 tries to unpin post
3. Not available as an option in the GUI.

**Comment by dessalines** [comment]
I should be able to get to this early next week.
