### ISSUE TITLE
Add image cropping and error messages before uploading them

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#88]
Has much to do with #87 
Currently any dimensions for avatars, icons and banners are allowed by they're stretched. Instead of this, add a image-cropping widget before uploading it, to maintain a proportion.

Also, this widget should inform users if the image that they want to upload is too big in dimensions and which dimensions they must have. For example:

| Avatar     | Community Icon | Banner
| :-:            | :-:                        | :-:
| 500x500 | 750x750              | 3000x1000

To maintain a specific size (as proposed on #87) or just a proportion is your choice

**Comment by dessalines** [comment]
I can add a pict-rs thumbnail size for these, but I really don't want to add an image editing utility into the UI, I'd like to keep it lean.
