### ISSUE TITLE
HTML in article preview isn't sanitized

### ISSUE THREAD

**Issue by zcdunn** [LemmyNet/lemmy-ui#882]
### Issue Summary
I'm not sure how lemmy generates the article previews so sorry if this belongs in the backend repo.

It seems like HTML in the article preview is not sanitized and is being parsed by the browser. See [this post](https://lemmy.ml/post/673497) for an example. The description of the article includes `<textarea>` and it's being rendered as a textarea by the browser instead of displaying the text _<textarea>_

### Steps to Reproduce

1. Find an article that includes HTML in the description metadata
2. Create a post on lemmy linking to that article.

### Technical details

Probably irrelevant but:
MacOS Catalina (10.15.7)
Firefox (108.0.1)

**Comment by sweepline** [comment]
This is still an issue, check out this post https://lemmy.world/post/258607.
