### ISSUE TITLE
 Collapse clicking the line like in Reddit

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#896]
I find the collapse comments button isn't intuitive. It's probably intuitive for people who come from old Reddit but I came from the new Reddit interface and was used to collapsing the comments using the line instead. It wasn't until someone told me that I realized it was possible to collapse the comments. It would be nice to have both options since the interface is going to look the same.

**Comment by dessalines** [comment]
What would that look like?

**Comment by JediMaster25** [comment]
![Screenshot from 2023-01-21 00-39-52](https://user-images.githubusercontent.com/105824751/213824162-ee4a15a2-8e74-4bd7-97bd-7a4cdf37a74b.png)
![Screenshot from 2023-01-21 00-39-57](https://user-images.githubusercontent.com/105824751/213824171-e6e99491-c826-405f-9842-1fc20aebcab1.png)

**Comment by dessalines** [comment]
I've never seen clicking the line to collapse in any other platform, that doesn't make any sense to me. Usually if its not indicated as an explicit [-] / [+], then its a click and hold to collapse, which is what I have in jerboa.

Don't really see the point in this as there's already a button.
