### ISSUE TITLE
The ability to disable the `banned` tag that appears next to a banned user's comments/posts

### ISSUE THREAD

**Issue by not-layla** [LemmyNet/lemmy-ui#899]
### Is your proposal related to a problem?

When a user is banned, a red bubble is displayed next to their name in posts, comments, and on their profile. Not sure if Lemmy still does this, but their comments are also automatically collapsed. This leads to a lot of meta-commentary by other users that can be avoided by just not displaying the tag. This is the norm on e.g. Reddit. Of course, no transparency is lost, because the tag still renders on their user profile and all details remain in the modlog.

### Describe the solution you'd like

Either an option to enable/disable the `banned` tag that appears next to a user's username on posts/comments after they've been banned and control the collapsing of their comments, or a just removing this behaviour entirely.

### Describe alternatives you've considered

n/a

### Additional context

We [disabled this](https://git.chapo.chat/hexbear-collective/hexbear-frontend/pulls/208) a while back (for posts and comments), it's been a positive change to site culture.

The change is quite small, so if you guys aren't interested in incorporating it, we could quite easily keep as a patch that we rebase onto new Lemmy releases. But imo it's a good feature that should be in Lemmy as well.

**Comment by lionirdeadman** [comment]
This behaviour doesn't exist anymore.
