### ISSUE TITLE
Enable using ctrl-k to enter a link like on reddit/github/xenforo/libreoffice

### ISSUE THREAD

**Issue by wiki-me** [LemmyNet/lemmy-ui#901]
### Is your proposal related to a problem?

I want to use CTRL-k to enter links for faster editing (like on reddit/github/xenforo/libreoffice)

### Describe the solution you'd like

Add the keyboard shortcut , selecting a word and pressing ctrl-k will popup a message where you can enter the link (the reddit way).

### Describe alternatives you've considered

Doing it the github way, where it will insert the markup and the cursor will move to where the link is.

**Comment by dessalines** [comment]
Seems like a good first issue.

**Comment by Kommynct** [comment]
I think my idea in #984 would be better to implement, no?
