### ISSUE TITLE
Unable to edit post

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy-ui#908]
I posted https://lemmy.ml/post/742610 on Lemmy.ml

But then realized the bullet points were not appearing - so I went back into edit it.

After I edit it, I an preview it and it looks fine - bullets appear
![image](https://user-images.githubusercontent.com/97898454/216385262-02646082-b727-4cee-a5dd-8845941e44f9.png)

So I hit save and the bullets do not appear

![image](https://user-images.githubusercontent.com/97898454/216385815-3ad3ba1e-3ca1-4fc0-8509-d276c8c65f5b.png)

I am running Brave Browser on Linux Mint

**Comment by dessalines** [comment]
Sry about that, didn't catch it.
