### ISSUE TITLE
Trending Communities

### ISSUE THREAD

**Issue by Kap2022** [LemmyNet/lemmy-ui#909]
"Trending Communities" is a misleading title as it is really new communities.

Can we either:

1. Change it to say "New Communities", or 
2. Include communities based on some other criteria like:

- [ ] 3. user per month
- [ ] 4. most posts in the past month or week
- [ ] 5. most comments in the past month or week
- [ ] 6. etc

**Comment by Nutomic** [comment]
Looks like this is fixed, its showing most active communities now.
