### ISSUE TITLE
Links to communities not working from inside instance

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#91]
### Issue Summary

Clicking a link to a community from our instance, from inside our instance, does not work. Refreshing the page, with the same URL, does load the page.

### Steps to Reproduce

1. Go to https://lemmy.eus
2. Click a link to a community from inside the instance
3. The page won't load
4. Refresh the page (F5) and it will load, having the same URL

### Technical details

* https://lemmy.eus instance
* v 0.8.8

**Comment by dessalines** [comment]
Fix will be in the next release
