### ISSUE TITLE
Create a comment in Deutsch is not allowed

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy-ui#919]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

When i create a comment, and the language for the comment is "Deutsch", i get the error "language not allowed" in the Webfrontend.
The "Answer"-Button changes to a spinner and is not usable anymore. It stays spinning. I have to "Cancel" and create it again, with the right language "English"

On the server i see in the logs this ERROR-Message

```
lemmy_1     | 2023-02-03T15:22:54.907502Z ERROR lemmy_server::api_routes_websocket: Error during message handling language_not_allowed: language_not_allowed                                                       
lemmy_1     |    0: lemmy_api_crud::comment::create::perform                                                                                                                                                       
lemmy_1     |            with self=CreateComment { content: "which one is it?", post_id: PostId(132386), parent_id: Some(CommentId(59722)), language_id: Some(LanguageId(0)), form_id: Some("comment-form-BWf3BJIag
OlM72MKlKvS"), auth: Sensitive }                                                                                                                                                                                   
lemmy_1     |              at crates/api_crud/src/comment/create.rs:41                                                                                                                                             
```

No message in Browser-Console.

The really strange thing is, Comments with "German" in the SAME Posting on other places are no problem.

Answering here https://lemmy.ml/comment/381491 or here https://rytter.me/objects/4c906314-1763-db68-da8c-fff695697098 from my lemmy (lemmy.schuerz.at) gives me the error.

Answering here https://lemmy.ml/comment/381812 from my lemmy in "Deutsch" is no problem.
Its the same Posting!

My language-Settings are "Deutsch" and "English" in adminsitration-section

**Comment by dessalines** [comment]
Do you have Deutsch as an allowed language for both the community, and the instance?

**Comment by xundeenergie** [comment]
As i told you:
Both happens in the SAME posting.
On one comment i can answer with "Deutsch" on another comment I'm not allowed to use "Deutsch"

Same community, same posting. It is a remote-followed community, not from my instance. 
It's from lemmy.ml and the posting from my examples is the announcement for lemmy 0.17.0

**Comment by dessalines** [comment]
`self=CreateComment { content: "which one is it?", post_id: PostId(132386), parent_id: Some(CommentId(59722)), language_id: Some(LanguageId(0)`

The `LanguageId(0)` is undetermined, so maybe lemmy-ui isn't correctly setting that language for some reason.

**Comment by xundeenergie** [comment]
I made some comments not in this thread, where i can post in german and where not.

And yes... maybe the language is not set correctly. But why?

Maybe it is a question of the theme?

**Comment by xundeenergie** [comment]
no it's not the theme. I changed to standard-browser and tried to comment on a comment, where i'm not allowed to answer in "Deutsch" before. Im also not allowed now.

**Comment by dessalines** [comment]
If its still saying `LanguageId(0)`, for no matter what language you change it to, then that's a bug in the UI code.

**Comment by xundeenergie** [comment]
> If its still saying `LanguageId(0)`, for no matter what language you change it to, then that's a bug in the UI code.

i can answer in English. But not in Deutsch. And only on some comments... 
on other comments i'm allowed to anser in "Deutsch". How i said. In the same Thread, same community, same posting... just on other comment... but reproduceable. 

First i thougt it depends on a comment, which comes from friendica. But i tried it on many other comments from lemmy.ml-users and users from other lemmys (sopuli, mander.xyz...)... still the same. some answers are allowed in deutsch and englisch, some anwers are only allowed in english.

all in the same thread!
