### ISSUE TITLE
searchfield in smartphone-design is to small

### ISSUE THREAD

**Issue by xundeenergie** [LemmyNet/lemmy-ui#921]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

In Lemmy 0.17.0 the searchfield is a little short...

See screenshot

![Screenshot_20230204_214042](https://user-images.githubusercontent.com/5894829/216788773-b8506e76-405f-4414-b7cf-ac3bd5cd7237.jpg)

It's firefox on android

**Comment by dessalines** [comment]
Verified.

**Comment by PrincessMiki** [comment]
It's possible that the magnifying hit box shrunk and is too small to be clickable on some devices

I zoomed in all the way and the magnifying glass still is unclickable
