### ISSUE TITLE
Comment erased while typing it

### ISSUE THREAD

**Issue by richardARPANET** [LemmyNet/lemmy-ui#929]
### Issue Summary

A community member reported this so I have not tried it myself, other users confirmed it.

"when I’m trying to make a comment and someone replies to me, my comment gets erased"

**Comment by dessalines** [comment]
I fixed this in `0.17.1`. Could you provide a way to replicate this?

**Comment by richardARPANET** [comment]
maybe it's fixed then and they're just remembering it from the older version. will reopen if it gets reported again
