### ISSUE TITLE
[bug] Relative links in remote community's description don't work

### ISSUE THREAD

**Issue by lapete** [LemmyNet/lemmy-ui#93]
When I open a remote community in lemmy, relative links in the description sidebar (and probably elsewhere, not tested) try to add the links to my current instance.
Example: In my instance, I open !selfhosted@lemmy.ml remotely. The sidebar says:

> Overlaps somewhat with /c/floss_replacement and /c/privacy; crossposts welcome

When I click the link, it adds the link to my instance's domain, but my instance doesn't have these communities and I get:
> 404 Code: Couldn't find community.
 (and if it would have, it shouldn't link to the local ones but to the originals on lemmy.ml)

Lemmy ui should recognize it's viewing a remote community and automatically append the @remote.instance in the text as well as construct absolute links.

**Comment by dessalines** [comment]
All markdown fields like descriptions, comments, etc unfortunately need to use full, not relative urls. I think I also have this wrong in the expanders for users and community search too. 

The only way around this would be to add some custom functionality to the markdown parser, which I don't have time to do right now.
