### ISSUE TITLE
messages from blocked users suddenly all reapprared in my inbox as unread 

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy-ui#933]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

messages from blocked users suddenly all reapprared in my inbox as unread 

They still are blocked in their profile and there comments are still hidden from sight on the actual post ( lemmy.ml/post28495)

### Steps to Reproduce

Click inbox today, 8 unread msgs

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? 
* Any browser console errors?

**Comment by PrincessMiki** [comment]
*reappeared

**Comment by dessalines** [comment]
How old were these comments? They might have been before we added blocking private messages properly.

**Comment by PrincessMiki** [comment]
Not sure if it should be open still actually

**Comment by dessalines** [comment]
I'd say since this is a fixed issue *for content made after we added blocking*, it can be closed. Old instances might be affected, but you can just click the *mark all as read* button.
