### ISSUE TITLE
titles are being cut off

### ISSUE THREAD

**Issue by PrincessMiki** [LemmyNet/lemmy-ui#940]
Found a bug? Please fill out the sections below. 👍

For backend issues, use [lemmy](https://github.com/LemmyNet/lemmy)

### Issue Summary

Titles of posts are being cut off

### Steps to Reproduce

I suspect it's from users who are not on the same instance, but am unsure 

### Technical details

* Please post your log: `sudo docker-compose logs > lemmy_log.out`.
* What OS are you trying to install lemmy on? 
* Any browser console errors?

**Comment by dessalines** [comment]
Dupe of https://github.com/LemmyNet/lemmy/issues/2718
