### ISSUE TITLE
Pagination improvement

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#942]
Allow going directly to the first/last post with pagination. 

The next page button should be hidden or disabled when you are at the last page with posts.

**Comment by dessalines** [comment]
2nd one is a dupe of #103 .

Also, adding a ton of paging buttons clutters up the UI. I might switch to smart scrolling pagination like I've done in jerboa, in which case none of these buttons would exist.

**Comment by JediMaster25** [comment]
As long as there is some quick way of getting to the first post, I don't mind whether it's scrolling or pagination.

**Comment by dessalines** [comment]
The back button, or reloading the page. You can only get to other pages after clicking away from the first.

**Comment by JediMaster25** [comment]
By the first post I mean by date. With pagination the way to find it now is by doing binary search on the url index.

**Comment by dessalines** [comment]
That has nothing to do with pagination then, but with the sorts. We have an `Old` sort, and a `New` sort.

**Comment by JediMaster25** [comment]
I hadn't seen it. That's good for me.
