### ISSUE TITLE
See both posts and comments

### ISSUE THREAD

**Issue by JediMaster25** [LemmyNet/lemmy-ui#946]
Be able to see both posts and comments at the same time on the feed.

**Comment by Nutomic** [comment]
I dont think this makes much sense because they are completely different things. If you view a communith from Mastodon you will see it like that though.

**Comment by JediMaster25** [comment]
It would be useful to quickly see all activity in small instances or communities.

**Comment by 8ullyMaguire** [comment]
https://github.com/LemmyNet/lemmy/issues/3950
