### ISSUE TITLE
Markdown formatting buttons-bar should stay always visible

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#95]
Currently, `v0.8.9`, when writing posts (and any text field) the markdown formatting buttons-bar is not visible, as it stays always on bottom.
However, I propose that it stay always visible, for example the text box being scrollable, and the buttons-bar being always visible. This is the workflow of many other websites, for example Github issues.

**Comment by dessalines** [comment]
No I really don't like the idea of a scrolling markdown box, I much prefer the smart expanding one like I have now. The reddit and github ones are terrible, they're at like 6 lines max, then you can't see the rest of your text.

**Comment by Porrumentzio** [comment]
And what about putting that buttons-bar as a lateral bar? Something to not having to scroll up and down to format a large text, mainly on tiny screens

**Comment by dessalines** [comment]
I really don't like that.

**Comment by Nutomic** [comment]
I think this is a really good idea on mobile, especially for smaller screens. But we can keep the layout on desktop as it is now.

**Comment by dessalines** [comment]
Most mobile clients have dedicated reply pages, where the bottom toolbar is static, and the edit box is its own page. It might be possible to do something like that far in the future.

**Comment by Nutomic** [comment]
@Porrumentzio and fyi an android app for Lemmy will be released in the next days, so that should be better.

https://github.com/krawieck/lemmur

**Comment by Porrumentzio** [comment]
I'll try, although there are still computers with small displays/screens, so that's also a problem
Thanks :)
