### ISSUE TITLE
can i deploy  lemmy-ui on vercel?

### ISSUE THREAD

**Issue by kulame** [LemmyNet/lemmy-ui#955]
can i deploy  lemmy-ui on vercel?

**Comment by xximj** [comment]
Yes, but you need to point API configuration to your lemmy server.

**Comment by kulame** [comment]
It looks like Vercel does not support websockets, so it is difficult to use Vercel to deploy applications that support websockets.

**Comment by xximj** [comment]
Not sure but I think lemmy-ui will start using regular http requests if websockets aren't available.
