### ISSUE TITLE
markdown support `collapsed sections` syntax

### ISSUE THREAD

**Issue by qupig** [LemmyNet/lemmy-ui#958]
[Organizing information with collapsed sections](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections)

<details><summary>Example</summary>
<p>

#### We can hide anything, even code!

```ruby
   puts "Hello World"
```

</p>
</details>

**Comment by dessalines** [comment]
Already works. https://enterprise.lemmy.ml/comment/16697
