### ISSUE TITLE
In community-listing boxes each community link should display in a unic line

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#96]
Currently, `v0.8.9`, in the boxes on the sidebar where communities are enumerated or listed, they do not appear on a line for each, and this makes difficult to associate icons with links:

![irudia](https://user-images.githubusercontent.com/61913683/100983408-91cdcb00-3549-11eb-912d-64435da9fe67.png)

Instead, it should use a unic line for each community-link

**Comment by Porrumentzio** [comment]
Maybe, if two entire community-names (icon+link) can be displayed in a unic row/line, it would be well. But the community-name should never be splitted into icon and link

**Comment by Porrumentzio** [comment]
A similar issue happens on communities' logos and banners:

![irudia](https://user-images.githubusercontent.com/61913683/101247165-f6d71b80-3717-11eb-80eb-13945041d7c2.png)

Logo should always display on the same place, just at left of name

**Comment by dessalines** [comment]
Could you link to this, so I could have an example. I've only seen it do this when the banner isn't that wide.

**Comment by Porrumentzio** [comment]
This happens in the main page, in the box at right:
https://lemmy.eus/
