### ISSUE TITLE
Links/buttons that require being logged in show up when not logged in 

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#975]
### Proposal
Currently in the UI, several things show up for actions that only make sense while logged in. For instance, consider the home page:

![Home Page](https://user-images.githubusercontent.com/28871516/230249564-f404a283-09aa-47c3-810d-d4147ef025a0.png)

Creating a community, creating a post, or viewing subscribed communities are things that I would think only make sense when logged in to an account. Sure enough, for the first 2, clicking on them will redirect the user to the login page (and not let them navigate back in history for some reason).

The community page is another example:

![Community Page](https://user-images.githubusercontent.com/28871516/230250169-6a54d465-43c8-443f-9638-d0178e6332a9.png)

Subscribing, creating a post, and blocking a community again don't make sense to do when not logged in and, again, they all show error toasts when you try clicking them anyway.

### Describe the solution you'd like

My proposal is to hide these UI elements when a user is not logged in. However, I saw #974 and it seems that the maintainers want to provide information for users interested in subscribing to a community from another instance. Fortunately, I have an idea that might satisfy what @Nutomic was trying to do in that issue.

The create post and create community buttons/links can still be hidden. For communities, in addition to hiding the action buttons, the buttons in the sidebar are replaced with a message like @Nutomic mentioned in #974. It could look something like this:

![community with message](https://user-images.githubusercontent.com/28871516/230252573-1af08b9a-ddef-4b6a-a947-be2f79268191.png)

Let me know if you want it implemented. I've gotten familiar enough with the UI codebase I shouldn't need any guidance. It even seems the [profile page is doing something similar](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/person/profile.tsx#L434-L479).

**Comment by Nutomic** [comment]
This sounds great, I hope that you will implement it! The exact text and design will need some more fine-tuning of course. As you mention the profile page, it would also make sense to show a similar message for following the user. As this is now possible from Mastodon etc (but not from Lemmy which only lets you follow communities).

**Comment by Bakcodi** [comment]
It is better to keep these buttons as-is. This is the main thing that encourages users to signup to get better experience. Otherwise people can mistake the site for a read-only blog that has a comment-box. And 90% users don't signup to a blog.

**Comment by SleeplessOne1917** [comment]
In the case of communities and profiles, the direction the issue was heading was to display a message notifying the user that they are not logged in. This could also be added to the home page. A call to action to signup can be added to these messages to encourage users to create an account to get the full experience. This could both meet the concern raised about encouraging users to sign up while not displaying buttons/links that don't make sense for a non-logged in user.

@Bakcodi @dessalines @Nutomic Does this sound like a good user experience?

**Comment by Nutomic** [comment]
Yes we can change the message to give two options to the user: either register/login, or fetch the object from another Fediverse instance.

**Comment by dessalines** [comment]
In a lot of places, actions that require a signup automatically navigate you to the login page, and display the message. I think that's the best precedent, because it both notifies you that you can't do X, as well as encourages you to sign up. I'll probably use that methodology when I add in-app signups to jerboa, rather than hiding elements when you're not logged in.

**Comment by Nutomic** [comment]
Thing is that many people already have an account on another Lemmy instance, or on another platform like Mastodon or Friendica. For them it doesnt necessarily make sense to create a new account, we should also explain how they can interact from their existing account.

**Comment by SleeplessOne1917** [comment]
> In a lot of places, actions that require a signup automatically navigate you to the login page, and display the message. I think that's the best precedent, because it both notifies you that you can't do X, as well as encourages you to sign up.

If this is the approach you'd like to go with then the error toast for trying to do an action requiring a login should probably be removed. Seeing that pop up with a call to action to create an account or try to find the instance from another instance sends mixed messages.
