### ISSUE TITLE
How are the archive links that show up when creating a post supposed to work?

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#976]
When creating a post, if someone enters a URL there are grey links that pop up that lead to various internet archives of the page. It looks like this:
![post form with archive links](https://user-images.githubusercontent.com/28871516/230506022-fba03818-3d3e-48b5-bcaa-bdc88e8c167c.png)

When the user clicks any of the archive links, they leave the page. Is this behavior supposed to happen?  If not, is it supposed to behave similarly to the "copy suggested title" link in that it inserts the archive link into the URL field instead of navigating away from the page?

**Comment by dessalines** [comment]
Yes, unfortunately they must leave the page because those platforms need to generate their own links which must then be copied.
