### ISSUE TITLE
Separate Rate limit settings into its own tab

### ISSUE THREAD

**Issue by dessalines** [LemmyNet/lemmy-ui#981]
Self explanatory.

**Comment by SleeplessOne1917** [comment]
I'm wondering if only rate limiting should be in its own tab, or if it should be split up even more. Currently, the site tab on the admin page takes up a lot of vertical space and has a lot of information: this means users have to scan through a bunch of stuff to find the setting they want and, when they want to save, have to scroll all the way to the bottom of a long page. Compartmentalizing the settings into a few more tabs should make it both easier to find the setting you're looking for and reduce the scroll distance needed to reach the save button.

Here's what I'm thinking for compartmentalizing the Site tab settings into:

### Personalization
- Name
- Icon
- Banner
- Description
- Theme
- Sidebar
- Legal

### General
- Enable Downvotes
- Enable NSFW
- Registration Mode
- Only admins can create communities
- Require email verification
- Email admins on receiving new applications
- Email admins on receiving new reports
- Private Instance
- Hide modlog mod names
- Slur filter regex
- Languages
- Max actor name length
- Captcha enabled

### Federation
- Federation enabled
- Allowed/blocked instances
- Federation debug mode
- Federation worker count

### Rate Limiting
All the rate limiting options.

Let me know what you think.

**Comment by dessalines** [comment]
Sorry I missed this. This seems fine to me, although some of the Personalization and General settings could have overlap. 

I see a lot of apps have a `Look and Feel` settings tab, but we really only have theme there.

How about a `Personalization` for the most important things you've already listed, and then rename the `General` to `Additional (or More) Settings`, to denote these are less important options, but still available, and on their own tab?

**Comment by SleeplessOne1917** [comment]
That works.
