### ISSUE TITLE
Markdown headers do not scale according to its logic

### ISSUE THREAD

**Issue by Porrumentzio** [LemmyNet/lemmy-ui#99]
In Markdown markup, each `#` creates a tinier title.

But on Lemmy's text boxes, this does not work:
writting `# Title` or `### Title` will be the same.

I would like to solve this "problem"

**Comment by dessalines** [comment]
That's intentional, mainly because I don't want people to be able to have giant titles that take up half the screen. Its coming from this line:

https://github.com/LemmyNet/lemmy-ui/blob/main/src/assets/css/main.css#L59

I'd be okay with *some* scaling, but it should be very minimal.

**Comment by Porrumentzio** [comment]
Maybe the maximum size of first title could be limited, so it does not get too big.

I would thank having 3 or 4 title scales!
