### ISSUE TITLE
Add content warning to modlog ala Hexbear

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#991]
I noticed that Hexbear has a content warning on their modlog:
![image](https://user-images.githubusercontent.com/28871516/234995010-152fb70d-ec96-44fc-9d81-f9bf0e5768a4.png)

Upon some reflection, this seems like a good addition to the upstream. Considering someone saying bigoted or otherwise disturbing things is going to be banworthy for most admin teams that aren't asleep at the wheel, and all of those potentially disturbing things will be displayed in the modlog, giving users a heads up seems sensible.

**Comment by dessalines** [comment]
Agree, seems like a good idea.
