### ISSUE TITLE
Make webmanifest use custom icon, name, and description

### ISSUE THREAD

**Issue by SleeplessOne1917** [LemmyNet/lemmy-ui#996]
Currently, whenever Lemmy is used as a PWA, the default icon, name, and description are always used.
For example, the instance lemmygrad.ml is named "Lemmygrad" and has the following icon:
![Lemmygrad icon](https://lemmygrad.ml/pictrs/image/gB8yP0oFF5.png?format=webp&thumbnail=96)

Compare this to what the icon for the Lemmygrad PWA looks like on my phone:
![PWA_icon](https://user-images.githubusercontent.com/28871516/236080000-708bd037-e316-480e-96bc-25e60da0e2bd.jpg)

Currently, the site name, icon, and description are set in the admin page and saved in the database. To implement this, I think we'll have to either have instance admins set those things in the site config, or we could generate the manifest dynamically when a page is being fetched.

**Comment by dessalines** [comment]
The [webmanifest currently is just a static file](https://github.com/LemmyNet/lemmy-ui/blob/main/src/assets/manifest.webmanifest#L2), but it could built on the fly and served from the node server. It could at least get the correct name of the site and at least one size for the icon.

**Comment by SleeplessOne1917** [comment]
Closing this since the PR was merged.
